import { createElement, type CSSProperties, type ReactElement } from "react";

import type { ContentDestination, SocialTemplate } from "@/lib/content/types";

/**
 * Deterministic branded social graphics.
 *
 * Controlled layouts and real brand colors only: the same inputs always produce the same image, and
 * nothing here is generated by a model. Satori (behind next/og) requires an explicit `display: flex`
 * on any element with more than one child, so every container below sets it.
 */

export type BrandPalette = {
  /** Page background. */
  base: string;
  /** Primary accent — the rule, the badge, the emphasis. */
  accent: string;
  /** Secondary accent — supporting marks. */
  support: string;
  ink: string;
  muted: string;
  wordmark: string;
};

export const BRAND_PALETTES: Readonly<Record<ContentDestination, BrandPalette>> = {
  expungement_ai: {
    base: "#0B1320",
    accent: "#FF3B00",
    support: "#00A99D",
    ink: "#FFFFFF",
    muted: "#9AA7BC",
    wordmark: "Expungement.ai"
  },
  legalease_partner: {
    base: "#101046",
    accent: "#F04800",
    support: "#B8D8D8",
    ink: "#FFFFFF",
    muted: "#A9AEDC",
    wordmark: "LegalEase Partner"
  }
};

const DEFAULT_EYEBROW: Readonly<Record<SocialTemplate, string>> = {
  editorial_cover: "Article",
  founder_note: "A note from the founder",
  partner_spotlight: "Partner spotlight",
  quote_card: "In their words",
  product_announcement: "Product announcement",
  state_resource: "State resource"
};

export type SocialCardInput = {
  template: SocialTemplate;
  destination: ContentDestination;
  width: number;
  height: number;
  title: string;
  subtitle?: string | null;
  eyebrow?: string | null;
  attribution?: string | null;
  stateCode?: string | null;
};

function clampText(value: string, max: number): string {
  const trimmed = value.trim();
  if (trimmed.length <= max) return trimmed;
  return `${trimmed.slice(0, max - 1).trimEnd()}…`;
}

/** Deterministic type scale: bigger canvases and shorter headlines get larger type. */
function titleFontSize(width: number, length: number): number {
  const base = width * 0.062;
  const factor = length > 110 ? 0.68 : length > 80 ? 0.78 : length > 50 ? 0.9 : 1;
  return Math.round(base * factor);
}

function div(style: CSSProperties, children: (ReactElement | string | null)[] | string, key?: string): ReactElement {
  const kids = Array.isArray(children) ? children.filter((child): child is ReactElement | string => child !== null) : children;
  return createElement("div", { style, key }, kids);
}

export function buildSocialCardElement(input: SocialCardInput): ReactElement {
  const palette = BRAND_PALETTES[input.destination];
  const { width, height, template } = input;

  const pad = Math.round(width * 0.075);
  const eyebrow = (input.eyebrow?.trim() || DEFAULT_EYEBROW[template]).toUpperCase();
  const isQuote = template === "quote_card";
  const title = clampText(input.title, isQuote ? 220 : 140);
  const subtitle = input.subtitle?.trim() ? clampText(input.subtitle, 160) : null;
  const attribution = input.attribution?.trim() ? clampText(input.attribution, 80) : null;
  const stateCode = input.stateCode?.trim() ? input.stateCode.trim().toUpperCase().slice(0, 2) : null;

  const eyebrowSize = Math.round(width * 0.022);
  const bodySize = Math.round(width * 0.028);
  const headline = isQuote
    ? Math.round(titleFontSize(width, title.length) * 0.92)
    : titleFontSize(width, title.length);

  // Header: eyebrow, plus the state chip or the announcement badge where the template calls for one.
  const header = div(
    {
      display: "flex",
      alignItems: "center",
      gap: Math.round(width * 0.02)
    },
    [
      template === "state_resource" && stateCode
        ? div(
            {
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              width: Math.round(width * 0.1),
              height: Math.round(width * 0.1),
              borderRadius: Math.round(width * 0.02),
              backgroundColor: palette.accent,
              color: "#FFFFFF",
              fontSize: Math.round(width * 0.042),
              fontWeight: 700,
              letterSpacing: -1
            },
            stateCode,
            "state-chip"
          )
        : null,
      template === "product_announcement"
        ? div(
            {
              display: "flex",
              alignItems: "center",
              paddingLeft: Math.round(width * 0.018),
              paddingRight: Math.round(width * 0.018),
              paddingTop: Math.round(width * 0.008),
              paddingBottom: Math.round(width * 0.008),
              borderRadius: 999,
              backgroundColor: palette.accent,
              color: "#FFFFFF",
              fontSize: eyebrowSize,
              fontWeight: 700,
              letterSpacing: 2
            },
            "NEW",
            "new-badge"
          )
        : null,
      div(
        {
          display: "flex",
          color: template === "state_resource" || template === "product_announcement" ? palette.muted : palette.support,
          fontSize: eyebrowSize,
          fontWeight: 700,
          letterSpacing: 3
        },
        eyebrow,
        "eyebrow"
      )
    ],
    "header"
  );

  // Body.
  const bodyChildren: (ReactElement | null)[] = [];

  if (isQuote) {
    bodyChildren.push(
      div(
        {
          display: "flex",
          color: palette.accent,
          fontSize: Math.round(width * 0.12),
          fontWeight: 700,
          lineHeight: 0.9,
          marginBottom: Math.round(width * 0.01)
        },
        "“",
        "quote-mark"
      )
    );
  }

  bodyChildren.push(
    div(
      {
        display: "flex",
        color: palette.ink,
        fontSize: headline,
        fontWeight: 700,
        lineHeight: 1.12,
        letterSpacing: -1.5,
        fontStyle: isQuote ? "italic" : "normal"
      },
      title,
      "title"
    )
  );

  if (subtitle) {
    bodyChildren.push(
      div(
        {
          display: "flex",
          color: palette.muted,
          fontSize: bodySize,
          lineHeight: 1.4,
          marginTop: Math.round(width * 0.025)
        },
        subtitle,
        "subtitle"
      )
    );
  }

  if (attribution) {
    bodyChildren.push(
      div(
        {
          display: "flex",
          alignItems: "center",
          gap: Math.round(width * 0.012),
          marginTop: Math.round(width * 0.03),
          color: palette.support,
          fontSize: bodySize,
          fontWeight: 600
        },
        [
          div(
            {
              display: "flex",
              width: Math.round(width * 0.03),
              height: 3,
              backgroundColor: palette.accent
            },
            [],
            "attr-rule"
          ),
          div({ display: "flex" }, attribution, "attr-text")
        ],
        "attribution"
      )
    );
  }

  const body = div(
    {
      display: "flex",
      flexDirection: "column",
      justifyContent: "center",
      flexGrow: 1,
      paddingTop: Math.round(height * 0.04),
      paddingBottom: Math.round(height * 0.04)
    },
    bodyChildren,
    "body"
  );

  // Footer: accent rule + wordmark.
  const footer = div(
    {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between"
    },
    [
      div(
        {
          display: "flex",
          alignItems: "center",
          gap: Math.round(width * 0.014)
        },
        [
          div(
            {
              display: "flex",
              width: Math.round(width * 0.045),
              height: Math.round(width * 0.008),
              backgroundColor: palette.accent
            },
            [],
            "mark"
          ),
          div(
            {
              display: "flex",
              color: palette.ink,
              fontSize: Math.round(width * 0.026),
              fontWeight: 700,
              letterSpacing: -0.5
            },
            palette.wordmark,
            "wordmark"
          )
        ],
        "brand"
      ),
      div(
        {
          display: "flex",
          color: palette.muted,
          fontSize: Math.round(width * 0.02),
          fontWeight: 600,
          letterSpacing: 1
        },
        template === "partner_spotlight" ? "PARTNER NETWORK" : "SELF-HELP INFORMATION, NOT LEGAL ADVICE",
        "footnote"
      )
    ],
    "footer"
  );

  return div(
    {
      display: "flex",
      flexDirection: "column",
      width: "100%",
      height: "100%",
      backgroundColor: palette.base,
      paddingTop: pad,
      paddingBottom: pad,
      paddingLeft: pad,
      paddingRight: pad,
      // A deliberate brand edge rather than decorative imagery.
      borderTop: `${Math.round(height * 0.018)}px solid ${palette.accent}`,
      fontFamily: "sans-serif"
    },
    [header, body, footer],
    "card"
  );
}
