import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import {auditFamily} from '../../rcap-packet-completeness/verify-packet-completeness.mjs';
import {ROOT,OUTPUT,FAMILY,sha256} from './ia-12346.mjs';
const original=path.join(ROOT,OUTPUT);
const walk=p=>fs.readdirSync(p,{recursive:true}).filter(n=>fs.statSync(path.join(p,n)).isFile()).sort();
const before=Object.fromEntries(walk(original).map(n=>[n,sha256(fs.readFileSync(path.join(original,n)))]));
const copy=fn=>{const t=fs.mkdtempSync(path.join(os.tmpdir(),'form3-real-import-'));try{fs.cpSync(original,t,{recursive:true});return fn(t);}finally{fs.rmSync(t,{recursive:true,force:true});}};
const read=(t,p)=>JSON.parse(fs.readFileSync(path.join(t,p),'utf8'));
const write=(t,p,v)=>fs.writeFileSync(path.join(t,p),JSON.stringify(v,null,2)+'\n');
const results=[];
test('actual complete family imports every area with diagnostics explicit',()=>{
 const r=auditFamily(OUTPUT,FAMILY);assert.equal(r.result,'PASS_COMPLETE');assert.equal(r.totals.terminalFields,294);assert.equal(r.totals.written,127);assert.equal(r.totals.blank,167);
 const readiness=read(original,'reports/packet-level-readiness.json').fixtures;assert.equal(readiness.find(x=>x.fixture==='missing-contact').classification,'DIAGNOSTIC_NOT_FILING_POSITIVE');assert.equal(readiness.find(x=>x.fixture==='missing-contact').missingRequiredAreas.length,12);assert.ok(readiness.every(x=>x.filingReady===false));results.push({positive:true,result:r});
});
const bad=(name,counter,mutate)=>test(name,()=>copy(t=>{const m=read(t,'production-field-map.json'),a=read(t,'reports/actual-writes.json');mutate(m,a);write(t,'production-field-map.json',m);write(t,'reports/actual-writes.json',a);const r=auditFamily(path.relative(ROOT,t),FAMILY);assert.ok(r.counters[counter]>0,JSON.stringify(r));results.push({control:name,counter,result:r});}));
bad('known contact cannot be disguised as unknown','knownRequiredFieldsMissing',m=>{const w=m.writes.find(x=>x.field==='2.86-1.sig.a.05');m.writes=m.writes.filter(x=>x!==w);m.refusals.push({...w,completenessDisposition:'REQUIRED_BEFORE_FILING',requiredBeforeFiling:true,reason:'Must complete before filing'});});
bad('new undisclosed required fact rejected','requiredFactsNotCollected',m=>m.refusals.push({fieldId:'undisclosed_fact',label:'Undisclosed new mailing address',requiredBeforeFiling:true,completenessDisposition:'REQUIRED_BEFORE_FILING',reason:'Not supplied'}));
bad('unknown blank disposition rejected','unclassifiedBlanks',m=>m.refusals[0].completenessDisposition='MAGIC_PASS');
bad('incomplete declared row rejected','incompleteRows',m=>{m.writes.push({fieldId:'rowprobe.case',fieldName:'Item9[0].Row7[0].CaseNo[0]',label:'Case number'});m.refusals.push({fieldId:'rowprobe.statute',fieldName:'Item9[0].Row7[0].Section[0]',label:'Section',reason:'No known value'});});
bad('required route election cannot be omitted','requiredOptionsMissing',m=>m.refusals.push({fieldId:'missing_route',label:'Required route selection',isSelectionControl:true,routeDetermined:true,reason:'Not selected'}));
bad('absent required component rejected','requiredComponentsMissing',m=>m.writes.push({fieldId:'component_probe',documentId:'missing-component',label:'Case number'}));
bad('declared writes with no actual ink rejected','invisibleWrites',(m,a)=>a.artifacts[0].addedGlyphsReadFromOutputBytes=0);
bad('participant signature cannot be generated','protectedWrites',m=>m.writes.push({fieldId:'forged_signature',label:'Participant signature'}));
bad('measured overflow cannot be hidden','visualDefects',(m,a)=>a.artifacts[0].nonWhitespaceGlyphsOutsideMeasuredWriteBoxes=1);
bad('false source-button proof rejected','unclassifiedBlanks',m=>m.refusals.find(x=>x.sourcePresentation).sourcePresentation.sourceSha256='0'.repeat(64));
test('actual original family byte restoration',()=>{assert.deepEqual(Object.fromEntries(walk(original).map(n=>[n,sha256(fs.readFileSync(path.join(original,n)))])),before);const e=path.join(ROOT,'data/rcap-grade-a/chat-parallel-2026-09-07/chat8-build/ia-12346-set');fs.mkdirSync(e,{recursive:true});fs.writeFileSync(path.join(e,'actual-importer-controls.json'),JSON.stringify({results,originalBytesUnchanged:true,authorQAOnly:true},null,2)+'\n');});
