import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {ROOT,OUTPUT,SOURCE_SHA256} from './ia-901c3.mjs';
import {REPORT_RULE,writeForm2Inventory} from './ia-901c3-inventory-v2.mjs';
const original=path.join(ROOT,OUTPUT);
async function withCopy(action) {const t=await fs.mkdtemp(path.join(os.tmpdir(),'form2-inventory-'));try{await fs.cp(original,t,{recursive:true});return await action(t);}finally{await fs.rm(t,{recursive:true,force:true});}}
test('actual Form2 source binds 30 days, not the old synthetic test interval',()=>{assert.equal(REPORT_RULE.maxAgeDays,30);assert.equal(REPORT_RULE.sourceSha256,SOURCE_SHA256);assert.match(REPORT_RULE.sourceLocator,/item 9/);});
test('all eight complete generated packets have measured input inventory but no invented report',async()=>withCopy(async t=>{const l=await writeForm2Inventory(t);assert.equal(l.fixtures.length,8);for(const r of l.fixtures){assert.ok(r.actualAssemblerInputInventory.length>=2);assert.equal(r.returnedReportAssessment.reportInAssembly,false);assert.equal(r.returnedReportAssessment.mayPopulateAttachmentPresenceDeclaration,false);assert.equal(r.externalRecordAuthenticated,false);assert.equal(r.sourcePrintedAttachmentCheckbox,'LEFT_BLANK');assert.equal(r.filingReady,false);}}));
test('canonical reported receipt is not an assembled attachment',async()=>withCopy(async t=>{const r=(await writeForm2Inventory(t)).fixtures.find(r=>r.fixture==='canonical');assert.equal(r.participantReportedReceipt.status,'received');assert.equal(r.returnedReportAssessment.status,'DRAFT_NEEDS_REPORT_ATTACHMENT');assert.equal(r.signedReleaseReadyByParticipantReport,true);}));
test('30-day boundary and 31-day stale report are distinct',async()=>withCopy(async t=>{const rows=(await writeForm2Inventory(t)).fixtures;assert.equal(rows.find(r=>r.fixture==='boundary').returnedReportAssessment.status,'DRAFT_NEEDS_REPORT_ATTACHMENT');assert.equal(rows.find(r=>r.fixture==='history-stale').returnedReportAssessment.status,'REPORT_OUTSIDE_BOUND_TIMING');}));
test('pending request is not receipt; unknown receipt remains unknown',async()=>withCopy(async t=>{const rows=(await writeForm2Inventory(t)).fixtures;assert.equal(rows.find(r=>r.fixture==='history-requested').returnedReportAssessment.status,'NEEDS_RETURNED_REPORT');assert.equal(rows.find(r=>r.fixture==='missing-identifiers').returnedReportAssessment.status,'REPORT_AVAILABILITY_UNKNOWN');}));
test('unconfirmed release and exact-eight-year filing remain stopped',async()=>withCopy(async t=>{const rows=(await writeForm2Inventory(t)).fixtures;assert.ok(rows.find(r=>r.fixture==='release-missing').stoppingReasons.includes('SIGNED_RELEASE_NOT_CONFIRMED'));assert.ok(rows.find(r=>r.fixture==='exact-eight-years').stoppingReasons.includes('MORE_THAN_EIGHT_YEARS_NOT_MET'));}));
test('corrupt actual component bytes refuse inventory',async()=>withCopy(async t=>{await fs.appendFile(path.join(t,'components/canonical/form-2.pdf'),'changed');await assert.rejects(writeForm2Inventory(t),/Component bytes differ/);}));
test('arbitrary request/bill/report filename cannot impersonate an accepted assembly component',async()=>withCopy(async t=>{const p=path.join(t,'reports/rendered-artifacts.json');const m=JSON.parse(await fs.readFile(p));m.packets[0].documents[0].id='returned-dci-history';await fs.writeFile(p,JSON.stringify(m));await assert.rejects(writeForm2Inventory(t),/Unrecognized generator component/);}));
test('false item-9 automatic attachment assertion is refused',async()=>withCopy(async t=>{const p=path.join(t,'reports/canonical.json');const r=JSON.parse(await fs.readFile(p));r.actualWrites.push({fieldId:'2.86-2.09',value:true});await fs.writeFile(p,JSON.stringify(r));await assert.rejects(writeForm2Inventory(t),/Item 9 may not declare/);}));
test('actual combined-PDF mismatch refuses inventory',async()=>withCopy(async t=>{await fs.appendFile(path.join(t,'fixtures/canonical.pdf'),'changed');await assert.rejects(writeForm2Inventory(t),/Combined PDF drift/);}));
