// Georgia eligibility rules. Sourced from the Georgia Record Restriction &
// Sealing Agent Training Reference (Nationwide Record Clearing), corroborated by
// the official GBI/GCIC page and Georgia Courts guidance. Citations are
// O.C.G.A. § 35-3-37 unless otherwise noted.
export const gaEligibilityRules = [
  "Georgia does not use the word 'expungement.' The remedy is RECORD RESTRICTION (limiting who can see a criminal history record for non-criminal-justice purposes) plus, as a separate second step, SEALING of the clerk of court's file by court order. Neither destroys the record; criminal-justice agencies retain access. A record must be restricted before the court file can be sealed.",
  "Routing turns first on conviction vs. non-conviction, and on the July 1, 2013 arrest-date dividing line. The agent should (1) determine conviction vs. non-conviction; (2) for non-convictions, check the pre/post-July-2013 process; (3) for convictions, check the SB 288 two-misdemeanor lifetime cap or the pardoned-felony path; (4) screen the excluded-offense list; and (5) treat sealing the court file as a distinct second step.",
  "Pathway 1 — Non-conviction restriction (§ 35-3-37(h)): the core eligible category is charges that did not result in a conviction — dismissed, nolle prosequi/prossed, not presented to the grand jury, no further action anticipated, dead docketed for the required period, acquittal, or completion of a pretrial diversion program. For arrests on or after July 1, 2013 the record is generally restricted automatically when the clerk or prosecutor enters the qualifying disposition into GCIC (no application; the person may contact the prosecutor to confirm). For arrests before July 1, 2013 the person must apply at the arresting agency using the GBI Request to Restrict Arrest Record form, with prosecutor approval.",
  "Pathway 2 — Automatic restriction (§ 35-3-37(j.1), 2021): certain non-conviction records are restricted automatically, without any request.",
  "Pathway 3 — SB 288 misdemeanor-conviction restriction and sealing (§ 35-3-37(j)(4)): since January 1, 2021 a person may petition the court to restrict and seal up to two misdemeanor convictions in a lifetime, provided all sentence terms are complete, the person has no convictions for at least four years before filing, has no pending charges, and the offense is not on the excluded list. The grant is discretionary on an interests-of-justice showing; the prosecuting attorney has 90 days to object.",
  "Pathway 4 — Pardoned felony restriction (§ 35-3-37(j)(7)): a felony conviction pardoned by the Georgia State Board of Pardons and Paroles may be restricted if the person has not been convicted of a new offense (other than a non-serious traffic offense) since the pardon and has no pending charges. This is one of the few routes to restrict a felony conviction.",
  "Pathway 5 — Youthful / first-offender routes: misdemeanors committed before age 21 (with exceptions for serious traffic, sexual, and certain other offenses) have long been restrictable, and retroactive First Offender treatment (O.C.G.A. § 42-8-66) can in some cases convert a conviction into a first-offender discharge that is then restrictable.",
  "The separate sealing step (§ 35-3-37(m)): restriction hides the record in the GCIC criminal-history system, but the clerk of court's file remains a public court record. To close it, the person files a motion/petition to seal the clerk's record under § 35-3-37(m). Restriction must occur first; sealing is the second step.",
  "Effect of relief: a restricted record does not appear on a GCIC background check seen by employers, landlords, or the general public, and the person may state the record does not exist; but criminal-justice agencies retain access, and the clerk's court file stays public until separately sealed under § 35-3-37(m).",
  "Decision-makers differ by pathway: non-conviction restriction runs through the prosecuting attorney (who completes Section Three of the GBI form) and GCIC, with denials appealable to the Superior Court within 30 days; SB 288 conviction restriction runs through the Superior/State Court with a 90-day prosecutor objection window before the court may grant unopposed."
];
