-- Phase 37: allow source-driven RCAP document packets for the all-state
-- petition/motion route set.
--
-- Review before applying to production. This is additive: it preserves every
-- value allowed by Phase 27 and expands state/pathway coverage for
-- source-driven packet persistence. It does not alter RLS, auth, Stripe, or
-- generated packet behavior.

alter table rcap_document_packets drop constraint if exists rcap_document_packets_state_check;
alter table rcap_document_packets add constraint rcap_document_packets_state_check check (
  state in (
    'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL',
    'GA', 'HI', 'IA', 'ID', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA',
    'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE',
    'NH', 'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI',
    'SC', 'SD', 'TN', 'TX', 'UT', 'VA', 'VT', 'WA', 'WI', 'WV',
    'WY'
  )
);

alter table rcap_document_packets drop constraint if exists rcap_document_packets_document_type_check;
alter table rcap_document_packets add constraint rcap_document_packets_document_type_check check (
  document_type is null or document_type in (
    'source_driven_packet',
    'mississippi_non_conviction_petition',
    'mississippi_misdemeanor_conviction_petition',
    'mississippi_felony_conviction_petition',
    'mississippi_certificate_of_service',
    'mississippi_proposed_order_placeholder',
    'illinois_request_to_expungeseal_packet',
    'illinois_case_list',
    'illinois_additional_arrests_expungement',
    'illinois_additional_arrests_sealing',
    'illinois_order_granting_placeholder',
    'illinois_order_denying_reference',
    'illinois_notice_of_filing_placeholder',
    'illinois_fee_waiver_instructions',
    'dc_motion_to_seal',
    'dc_motion_to_expunge',
    'dc_statement_of_points_and_authorities',
    'dc_proposed_order',
    'dc_certificate_of_service',
    'dc_filing_instructions'
  )
);

alter table rcap_document_packets drop constraint if exists rcap_document_packets_pathway_check;
alter table rcap_document_packets add constraint rcap_document_packets_pathway_check check (
  pathway in (
    'source_engine_packet_plan',
    'non_conviction',
    'misdemeanor_conviction',
    'felony_conviction',
    'more_information_needed',
    'expungement_non_conviction',
    'expungement_supervision_or_qualified_probation',
    'sealing_conviction',
    'excluded_or_needs_review',
    'needs_rap_sheet',
    'automatic_expungement',
    'automatic_sealing',
    'motion_actual_innocence_expungement',
    'motion_interests_of_justice_sealing',
    'needs_review',
    'additional-justice-or-municipal-court-misdemeanor-relief',
    'adult-conviction-expungement-narrow-statutory-route',
    'adult-conviction-expungement-under-wis-stat-973-015',
    'adult-conviction-sealing',
    'adult-conviction-sealing-or-expungement-under-ohio-rev-code-2953-32',
    'adult-felony-conviction-sealing',
    'adult-felony-vacation-under-rcw-9-94a-640',
    'adult-misdemeanor-conviction-sealing',
    'adult-misdemeanor-gross-misdemeanor-vacation-under-rcw-9-96-060',
    'adult-non-conviction-expungement',
    'adult-non-conviction-expungement-under-crim-proc-10-105',
    'adult-non-conviction-expungement-w-s-7-13-1401',
    'arrest-dismissal-and-other-non-conviction-expungement-under-n-j-s-a-2c-52-6',
    'cannabis-sentence-dismissal-incarcerated-person-pathway',
    'cannabis-specific-automatic-or-petition-expungement',
    'cannabis-specific-expungement',
    'conditional-treatment-sealing-under-cpl-160-58',
    'conviction-annulment-under-rsa-651-5',
    'conviction-expungement-with-sealed-confidential-access',
    'conviction-or-diversion-216614',
    'court-ordered-sealing-943-059',
    'criminal-identity-theft-mistaken-identity-relief',
    'dc_actual_innocence_expungement_16_803',
    'dc_motion_seal_felony_conviction_8yr_16_806',
    'dc_motion_seal_misdemeanor_conviction_5yr_16_806',
    'dc_motion_seal_nonconviction_16_806',
    'deferred-imposition-dismissal-and-sealing',
    'deferred-sentence-dismissal-or-confidentiality-route',
    'discretionary-conviction-sealing-by-petition-under-cpl-160-59',
    'dui-nonadjudication',
    'dui-record-sealing-under-the-separate-dui-statute',
    'eligible-conviction-expungement',
    'eligible-conviction-expungement-under-crim-proc-10-110',
    'eligible-conviction-expungement-under-w-va-code-61-11-26',
    'eligible-felony-conviction-expungement-99-19-71',
    'expungement-after-eligible-supervision-or-qualified-probation',
    'felony-conviction-431073',
    'first-offender-nontraffic-misdemeanor-conviction-expungement-99-19-71-1',
    'first-offense-controlled-substance-conditional-discharge-relief',
    'first-offense-dui-expungement',
    'first-offense-possession-sealing',
    'general-conviction-record-sealing-under-nrs-179-245',
    'general-conviction-sealing-under-n-d-c-c-chapter-12-60-1',
    'human-trafficking-survivor-vacatur-and-expungement',
    'intervention-court-completion-expungement',
    'juvenile-allegation-expungement',
    'juvenile-automatic-or-petition-expungement',
    'lawful-self-defense-expunction-943-0578',
    'marijuana-hashish-expungement-under-n-j-s-a-2c-52-5-1-5-2-and-6-1',
    'marijuana-related-redesignation-expungement-under-mmrta',
    'marijuana-specific-summary-pardon-or-sealing-relief',
    'minor-in-possession-underage-alcohol-expungement',
    'minor-prostitution-7251',
    'misdemeanor-901c3',
    'misdemeanor-conviction-expungement-under-mont-code-46-18-1104',
    'misdemeanor-violation-traffic-conviction',
    'no-conviction-released-without-conviction',
    'non-conviction-arrest-or-criminal-charge-expungement',
    'non-conviction-court-record-closing-under-n-d-c-c-12-60-1-05',
    'non-conviction-expungement-for-dismissal-no-disposition-or-acquittal',
    'nonadjudication-under-99-15-26',
    'nonconviction-901c2',
    'nonviolent-conviction-expunction-under-g-s-15a-145-5',
    'not-more-than-two-eligible-felony-convictions-expungement',
    'one-eligible-nonviolent-felony-conviction-expungement',
    'other-eligible-misdemeanor-conviction-expungement',
    'path-a-first-offender-conviction-expungement',
    'path-b-multiple-misdemeanor-expungement',
    'path-d-petition-based-expungement-with-a-bci-certificate-of-eligibility',
    'path-e-petition-based-non-conviction-expungement',
    'path-f-petition-based-conviction-expungement',
    'pathway-1-free-non-conviction-expunction-under-tenn-code-40-32-101-a-40-32-106',
    'pathway-3-eligible-conviction-expunction-under-40-32-101-g-40-32-107',
    'pathway-4-two-offense-expunction-under-40-32-101-k',
    'petition-based-conviction-sealing-jdf-612-24-72-706',
    'petition-based-expungement-under-609a-02-03',
    'petition-based-non-conviction-sealing-jdf-417-24-72-704',
    'petitioned-clean-slate-erasure-for-eligible-pre-2000-convictions-jd-cr-202',
    'petitioned-nondisclosure-after-completed-deferred-adjudication-411-0725',
    'petitioned-nondisclosure-for-an-eligible-conviction-411-0735',
    'pretrial-intervention-or-diversion-expungement',
    'prop-64-completed-sentence-application-11361-8',
    'prop-64-currently-serving-petition-11361-8',
    'public-intoxication-12346',
    'regular-expungement-under-n-j-s-a-2c-52-2-2c-52-3',
    'restriction-and-sealing-of-a-pardoned-felony',
    'sb-288-misdemeanor-conviction-restriction-and-sealing',
    'second-chance-act-shielding',
    'set-aside-by-application-under-mcl-780-621',
    'set-aside-of-arrests-or-charges-without-conviction-under-ors-137-225-1-c',
    'set-aside-of-eligible-convictions-under-ors-137-225-1-a',
    'situation-a-non-convictions',
    'situation-b-misdemeanor-convictions',
    'situation-c-felony-convictions',
    'specialty-court-accelerated',
    'suspended-imposition-of-sentence-sealing',
    'tool-1-dismissal-set-aside',
    'tool-3-petition-based-felony-sealing',
    'tool-4-arrest-record-sealing',
    'uncharged-or-unprosecuted-misdemeanor-after-12-months-99-15-59',
    'underage-alcohol-12347'
  )
);

create index if not exists rcap_document_packets_source_state_idx
  on rcap_document_packets(state, created_at)
  where document_type = 'source_driven_packet';
