// Auto-generated by scripts/generate-all50-state-pack-batch.mjs.
// Build-first metadata is sourced from private/Nationwide Record Clearing.
// QA, visual review, counsel review, and source freshness review are tracked
// separately and do not block ordinary RCAP build work.

export const coloradoAll50BuildMetadata = {
  "jurisdiction": {
    "code": "CO",
    "name": "Colorado",
    "slug": "colorado",
    "sourceFolders": [
      "LegalEase Colorado"
    ]
  },
  "products": [
    "record_clearing_guidance_packet",
    "official_pdf_overlay_draft",
    "custom_pleading_or_state_pack_draft"
  ],
  "pathways": [
    {
      "id": "record_clearing_review",
      "label": "Colorado record-clearing review",
      "output": "guidance_packet",
      "reviewRequiredBeforeLive": true
    },
    {
      "id": "official_form_overlay",
      "label": "Colorado official form overlay draft",
      "output": "official_pdf_overlay_draft",
      "reviewRequiredBeforeLive": true
    },
    {
      "id": "custom_pleading",
      "label": "Colorado custom pleading draft",
      "output": "custom_pleading_or_state_pack_draft",
      "reviewRequiredBeforeLive": true
    }
  ],
  "requiredUserInputs": [
    "participant_full_legal_name",
    "date_of_birth_if_required_by_selected_form",
    "contact_information",
    "case_number",
    "court_or_agency_name",
    "county_or_filing_location",
    "charge_or_record_description",
    "case_outcome",
    "disposition_date_if_known",
    "sentence_completion_or_supervision_status_if_applicable",
    "records_or_background_report_if_available"
  ],
  "filingDestinationGuidance": [
    "Use the court, clerk, agency, or official filing destination identified in the selected Nationwide resource packet or official form.",
    "If the correct filing destination is unclear, keep the packet guidance-only and flag the state for post-build QA/attorney review.",
    "Do not invent clerk addresses, agency addresses, local fees, or service rules."
  ],
  "filingSteps": [
    "Confirm the record-clearing pathway from the participant's answers and available source packet.",
    "Collect required user inputs and mark unknown information plainly.",
    "Select official form overlay, custom pleading, or guidance-only fallback.",
    "Generate internal review packet and source inventory artifact.",
    "Route to QA, visual review when an official PDF overlay exists, and counsel review before live use."
  ],
  "feesCopiesServiceNotes": [
    "Use fee, copy, and service notes only when present in the Nationwide source packet or official form.",
    "When fee/copy/service information is absent or unclear, state that the participant should verify current local requirements with the filing court or agency.",
    "Do not treat missing fee data as a blocker for guidance fallback generation."
  ],
  "officialFormInventory": [
    {
      "fileName": "Colorado-RecordSealing-Agent-Reference.pdf",
      "relativePath": "LegalEase Colorado/Colorado-RecordSealing-Agent-Reference.pdf",
      "sha256": "38c8964c37af23fdace1d48f0e9c4d091e06889e8e5fa2ea1bd1854270e33cdd",
      "sizeBytes": 23329
    },
    {
      "fileName": "JDF 2361 - Z Rem.pdf",
      "relativePath": "LegalEase Colorado/JDF 2361 - Z Rem.pdf",
      "sha256": "d398bb48c1b01d9b5b4ca390505d9c351647cab3400b7bc2265e1f9d7c06f795",
      "sizeBytes": 566503
    },
    {
      "fileName": "JDF 419 Order and Notice of Hearing.pdf",
      "relativePath": "LegalEase Colorado/JDF 419 Order and Notice of Hearing.pdf",
      "sha256": "64012a2a3ef643f5b9a587e5181c3332f788764324003709913688d2f9bd86a2",
      "sizeBytes": 50720
    },
    {
      "fileName": "JDF 435 order denying petition to seal.pdf",
      "relativePath": "LegalEase Colorado/JDF 435 order denying petition to seal.pdf",
      "sha256": "59026b6ad9809e21fd9cb071adb5725329ac7a65f4a7c3055b11ac57b9f2dd15",
      "sizeBytes": 50394
    },
    {
      "fileName": "JDF 684 Order Denying Petition to Seal Criminal Conviction Municipal Records.pdf",
      "relativePath": "LegalEase Colorado/JDF 684 Order Denying Petition to Seal Criminal Conviction Municipal Records.pdf",
      "sha256": "36fc6a2acbfcd7ce032b5a2d43645517aa53541f25c7c5395dd782395d67f874",
      "sizeBytes": 49317
    },
    {
      "fileName": "JDF 685 Order and Notice of Hearing on Petition to Seal Criminal Conviction Municipal Records.pdf",
      "relativePath": "LegalEase Colorado/JDF 685 Order and Notice of Hearing on Petition to Seal Criminal Conviction Municipal Records.pdf",
      "sha256": "d5dc81f76b71437ecde58e74004c4893ea6a83b1b87aba63c58282395c421462",
      "sizeBytes": 50317
    },
    {
      "fileName": "JDF2370.pdf",
      "relativePath": "LegalEase Colorado/JDF2370.pdf",
      "sha256": "cc0b5737ef0598f9e667e50b00aecbd95f53fdb9aa2bc546f8aaa910da480149",
      "sizeBytes": 614271
    },
    {
      "fileName": "JDF2371.pdf",
      "relativePath": "LegalEase Colorado/JDF2371.pdf",
      "sha256": "642558b85e3f3df8c15808369685bbe56398523c7794b6a949d20fd7b4f8b6d6",
      "sizeBytes": 669287
    },
    {
      "fileName": "JDF2374.pdf",
      "relativePath": "LegalEase Colorado/JDF2374.pdf",
      "sha256": "36a7ad4767ac8333183cd26775265697d1c6574029f7f722462f09d382990a72",
      "sizeBytes": 1051131
    },
    {
      "fileName": "JDF302.pdf",
      "relativePath": "LegalEase Colorado/JDF302.pdf",
      "sha256": "53459fde5fcd0d22ca4b93766fe7f2bc6c6c8a578b5044f46bc0317be2b702c5",
      "sizeBytes": 121346
    },
    {
      "fileName": "JDF302.spanish.pdf",
      "relativePath": "LegalEase Colorado/JDF302.spanish.pdf",
      "sha256": "e11492a29e5edcfe17269cbb4282b08ad747f4b10545715397e343b74f3a1eeb",
      "sizeBytes": 165950
    },
    {
      "fileName": "JDF304.pdf",
      "relativePath": "LegalEase Colorado/JDF304.pdf",
      "sha256": "64bd7f9879719bb257b9a794cd1022d27e6c94b5e18ac102cc203064d8109eba",
      "sizeBytes": 1083204
    },
    {
      "fileName": "JDF324.pdf",
      "relativePath": "LegalEase Colorado/JDF324.pdf",
      "sha256": "fa436ee1561713cad238b33fd761b0a97afbe0e9c0f8b70bdc6662990d7852fa",
      "sizeBytes": 30539
    },
    {
      "fileName": "JDF324.spanish.pdf",
      "relativePath": "LegalEase Colorado/JDF324.spanish.pdf",
      "sha256": "14c2de516ad4c4d159fa941b114e1bce01f67c85c47b7b480c4fa4ac81f4c795",
      "sizeBytes": 37438
    },
    {
      "fileName": "JDF326.pdf",
      "relativePath": "LegalEase Colorado/JDF326.pdf",
      "sha256": "7abccec3a4e65e227661f2716f8e61c4e88e6c33c8c5ded4dd8140bab84b23cd",
      "sizeBytes": 91947
    },
    {
      "fileName": "JDF326.spanish.pdf",
      "relativePath": "LegalEase Colorado/JDF326.spanish.pdf",
      "sha256": "ee6cb8c259ee0c683a927878bd09d890ef977e8566677c32cdeaf811f9546dd1",
      "sizeBytes": 154831
    },
    {
      "fileName": "JDF416.pdf",
      "relativePath": "LegalEase Colorado/JDF416.pdf",
      "sha256": "26b07edc2300b2fd9dc8a5114fa3738fb4b377a7aa1ea089cecf6861b96235af",
      "sizeBytes": 655751
    },
    {
      "fileName": "JDF417.pdf",
      "relativePath": "LegalEase Colorado/JDF417.pdf",
      "sha256": "e0e1aefac85269087ca0f69252c501b14020a301d2cf6e5fbcc26aa5338f6dd4",
      "sizeBytes": 1651354
    },
    {
      "fileName": "JDF418.pdf",
      "relativePath": "LegalEase Colorado/JDF418.pdf",
      "sha256": "1fae098394b532e45c85ac04019ce3ecff54be2a8382badba4749f25527a5e9d",
      "sizeBytes": 596551
    },
    {
      "fileName": "JDF477.pdf",
      "relativePath": "LegalEase Colorado/JDF477.pdf",
      "sha256": "9bb822f0163adefb1da1748b50b7323f027b90e32a759e737c0a321c8b47404d",
      "sizeBytes": 666230
    },
    {
      "fileName": "JDF478.pdf",
      "relativePath": "LegalEase Colorado/JDF478.pdf",
      "sha256": "cbe8ed7ce129cc35a1af1ba778507c771265e326ea0e3c9d94940e3cabeed096",
      "sizeBytes": 652768
    },
    {
      "fileName": "JDF492.pdf",
      "relativePath": "LegalEase Colorado/JDF492.pdf",
      "sha256": "6b7e427a9696110d6568909802ab9204f9e80d01ca33e577e71678f9514dc996",
      "sizeBytes": 546426
    },
    {
      "fileName": "JDF493.pdf",
      "relativePath": "LegalEase Colorado/JDF493.pdf",
      "sha256": "3dbd29f70847fc488fdba00b0a549b2276ea335bcfd1e72eb19ac2dd220d68d9",
      "sizeBytes": 552269
    },
    {
      "fileName": "JDF493.spanish.pdf",
      "relativePath": "LegalEase Colorado/JDF493.spanish.pdf",
      "sha256": "037c41260cd352b7b20a8a3ed909e4bffedb1de5ee1e0b174bfbb2f59421f476",
      "sizeBytes": 1027753
    },
    {
      "fileName": "JDF611.pdf",
      "relativePath": "LegalEase Colorado/JDF611.pdf",
      "sha256": "8f7983af4346e8ccfdc218d01622263af4e783e24a3d7654772d502a74d44fc5",
      "sizeBytes": 631473
    },
    {
      "fileName": "JDF612.pdf",
      "relativePath": "LegalEase Colorado/JDF612.pdf",
      "sha256": "4a45070b9332e73ddbb3ec9cb8d326b707589856d3104b8ab7d9ab991d9d496b",
      "sizeBytes": 737628
    },
    {
      "fileName": "JDF614.pdf",
      "relativePath": "LegalEase Colorado/JDF614.pdf",
      "sha256": "08f0a13f9aa7f5036f6f28748648fdee56aed9ee1f511f6f10e183e0bfa5e08b",
      "sizeBytes": 555787
    },
    {
      "fileName": "JDF615.pdf",
      "relativePath": "LegalEase Colorado/JDF615.pdf",
      "sha256": "184a33faf5d800a189f4c0fbd180912a02888d60e1100ca586064a8c753a0a26",
      "sizeBytes": 1054204
    },
    {
      "fileName": "JDF641.pdf",
      "relativePath": "LegalEase Colorado/JDF641.pdf",
      "sha256": "6ad1d7c43b454b3b50c9c77313528b9660ada8a730d9ed5c384479809173ab02",
      "sizeBytes": 721895
    },
    {
      "fileName": "JDF642.pdf",
      "relativePath": "LegalEase Colorado/JDF642.pdf",
      "sha256": "584708616e982657f341b17bd58166a73ca05529a73bae715ce5f38168f0c52c",
      "sizeBytes": 612824
    },
    {
      "fileName": "JDF682.pdf",
      "relativePath": "LegalEase Colorado/JDF682.pdf",
      "sha256": "5a05097b1c2b0a22beb3c44fca7b15fc0bf40911c6590bcd6c46546e1006f0fb",
      "sizeBytes": 137369
    },
    {
      "fileName": "JDF683.pdf",
      "relativePath": "LegalEase Colorado/JDF683.pdf",
      "sha256": "6b451ae32c01ef1e637a460df627d246e1b4a61d4ac4f166005a7349fa87202e",
      "sizeBytes": 82760
    },
    {
      "fileName": "JDF686.pdf",
      "relativePath": "LegalEase Colorado/JDF686.pdf",
      "sha256": "abf997d8e701df0c74b1eb7833b35f30c006b50bf71b019abf7754d898433200",
      "sizeBytes": 63657
    }
  ],
  "resourcePacketInventory": [
    {
      "fileName": "Colorado-JDF-Complete.html",
      "relativePath": "LegalEase Colorado/Colorado-JDF-Complete.html",
      "classification": "reference",
      "sha256": "85f4ad5a0141c295993b8d1dd23ee88c5dbaa38c787cbc0d548bfdf6841529de",
      "sizeBytes": 66736
    },
    {
      "fileName": "court-order-sealing-of-arrests.html",
      "relativePath": "LegalEase Colorado/court-order-sealing-of-arrests.html",
      "classification": "reference",
      "sha256": "839e824653a3e39d1b1ef14a12e3c8bed3122389f38d21b1f6e19dfe75ad12d8",
      "sizeBytes": 86643
    },
    {
      "fileName": "guide-sealing-conviction-records-multiple-cases.html",
      "relativePath": "LegalEase Colorado/guide-sealing-conviction-records-multiple-cases.html",
      "classification": "reference",
      "sha256": "3a28cafa4bf3f79c7461d6870405a2028790d57a7222371d431b3959156fe227",
      "sizeBytes": 60043
    },
    {
      "fileName": "how-expunge-juvenile-delinquency-records.html",
      "relativePath": "LegalEase Colorado/how-expunge-juvenile-delinquency-records.html",
      "classification": "reference",
      "sha256": "dfdd6af6b2c34c37dcd8fdbb4128dacd2458b009026e52208dab4ac2961cb2c7",
      "sizeBytes": 60480
    },
    {
      "fileName": "how-seal-criminal-records-non-convictions.html",
      "relativePath": "LegalEase Colorado/how-seal-criminal-records-non-convictions.html",
      "classification": "reference",
      "sha256": "815c34baa1c35141ddd79d56d6d2a9f8da802a0052f59246d4ba303646e9808e",
      "sizeBytes": 60001
    },
    {
      "fileName": "JDF613.pdf.html",
      "relativePath": "LegalEase Colorado/JDF613.pdf.html",
      "classification": "reference",
      "sha256": "5099d021a5cd9f17962d53e112b2ec938bc78080101182c6b7bb9e33efb88df7",
      "sizeBytes": 58186
    },
    {
      "fileName": "motion-seal-conviction-record-pardoned.html",
      "relativePath": "LegalEase Colorado/motion-seal-conviction-record-pardoned.html",
      "classification": "reference",
      "sha256": "91410ea5959e8a741bc78774d5f57de81ee86fe14d4a6b21363249affcb3c401",
      "sizeBytes": 60593
    },
    {
      "fileName": "order-seal-pardoned-conviction-records.html",
      "relativePath": "LegalEase Colorado/order-seal-pardoned-conviction-records.html",
      "classification": "reference",
      "sha256": "52fd67da32b7c561fd8775f728951c419411e16dd16a96c6ce39f3c62a698b76",
      "sizeBytes": 59975
    },
    {
      "fileName": "request-hearing-automatic-sealing.html",
      "relativePath": "LegalEase Colorado/request-hearing-automatic-sealing.html",
      "classification": "reference",
      "sha256": "02f72b5a7a5b5789f89d5fda6352a30a38f22672fbd5d02b136287b7d10d5e98",
      "sizeBytes": 59977
    },
    {
      "fileName": "seal-my-case.html",
      "relativePath": "LegalEase Colorado/seal-my-case.html",
      "classification": "reference",
      "sha256": "3e6cd3d3a6a87c0aaae2b27e4446b7f63e2be421e4f4dded9104f929451401ba",
      "sizeBytes": 101332
    },
    {
      "fileName": "seal-my-case2",
      "relativePath": "LegalEase Colorado/seal-my-case2",
      "classification": "other",
      "sha256": "3e6cd3d3a6a87c0aaae2b27e4446b7f63e2be421e4f4dded9104f929451401ba",
      "sizeBytes": 101332
    },
    {
      "fileName": "seal-my-case3",
      "relativePath": "LegalEase Colorado/seal-my-case3",
      "classification": "other",
      "sha256": "3e6cd3d3a6a87c0aaae2b27e4446b7f63e2be421e4f4dded9104f929451401ba",
      "sizeBytes": 101332
    },
    {
      "fileName": "seal-my-case4",
      "relativePath": "LegalEase Colorado/seal-my-case4",
      "classification": "other",
      "sha256": "3e6cd3d3a6a87c0aaae2b27e4446b7f63e2be421e4f4dded9104f929451401ba",
      "sizeBytes": 101332
    },
    {
      "fileName": "seal-my-case5",
      "relativePath": "LegalEase Colorado/seal-my-case5",
      "classification": "other",
      "sha256": "3e6cd3d3a6a87c0aaae2b27e4446b7f63e2be421e4f4dded9104f929451401ba",
      "sizeBytes": 101332
    }
  ],
  "customPleadingSupport": {
    "supported": true,
    "status": "draft_config_allowed",
    "notes": "Pleading-style draft support may be built from Nationwide resources and coded state-pack data where available."
  },
  "guidanceOnlyFallback": {
    "supported": true,
    "label": "Colorado record-clearing guidance fallback",
    "status": "built",
    "notes": "Available for internal review even when official forms or pleading templates need more work."
  },
  "disclaimer": "This RCAP build artifact is for internal document-preparation and review workflows. It is not legal advice, does not guarantee eligibility or outcomes, and is not approved for live use until QA, counsel, and any required visual review pass.",
  "buildStatusMetadata": {
    "buildStatus": "state_built",
    "statusHistory": [
      "not_started",
      "nationwide_resources_found",
      "resource_packet_ingested",
      "official_forms_ingested",
      "overlay_field_maps_drafted",
      "overlay_samples_rendered",
      "state_pack_built",
      "pleading_packet_rendered",
      "guidance_packet_rendered",
      "state_built"
    ],
    "reviewStatuses": {
      "qa": "pending",
      "visual": "pending",
      "counsel": "pending",
      "sourceFreshness": "pending"
    },
    "loops": [
      {
        "id": "nationwide_folder_ingestion_loop",
        "status": "completed"
      },
      {
        "id": "all_state_build_loop",
        "status": "completed"
      },
      {
        "id": "official_pdf_overlay_factory_loop",
        "status": "draft_ready"
      },
      {
        "id": "field_map_retry_loop",
        "status": "pending_retry_artifacts"
      },
      {
        "id": "custom_pleading_factory_loop",
        "status": "draft_ready"
      },
      {
        "id": "guidance_packet_loop",
        "status": "completed"
      },
      {
        "id": "packet_render_qa_loop",
        "status": "pending_review"
      },
      {
        "id": "review_artifact_loop",
        "status": "completed"
      },
      {
        "id": "integration_preview_loop",
        "status": "internal_preview_ready"
      },
      {
        "id": "official_forms_watcher_loop",
        "status": "source_tracked"
      }
    ],
    "liveRouting": {
      "approvedForLive": false,
      "live": false,
      "note": "Build-first state output is internal review material only."
    }
  },
  "buildIssues": []
} as const;
