// Maine eligibility rules. Sourced from the Maine Criminal Record Sealing — Wilma
// Agent Training Reference (Nationwide Record Clearing), corroborated by the cited
// Maine statutes and Maine Judicial Branch guidance. Citations are M.R.S. unless
// noted. In Maine the adult remedy is SEALING, not expungement.
export const meEligibilityRules = [
  "Maine generally does NOT erase or expunge adult criminal records. The remedy is record SEALING: a sealed conviction becomes confidential criminal-history record information and is restricted from public disclosure, but courts, criminal-justice agencies, licensing agencies, financial regulators, some fingerprint-based background-check entities, victims, and other statutorily authorized recipients may still access it (15 M.R.S. § 2265). Use 'seal from most public access,' not 'delete,' 'erase,' or 'wipe clean.'",
  "General adult conviction sealing (15 M.R.S. §§ 2261-2264; form CR-218): this is a conviction-specific motion, filed in the underlying criminal proceeding, not a whole-record sweep. An 'eligible criminal conviction' (§ 2261(6)) is a current or former Class E crime EXCEPT current/former Class E crimes under Title 17-A, Chapter 11, plus specified marijuana-related convictions committed before January 30, 2017.",
  "General adult sealing prerequisites (15 M.R.S. § 2262): all must be confirmed — (1) an eligible conviction under § 2261(6); (2) at least 4 years since the person fully satisfied the sentence (including incarceration, probation, administrative release, license suspension, fines, restitution, and community service); (3) no later Maine criminal conviction; (4) no later Maine criminal charge dismissed as a result of deferred disposition; (5) no later conviction in another jurisdiction; and (6) no pending criminal charges in Maine or another jurisdiction.",
  "Engaging-in-prostitution sealing (15 M.R.S. § 2262-A; form CR-289): a special, narrow, named-offense route for a former Class E conviction for engaging in prostitution under former Title 17-A § 853-A. Requires at least 1 year after fully satisfying the sentence and no disqualifying later conviction for aggravated sex trafficking, sex trafficking, engaging a person in prostitution, patronizing prostitution of a minor/person with a mental disability, or substantially similar conduct elsewhere. PL 2025 ch. 513 removed the separate 'eligible criminal conviction' requirement and changed the one-year rule to refer to 'a criminal conviction.' Do not route every prostitution/trafficking-related case here.",
  "Sex-trafficking / sexual-exploitation survivor sealing (15 M.R.S. § 2262-B; PL 2025 ch. 513, effective January 11, 2026): criminal-history record information relating to ANY current or former crime may be sealed if the person establishes (1) victim status — they were a victim of sex trafficking or sexual exploitation; (2) a causal connection — the crime of conviction was a substantial result of the trafficking/exploitation; with (3) the motion filed at any time after conviction. Official documentation is not required (and if presented creates a presumption); the filer/witnesses may participate remotely; the court may grant without a hearing if the State consents; the person must establish prerequisites by a preponderance. This route is trauma-sensitive — route to manual/legal review.",
  "Non-conviction records (16 M.R.S. §§ 703, 705): these are governed by Maine's criminal-history confidentiality framework, NOT the CR-218 conviction-sealing motion. Confidential criminal-history record information includes arrest/summons information older than one year with no active prosecution, law-enforcement non-referral, prosecutor declined prosecution, grand-jury no bill, dismissal with prejudice or final prosecutor dismissal not as part of a plea agreement, acquittal, mistrial with prejudice, jurisdictional termination, and full/free pardon. Maine still allows certain specific-date inquiries about whether a named person was arrested/detained/summonsed/charged on a specific date. For no-conviction cases, do not generate CR-218 — flag confidential-history route and verify SBI record status.",
  "Pardon route: a full and free pardon does not wipe the record clean — it makes the pardoned conviction confidential criminal-history information available only under limited statutory conditions. Do not promise expungement; route to pardon-confidentiality verification and SBI/FBI-record review.",
  "Juvenile automatic sealing (15 M.R.S. § 3308-C): for a juvenile adjudicated of a Class D or Class E juvenile crime, or a juvenile crime that would be a civil offense if committed by an adult, the court automatically seals the juvenile court record within 5 business days after a Notice of Discharge is filed.",
  "Juvenile petition sealing (15 M.R.S. § 3308-C; form JV-043): for juvenile adjudications that would be murder, Class A, Class B, Class C, or OUI if committed by an adult, the person may petition to seal if at least 3 years have passed since discharge from the juvenile disposition, there has been no later juvenile adjudication or adult conviction, and no current juvenile/adult proceedings are pending. The court may grant unless the public's right to information substantially outweighs the juvenile's privacy interest. Sealing does not remove firearm prohibitions."
];
