// Maine filing workflow. Sourced from the Maine Criminal Record Sealing — Wilma
// Agent Training Reference (Nationwide Record Clearing), sections 3, 10-12,
// corroborated by 15 M.R.S. § 2264 and Maine Judicial Branch guidance. Maine uses
// official Judicial Branch forms; this pack is shadow-only research and wires no
// renderer.
export const meFilingInstructions = [
  "Get the record first: help the user obtain their Maine criminal-history record from the Maine State Police / State Bureau of Identification (SBI). The online public criminal-history search costs $31 and a notarized background check costs $41; the SBI record is the baseline for confirming whether the case is a conviction, dismissal, or other disposition and its class.",
  "Determine the route: general adult conviction sealing (CR-218; §§ 2263-2264), former Class E engaging-in-prostitution (CR-289; § 2262-A), sex-trafficking/sexual-exploitation survivor sealing (§ 2262-B), non-conviction confidentiality (16 M.R.S. §§ 703, 705 — not CR-218), pardon confidentiality, or juvenile sealing (automatic, or petition via JV-043 under § 3308-C).",
  "General adult sealing (CR-218): complete the Motion to Seal Criminal History (brought under 15 M.R.S. §§ 2263-2264) and return it to the clerk's office for the court where the conviction occurred. The motion must address each statutory prerequisite, including certifying that at least 4 years have passed since completing all sentencing components and that there are no later convictions, no later deferred-disposition dismissal, and no pending charges.",
  "Engaging-in-prostitution (CR-289): file the Motion to Seal Conviction for Engaging in Prostitution with the clerk's office for the court in which the conviction occurred.",
  "Hearing and grant: the court schedules a hearing and reviews the statutory requirements; the person has the right to counsel but is not entitled to state-appointed counsel for the sealing motion, and the prosecutorial office that handled the original case may represent the State. The court grants if the filer proves each requirement by a preponderance of the evidence. If granted, the court notifies the SBI, which seals the conviction and mails notice to the person.",
  "Survivor sealing (§ 2262-B): the motion may be filed at any time after conviction; the filer/witnesses may participate remotely; official documentation is not required (and if presented creates a presumption); and the court may grant without a hearing if the State consents. Multiple § 2262-B motions are consolidated to one location. This is trauma-sensitive — use gentle, minimal questions and route to manual/legal review.",
  "Non-conviction cases: do NOT generate CR-218. Collect the disposition and flag as likely confidential criminal-history route, verify SBI record status, and note that court-record access may need separate review.",
  "Fees: the Maine court fee schedule lists a $60 fee for certain post-judgment motions/requests; confirm the exact CR-218/CR-289 fee with the clerk at filing because local processing depends on how the motion is docketed. If the user cannot afford fees, surface the fee-waiver route — CV-067 Application to Proceed Without Payment of Fees, filed with the CV-191 Financial Affidavit."
];
