#!/bin/bash
# Acquire the official source binaries this repository still needs.
#
# Generated by scripts/generate-rcap-external-source-operator-package.mjs.
# Runs on macOS with no credentials, no tokens and no proxy: just curl, which
# ships with the system. Double-click it in Finder, or run it from Terminal.
#
# It downloads ONLY exact official binary URLs on publisher hosts. Rows that
# need a landing page resolved, an edition compared, or a source identified at
# all are deliberately not here -- a script cannot do any of those, and
# pretending it can is how a wrong edition gets pinned.
#
# Every download is hash-checked where a hash is pinned. A file whose hash does
# not match is MOVED ASIDE, not kept: a different edition of the right form is
# still the wrong bytes, and it needs the drift comparison rather than a pin.
set -u

DEST="${1:-$HOME/Downloads/rcap-official-sources}"
mkdir -p "$DEST/mismatched"
echo "Downloading into: $DEST"
echo

ok=0; mismatched=0; failed=0

fetch() {
  local url="$1" out="$2" expected="$3" label="$4"
  echo "==> $label"
  if ! curl --fail --location --silent --show-error --proto '=https' --tlsv1.2 \
       --connect-timeout 20 --max-time 180 --retry 2 --retry-delay 3 \
       -o "$DEST/$out" "$url"; then
    echo "    FAILED to download $url"; failed=$((failed+1)); return
  fi
  if [ -n "$expected" ]; then
    local actual; actual=$(shasum -a 256 "$DEST/$out" | awk '{print $1}')
    if [ "$actual" != "$expected" ]; then
      echo "    HASH MISMATCH — expected $expected"
      echo "                    got      $actual"
      echo "    This is a different edition. Moved to mismatched/ for the drift comparison."
      mv "$DEST/$out" "$DEST/mismatched/$out"; mismatched=$((mismatched+1)); return
    fi
    echo "    ok — hash matches the pin"
  else
    echo "    downloaded (no pinned hash to verify against; record its hash before pinning)"
  fi
  ok=$((ok+1))
}

echo "--- Drift comparisons: the CURRENT official edition, for comparison only ---"
echo "    These are NOT pinned. They are expected to differ from the pinned"
echo "    edition -- that is what the comparison is for. Nothing here should"
echo "    replace a pinned source until someone has compared the two."
echo
mkdir -p "$DEST/drift-comparison"
fetch "https://www.vacourts.gov/forms/circuit/cc1473.pdf" "drift-comparison/va-cc1473.pdf" "" "VA cc1473.pdf — current edition for drift comparison (pinned: revision unrecorded)"


echo
echo "Downloaded and verified : $ok"
echo "Hash mismatches (drift) : $mismatched"
echo "Failed                  : $failed"
echo
echo "Verified files are in $DEST. Hand them back with their sha256."
echo "Anything in $DEST/mismatched is a DIFFERENT EDITION of the right form."
echo "Do not pin it. It goes to the drift comparison."
