// Massachusetts eligibility rules. Sourced from the Massachusetts Sealing &
// Expungement — Wilma Agent Training Reference (Nationwide Record Clearing),
// corroborated by M.G.L. c. 276, §§ 100A-100T and Massachusetts Trial Court /
// Probation Service guidance. Citations are M.G.L. c. 276 unless noted.
export const maEligibilityRules = [
  "Massachusetts has two distinct remedies. SEALING hides the record from most public/employer/housing background checks but does not destroy it (criminal-justice agencies, courts, and some authorized users may still access it); sealed records generally do not disqualify from public service, and ordinary employment/housing/license applications must let a person with a sealed record answer 'no record.' EXPUNGEMENT is the permanent erasure/destruction of a record so it is no longer accessible to or maintained by the court, criminal-justice agencies, or other government agencies (§ 100E) — stronger than sealing, but narrow. Never say a record will be 'erased' unless the route is true expungement.",
  "Adult conviction sealing (§ 100A): waiting periods run from the court appearance/disposition (including any incarceration/custody) — misdemeanor 3 years; felony 7 years; sex offense 15 years after disposition/supervision/incarceration OR as long as the registration duty continues, whichever is longer; an offense no longer a crime may be sealed immediately/forthwith unless the same conduct remains criminal under a different designation. Section 100A requires no Massachusetts guilty finding during the applicable 3- or 7-year period (except minor motor-vehicle offenses punishable by a fine of not more than $50) and that the petitioner have no disqualifying out-of-state/federal/U.S.-possession convictions or imprisonment during the same lookback.",
  "Adult sealing disqualifiers / special handling (§ 100A): firearms convictions under M.G.L. c. 140 §§ 121-131H are generally not sealable; public-corruption/obstruction-type convictions under c. 268 or c. 268A are generally not sealable except resisting arrest; Level 2 or Level 3 sex-offender classification is not eligible to seal sex offenses; 209A abuse-prevention or 258E harassment-prevention order violations are treated as a felony for sealing timing; a subsequent not guilty/dismissal/nolle/no bill does not interrupt the waiting period; an old felony now classified as a misdemeanor (or an unknown level) is treated as a misdemeanor.",
  "Non-conviction sealing (§ 100C): not-guilty, no-bill, and no-probable-cause records are to be sealed by the Commissioner of Probation and the court/probation offices UNLESS the defendant makes a written request not to seal. Dismissals and nolle prosequi require a court petition and a finding that 'substantial justice would best be served' by sealing — do not treat every dismissal as automatically sealed.",
  "Juvenile sealing (§ 100B): a delinquency court-appearance record on file with the Commissioner of Probation may be sealed 3 years after the court appearance/disposition (including supervision, probation, commitment, or parole) terminated, with no Massachusetts adjudication or guilty finding during the preceding 3 years (except minor motor-vehicle offenses), no Massachusetts imprisonment/commitment during that period, and no disqualifying out-of-state/federal record; the request is made on a Commissioner-furnished form signed under penalties of perjury. Juvenile sealing is broader than juvenile/youthful-offender expungement.",
  "Time-based expungement (§§ 100F, 100G, 100H, 100I, 100J): available only in limited cases. Section 100G lets a petitioner with not more than 2 records of conviction petition the Commissioner of Probation (multiple offenses from the same incident count as one); § 100H covers not more than 2 records without an adjudication/conviction; § 100F covers juvenile/youthful-offender adjudications. The Commissioner certifies eligibility under §§ 100I and 100J, the DA gets notice, and the court may grant or deny based on the best interests of justice.",
  "Time-based expungement eligibility (§ 100I): route here only if ALL are true — all offenses occurred before the person's 21st birthday; the offense is not listed in § 100J; the waiting period (at least 3 years for misdemeanor-only, at least 7 years for any felony, including incarceration/custody/probation) is met; no other Massachusetts criminal/juvenile appearances or dispositions except minor motor-vehicle offenses and the records being expunged; no other out-of-state/U.S.-possession/federal appearances/dispositions except minor motor-vehicle offenses; and the petitioner certifies they are not currently the subject of an active criminal investigation. Multiple offenses from the same incident count as one.",
  "Time-based expungement disqualifiers (§ 100J): generally route away (attorney/manual review) where the record involves death or serious bodily injury; intent to cause death or serious bodily injury; a dangerous weapon; an offense against an elderly or disabled person; a sex offense, child sex offense, or sexually violent offense; OUI/OUI-type under c. 90 § 24; firearms offenses under c. 140 §§ 121-131Q; restraining-order/abuse-prevention/harassment-prevention order violations; or domestic assault and battery under c. 265 § 13M.",
  "Non-time-based expungement (§ 100K): a court may order expungement if it finds by CLEAR AND CONVINCING evidence that the record was created because of false identification, unauthorized use/theft of identity, an offense that is no longer a crime, demonstrable law-enforcement error, civilian/expert-witness error, court-employee error, or fraud on the court; the court may also consider the best interests of justice and must enter written findings if it grants. This is not a general hardship expungement.",
  "Marijuana-only expungement (Petition for Expungement of Marijuana Offenses; § 100K logic): marijuana does not automatically mean eligible — confirm the record was marijuana-only, identify the exact charge (e.g., possession under G.L. c. 94C, § 34), confirm the conduct is now decriminalized/legalized, and confirm there was no non-marijuana charge in the same case before routing to the marijuana expungement form and docket verification.",
  "CWOF caution: Massachusetts users often misunderstand whether a continuance without a finding (CWOF) counts as a conviction or non-conviction for different purposes — flag CWOF dispositions for review rather than auto-routing."
];
