export const APPROVED_LANDING_COPY_EN: Record<string, string> = {
  skip_main: "Skip to main content",
  site_notice: "Site notice",
  menu_open: "Open menu",
  menu_close: "Close menu",
  hero_alt: "An open mountain road leading toward a sunrise between two peaks.",
  guided_check_alt: "Example question from the free screening.",
  packet_result_alt: "Example result showing that a supported self-help packet may be available.",
  briefcase_alt: "Example of a free Briefcase with cases, documents, and next steps.",
  wilma_alt: "Wilma, the Expungement.ai filing guide.",
  announce: '<span class="gold">Free screening</span>: no account and no payment required to begin.',
  announce_cta: "Check my options",
  nav_how: "How it works",
  nav_brief: "What you get",
  nav_pricing: "Price",
  nav_privacy: "Trust & privacy",
  nav_faq: "Questions",
  nav_login: "Log in",
  nav_cta: "Check my options",
  m_cta: "Check my options",
  hero_eyebrow: "FREE SCREENING",
  hero_h1: "The law is complicated. Your next step should not be.",
  hero_sub: "Check your record-clearing options for free. No account required. Answer plain-English questions about your state, case, and outcome. If a supported self-help packet is available, review your information before paying $50 to generate it.",
  hero_cta1: "Check my options",
  hero_cta2: "See a sample packet",
  hero_micro: "No account to begin · No payment to start · Free screenings in 50 states and D.C.",
  hero_disclaimer: "Self-help document preparation. Not a law firm. The court or agency makes the final decision.",
  hero_story_label: "How the product works",
  hero_story_tabs_label: "Choose a product example",
  hero_story_guided: "Free screening",
  hero_story_briefcase: "Free Briefcase",
  hero_story_packet: "Supported packet",
  hero_story_example: "Example",
  hero_story_case: "Example supported case",
  hero_story_case_status: "Packet information in progress",
  hero_story_case_free: "Your Briefcase is free.",
  hero_story_case_next: "Next step: Continue packet information",
  hero_story_packet_status: "Packet information reviewed",
  hero_story_packet_price: "$50 one time for this case",
  hero_story_packet_kind: "Supported self-help packet",
  hero_story_packet_fees: "Court filing fees are separate",
  hero_story_packet_subscription: "No subscription",
  strip_h0: "Free screening",
  strip_p0: "See which record-clearing paths may be available before you spend anything.",
  strip_h1: "Start without an account",
  strip_p1: "Begin the screening before creating an account.",
  strip_h2: "Filing steps for your court",
  strip_p2: "See what to file, where to file, and which court fees or fee-waiver steps may apply.",
  strip_h3: "$50 supported self-help packet",
  strip_p3: "Your Briefcase is free. No subscription. Court filing fees are separate.",
  prob_eye: "The barrier",
  prob_h2: "The case ended. The record may still show up.",
  prob_lead: "An arrest, dismissal, misdemeanor, or conviction can still appear on a background check and affect work, housing, school, or licensing. Expungement.ai helps you explore which record-clearing paths may be available, then shows the next step.",
  prob_cta: "Check my options",
  fade0: "Work",
  fade1: "Housing",
  fade2: "School and licensing",
  fade3: "Explore possible next steps",
  elig_eye: "Free screening",
  elig_h2: "Start with what you know. We’ll guide the rest.",
  elig_lead: "You do not need legal vocabulary to begin. We ask plain-English questions, explain confusing terms, and let you choose “Not sure” when you do not have an answer. If the facts do not support a clear option, the check stops before payment.",
  elig_b0: "Choose “Not sure” when you do not know",
  elig_b1: "See explanations as you go",
  elig_b2: "Stop at any time",
  elig_b3: "No account required to begin",
  elig_cta: "Check my options",
  mock_title: "Example from the free screening",
  mock_step: "Example question",
  mock_q: "What happened with the case?",
  chip0: "Dismissed",
  chip1: "Not guilty",
  chip2: "Arrest only",
  chip3: "Guilty or conviction",
  chip4: "Still open",
  chip5: "Not sure",
  mock_tip: "Questions and explanations change based on your state and case.",
  how_eye: "How it works",
  how_h2: "Three steps. No legal maze.",
  how_h0: "1. See which paths may be available.",
  how_p0: "Answer plain-English questions about your state, case, and outcome. The check shows whether a supported record-clearing path may be available before you pay.",
  how_h1: "2. Generate a supported self-help packet.",
  how_p1: "Review your packet information first. Then pay $50 to generate the available documents and filing instructions for your case.",
  how_h3: "3. File it yourself with clear steps.",
  how_p2: "Download your packet, follow the checklist for your court, and use your Briefcase to track what is ready, filed, or waiting.",
  how_cta: "Check my options",
  brief_eye: "Your Briefcase",
  brief_h2: "Your documents and next steps, in one place.",
  brief_lead: "Legal terms explained. Documents organized. One next step at a time. Your free Briefcase keeps each supported case, available document, and filing step together.",
  brief_b0: "See each case and its current stage",
  brief_b1: "Download available self-help documents",
  brief_b2: "Follow the filing instructions in your packet",
  brief_b3: "Track what is ready, filed, or waiting",
  brief_b4: "Ask Wilma to explain confusing steps in plain English",
  brief_cta: "See how the Briefcase works",
  brief_demo_label: "Example Briefcase",
  brief_demo_note: "This demonstration uses a fictional case and no real participant information.",
  brief_demo_tabs_label: "Example Briefcase stages",
  brief_demo_case: "Example supported case",
  brief_demo_next: "Next step",
  brief_demo_s0: "Matter saved",
  brief_demo_s1: "Packet information in progress",
  brief_demo_s2: "Ready to review",
  brief_demo_s3: "Packet ready",
  brief_demo_n0: "Review your result",
  brief_demo_n1: "Continue packet information",
  brief_demo_n2: "Review before payment",
  brief_demo_n3: "Download packet",
  pk_eye: "What you get",
  pk_h2: "A self-help packet built from your answers.",
  pk_lead: "Record-clearing rules vary by state, court, case type, and outcome. When a supported packet is available, Expungement.ai uses your answers to generate the available documents and filing instructions for that case.",
  pk_b0: "State-specific screening",
  pk_b1: "Available self-help documents",
  pk_b2: "Filing steps for the supported court",
  pk_b3: "Plain-English explanations",
  pk_b4: "Fee-waiver guidance when available",
  pk_b5: "Clear boundaries when legal help may be needed",
  pc_h0: "Petition",
  pc_p0: "Your request for record clearing",
  pc_h1: "Proposed order",
  pc_p1: "A document the judge may sign",
  pc_h2: "Filing checklist",
  pc_p2: "Where to file, what to bring, and what to expect",
  pc_h3: "Fee-waiver guidance",
  pc_p3: "How to ask the court to waive filing fees when that option is available",
  sm_eye: "Sample packet",
  sm_h2: "See a sample before you pay.",
  sm_lead: "The sample shows the document types and filing guidance a supported packet may contain. Your actual packet depends on your state, court, case, and result.",
  sm_cta: "View sample packet",
  sm_fine: "Sample only. Your actual documents depend on your state, court, case, and supported record-clearing path.",
  tab0: "Petition",
  tab1: "Filing checklist",
  tab2: "Fee waiver",
  tab3: "Court instructions",
  tab4: "Next steps",
  pr_eye: "Pricing",
  pr_h2: "$50 for one supported self-help packet.",
  pr_intro: "The screening, Briefcase, and packet-information review cost nothing. Pay only when a supported packet is ready to generate.",
  pr_sub: "per supported self-help packet",
  pr_included: "Included",
  pr_free: "Your free screening, Briefcase, and packet-information review remain free.",
  prl0: "Free screening",
  prl1: "Available self-help court documents",
  prl2: "Filing instructions for the supported court",
  prl3: "Fee-waiver guidance when available",
  prl4: "Briefcase tracking",
  prl5: "Wilma’s plain-English explanations",
  pr_not_included: "Not included",
  prx0: "Court filing fees",
  prx1: "Attorney strategy or representation",
  prx2: "Filing on your behalf or any promised court outcome",
  pr_fine: "No subscription. Court filing fees are separate. Some courts offer fee waivers. When available, your filing instructions explain how to ask.",
  pr_cover_h: "What the $50 covers",
  pr_cover_p: "Expungement.ai prepares supported self-help documents and filing instructions. You file them yourself. Attorney strategy, representation, court filing fees, and court approval are not included.",
  pr_cta: "Check my options",
  pv_eye: "Trust & privacy",
  pv_h2: "Your record is sensitive. Your privacy should be obvious.",
  pv_lead: "Start the screening without creating an account. We ask for the information needed to check supported paths and prepare a packet. We do not sell your personal information.",
  pv0: "No account required to begin",
  pv1: "No payment required to start",
  pv2: "Privacy policy available before sensitive details",
  pv3: "You decide whether to save and continue",
  pv5: "Human support without judgment",
  pv_cta: "Read our privacy policy",
  wl_eye: "Your filing guide",
  wl_h2: "Meet Wilma, your plain-English filing guide.",
  wl_lead: "Wilma explains confusing steps, defines legal terms, and points you back to your checklist. She does not decide which record-clearing option may be available, replace a lawyer, or promise a court outcome.",
  wl_p0: "What does dismissed mean in my state?",
  wl_p1: "Where do I file this packet?",
  wl_p2: "What should I bring to court?",
  wl_p3: "How do I ask about a fee waiver?",
  wl_p4: "What happens after I file?",
  wl_safe: "Wilma provides general self-help information, not legal advice.",
  wl_action: "See Wilma explain it",
  wl_action_close: "Close Wilma explanation",
  wl_example: "Example explanation",
  wl_you: "You",
  wl_q: "What does “file with the court” mean?",
  wl_a: "It means submitting your completed packet to the court. Follow the instructions included with your supported packet and confirm current requirements with the court.",
  st_eye: "Coverage",
  st_h2: "Free screenings in 50 states and D.C.",
  st_lead: "Start with your state, record type, outcome, and timing. The screening looks for supported record-clearing paths before you pay. Packet availability depends on your state, court, case, and result.",
  st_choose: "Choose your state",
  st_result: "We’ll ask about your record type, outcome, timing, and court requirements.",
  st_lab: "States and district available",
  fq_eye: "Questions",
  fq_h2: "The things people ask before they start",
  fq_q0: "Is this actually legit?",
  fq_a0: "Expungement.ai is a self-help document-preparation product. The screening looks for supported record-clearing paths, and supported packets include available documents and filing instructions. Expungement.ai is not a law firm, does not represent you, and does not file on your behalf.",
  fq_q1: "Do I need a lawyer?",
  fq_a1: "Not always. Expungement.ai provides self-help documents and general information, not legal advice. If your case is complicated or you need legal strategy or representation, speak with a licensed attorney in your state.",
  fq_q2: "What is available in my state?",
  fq_a2: "The free screening is available for all 50 states and D.C. A paid packet is not available for every case. Packet availability depends on your state, court, case, and result.",
  fq_q3: "What does the $50 cover?",
  fq_a3: "The $50 covers one supported self-help packet for one case, including available documents and filing instructions. Your screening, Briefcase, and packet-information review are free. Court filing fees are separate.",
  fq_q4: "What happens if the court denies my request?",
  fq_a4: "The court or agency makes the final decision, and approval is not guaranteed. Expungement.ai does not represent you in court. If you need advice about a denial or your next legal step, speak with a licensed attorney.",
  fq_q5: "How is my information used?",
  fq_a5: "We ask for the information needed to check supported paths, save your work when you choose, and prepare a supported packet. We do not sell your personal information. Read our privacy policy for details.",
  fq_q6: "Is Expungement.ai a law firm?",
  fq_a6: "No. Expungement.ai is self-help document-preparation software. It does not provide legal representation, represent you, or file on your behalf.",
  fn_h2: "Start with what happened. See what may be available.",
  fn_p: "The screening is free to start. No account is required to begin. If a supported packet is available, review your information before deciding whether to pay $50 to generate it.",
  fn_cta: "Check my options",
  fn_micro: "No account · No payment to start · Self-help information · Not legal advice",
  ft_brand: "Expungement.ai, from LegalEase",
  ft_blurb: "Expungement.ai helps people explore supported record-clearing paths and prepare available self-help documents and filing guidance.",
  ft_product: "Product",
  ft_check: "Check my options",
  ft_resources: "Resources",
  ft_sample: "Sample packet",
  ft_legal: "Legal",
  ft_pp: "Privacy policy",
  ft_tos: "Terms of service",
  ft_contact: "Contact us",
  ft_disc: "Expungement.ai is not a law firm and is not a substitute for the advice of an attorney. We provide self-help document preparation and general information, not legal advice, and we do not represent you or file on your behalf. Using this site does not create an attorney-client relationship. Available paths and outcomes depend on your individual circumstances and your state’s laws. If you need legal advice, consult a licensed attorney in your state.",
  ft_copy: "© 2026 Expungement.ai. All rights reserved.",
  ft_priv: "We do not sell your personal information.",
  sticky_cta: "Check my options",
  sticky_sl: "No account · No payment to start",
  home_label: "Expungement.ai home",
  primary_navigation: "Primary navigation",
  mobile_navigation: "Mobile navigation",
  language_selector: "Choose language",
  language_english: "Use English",
  language_spanish: "Usar español",
  v3_announce: "Free screening. No account or payment to start.",
  hero_facts_label: "Three facts about starting",
  hero_fact_account: "No account to begin",
  hero_fact_account_detail: "Begin before creating a login.",
  hero_fact_payment: "No payment to start",
  hero_fact_payment_detail: "Review the screening result first.",
  hero_fact_coverage: "50 states + D.C. screening",
  hero_fact_coverage_detail: "Packet availability depends on your result.",
  video_pause: "Pause background video",
  video_play: "Play background video",
  video_pause_short: "Pause video",
  video_play_short: "Play video",
  barrier_work: "Work and licensing",
  barrier_housing: "Housing",
  barrier_school: "School and training",
  barrier_work_alt: "A person standing beside tools in a workshop.",
  barrier_housing_alt: "A person reviewing household paperwork at a table.",
  barrier_school_alt: "A student writing beside a laptop in a library.",
  guided_caption: "Example from the free screening. Questions and explanations change based on your state and case.",
  how_packet_review: "Packet review",
  how_filing_steps: "Filing steps",
  packet_review_aria: "Example packet-information review",
  packet_review_state: "State",
  packet_review_answers: "From your answers",
  packet_review_court: "Court",
  packet_review_case: "From your case",
  packet_review_price: "Packet price",
  packet_review_next: "Next step",
  packet_review_before_payment: "Review before payment",
  filing_progress_aria: "Example filing progress",
  filing_review: "Review",
  filing_prepare: "Prepare",
  filing_file: "File it",
  filing_court: "Court",
  brief_progress_aria: "Example Briefcase progress detail",
  pc_h4: "Court instructions",
  pc_p4: "Where and how to file for the supported court.",
  packet_scope: "Depending on your state, court, case, and result, a packet may include these documents and instructions.",
  document_set_label: "Possible packet documents",
  document_selected_label: "Selected document",
  pricing_sequence_label: "Cost sequence",
  price_guided_label: "Free screening",
  price_guided_detail: "See which supported record-clearing paths may be available.",
  price_packet_label: "Supported self-help packet",
  price_packet_detail: "One supported packet for one case, after you review the packet information.",
  price_court_label: "Court filing fee",
  price_court_detail: "Court fees are separate. Fee-waiver guidance appears when available.",
  price_varies: "Varies",
  privacy_practices_label: "Privacy practices",
  privacy_practice_label: "Practice",
  pv0_detail: "You can start the screening before creating a login.",
  pv1_detail: "The screening comes before checkout.",
  pv2_detail: "You can read the privacy policy before the screening requests sensitive information.",
  pv3_detail: "You choose whether to create an account, save your work, and continue.",
  pv4: "We do not sell your personal information",
  pv4_detail: "We do not sell your personal information.",
  pv5_detail: "Support is available in calm, plain language without judgment.",
  wl_demo_aria: "Illustrative Wilma conversation",
  wl_illustrative: "Illustrative example.",
  coverage_reference_label: "Selected jurisdiction",
  coverage_matrix_label: "Choose a state or the District of Columbia",
  coverage_selected: "selected",
  coverage_guided_heading: "{state} screening",
  coverage_question_count: "Up to {count} plain-English questions",
  coverage_topics_heading: "You may be asked about",
  coverage_start_state: "Start the {state} check",
  coverage_no_account: "No account or payment is required to begin.",
  coverage_packet_boundary: "Packet availability depends on your answers, court, case, and result.",
  coverage_selected_announcement: "{state} selected. The panel now shows up to {count} questions and state-specific topics.",
  footer_legalease_label: "A LegalEase product",
  footer_legalease_link_label: "Visit the LegalEase homepage",
  _title: "Expungement.ai | Free guided record-clearing check",
  _desc: "Check your record-clearing options for free. No account required. If a supported self-help packet is available, review your information before paying $50 to generate it."
};

export const APPROVED_LANDING_COPY_ES: Record<string, string> = {
  skip_main: "Saltar al contenido principal",
  site_notice: "Aviso del sitio",
  menu_open: "Abrir menú",
  menu_close: "Cerrar menú",
  hero_alt: "Una carretera abierta conduce hacia el amanecer entre dos montañas.",
  guided_check_alt: "Pregunta de ejemplo de la evaluación gratuita.",
  packet_result_alt: "Resultado de ejemplo que muestra que podría haber un paquete de autoayuda disponible.",
  briefcase_alt: "Ejemplo de un Maletín gratuito con casos, documentos y próximos pasos.",
  wilma_alt: "Wilma, la guía de presentación de Expungement.ai.",
  announce: '<span class="gold">Evaluación gratuita</span>: no necesita cuenta ni pago para comenzar.',
  announce_cta: "Ver mis opciones",
  nav_how: "Cómo funciona",
  nav_brief: "Qué incluye",
  nav_pricing: "Precio",
  nav_privacy: "Confianza y privacidad",
  nav_faq: "Preguntas",
  nav_login: "Iniciar sesión",
  nav_cta: "Ver mis opciones",
  m_cta: "Ver mis opciones",
  hero_eyebrow: "EVALUACIÓN GRATUITA",
  hero_h1: "La ley es complicada. Su próximo paso no debería serlo.",
  hero_sub: "Consulte sus opciones para limpiar antecedentes, gratis. No necesita una cuenta. Responda preguntas claras sobre su estado, caso y resultado. Si hay un paquete de autoayuda disponible, revise su información antes de pagar $50 para generarlo.",
  hero_cta1: "Ver mis opciones",
  hero_cta2: "Ver un paquete de ejemplo",
  hero_micro: "Sin cuenta para comenzar · Sin pago para empezar · Revisiones guiadas gratis en los 50 estados y D.C.",
  hero_disclaimer: "Preparación de documentos de autoayuda. No somos un bufete de abogados. El tribunal o la agencia toma la decisión final.",
  hero_story_label: "Cómo funciona el producto",
  hero_story_tabs_label: "Elija un ejemplo del producto",
  hero_story_guided: "Evaluación gratuita",
  hero_story_briefcase: "Maletín gratuito",
  hero_story_packet: "Paquete de autoayuda",
  hero_story_example: "Ejemplo",
  hero_story_case: "Ejemplo de un caso disponible",
  hero_story_case_status: "Información del paquete en curso",
  hero_story_case_free: "Su Maletín es gratuito.",
  hero_story_case_next: "Siguiente paso: Continúe con la información del paquete",
  hero_story_packet_status: "Información del paquete revisada",
  hero_story_packet_price: "$50 una sola vez por este caso",
  hero_story_packet_kind: "Paquete de autoayuda disponible",
  hero_story_packet_fees: "Las tasas del tribunal se pagan por separado",
  hero_story_packet_subscription: "Sin suscripción",
  strip_h0: "Evaluación gratuita",
  strip_p0: "Vea qué opciones para limpiar antecedentes podrían estar disponibles antes de gastar dinero.",
  strip_h1: "Comience sin una cuenta",
  strip_p1: "Inicie la evaluación antes de crear una cuenta.",
  strip_h2: "Pasos de presentación para su tribunal",
  strip_p2: "Vea qué presentar, dónde hacerlo y qué tasas o exenciones podrían corresponder.",
  strip_h3: "Paquete de autoayuda por $50",
  strip_p3: "Su Maletín es gratis. Sin suscripción. Las tasas del tribunal se pagan por separado.",
  prob_eye: "La barrera",
  prob_h2: "El caso terminó. El antecedente aún puede aparecer.",
  prob_lead: "Un arresto, una desestimación, un delito menor o una condena aún puede aparecer en una verificación de antecedentes y afectar el trabajo, la vivienda, los estudios o las licencias. Expungement.ai le ayuda a explorar qué opciones podrían estar disponibles y le muestra el próximo paso.",
  prob_cta: "Ver mis opciones",
  fade0: "Trabajo",
  fade1: "Vivienda",
  fade2: "Estudios y licencias",
  fade3: "Explore posibles próximos pasos",
  elig_eye: "Evaluación gratuita",
  elig_h2: "Comience con lo que sabe. Le guiaremos con lo demás.",
  elig_lead: "No necesita conocer vocabulario legal para comenzar. Hacemos preguntas claras, explicamos términos confusos y le permitimos elegir “No estoy seguro” cuando no tenga una respuesta. Si los hechos no respaldan una opción clara, la revisión se detiene antes del pago.",
  elig_b0: "Elija “No estoy seguro” cuando no sepa",
  elig_b1: "Vea explicaciones a medida que avanza",
  elig_b2: "Deténgase en cualquier momento",
  elig_b3: "No necesita una cuenta para comenzar",
  elig_cta: "Ver mis opciones",
  mock_title: "Ejemplo de la evaluación gratuita",
  mock_step: "Pregunta de ejemplo",
  mock_q: "¿Qué pasó con el caso?",
  chip0: "Desestimado",
  chip1: "No culpable",
  chip2: "Solo arresto",
  chip3: "Culpable o condenado",
  chip4: "Aún abierto",
  chip5: "No estoy seguro",
  mock_tip: "Las preguntas y explicaciones cambian según su estado y caso.",
  how_eye: "Cómo funciona",
  how_h2: "Tres pasos. Sin laberintos legales.",
  how_h0: "1. Vea qué opciones podrían estar disponibles.",
  how_p0: "Responda preguntas claras sobre su estado, caso y resultado. La revisión muestra si podría haber una opción disponible antes de pagar.",
  how_h1: "2. Genere un paquete de autoayuda disponible.",
  how_p1: "Primero revise la información del paquete. Luego pague $50 para generar los documentos e instrucciones disponibles para su caso.",
  how_h3: "3. Preséntelo usted mismo con pasos claros.",
  how_p2: "Descargue el paquete, siga la lista de su tribunal y use el Maletín para saber qué está listo, presentado o en espera.",
  how_cta: "Ver mis opciones",
  brief_eye: "Su Maletín",
  brief_h2: "Sus documentos y próximos pasos, en un solo lugar.",
  brief_lead: "Términos legales explicados. Documentos organizados. Un próximo paso a la vez. Su Maletín gratuito mantiene juntos cada caso guardado, los documentos disponibles y los pasos de presentación.",
  brief_b0: "Vea cada caso y su etapa actual",
  brief_b1: "Descargue los documentos de autoayuda disponibles",
  brief_b2: "Siga las instrucciones incluidas en su paquete",
  brief_b3: "Controle qué está listo, presentado o en espera",
  brief_b4: "Pida a Wilma que explique pasos confusos con palabras claras",
  brief_cta: "Vea cómo funciona el Maletín",
  brief_demo_label: "Maletín de ejemplo",
  brief_demo_note: "Esta demostración usa un caso ficticio y no contiene información real de ninguna persona.",
  brief_demo_tabs_label: "Etapas del Maletín de ejemplo",
  brief_demo_case: "Ejemplo de un caso disponible",
  brief_demo_next: "Siguiente paso",
  brief_demo_s0: "Asunto guardado",
  brief_demo_s1: "Información del paquete en curso",
  brief_demo_s2: "Listo para revisar",
  brief_demo_s3: "Paquete listo",
  brief_demo_n0: "Revise su resultado",
  brief_demo_n1: "Continúe con la información del paquete",
  brief_demo_n2: "Revise antes de pagar",
  brief_demo_n3: "Descargue el paquete",
  pk_eye: "Qué incluye",
  pk_h2: "Un paquete de autoayuda creado con sus respuestas.",
  pk_lead: "Las reglas cambian según el estado, tribunal, tipo de caso y resultado. Cuando hay un paquete disponible, Expungement.ai usa sus respuestas para generar los documentos e instrucciones disponibles para ese caso.",
  pk_b0: "Evaluación específica para su estado",
  pk_b1: "Documentos de autoayuda disponibles",
  pk_b2: "Pasos para el tribunal correspondiente",
  pk_b3: "Explicaciones con palabras claras",
  pk_b4: "Información sobre exención de tasas cuando esté disponible",
  pk_b5: "Límites claros cuando podría necesitar ayuda legal",
  pc_h0: "Petición",
  pc_p0: "Su solicitud para limpiar antecedentes",
  pc_h1: "Orden propuesta",
  pc_p1: "Un documento que el juez puede firmar",
  pc_h2: "Lista de presentación",
  pc_p2: "Dónde presentar, qué llevar y qué esperar",
  pc_h3: "Información sobre exención de tasas",
  pc_p3: "Cómo pedir que el tribunal exima las tasas cuando exista esa opción",
  sm_eye: "Paquete de ejemplo",
  sm_h2: "Vea un ejemplo antes de pagar.",
  sm_lead: "El ejemplo muestra los tipos de documentos y las instrucciones que puede contener un paquete disponible. Su paquete dependerá de su estado, tribunal, caso y resultado.",
  sm_cta: "Ver paquete de ejemplo",
  sm_fine: "Solo es un ejemplo. Sus documentos dependerán de su estado, tribunal, caso y opción disponible.",
  tab0: "Petición",
  tab1: "Lista de presentación",
  tab2: "Exención de tasas",
  tab3: "Instrucciones del tribunal",
  tab4: "Próximos pasos",
  pr_eye: "Precio",
  pr_h2: "$50 por un paquete de autoayuda disponible.",
  pr_intro: "La evaluación, el Maletín y la revisión de la información del paquete no cuestan nada. Pague solo cuando haya un paquete listo para generar.",
  pr_sub: "por paquete de autoayuda disponible",
  pr_included: "Incluye",
  pr_free: "Su evaluación, Maletín y revisión de la información del paquete siguen siendo gratis.",
  prl0: "Evaluación gratuita",
  prl1: "Documentos judiciales de autoayuda disponibles",
  prl2: "Instrucciones para el tribunal correspondiente",
  prl3: "Información sobre exención de tasas cuando esté disponible",
  prl4: "Seguimiento en el Maletín",
  prl5: "Explicaciones claras de Wilma",
  pr_not_included: "No incluye",
  prx0: "Tasas de presentación del tribunal",
  prx1: "Estrategia o representación de un abogado",
  prx2: "Presentación en su nombre o cualquier promesa sobre el resultado",
  pr_fine: "Sin suscripción. Las tasas del tribunal se pagan por separado. Algunos tribunales ofrecen exenciones. Cuando estén disponibles, sus instrucciones explican cómo solicitarlas.",
  pr_cover_h: "Qué cubren los $50",
  pr_cover_p: "Expungement.ai prepara documentos de autoayuda e instrucciones disponibles. Usted los presenta. No se incluyen estrategia legal, representación, tasas del tribunal ni aprobación judicial.",
  pr_cta: "Ver mis opciones",
  pv_eye: "Confianza y privacidad",
  pv_h2: "Su antecedente es sensible. Su privacidad debe ser clara.",
  pv_lead: "Comience la evaluación sin crear una cuenta. Pedimos la información necesaria para revisar las opciones disponibles y preparar un paquete. No vendemos su información personal.",
  pv0: "No necesita una cuenta para comenzar",
  pv1: "No necesita pagar para empezar",
  pv2: "La política de privacidad está disponible antes de los datos sensibles",
  pv3: "Usted decide si guarda y continúa",
  pv5: "Apoyo humano sin juicios",
  pv_cta: "Leer nuestra política de privacidad",
  wl_eye: "Su guía de presentación",
  wl_h2: "Conozca a Wilma, su guía de presentación con palabras claras.",
  wl_lead: "Wilma explica pasos confusos, define términos legales y le devuelve a su lista. No decide qué opción podría estar disponible, no reemplaza a un abogado ni promete un resultado judicial.",
  wl_p0: "¿Qué significa desestimado en mi estado?",
  wl_p1: "¿Dónde presento este paquete?",
  wl_p2: "¿Qué debo llevar al tribunal?",
  wl_p3: "¿Cómo pregunto por una exención de tasas?",
  wl_p4: "¿Qué pasa después de presentar?",
  wl_safe: "Wilma ofrece información general de autoayuda, no asesoría legal.",
  wl_action: "Vea cómo lo explica Wilma",
  wl_action_close: "Cerrar la explicación de Wilma",
  wl_example: "Ejemplo de explicación",
  wl_you: "Usted",
  wl_q: "¿Qué significa “presentar ante el tribunal”?",
  wl_a: "Significa entregar su paquete completo al tribunal. Siga las instrucciones incluidas con su paquete y confirme los requisitos actuales con el tribunal.",
  st_eye: "Cobertura",
  st_h2: "Revisiones guiadas gratis en los 50 estados y D.C.",
  st_lead: "Comience con su estado, tipo de antecedente, resultado y fechas. La revisión busca opciones respaldadas antes de que pague. La disponibilidad del paquete depende de su estado, tribunal, caso y resultado.",
  st_choose: "Elija su estado",
  st_result: "Preguntaremos sobre el tipo de antecedente, resultado, fechas y requisitos del tribunal.",
  st_lab: "Estados y distrito disponibles",
  fq_eye: "Preguntas",
  fq_h2: "Lo que la gente pregunta antes de comenzar",
  fq_q0: "¿Esto es legítimo?",
  fq_a0: "Expungement.ai es un producto de preparación de documentos de autoayuda. La revisión busca opciones disponibles, y los paquetes disponibles incluyen documentos e instrucciones. Expungement.ai no es un bufete, no le representa ni presenta documentos en su nombre.",
  fq_q1: "¿Necesito un abogado?",
  fq_a1: "No siempre. Expungement.ai ofrece documentos de autoayuda e información general, no asesoría legal. Si su caso es complicado o necesita estrategia o representación, hable con un abogado con licencia en su estado.",
  fq_q2: "¿Qué está disponible en mi estado?",
  fq_a2: "La evaluación gratuita está disponible en los 50 estados y D.C. No hay un paquete pagado para cada caso. La disponibilidad depende de su estado, tribunal, caso y resultado.",
  fq_q3: "¿Qué cubren los $50?",
  fq_a3: "Los $50 cubren un paquete de autoayuda para un caso, con los documentos e instrucciones disponibles. La evaluación, el Maletín y la revisión de información son gratis. Las tasas del tribunal se pagan por separado.",
  fq_q4: "¿Qué pasa si el tribunal rechaza mi solicitud?",
  fq_a4: "El tribunal o la agencia toma la decisión final y no se garantiza la aprobación. Expungement.ai no le representa. Si necesita consejo sobre un rechazo o su próximo paso legal, hable con un abogado con licencia.",
  fq_q5: "¿Cómo se usa mi información?",
  fq_a5: "Pedimos la información necesaria para revisar las opciones disponibles, guardar su trabajo cuando usted lo elija y preparar un paquete. No vendemos su información personal. Lea nuestra política de privacidad para conocer los detalles.",
  fq_q6: "¿Expungement.ai es un bufete de abogados?",
  fq_a6: "No. Expungement.ai es software de preparación de documentos de autoayuda. No ofrece representación legal, no le representa ni presenta documentos en su nombre.",
  fn_h2: "Comience con lo que pasó. Vea qué podría estar disponible.",
  fn_p: "La evaluación es gratis. No necesita una cuenta para comenzar. Si hay un paquete disponible, revise su información antes de decidir si paga $50 para generarlo.",
  fn_cta: "Ver mis opciones",
  fn_micro: "Sin cuenta · Sin pago para empezar · Información de autoayuda · No es asesoría legal",
  ft_brand: "Expungement.ai, de LegalEase",
  ft_blurb: "Expungement.ai ayuda a explorar opciones disponibles y a preparar documentos de autoayuda e instrucciones de presentación.",
  ft_product: "Producto",
  ft_check: "Ver mis opciones",
  ft_resources: "Recursos",
  ft_sample: "Paquete de ejemplo",
  ft_legal: "Legal",
  ft_pp: "Política de privacidad",
  ft_tos: "Términos de servicio",
  ft_contact: "Contáctenos",
  ft_disc: "Expungement.ai no es un bufete de abogados ni sustituye el consejo de un abogado. Ofrecemos preparación de documentos de autoayuda e información general, no asesoría legal, y no le representamos ni presentamos documentos en su nombre. Usar este sitio no crea una relación abogado-cliente. Las opciones y los resultados dependen de sus circunstancias y de las leyes de su estado. Si necesita asesoría legal, consulte a un abogado con licencia en su estado.",
  ft_copy: "© 2026 Expungement.ai. Todos los derechos reservados.",
  ft_priv: "No vendemos su información personal.",
  sticky_cta: "Ver mis opciones",
  sticky_sl: "Sin cuenta · Sin pago para empezar",
  home_label: "Página principal de Expungement.ai",
  primary_navigation: "Navegación principal",
  mobile_navigation: "Navegación móvil",
  language_selector: "Elegir idioma",
  language_english: "Usar inglés",
  language_spanish: "Usar español",
  v3_announce: "Evaluación gratuita. No necesita una cuenta ni pagar para comenzar.",
  hero_facts_label: "Tres datos sobre cómo comenzar",
  hero_fact_account: "Sin cuenta para comenzar",
  hero_fact_account_detail: "Comience antes de crear un inicio de sesión.",
  hero_fact_payment: "Sin pago para empezar",
  hero_fact_payment_detail: "Primero revise el resultado de la evaluación.",
  hero_fact_coverage: "Evaluación en 50 estados + D.C.",
  hero_fact_coverage_detail: "La disponibilidad del paquete depende de su resultado.",
  video_pause: "Pausar el video de fondo",
  video_play: "Reproducir el video de fondo",
  video_pause_short: "Pausar video",
  video_play_short: "Reproducir video",
  barrier_work: "Trabajo y licencias",
  barrier_housing: "Vivienda",
  barrier_school: "Estudios y capacitación",
  barrier_work_alt: "Una persona de pie junto a herramientas en un taller.",
  barrier_housing_alt: "Una persona revisa documentos del hogar en una mesa.",
  barrier_school_alt: "Una estudiante escribe junto a una computadora portátil en una biblioteca.",
  guided_caption: "Ejemplo de la evaluación gratuita. Las preguntas y explicaciones cambian según su estado y caso.",
  how_packet_review: "Revisión del paquete",
  how_filing_steps: "Pasos de presentación",
  packet_review_aria: "Ejemplo de revisión de la información del paquete",
  packet_review_state: "Estado",
  packet_review_answers: "Según sus respuestas",
  packet_review_court: "Tribunal",
  packet_review_case: "Según su caso",
  packet_review_price: "Precio del paquete",
  packet_review_next: "Siguiente paso",
  packet_review_before_payment: "Revisar antes de pagar",
  filing_progress_aria: "Ejemplo de progreso de presentación",
  filing_review: "Revisar",
  filing_prepare: "Preparar",
  filing_file: "Presentar",
  filing_court: "Tribunal",
  brief_progress_aria: "Detalle de progreso del Maletín de ejemplo",
  pc_h4: "Instrucciones del tribunal",
  pc_p4: "Dónde y cómo presentar ante el tribunal correspondiente.",
  packet_scope: "Según su estado, tribunal, caso y resultado, un paquete puede incluir estos documentos e instrucciones.",
  document_set_label: "Posibles documentos del paquete",
  document_selected_label: "Documento seleccionado",
  pricing_sequence_label: "Secuencia de costos",
  price_guided_label: "Evaluación gratuita",
  price_guided_detail: "Vea qué opciones disponibles para limpiar antecedentes podrían corresponder.",
  price_packet_label: "Paquete de autoayuda disponible",
  price_packet_detail: "Un paquete disponible para un caso, después de revisar la información del paquete.",
  price_court_label: "Tasa de presentación del tribunal",
  price_court_detail: "Las tasas del tribunal se pagan por separado. La información sobre exenciones aparece cuando está disponible.",
  price_varies: "Varía",
  privacy_practices_label: "Prácticas de privacidad",
  privacy_practice_label: "Práctica",
  pv0_detail: "Puede comenzar la evaluación antes de crear un inicio de sesión.",
  pv1_detail: "La evaluación ocurre antes del pago.",
  pv2_detail: "Puede leer la política de privacidad antes de que la evaluación solicite información sensible.",
  pv3_detail: "Usted elige si crea una cuenta, guarda su trabajo y continúa.",
  pv4: "No vendemos su información personal",
  pv4_detail: "No vendemos su información personal.",
  pv5_detail: "El apoyo está disponible con palabras claras, calma y sin juicios.",
  wl_demo_aria: "Conversación ilustrativa con Wilma",
  wl_illustrative: "Ejemplo ilustrativo.",
  coverage_reference_label: "Jurisdicción seleccionada",
  coverage_matrix_label: "Elija un estado o el Distrito de Columbia",
  coverage_selected: "seleccionado",
  coverage_guided_heading: "Evaluación de {state}",
  coverage_question_count: "Hasta {count} preguntas con palabras claras",
  coverage_topics_heading: "Podríamos preguntarle sobre",
  coverage_start_state: "Comenzar la revisión de {state}",
  coverage_no_account: "No necesita una cuenta ni hacer un pago para comenzar.",
  coverage_packet_boundary: "La disponibilidad del paquete depende de sus respuestas, el tribunal, el caso y el resultado.",
  coverage_selected_announcement: "{state} seleccionado. El panel ahora muestra hasta {count} preguntas y temas específicos del estado.",
  footer_legalease_label: "Un producto de LegalEase",
  footer_legalease_link_label: "Visitar la página principal de LegalEase",
  _title: "Expungement.ai | Evaluación gratuita",
  _desc: "Comience una evaluación gratuita. Si hay un paquete de autoayuda disponible, revise su información antes de pagar $50 para generarlo."
};
