// Wisconsin eligibility rules. Sourced from the "Wisconsin Expungement — Wilma
// Agent Training Reference" (Nationwide Record Clearing / LegalEase Wisconsin),
// corroborated by the cited Wisconsin Statutes (Wis. Stat.) sections, the official
// Wisconsin Court System CR-266/CR-267 forms, and Wisconsin DOJ criminal-history
// guidance. Citations are Wis. Stat. unless otherwise noted.
export const wiEligibilityRules = [
  "Wisconsin is one of the NARROWEST expungement states. Adult conviction expungement under Wis. Stat. § 973.015 usually must be ordered by the judge AT SENTENCING. If expungement was not ordered at sentencing, treat the adult conviction as likely not expungeable later — Wisconsin case law says the § 973.015 expungement decision must be made at sentencing and the circuit court generally cannot revisit it later — unless the case fits the human-trafficking/prostitution route.",
  "What Wisconsin expungement does: it usually removes/seals the COURT record of the conviction from public court access (Wisconsin Circuit Court Access / WCCA, also called CCAP). It does NOT vacate the conviction or set it aside, and it does not erase every government record. The CR-266 form warns that only the court record of conviction is expunged — police, Crime Information Bureau, law-enforcement, and district-attorney records are not affected, and the conviction is not vacated or set aside.",
  "Adult conviction expungement basic eligibility (Wis. Stat. § 973.015): the person was UNDER 25 at the time of the offense; the maximum imprisonment for the offense was 6 years or less; the court ordered expungement at sentencing; the court found the person would benefit and society would not be harmed; and the person successfully completes the sentence. Successful completion means no subsequent conviction before completion, probation not revoked (if applicable), probation conditions satisfied, and sentence terms complete; the sentence must be fully completed before expungement takes effect.",
  "Execution after successful completion: for cases with probation or jail/prison, the detaining or probationary authority issues a certificate of discharge and forwards it to the court, which has the effect of expunging the record — confirm DOC or the correctional/detaining authority sent the certificate of discharge to the clerk. For cases with NO probation and NO incarceration, CR-266 (Petition to Expunge Criminal Court Record of Conviction — Non-Probation/Non-Incarceration) and proposed CR-267 (Order) are the standardized forms to ask the court to expunge the conviction record after successful completion.",
  "Mandatory youthful invasion-of-privacy route (Wis. Stat. § 973.015 with § 942.08(2)(b), (c), (d), or (3)): if the offense was certain invasion-of-privacy conduct and the person was under 18 when it was committed, the court SHALL order expungement at sentencing upon successful completion.",
  "Felony exclusions (Wis. Stat. § 973.015): for Class H felonies, the court may not order expungement if the person has a prior felony, the offense is a violent offense, or the offense is stalking, certain child-abuse offenses, or sexual assault by school staff. For Class I felonies, the court may not order expungement if the person has a prior felony, the offense is violent, or the offense is concealing the death of a child.",
  "Human-trafficking / prostitution relief (Wis. Stat. § 973.015(2m)): a person convicted, adjudicated delinquent, or found not guilty by reason of mental disease or defect for prostitution under § 944.30, where the offense was committed as a result of being a victim of trafficking for a commercial sex act, may move the court to VACATE the conviction/adjudication/finding or expunge the record. The motion must show the trafficking-victim status, the § 944.30 nexus, due diligence (considering safety), notice to and an opportunity to respond for the district attorney, and that the person will benefit and society will not be harmed. This is a special manual-review route.",
  "Adult non-conviction / arrest-only records: these are NOT handled through § 973.015. They route to Wisconsin DOJ-CIB fingerprint/arrest removal (Wis. Stat. § 165.84). A person may qualify if they were arrested and released without charge, found not guilty, had charges dismissed by the court or prosecutor, or no charges were filed. The request uses DJ-LE-250B, requires fingerprints, and has no fee; if the Wisconsin arrest information had been forwarded to the FBI, the FBI is contacted to remove it. All charges from the arrest event must be cleared — if one charge from the same arrest resulted in conviction, DOJ-CIB removal may be blocked. A conviction ordered expunged by a court CANNOT be removed from the Wisconsin criminal-history repository because the conviction disqualifies that arrest for removal.",
  "Juvenile adjudication expungement (Wis. Stat. § 938.355(4m)): a juvenile adjudicated delinquent may petition after reaching age 17 to expunge the court record of the adjudication, using JD-1780; the court may expunge if the juvenile satisfactorily completed the dispositional order, the juvenile will benefit, and society will not be harmed.",
  "Pardon route: a Wisconsin pardon is separate from expungement. Wisconsin DOJ says a pardon will not remove the arrest from the criminal-history record; the disposition shows that a Governor's pardon was issued and may restore certain rights. If a person says they were pardoned, do not say the record is expunged — route to pardon notation, rights restoration, and criminal-history update review.",
  "Civil and traffic matters: the Wisconsin expungement statute does not cover civil forfeitures, traffic citations, small claims, or civil cases.",
  "Scope limits: Wisconsin expungement removes the court record of conviction from public court access but does not remove DOJ-CIB, police, district-attorney, DOT, FBI, or private-background records, does not restore firearm rights, and does not by itself fix immigration consequences."
];
