// Wisconsin filing workflow. Sourced from the "Wisconsin Expungement — Wilma Agent
// Training Reference" (Nationwide Record Clearing), section 12, corroborated by Wis.
// Stat. § 973.015, § 938.355(4m), § 165.84, and the official Wisconsin Court System
// CR-266/CR-267 forms and Wisconsin DOJ-CIB guidance. Wisconsin uses official forms
// and the DOJ-CIB process; this pack is shadow-only research and wires no renderer.
export const wiFilingInstructions = [
  "Classify the matter first: adult conviction, juvenile adjudication, or non-conviction (dismissed/no-file/not-guilty arrest); confirm whether it is a civil forfeiture or traffic matter (not covered by the criminal expungement statute).",
  "Adult conviction where expungement was ordered at sentencing: (1) confirm the sentencing court ordered expungement; (2) confirm the sentence was successfully completed; (3) confirm no subsequent conviction occurred before completion; (4) if probation/incarceration existed, verify the certificate of discharge was sent to the clerk; (5) if no probation/incarceration existed, prepare CR-266 (Petition to Expunge Criminal Court Record of Conviction — Non-Probation/Non-Incarceration) and proposed CR-267 (Order); (6) file in the same circuit court case; (7) confirm the court record is removed from WCCA/CCAP public access.",
  "Mandatory youthful invasion-of-privacy route (§ 942.08): confirm the offense and that the person was under 18; the court shall order expungement at sentencing upon successful completion.",
  "Arrest-only / dismissed / not-guilty / no-file: (1) get the DOJ criminal-history record; (2) confirm the arrest event and all charges tied to that fingerprint card; (3) collect disposition/no-prosecution documents; (4) complete DJ-LE-250B (Fingerprint Record Removal Request) with the required fingerprint; (5) submit to Wisconsin DOJ-CIB; (6) if an FBI record was involved, confirm DOJ transmitted the removal. If one charge from the same arrest resulted in conviction, removal may be blocked.",
  "Juvenile adjudication (§ 938.355(4m)): (1) confirm age 17 or older; (2) confirm the dispositional order was completed; (3) prepare JD-1780 (Petition to Expunge Court Record of Adjudication / Recommendation of District Attorney); (4) seek the district attorney recommendation if required by local practice/form; (5) file in the juvenile court case; (6) attend a hearing if required.",
  "Trafficking-victim prostitution relief (§ 973.015(2m)): file a motion to vacate or expunge with supporting facts (which may include court records, immigration-related certifications, official government documentation, or other credible evidence), serve/notify the district attorney, and route to manual/legal review.",
  "Pardon route: a pardon does not expunge the record. Route to pardon notation, rights restoration, and a criminal-history-update review; do not file an expungement petition on the theory that a pardon erased the record.",
  "Record request: start with two records — Wisconsin Circuit Court Access (WCCA/CCAP) for the case details, and the Wisconsin DOJ-CIB criminal history for fingerprint-supported arrest/conviction information. Capture age at offense, the maximum possible imprisonment, the sentencing date, whether the judge ordered expungement at sentencing, the sentence type, and the sentence completion date."
];
