// Minnesota eligibility rules. Sourced from the Minnesota Expungement Reference
// for Wilma (Nationwide Record Clearing), corroborated by Minn. Stat. Chapter
// 609A (Revisor) and Minnesota Courts guidance. Citations are Minn. Stat.
export const mnEligibilityRules = [
  "In Minnesota, expungement generally means sealing criminal records from public view; it does not destroy the record. Courts, law enforcement, prosecutors, the BCA (Bureau of Criminal Apprehension), and some agencies may still access or reopen sealed records in legally permitted circumstances. Minnesota expungement law is mainly in Minn. Stat. Chapter 609A, which was affected by the 2026 Regular Session (including § 609A.015, subd. 5) — always prompt a final statute/form check before filing.",
  "Path A — Arrest, no charges filed (§ 299C.11): if the person was only arrested and no charges were filed, there may be no court case to expunge; instead the person may request destruction of arrest identification data (fingerprints, photographs, identification records). This generally applies when the prosecutor declined charges or charges were dismissed before a probable-cause determination, and the person has no felony or gross-misdemeanor conviction in the preceding 10 years.",
  "Path B — Mistaken identity (§ 609A.017): if the prosecutor dismisses or moves to dismiss before conviction and states the dismissal is due to mistaken identity (identity theft, misuse of identifying information, witness/law-enforcement misidentification, etc.), the court must issue an expungement order without a petition.",
  "Path C — Automatic Clean Slate (§ 609A.015): the BCA identifies potentially eligible cases, notifies the Judicial Branch, and qualifying records are sealed without a petition unless a court order prohibits sealing or the record is later found ineligible. Automatic Clean Slate relief does NOT automatically seal records held by the Commissioners of Children, Youth, and Families (DCYF); Health; or Human Services (DHS) — those may still require a petition.",
  "Path D — Cannabis (§§ 609A.055, 609A.06): certain nonfelony cannabis records are automatically expunged by the BCA under § 609A.055 without an application. Felony and some other cannabis cases go to the Cannabis Expungement Board under § 609A.06, which reviews eligible cases (often anonymously) and decides whether to expunge, vacate, dismiss, or resentence based on cannabis-law changes after August 1, 2023.",
  "Path E — Prosecutor agreement (§ 609A.025): if the prosecutor agrees to sealing for a person eligible under § 609A.02, subd. 3, the court may seal without a full petition unless public-safety interests outweigh the person's interests; the prosecutor must make a good-faith effort to notify victims and allow objection. Treat this as an attorney/prosecutor-negotiated route, not a default self-help route.",
  "Path F — Petition-based expungement (§ 609A.03, eligibility under § 609A.02): available where automatic expungement does not apply, has not happened yet, or does not cover the agencies the person needs (including records involving DHS/DCYF).",
  "Petition eligibility (§ 609A.02): (A) all pending actions/proceedings resolved in the person's favor — but a verdict of not guilty by reason of mental illness is NOT a resolution in favor; (B) diversion or stay of adjudication, after successful completion with no new crime charged for at least 1 year; (C) petty-misdemeanor or misdemeanor conviction, after no new conviction for at least 2 years after discharge of the sentence; (D) gross-misdemeanor conviction, after at least 3 years after discharge; (E) certain felonies listed in § 609A.02, subd. 3(b) (and some felonies later deemed gross misdemeanors/misdemeanors), with 4- or 5-year waits depending on offense.",
  "Listed-felony examples under § 609A.02, subd. 3(b) include certain controlled-substance possession offenses, some theft-related offenses, certain forgery/fraud offenses, third-degree burglary, criminal damage to property, failure to appear, receiving stolen goods, financial-transaction-card fraud, and other listed nonviolent/property/regulatory offenses. Verify the exact statute against § 609A.02, subd. 3(b) before marking a felony eligible; Minnesota does not make every felony expungeable.",
  "Registration bar (§ 243.166): a conviction requiring predatory/sex-offender registration under Minn. Stat. § 243.166 is not eligible for expungement under the felony petition list — escalate immediately if registration is mentioned.",
  "Automatic vs. petition: automatic eligibility is narrower than petition eligibility. A case may fail automatic Clean Slate screening but still be worth reviewing for petition-based expungement.",
  "Court standard (§ 609A.03): for most conviction-based petitions, expungement is an extraordinary remedy — the petitioner must prove by clear and convincing evidence that the benefit to them is commensurate with the disadvantages to the public and public safety. For cases resolved in the petitioner's favor or certain diversion/stay cases, the court generally grants expungement unless an agency proves that public or public-safety interests outweigh the disadvantages to the petitioner."
];
