// Ohio eligibility rules. Sourced from the Ohio Sealing & Expungement — Wilma
// Agent Training Reference (Nationwide Record Clearing), corroborated by the cited
// Ohio Rev. Code sections and Ohio Legal Help / Ohio Attorney General guidance.
// Citations are Ohio Rev. Code unless noted.
export const ohEligibilityRules = [
  "Ohio has BOTH sealing and expungement, and they are not the same. Sealing makes the record private from most employers, landlords, schools, and the general public but does not erase it (certain employers, licensing boards, prosecutors, judges, and police may still see it). Expungement is stronger: for many sections 'expunge' (§ 2953.31) means to destroy, delete, and erase a record so it is permanently irretrievable — but for § 2953.32 conviction expungements, BCI keeps a limited record for law-enforcement-employment qualification while other entities must destroy/delete/erase. Do not say 'completely gone from everywhere.'",
  "Adult conviction sealing/expungement (§ 2953.32): an eligible offender applies to the sentencing court (or a court of common pleas for an out-of-state/federal conviction) unless excluded by § 2953.32(A); the court checks timing, pending cases, rehabilitation, prosecutor/victim objections, and whether the person's interest outweighs legitimate government needs.",
  "Conviction waiting periods (§ 2953.32(B)): SEALING — one or two F3 convictions 3 years after final discharge; F4/F5 or misdemeanor 1 year; soliciting improper compensation (§ 2921.43) 7 years; person formerly subject to Chapter 2950 registration 5 years after registration ends; minor misdemeanor 6 months. EXPUNGEMENT — misdemeanor 1 year after final discharge; minor misdemeanor 6 months; felony 10 years after the date the person first becomes eligible to apply for sealing for that felony. Misdemeanor bail forfeiture — sealing any time after entry; expungement generally 1 year (6 months for minor misdemeanor). Calculate from final discharge, not the conviction date.",
  "Major conviction disqualifiers (§ 2953.32): likely ineligible/manual review if the conviction is in most traffic/motor-vehicle chapters (4506, 4507, 4510, 4511, 4549, or similar ordinances); a felony offense of violence that is not a sexually oriented offense; a sexually oriented offense while subject to Chapter 2950 registration; an offense where the victim was under 13 (except nonsupport under § 2919.21); theft in office (§ 2921.41); an F1 or F2; M1/M2 domestic violence (§ 2919.25 or similar ordinance); or an F3 where the person has too many other convictions under the statute's F3 counting rule. Some offenses are sealable but not expungeable, including M3/M4 domestic violence (§ 2919.25) and protection-order violations (§ 2919.27).",
  "Counting convictions (§ 2953.32): convictions connected with the same act or committed at the same time can count as one; two or three convictions from the same indictment/plea/proceeding involving related acts within three months may count as one unless the court finds that is not in the public interest. Never count cases by memory — get the full docket list and disposition dates.",
  "Non-conviction sealing/expungement (§ 2953.33): not guilty — any time after entry; dismissal — any time after the dismissal entry, subject to limitations and multiple-charge rules; grand-jury no bill — usually 2 years after the no bill is reported; governor pardon — any time after the pardon or after conditions are met. For dismissals the court determines whether the dismissal was with or without prejudice; if without prejudice it checks whether the statute of limitations has expired. A dismissal without prejudice where the SOL has not expired is not ready.",
  "Multiple charges from the same act (§ 2953.61): if a person was charged with two or more offenses from the same act and at least one charge has a different final disposition, they generally cannot seal/expunge only part of the record until they can seal/expunge all related charges (limited traffic exception). Ask for every charge and disposition before routing.",
  "Marijuana/hashish possession expungement (§ 2953.321, effective March 20, 2026): applies to certain dismissed/convicted/guilty-plea records for specified marijuana or hashish possession offenses under § 2925.11 (including hashish possession of not more than 15 grams for certain divisions). Apply to the sentencing court; the hearing is held 45-90 days after filing; the prosecutor may object; the filing fee is $50 unless indigent. Confirm the exact § 2925.11 division, substance, amount, and that the disposition occurred before the section's effective date.",
  "Human-trafficking-survivor conviction expungement (§ 2953.36): covers prostitution-related offenses (§§ 2907.24, 2907.241, 2907.25) and misdemeanor/F4/F5 convictions where participation resulted from trafficking victimization; may be filed any time and may request relief for more than one offense (each considered separately). Standard is preponderance for the prostitution category and clear and convincing for the broader category; excludes aggravated murder, murder, and rape (§§ 2903.01, 2903.02, 2907.02).",
  "Human-trafficking-survivor non-conviction expungement (§ 2953.521): a person found not guilty or named in a dismissed complaint/indictment/information may seek expungement if the case resulted from trafficking victimization; filable any time after the not-guilty/dismissal entry; the court checks the trafficking connection by preponderance, dismissal prejudice/SOL, pending proceedings, prosecutor objections, and government-interest balancing.",
  "Certain firearm/carry convictions (§ 2953.35): a narrow route for certain older firearm/carry convictions (specified former versions of §§ 2923.16, 2923.12); the court checks whether the conduct would no longer violate the provision; fee $50 unless indigent. Not a general firearm expungement.",
  "Prosecutor-initiated low-level controlled-substance (§ 2953.39): for certain Chapter 2925 violations that are M4 or minor misdemeanors (or equivalent ordinances), the PROSECUTOR may apply to seal/expunge after the corresponding § 2953.32 waiting period; the subject person and victim may object. This is prosecutor-initiated, not user-filed.",
  "Juvenile records (§§ 2151.356, 2151.358): records for delinquency adjudications involving aggravated murder, murder, or rape cannot be sealed (§ 2151.356); the juvenile court promptly seals records in several circumstances and can otherwise seal on motion/application once timing is met (no filing fee). Under § 2151.358, sealed juvenile records are expunged 5 years after the sealing order or upon the person's 23rd birthday, whichever is earlier, with earlier application possible on a showing of rehabilitation."
];
