// Montana eligibility rules. Sourced from the Montana Expungement Reference for
// Wilma (Nationwide Record Clearing), corroborated by the cited Mont. Code Ann.
// sections and Montana DOJ / Judicial Branch guidance. Citations are Mont. Code
// Ann. unless noted.
export const mtEligibilityRules = [
  "Montana record-clearing is not one pathway. Separate cases into misdemeanor conviction expungement (Title 46, ch. 18, part 11), non-conviction removal/sealing (§ 44-5-202), deferred-sentence dismissal/confidentiality (§ 46-18-204), and marijuana-related expungement/resentencing/redesignation (§ 16-12-113). For the misdemeanor statute, 'expunge' means to permanently destroy, delete, or erase a record from the Montana DOJ criminal-history record information system; 'record' excludes fingerprint records and data maintained for investigative purposes.",
  "Misdemeanor conviction expungement (§ 46-18-1104): a person convicted of one or more Montana misdemeanors may petition a District Court to expunge records of arrest, investigation, detention, and court proceedings related to the misdemeanor(s); the petition can cover misdemeanors from one or multiple courts/cases, but this Part 11 expungement may be used only ONCE in a lifetime — identify every misdemeanor to include before filing.",
  "Misdemeanor eligibility requirements: (1) one or more Montana misdemeanor convictions; (2) the sentence is complete (fines, jail, treatment, probation); (3) five years have passed since completion of all sentence terms; (4) no pending/open criminal case and the person is not jailed/charged for a new offense; and (5) no prior successful Montana misdemeanor expungement.",
  "Five-year rule (§ 46-18-1107): expungement is presumed if the person is not currently detained/charged/facing pending charges and either (a) has had no convictions in Montana, another state, or federal court for five years after completing the sentence terms (including financial obligations and court-ordered treatment); or (b) has applied to a U.S. military academy, applied to enlist in the armed forces/National Guard, or is currently serving and is being held back because of the conviction. Calculate the wait from the date all sentencing terms were completed, not the conviction date.",
  "Not-presumed offenses (§ 46-18-1108): expungement is NOT presumed (but not automatically barred) for convictions for assault (§ 45-5-201), partner or family member assault (§ 45-5-206), stalking (§ 45-5-220), sexual assault (§ 45-5-502), violation of a protective order (§ 45-5-626), DUI under Title 61 ch. 8 part 10, or any offense with an enhanced penalty because of DUI. For these, the court considers the petitioner's age at the offense, time since the offense, rehabilitation, likelihood of reoffending, and any other relevant factor.",
  "Court standard (§ 46-18-1109): the court decides by a preponderance of the evidence; a presumption of expungement may be overcome if public-safety interests demand denial. The prosecutor and any appearing victim must be given an opportunity to respond, and the formal rules of evidence do not apply at the hearing. The court can grant expungement for all, some, or none of the requested misdemeanors.",
  "Venue (§ 46-18-1105): the misdemeanor petition is filed in the District Court of a judicial district where the person was convicted of at least one misdemeanor for which expungement is sought; a person with convictions in different Montana courts may file where at least one conviction occurred and ask to expunge the whole misdemeanor record.",
  "Notice and victim rights (§ 46-18-1106): the petitioner must serve a copy of the petition on every prosecution office that prosecuted an offense for which expungement is requested; if there is a victim, the prosecution office must try to notify the victim within 14 days after receiving the petition and inform them of the right to respond.",
  "Non-conviction removal (§ 44-5-202): people whose charges were dismissed, deferred-prosecution dismissed, acquitted, dropped, or not filed can request CRISS to remove non-convictions; after July 1, 2017, CRISS automatically removes non-conviction arrest data, but a person may still request review if the record remains visible or incomplete. Do not route a non-conviction to the misdemeanor petition.",
  "Deferred-sentence dismissal (§ 46-18-204): for a felony deferred sentence the court must strike the guilty plea/verdict and dismiss the charge if no revocation petition was filed; for a misdemeanor deferred sentence the court may allow withdrawal of the plea or strike the verdict and dismiss. After dismissal, records become confidential criminal justice information, and public access requires a District Court order on good cause shown. If a deferred sentence has not been dismissed, contact the sentencing court to request dismissal first.",
  "Marijuana relief (§ 16-12-113, Montana Marijuana Regulation and Taxation Act): people convicted of acts that are now legal or punishable less severely may petition for expungement, resentencing, or redesignation. Use MMRTA Form A if currently serving the sentence (expungement/resentencing) and Form B if the sentence is completed (expungement/redesignation); a separate form is required for each conviction, filed in the court of conviction and served on the county attorney, who has 21 days to oppose.",
  "Felony (non-marijuana): Montana's standard misdemeanor expungement packet expressly does not cover felony convictions; Montana currently has no general process for expunging felony convictions except some marijuana-related felonies (or a deferred-sentence dismissal). Treat non-marijuana felonies as an escalation category.",
  "Scope limits: Montana relief does not remove federal/FBI records, clear Tribal-court or out-of-state convictions, remove private-background-check copies automatically, restore firearm rights, or fix immigration consequences; the misdemeanor packet expressly excludes out-of-state and Tribal-court convictions, and the statutory definition of 'record' excludes fingerprint and investigative data."
];
