// Approved pleading templates, keyed by template ID.
//
// A pleading template is jurisdiction-specific static legal language with
// placeholders for participant facts. It is deliberately NOT one national
// petition with the state name swapped: caption, authority, prayer and
// verification differ per jurisdiction and per mechanism.
//
// The renderer populates approved language with participant facts. It does not
// compose legal argument and makes no discretionary legal judgment beyond the
// template and the eligibility rules that selected it.
//
// No template in this registry has been approved by reviewing counsel. Each
// says so on its face, so a stray rendering cannot be mistaken for a filing.
// The `technical-fixture-*` entries are non-production fixtures that prove the
// renderer; the Mississippi entries are implementation Tranche 1 drafts awaiting
// counsel review.

export type PleadingSection = {
  heading?: string;
  numbered?: boolean;
  paragraphs: readonly string[];
};

export type PleadingTemplate = {
  templateId: string;
  version: string;
  technicalFixture: boolean;
  /** Printed at the top of every page-one rendering of a fixture. */
  fixtureBanner?: string;
  caption: {
    courtLine: string;
    partyBlockLeft: readonly string[];
    partyBlockRight: readonly string[];
  };
  title: string;
  preamble?: string;
  sections: readonly PleadingSection[];
  prayer: readonly string[];
  verification?: string;
  /**
   * Label for the participant signature rule. `null` suppresses the rule
   * entirely, which is correct for a proposed order: the court signs it.
   */
  signatureLabel?: string | null;
  signatureBlock: readonly string[];
  certificateOfService?: readonly string[];
};

// Jurisdiction template packs are registered here. Importing after the type
// declarations keeps the pack files free of a circular value dependency: they
// import the type only.
import { MISSISSIPPI_PLEADING_TEMPLATES } from "@/lib/rcap/packets/engines/pleading-templates-mississippi";

const FIXTURE_BANNER =
  "NON-PRODUCTION TECHNICAL FIXTURE — NOT A COURT FILING, NOT LEGAL ADVICE, NOT FOR SUBMISSION";

const BASE_TEMPLATES: Readonly<Record<string, PleadingTemplate>> = {
  "technical-fixture-petition": {
    templateId: "technical-fixture-petition",
    version: "1.0.0",
    technicalFixture: true,
    fixtureBanner: FIXTURE_BANNER,
    caption: {
      courtLine: "IN THE DISTRICT COURT OF {{county}} COUNTY, STATE OF NORTH DAKOTA",
      partyBlockLeft: ["STATE OF NORTH DAKOTA,", "", "Plaintiff,", "", "vs.", "", "{{petitionerName}},", "", "Defendant."],
      partyBlockRight: ["Case No. {{caseNumber}}", "", "TECHNICAL FIXTURE PETITION"]
    },
    title: "PETITION (TECHNICAL FIXTURE)",
    preamble:
      "This document is generated by an automated technical fixture to prove document assembly. It is not a pleading, has received no legal review, and must not be filed.",
    sections: [
      {
        heading: "PARTIES AND JURISDICTION",
        numbered: true,
        paragraphs: [
          "Petitioner is {{petitionerName}}, a resident of {{county}} County.",
          "This fixture references case number {{caseNumber}}.",
          "This section exists to prove that numbered factual allegations render, wrap across the full column width, and continue onto additional pages when the content is long enough to require them."
        ]
      },
      {
        heading: "FACTUAL BACKGROUND",
        numbered: true,
        paragraphs: [
          "The record at issue is dated {{recordDate}}.",
          "No representation is made here about eligibility, because this fixture performs no legal analysis whatsoever."
        ]
      }
    ],
    prayer: [
      "WHEREFORE, this technical fixture demonstrates that a prayer for relief renders in its correct position and that no substantive relief is requested."
    ],
    verification:
      "I declare that this is a technical fixture and contains no verified statement of fact.",
    signatureBlock: ["{{petitionerName}}", "Petitioner, self-represented"],
    certificateOfService: [
      "I certify that this technical fixture was not served on any party, because it is not a filing."
    ]
  },

  "technical-fixture-proposed-order": {
    templateId: "technical-fixture-proposed-order",
    version: "1.0.0",
    technicalFixture: true,
    fixtureBanner: FIXTURE_BANNER,
    caption: {
      courtLine: "IN THE DISTRICT COURT OF {{county}} COUNTY, STATE OF NORTH DAKOTA",
      partyBlockLeft: ["In re {{petitionerName}}"],
      partyBlockRight: ["Case No. {{caseNumber}}", "", "PROPOSED ORDER (FIXTURE)"]
    },
    title: "PROPOSED ORDER (TECHNICAL FIXTURE)",
    sections: [
      {
        paragraphs: [
          "This proposed order is a technical fixture. It grants nothing, orders nothing, and has no legal effect.",
          "It exists to prove that a packet set containing more than one component assembles its components in manifest order."
        ]
      }
    ],
    prayer: [],
    signatureBlock: ["_________________________", "District Court Judge (fixture placeholder)"]
  },

  "technical-fixture-certificate-of-service": {
    templateId: "technical-fixture-certificate-of-service",
    version: "1.0.0",
    technicalFixture: true,
    fixtureBanner: FIXTURE_BANNER,
    caption: {
      courtLine: "IN THE DISTRICT COURT OF {{county}} COUNTY, STATE OF NORTH DAKOTA",
      partyBlockLeft: ["In re {{petitionerName}}"],
      partyBlockRight: ["Case No. {{caseNumber}}"]
    },
    title: "CERTIFICATE OF SERVICE (TECHNICAL FIXTURE)",
    sections: [
      {
        paragraphs: [
          "No service was made. This fixture proves that a certificate-of-service component renders as its own packet component with its own template."
        ]
      }
    ],
    prayer: [],
    signatureBlock: ["{{petitionerName}}"]
  },

  "technical-fixture-fee-waiver": {
    templateId: "technical-fixture-fee-waiver",
    version: "1.0.0",
    technicalFixture: true,
    fixtureBanner: FIXTURE_BANNER,
    caption: {
      courtLine: "IN THE DISTRICT COURT OF {{county}} COUNTY, STATE OF NORTH DAKOTA",
      partyBlockLeft: ["In re {{petitionerName}}"],
      partyBlockRight: ["Case No. {{caseNumber}}"]
    },
    title: "APPLICATION TO WAIVE FEES (TECHNICAL FIXTURE)",
    sections: [
      {
        paragraphs: [
          "This component is CONDITIONAL. It renders only when the participant asked for a fee waiver, which proves the packet manifest drives assembly rather than a fixed list of documents."
        ]
      }
    ],
    prayer: [],
    signatureBlock: ["{{petitionerName}}"]
  }
};

export const PLEADING_TEMPLATES: Readonly<Record<string, PleadingTemplate>> = {
  ...BASE_TEMPLATES,
  ...MISSISSIPPI_PLEADING_TEMPLATES
};

export function pleadingTemplate(templateId: string | null): PleadingTemplate | null {
  if (!templateId) return null;
  return PLEADING_TEMPLATES[templateId] ?? null;
}
