"use client";
import {useState,useRef} from "react";
import type {getLaunchPreflight} from "@/lib/partners/onboarding/launch-preflight";
type Preflight=Awaited<ReturnType<typeof getLaunchPreflight>>;
export function LaunchControl({partnerSlug}:{partnerSlug:string}){
 const [view,setView]=useState<Preflight|null>(null),[message,setMessage]=useState(""),[pending,setPending]=useState(false),[confirmed,setConfirmed]=useState(false),[reason,setReason]=useState(""),[authority,setAuthority]=useState("");const request=useRef<{payload:string;id:string}|null>(null);
 const base=`/api/internal/partners/onboarding/phase1/${encodeURIComponent(partnerSlug)}`;
 async function refresh(){const response=await fetch(`${base}/launch`,{cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body.error??"Preflight unavailable.");setView(body.preflight);return body.preflight as Preflight;}
 async function run(action:"preflight"|"launch"|"grant"|"revoke",grantId?:string){setPending(true);setMessage("");try{
  if(action==="preflight"){const result=await refresh();setMessage(result.canLaunch?"Synthetic preflight ready. Review before confirming.":result.heldReason??result.effective.label);return;}
  if(!view)throw new Error("Review current preflight first.");
  const payload=action==="launch"?{snapshotHash:view.snapshotHash,confirmed}: {kind:action==="grant"?"grant":"revoke",checkKey:"communications_approved",grantId,reason,authorityReference:authority,snapshotHash:view.snapshotHash,expiresAt:new Date(Date.now()+7*86400000).toISOString()};
  const key=JSON.stringify(payload);if(!request.current || request.current.payload!==key)request.current={payload:key,id:crypto.randomUUID()};
  const response=await fetch(`${base}/${action==="launch"?"launch":"exceptions"}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...payload,requestId:request.current.id})});const body=await response.json();if(!response.ok)throw new Error(body.error??"Action could not be completed.");request.current=null;setConfirmed(false);await refresh();setMessage(action==="launch"?`Synthetic launch verified: ${body.result.publicUrl}`:action==="grant"?"Exception authorized; raw work remains incomplete.":"Exception revoked.");
 }catch(error){setMessage(error instanceof Error?error.message:"Action unavailable. Try again.");}finally{setPending(false);}}
 return <section aria-label="Launch controls" className="mb-6 rounded-xl border bg-white p-5"><h2 className="text-xl font-bold">Review and launch</h2><p className="mt-3 text-sm">Live launch remains disabled. Registered synthetic programs may complete a verified launch in a disposable loopback environment.</p><button className="mt-4 min-h-11 rounded bg-navy px-4 text-white" disabled={pending} onClick={()=>run("preflight")}>Review current preflight</button><p role="status" className="mt-3">{message}</p>{view?<><p className="mt-3">{view.effective.label}. {view.heldReason}</p><details className="mt-4"><summary className="min-h-11 cursor-pointer font-bold">Manage launch exceptions</summary><p>Only optional outreach timing can receive an operational exception. Required consent, payment, legal review and conditional alternatives remain restricted.</p><label className="mt-3 block">Reason<input className="mt-2 min-h-11 w-full rounded border p-2" value={reason} onChange={e=>setReason(e.target.value)}/></label><label className="mt-3 block">Authority reference<input className="mt-2 min-h-11 w-full rounded border p-2" value={authority} onChange={e=>setAuthority(e.target.value)}/></label><p className="mt-2 text-sm">Expires seven days after authorization. A changed program invalidates this exception.</p><button className="mt-4 min-h-11 rounded border px-4" disabled={pending||reason.trim().length<10||authority.trim().length<10} onClick={()=>run("grant")}>Authorize outreach-timing exception</button>{view.effective.activeExceptions.map(event=><div className="mt-3" key={event.id}><p>Exception authorized: {event.checkKey}; {event.reason}</p><button className="min-h-11 underline" disabled={pending||reason.trim().length<10||authority.trim().length<10} onClick={()=>run("revoke",event.id)}>Revoke exception</button></div>)}</details><label className="mt-5 flex gap-3"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I reviewed this exact synthetic program, its genuine approvals and existing activation authority.</label><button className="mt-4 min-h-11 rounded bg-navy px-4 text-white disabled:opacity-50" disabled={pending||!confirmed||!view.canLaunch} onClick={()=>run("launch")}>Launch synthetic program</button></>:null}</section>;
}
