"use client";
import Link from "next/link";
import {useState,useRef} from "react";
import type {getLaunchPreflight} from "@/lib/partners/onboarding/launch-preflight";
type Preflight=Awaited<ReturnType<typeof getLaunchPreflight>>;
export function LaunchControl({partnerSlug}:{partnerSlug:string}){
 const [view,setView]=useState<Preflight|null>(null),[message,setMessage]=useState(""),[pending,setPending]=useState(false),[confirmed,setConfirmed]=useState(false),[reason,setReason]=useState(""),[authority,setAuthority]=useState("");const [kind,setKind]=useState("sponsored"),[documentId,setDocumentId]=useState(""),[packetId,setPacketId]=useState(""),[expires,setExpires]=useState(""),[commercialConfirmed,setCommercialConfirmed]=useState(false);const [screenings,setScreenings]=useState(""),[packetCap,setPacketCap]=useState("");const request=useRef<{payload:string;id:string}|null>(null);
 const base=`/api/internal/partners/onboarding/phase1/${encodeURIComponent(partnerSlug)}`;
 async function refresh(){const response=await fetch(`${base}/launch`,{cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body.error??"Preflight unavailable.");setView(body.preflight);return body.preflight as Preflight;}
 async function run(action:"preflight"|"launch"|"grant"|"revoke"|"commercial"|"capacity"|"recover",grantId?:string){setPending(true);setMessage("");try{
  if(action==="preflight"){const result=await refresh();setMessage(result.canLaunch?"Preflight ready. Review before confirming.":result.heldReason??result.effective.label);return;}
  if(!view)throw new Error("Review current preflight first.");
  const payload=action==="recover"?{snapshotHash:view.latestOperation?.snapshot_hash,confirmed:true}:action==="capacity"?{documentId,authorityReference:authority,workspaceVersion:view.workspaceVersion,confirmed:commercialConfirmed,screeningsAllowed:Number(screenings),packetCap:Number(packetCap)}:action==="commercial"?{kind,documentId,packetEntitlementId:packetId,expiresAt:expires?new Date(expires).toISOString():null,authorityReference:authority,workspaceVersion:view.workspaceVersion,confirmed:commercialConfirmed}:action==="launch"?{snapshotHash:view.snapshotHash,confirmed}: {kind:action==="grant"?"grant":"revoke",checkKey:"communications_approved",grantId,reason,authorityReference:authority,snapshotHash:view.snapshotHash,expiresAt:new Date(Date.now()+7*86400000).toISOString()};
  const key=JSON.stringify(payload);if(!request.current || request.current.payload!==key)request.current={payload:key,id:crypto.randomUUID()};
  const response=await fetch(`${base}/${(action==="launch"||action==="recover")?"launch":action==="commercial"?"commercial-authority":action==="capacity"?"launch-capacity":"exceptions"}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...payload,requestId:action==="recover"?view.latestOperation?.request_id:request.current.id})});const body=await response.json();if(!response.ok){if(body.code==="invalid_transition"){request.current=null;await refresh();}throw new Error(body.error??"Action could not be completed.");}request.current=null;setConfirmed(false);await refresh();setMessage(action==="launch"?`${body.result.mode==="real"?"Live and verified":"Synthetic launch verified"}: ${body.result.publicUrl}`:action==="capacity"?"Documented capacity saved. Refresh and renew the affected package and approvals.":action==="commercial"?"Documented authority recorded. Refresh and renew current-source approvals before launch.":action==="grant"?"Exception authorized; raw work remains incomplete.":"Exception revoked.");
 }catch(error){setMessage(error instanceof Error?error.message:"Action unavailable. Try again.");}finally{setPending(false);}}
 return <section aria-label="Launch controls" className="mb-6 rounded-xl border bg-white p-5"><h2 className="text-xl font-bold">Review and launch</h2><p className="mt-3 text-sm">Real publication requires separate release authorization and verified partner-specific authority. Review the current package and resolve its remaining requirements here.</p><button className="mt-4 min-h-11 rounded bg-navy px-4 text-white" disabled={pending} onClick={()=>run("preflight")}>Review current preflight</button><p role="status" className="mt-3">{message}</p>{view?<><p className="mt-3">{view.program?.status}. {view.effective.label}. {view.heldReason}</p>{view.latestOperation?.step==="complete"?<p className="mt-3">Verified launch receipt: {view.latestOperation.operation_id}, recorded {view.latestOperation.created_at}.</p>:null}{view.latestOperation&&["prepared","publication_staged","public_verified"].includes(view.latestOperation.step)?<button className="mt-3 min-h-11 rounded border px-4" disabled={pending||!view.canRecover} onClick={()=>run("recover")}>Recover interrupted publication after safety lease</button>:null}{view.mode==="real"?<ul className="mt-3">{view.realAuthorityRequirements.map(item=><li key={item.label}>{item.label}: {item.passing?"Verified":"Required"}</li>)}</ul>:null}<details className="mt-4"><summary className="min-h-11 cursor-pointer font-bold">Review commercial authority</summary><p>Approved procurement evidence and a signed agreement are required. This does not record a payment or allocate capacity. Recording new authority reconciles the approved access model and requires renewed launch approvals.</p><p>{view.commercialAuthority?`Recorded ${view.commercialAuthority.kind} authority: ${view.commercialAuthority.authority_reference}. Expires ${view.commercialAuthority.expires_at}.`:"No documented commercial authorization recorded."}</p>
 <label className="mt-3 block">Authority type<select className="min-h-11 w-full rounded border p-2" value={kind} onChange={e=>setKind(e.target.value)}><option value="sponsored">Authorized sponsored program</option><option value="purchase_order">Approved purchase order</option><option value="verified_paid">Verified paid agreement</option></select></label>
 <label className="mt-3 block">Approved procurement document<select className="min-h-11 w-full rounded border p-2" value={documentId} onChange={e=>setDocumentId(e.target.value)}><option value="">Select reviewed document</option>{view.commercialDocuments.map(doc=><option key={doc.id} value={doc.id}>{doc.original_filename}</option>)}</select></label>{documentId?<Link className="mt-3 inline-flex min-h-11 items-center underline" href={`${base}/assets/${encodeURIComponent(documentId)}`} target="_blank" rel="noopener noreferrer">Open selected private procurement document</Link>:null}
 <label className="mt-3 block">Existing authorized packet allocation<select className="min-h-11 w-full rounded border p-2" value={packetId} onChange={e=>setPacketId(e.target.value)}><option value="">Select allocation</option>{view.packetAllocations.map(packet=><option key={packet.id} value={packet.id}>{packet.packet_cap} packets — {packet.id}</option>)}</select></label>
 <label className="mt-3 block">Contract or sponsor authorization reference<input className="min-h-11 w-full rounded border p-2" value={authority} onChange={e=>setAuthority(e.target.value)}/></label>
 <details className="mt-3"><summary className="min-h-11 cursor-pointer font-bold">Configure documented allocation</summary><p>Platform Admin only. Use the approved contract quantities. Existing usage, prices, and overage policy are preserved.</p><label className="mt-3 block">Screening allocation<input type="number" min="1" className="min-h-11 w-full rounded border p-2" value={screenings} onChange={e=>setScreenings(e.target.value)}/></label><label className="mt-3 block">Packet allocation<input type="number" min="1" className="min-h-11 w-full rounded border p-2" value={packetCap} onChange={e=>setPacketCap(e.target.value)}/></label><button className="mt-4 min-h-11 rounded border px-4" disabled={pending||!commercialConfirmed||!documentId||authority.trim().length<10||Number(screenings)<=0||Number(packetCap)<=0} onClick={()=>run("capacity")}>Save documented allocation</button></details>
 <label className="mt-3 block">Authority expires<input type="datetime-local" className="min-h-11 w-full rounded border p-2" value={expires} onChange={e=>setExpires(e.target.value)}/></label>
 <label className="mt-3 flex gap-3"><input type="checkbox" checked={commercialConfirmed} onChange={e=>setCommercialConfirmed(e.target.checked)}/>I verified the signed commercial document and authorize reconciliation to the approved participant joining method. This authority grants no payment or new capacity.</label>
 <button className="mt-4 min-h-11 rounded border px-4" disabled={pending||!commercialConfirmed||!documentId||!packetId||!expires||authority.trim().length<10} onClick={()=>run("commercial")}>Record documented commercial authority</button></details>
 <details className="mt-4"><summary className="min-h-11 cursor-pointer font-bold">Manage launch exceptions</summary><p>Only optional outreach timing can receive an operational exception. Required consent, payment, legal review and conditional alternatives remain restricted.</p><label className="mt-3 block">Reason<input className="mt-2 min-h-11 w-full rounded border p-2" value={reason} onChange={e=>setReason(e.target.value)}/></label><label className="mt-3 block">Authority reference<input className="mt-2 min-h-11 w-full rounded border p-2" value={authority} onChange={e=>setAuthority(e.target.value)}/></label><p className="mt-2 text-sm">Expires seven days after authorization. A changed program invalidates this exception.</p><button className="mt-4 min-h-11 rounded border px-4" disabled={pending||reason.trim().length<10||authority.trim().length<10} onClick={()=>run("grant")}>Authorize outreach-timing exception</button>{view.effective.activeExceptions.map(event=><div className="mt-3" key={event.id}><p>Exception authorized: {event.checkKey}; {event.reason}</p><button className="min-h-11 underline" disabled={pending||reason.trim().length<10||authority.trim().length<10} onClick={()=>run("revoke",event.id)}>Revoke exception</button></div>)}</details><label className="mt-5 flex gap-3"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I reviewed this exact program, its genuine approvals and existing activation authority.</label><button className="mt-4 min-h-11 rounded bg-navy px-4 text-white disabled:opacity-50" disabled={pending||!confirmed||!view.canLaunch} onClick={()=>run("launch")}>{view.mode==="real"?"Launch approved program":"Launch synthetic program"}</button></>:null}</section>;
}
