// Florida eligibility rules. Sourced from the Florida Sealing & Expungement
// Wilma Agent Training Reference (Nationwide Record Clearing), corroborated by
// the cited Florida Statutes and FDLE process pages. Citations are Fla. Stat.
export const flEligibilityRules = [
  "Florida is strict and process-heavy. For normal court-ordered sealing or expunction the person generally needs an FDLE Certificate of Eligibility first, and the certificate does not guarantee relief — the court still has discretion to deny. FDLE issues the certificate; relief does not happen until the proper court enters a certified order. A certificate is valid for 12 months.",
  "Court-ordered expunction (§ 943.0585): generally for cases that did not end in adjudication of guilt — no charging document filed, or a charge that was dismissed, nolle prosequi, dismissed by the court, resolved by judgment of acquittal, or ended in a not-guilty verdict. The record must not be ineligible under § 943.0584; the person must have no disqualifying prior adjudications, must not have been adjudicated guilty/delinquent for acts from the same arrest, must be off court supervision, and generally must have no prior Florida court-ordered seal/expunge. The petition must include the FDLE certificate and a sworn statement.",
  "Court-ordered sealing (§ 943.059): usually the route where adjudication was withheld (or another eligible non-conviction posture). The same gatekeeping applies — not ineligible under § 943.0584, no adjudication of guilt for the case, off court supervision, generally no prior Florida seal/expunge, and an FDLE Certificate of Eligibility obtained first. The court may deny even when FDLE issues the certificate.",
  "Disqualifiers (§ 943.0584): a long list of offenses is ineligible for court-ordered sealing or expunction when the record is a conviction for one of them. Critical Florida nuance — for § 943.0584, 'conviction' includes a guilty or no-contest plea or a determination of guilt even if adjudication was withheld. So a withhold does not guarantee eligibility; a plea or finding on a listed offense can still bar relief.",
  "Automatic sealing (§ 943.0595): FDLE automatically seals certain favorable records after receiving the certified disposition from the clerk — no charging document filed; a charging document filed but all counts dismissed/nolle prossed/dismissed by the court; a not-guilty verdict on all counts (unless not guilty by reason of insanity); or a judgment of acquittal on all counts. There is no limit on the number of automatic sealings, but automatic sealing does not compel other agencies to surrender or seal their own copies the way a full court-ordered order can.",
  "Human-trafficking victim expunction (§ 943.0583): Florida's broadest special route. A trafficking victim may petition to expunge records from arrests or charges for offenses committed or reported while they were a victim and as part of the trafficking scheme or at a trafficker's direction. It applies without regard to the disposition, so it can reach some convictions that normal sealing/expunction cannot. The clerk may not charge filing/service/copy fees and treats multiple eligible cases as a single petition. Official documentation creates a presumption but is not required; without it, the showing is clear and convincing evidence. It does not apply to offenses listed in § 775.084(1)(b)1.",
  "Lawful self-defense expunction (§ 943.0578): applies when the State Attorney or Statewide Prosecutor certifies that no charge was filed, or the charge was dismissed, because the person acted in lawful self-defense under Florida's justifiable-use-of-force law. It uses the specific FDLE lawful-self-defense process, not the normal expunction packet.",
  "Juvenile diversion expunction (§ 943.0582): a minor who successfully completed an authorized diversion program may qualify, where the diversion was based on a misdemeanor or a felony that is not a forcible felony and not a felony involving manufacture, sale, purchase, transport, possession, or use of a firearm or weapon. It does not block a later normal court-ordered sealing/expunction if otherwise eligible.",
  "Early juvenile expunction (§ 943.0515): a person age 18 or older but under 21 may apply if they have not been charged with, or found to have committed, any criminal offense during the 5 years before the application date. Only offenses committed before age 18 are eligible under this early-juvenile route.",
  "Administrative expunction (§ 943.0581): for an arrest made contrary to law or by mistake (including identity error). The arresting agency, sheriff, State Attorney, or the arrested person may pursue it through FDLE, but the person's application must be supported by the head of the arresting agency/designee or the State Attorney/designee. It is not a substitute for the normal 'case dismissed' route.",
  "Expunction after prior sealing: a record that was previously sealed may generally be expunged only after it has been sealed for at least 10 years, unless the case fits the no-file / dismissal-before-trial / acquittal / not-guilty exception."
];
