import test from 'node:test';import assert from 'node:assert/strict';import {startEphemeralPg} from '../lib/rcap-ephemeral-pg.mjs';
const migration='supabase/migrations/20261010232754_rcap_clinic_preconsent_reset.sql';
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`,owner=id(1),event=id(2),entry=id(3),session=id(4),code=id(5),hash='a'.repeat(64);
function setup(){const pg=startEphemeralPg();pg.sql(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create table auth.users(id uuid primary key);insert into auth.users values('${owner}');
create table clinic_assisted_sessions(id uuid primary key,participant_user_id uuid,handoff_token_hash text);
create table clinic_event_access_redemptions(id uuid primary key,event_id uuid,access_code_id uuid,redemption_nonce_hash text,redeemed_at timestamptz default now());
create table clinic_event_audit(event_id uuid,actor_user_id uuid,action text,target_type text,target_id uuid,metadata jsonb);
insert into clinic_event_access_redemptions(id,event_id,access_code_id,redemption_nonce_hash) values('${entry}','${event}','${code}','${hash}');
create function clinic_redeem_event_code(text,text,text) returns table(outcome text,event_id uuid) language plpgsql as $$begin return query select 'already_redeemed'::text,'${event}'::uuid;end$$;
create function clinic_start_assisted_session(uuid,uuid,uuid,uuid,text,text,text,timestamptz,integer) returns uuid language plpgsql as $$begin
if $7<>'explicit-test-consent' then raise exception 'consent denied';end if;
insert into public.clinic_assisted_sessions values('${session}',$3,$5) on conflict(id) do nothing;return '${session}'::uuid;end$$;`);pg.applyFile(migration);return pg;}
const start=`select clinic_start_assisted_session_for_entry('${hash}','${event}','${id(6)}','${owner}','${id(7)}','${'b'.repeat(64)}','${'c'.repeat(64)}','explicit-test-consent',now(),30)`;
const close=`select clinic_close_unassisted_entry('${hash}','${owner}')`;
function fresh(pg){pg.sql('update clinic_event_access_redemptions set reset_binding_supported=true');}
test('closed entry is atomic, replayable, audited once, and never manufactures consent',()=>{const pg=setup();try{fresh(pg);const first=pg.json(close);const repeat=pg.json(close);assert.deepEqual(first,repeat);assert.equal(pg.scalar('select count(*) from clinic_event_audit'),'1');assert.equal(pg.scalar('select count(*) from clinic_assisted_sessions'),'0');assert.match(pg.sqlExpectError(start),/clinic_entry_unavailable/);assert.match(pg.sqlExpectError(close.replace(owner,id(8))),/clinic_entry_owner_mismatch/);}finally{pg.stop();}});
test('assistance binds the exact entry, preserves existing consent guard and idempotency, then refuses empty reset',()=>{const pg=setup();try{fresh(pg);assert.match(pg.sqlExpectError(start.replace('explicit-test-consent','missing')),/consent denied/);assert.equal(pg.scalar('select count(*) from clinic_assisted_sessions'),'0');assert.equal(pg.scalar(start),session);assert.equal(pg.scalar(start),session);assert.equal(pg.scalar('select assisted_session_id from clinic_event_access_redemptions'),session);assert.match(pg.sqlExpectError(close),/clinic_handoff_required/);assert.equal(pg.scalar('select count(*) from clinic_event_audit'),'0');assert.match(pg.sqlExpectError(start.replace(owner,id(8))),/clinic_entry_already_used/);}finally{pg.stop();}});
test('historical entry, expired entry, wrong event, and public roles fail closed',()=>{const pg=setup();try{assert.match(pg.sqlExpectError(close),/clinic_handoff_required/);fresh(pg);assert.match(pg.sqlExpectError(start.replace(event,id(8))),/clinic_entry_unavailable/);pg.sql("update clinic_event_access_redemptions set redeemed_at=now()-interval '9 hours'");assert.match(pg.sqlExpectError(close),/clinic_handoff_required/);assert.match(pg.sqlExpectError(start),/clinic_entry_unavailable/);for(const role of ['anon','authenticated']){assert.match(pg.sqlExpectError(`set role ${role};${close}`),/permission denied/);assert.match(pg.sqlExpectError(`set role ${role};${start}`),/permission denied/);}assert.equal(pg.scalar("select has_function_privilege('service_role','clinic_close_unassisted_entry(text,uuid)','execute')"),'t');}finally{pg.stop();}});
for(const first of ['close','start'])test('concurrent '+first+' serializes with its competing action',async()=>{const pg=setup();try{fresh(pg);const winner=first==='close'?close:start,loser=first==='close'?start:close;const held=pg.sqlAsync(`begin;select id from clinic_event_access_redemptions where id='${entry}' for update;select pg_sleep(0.4);${winner};commit;`);for(let i=0;i<50;i++){if(pg.scalar("select count(*) from pg_stat_activity where wait_event='PgSleep'")==='1')break;await new Promise(r=>setTimeout(r,10));}const competing=pg.sqlAsync(loser);assert.equal((await held).ok,true);const result=await competing;assert.equal(result.ok,false);assert.match(result.err,first==='close'?/clinic_entry_unavailable/:/clinic_handoff_required/);assert.equal(pg.scalar('select count(*) from clinic_assisted_sessions'),first==='close'?'0':'1');}finally{pg.stop();}});

test('new redemption and reset provenance commit together; a replay retains the exact existing binding',()=>{const pg=setup();try{
 pg.sql(`create or replace function public.clinic_redeem_event_code(text,text,text) returns table(outcome text,event_id uuid) language plpgsql as $$begin
 if exists(select 1 from public.clinic_event_access_redemptions where redemption_nonce_hash=$3) then return query select 'already_redeemed'::text,'${event}'::uuid;return;end if;
 insert into public.clinic_event_access_redemptions(id,event_id,access_code_id,redemption_nonce_hash) values('${id(9)}','${event}','${code}',$3);
 return query select 'redeemed'::text,'${event}'::uuid;end$$;`);
 const nonce='d'.repeat(64),call=`select outcome from clinic_redeem_event_code_with_reset('test-clinic','code-hash','${nonce}')`;
 assert.equal(pg.scalar(call),'redeemed');assert.equal(pg.scalar(`select reset_binding_supported from clinic_event_access_redemptions where redemption_nonce_hash='${nonce}'`),'t');
 assert.equal(pg.scalar(call),'already_redeemed');assert.equal(pg.scalar('select count(*) from clinic_event_access_redemptions'),'2');
 assert.equal(pg.scalar(`select reset_binding_supported from clinic_event_access_redemptions where id='${entry}'`),'f','No historical entry is silently reclassified');
 }finally{pg.stop();}});
