import assert from 'node:assert/strict';
import {actorBrowser,record,save,origin,db,checked,write,materialIds} from './campaign-support.mjs';
const a=await actorBrowser('admin'),p=a.page;const slug=process.env.RCAP_RESUME_ADMIN??`grade-a-admin-${Date.now().toString(36)}`;
let state,creation;
try {
 if(!process.env.RCAP_RESUME_ADMIN){
 await p.goto(origin+'/internal');await p.getByRole('link',{name:/^RCAP Programs/}).click();await p.getByRole('heading',{name:'Programs',exact:true}).waitFor();
 await record(a,['A-T01'],['Sign in as Platform Admin','Click RCAP Programs'],'Command Center opens the canonical searchable Programs index.');
 await p.getByRole('searchbox',{name:'Find a program'}).fill('no-program-with-this-unique-name');await p.getByRole('button',{name:'Search',exact:true}).click();await p.getByText('No programs match these filters. Clear filters to see all programs.').waitFor();await p.getByRole('link',{name:'Clear filters',exact:true}).click();await p.getByRole('link',{name:'Open program',exact:true}).first().waitFor();
 await record(a,['A-T03'],['Search a nonexistent program','Clear filters'],'Empty state and clear action restore existing programs without mutation.');
 await p.getByRole('link',{name:'Create program',exact:true}).click();await p.getByLabel('Program operator',{exact:true}).selectOption('legalease_managed');await p.getByLabel('Public organization name',{exact:true}).fill('Grade A Isolated Organization');await p.getByLabel('Participant page address',{exact:false}).fill(slug);await p.getByLabel('Program name',{exact:true}).fill('Grade A Screening Program');
 for(const name of ['California','District of Columbia','Virginia'])await p.getByRole('checkbox',{name,exact:true}).check();await p.getByLabel('Enable English and Spanish').check();await p.getByLabel('Internal creation reason',{exact:false}).fill('Authorized isolated integrated acceptance; no Production records or rights copied.');await p.getByRole('button',{name:'Review program',exact:true}).click();
 const createdPromise=p.waitForResponse(r=>r.request().method()==='POST'&&r.url().endsWith('/api/internal/partners/provisioning'));await p.getByRole('button',{name:'Create program',exact:true}).click();const created=await createdPromise;assert.equal(created.status(),200);creation=await created.json();await p.waitForURL(u=>u.pathname===`/internal/partners/onboarding/${slug}`);
 const replay=await a.context.request.post(created.url(),{headers:{origin},data:created.request().postDataJSON()});assert.equal(replay.status(),200);const replayed=(await replay.json()).result;assert.equal(replayed.partnerSlug,creation.result.partnerSlug);assert.equal(replayed.replayed,true);
 await record(a,['A-T04'],['Create LegalEase-managed program with approved bilingual defaults','Replay the exact intercepted creation request'],'One canonical program is created; retry returns the same receipt.',{fixture:slug,creation:creation.result});
 await p.getByLabel('Program operator',{exact:true}).selectOption('partner_managed');assert.ok((await p.locator('#configure-program').innerText()).includes('Partner-managed: existing consent and service authority apply.'));await p.getByLabel('Program operator',{exact:true}).selectOption('legalease_managed');
 const configBefore=await a.context.request.get(`${origin}/api/internal/partners/onboarding/phase1/${slug}/configuration`);assert.equal((await configBefore.json()).configuration.operatingModel,'legalease_managed');
 await record(a,['A-T06'],['Switch operator in unsaved draft','Read authoritative configuration','Restore draft operator'],'Draft reflects genuine authority distinction without changing saved operating rights.',{fixture:slug});
 state=await save(p);assert.equal(state.preparationError,null);assert.equal(state.operations.canStart,true);assert.deepEqual(state.configuration.data.geography_audience_language_accessibility.jurisdictions,['CA','DC','VA']);assert.equal(state.operations.view.materials.length,2);assert.deepEqual(state.operations.view.materials.find(m=>m.type==='co_branded_page_configuration').document.pagePreview.missing,[]);
 await p.reload();for(const name of ['California','District of Columbia','Virginia'])assert.equal(await p.getByRole('checkbox',{name,exact:true}).isChecked(),true);
 await record(a,['A-T07','A-T13'],['Save program','Read back saved configuration and current materials','Refresh selected jurisdictions'],'LegalEase screening-only program needs no fabricated agreement or funding; all three jurisdictions persist.',{fixture:slug,version:state.configuration.version,materials:materialIds(state.operations),canStart:state.operations.canStart});
 }else{await p.goto(`${origin}/internal/partners/onboarding/${slug}`);const configuration=(await(await a.context.request.get(`${origin}/api/internal/partners/onboarding/phase1/${slug}/configuration`)).json()).configuration;const operations=(await(await a.context.request.get(`${origin}/api/internal/partners/onboarding/phase1/${slug}/program`)).json()).operations;state={configuration,operations};creation={result:{partnerSlug:slug}};}
 let mutations=0;p.on('request',r=>{if(r.method()==='POST'&&r.url().includes('/onboarding/phase1/'))mutations++;});const before=mutations;await p.reload();
 for(const [label,id] of [['Program Summary','program-summary-preview'],['Participant Page','participant-page-preview']]){await p.getByRole('link',{name:`View ${label}`,exact:true}).click();await p.waitForFunction(id=>document.activeElement?.id===id,id);}
 assert.equal(mutations,before);const preview=p.locator('#participant-page-preview');for(const language of ['Español','English'])for(const device of ['Mobile','Desktop']){await preview.getByRole('button',{name:language,exact:true}).click();assert.equal(await preview.getByRole('button',{name:language,exact:true}).getAttribute('aria-pressed'),'true');await preview.getByRole('button',{name:device,exact:true}).click();assert.equal(await preview.getByRole('button',{name:device,exact:true}).getAttribute('aria-pressed'),'true');assert.equal(await preview.getAttribute('data-material-id'),state.operations.view.materials.find(m=>m.type==='co_branded_page_configuration').id);}
 await record(a,['A-T23','A-T27'],['Fresh reload','Click both View actions','Switch English/Español and Mobile/Desktop'],'Both exact current material versions are immediately available; focus moves to each document and preview toggles use the same version.',{fixture:slug,preparationRequests:mutations-before,materials:materialIds(state.operations)});
 const review=p.locator('#final-program-review');for(const text of ['LegalEase','California, District of Columbia, Virginia','screening only','Spanish enabled','Program Summary · Version','Participant Page · Version'])assert.ok((await review.innerText()).includes(text),text);
 await record(a,['A-T29'],['Read Final Review immediately below both materials'],'Final review shows operator, full scope, languages, services and exact current versions with one confirmation.',{fixture:slug,materials:materialIds(state.operations)});
 await p.getByLabel('Confirm operating scope and current materials',{exact:true}).check();await p.getByLabel('Public program name',{exact:true}).fill('Grade A Renamed Screening Program');assert.equal(await p.getByRole('button',{name:'Start Program',exact:true}).count(),0);state=await save(p);assert.equal(state.preparationError,null);assert.equal(await p.getByLabel('Confirm operating scope and current materials',{exact:true}).isChecked(),false);
 await record(a,['A-T30'],['Select final confirmation','Edit public program name','Save changed configuration'],'Editing invalidates the old confirmation; refreshed exact versions require a new confirmation.',{fixture:slug,version:state.configuration.version,materials:materialIds(state.operations)});
 const english=state.configuration.data.brand_public_page.program_headline;const spanish=state.configuration.data.brand_public_page.program_headline_es;await p.getByLabel('Enable Spanish',{exact:true}).uncheck();const off=await save(p);assert.equal(off.configuration.data.brand_public_page.program_headline,english);assert.equal(off.configuration.data.brand_public_page.program_headline_es,spanish);await p.getByLabel('Enable Spanish',{exact:true}).check();state=await save(p);assert.equal(state.preparationError,null);assert.equal(state.configuration.data.brand_public_page.program_headline,english);assert.equal(state.configuration.data.brand_public_page.program_headline_es,spanish);
 await record(a,['A-T15'],['Disable Spanish and Save','Re-enable Spanish and Save'],'Stored source-matched Spanish and the original English survive language toggles.',{fixture:slug,version:state.configuration.version});
 await p.getByRole('checkbox',{name:'District of Columbia',exact:true}).uncheck();await p.getByRole('checkbox',{name:'Virginia',exact:true}).uncheck();await p.getByLabel('Service area description',{exact:true}).fill('Multi-State');await p.getByRole('button',{name:'Use selected jurisdictions in description',exact:true}).click();assert.equal(await p.getByLabel('Service area description',{exact:true}).inputValue(),'California');state=await save(p);assert.deepEqual(state.configuration.data.geography_audience_language_accessibility.jurisdictions,['CA']);
 await record(a,['A-T14'],['Select only California','Describe scope as Multi-State','Use selected jurisdictions in description','Save'],'Mismatch is explained and directly corrected without granting any additional jurisdiction.',{fixture:slug,jurisdictions:['CA']});
 for(const name of ['District of Columbia','Virginia'])await p.getByRole('checkbox',{name,exact:true}).check();state=await save(p);
 await p.getByLabel('Enable Spanish',{exact:true}).uncheck();state=await save(p);const summaryBefore=state.operations.view.materials.find(m=>m.type==='implementation_brief');await p.getByLabel('Primary action label',{exact:true}).fill('Explore screening');await p.getByLabel('Participant support copy',{exact:true}).fill('Contact program support for help using this screening program.');state=await save(p);assert.equal(state.preparationError,null);assert.equal(state.operations.view.materials.find(m=>m.type==='implementation_brief').id,summaryBefore.id);await p.getByRole('link',{name:'Review Program Materials',exact:true}).click();await p.waitForFunction(()=>document.activeElement?.id==='program-materials');await p.reload();assert.equal(await p.getByLabel('Primary action label',{exact:true}).inputValue(),'Explore screening');
 await record(a,['A-T10','A-T28'],['Edit CTA and support copy','Save','Review Program Materials','Refresh persisted fields'],'Saved public fields read back unchanged; only the affected Participant Page regenerates and Save links directly to focused Preview.',{fixture:slug,summaryId:summaryBefore.id,materials:materialIds(state.operations)});
 const tab=await a.context.newPage();await tab.goto(p.url());await p.getByLabel('Public program name',{exact:true}).fill('Grade A Current Name');await tab.getByLabel('Public program name',{exact:true}).fill('Grade A Preserved Draft');state=await save(p);const conflict=tab.waitForResponse(r=>r.request().method()==='POST'&&r.url().endsWith('/configuration'));await tab.getByRole('button',{name:'Save program',exact:true}).click();assert.equal((await conflict).status(),409);assert.equal(await tab.getByLabel('Public program name',{exact:true}).inputValue(),'Grade A Preserved Draft');await tab.getByRole('button',{name:'Review latest saved version',exact:true}).click();await tab.getByRole('button',{name:'Use saved value',exact:true}).click();assert.equal(await tab.getByLabel('Public program name',{exact:true}).inputValue(),'Grade A Current Name');await tab.close();
 await record(a,['A-T22'],['Open two editors','Save the first edit','Save stale second edit','Review latest saved version and choose saved value'],'Stale revision is refused, unsaved draft is preserved and the conflict is resolved explicitly.',{fixture:slug,conflictStatus:409,version:state.configuration.version});
 await p.getByLabel('Confirm operating scope and current materials',{exact:true}).check();const launchedPromise=p.waitForResponse(r=>r.request().method()==='POST'&&r.url().endsWith('/program'));await p.getByRole('button',{name:'Start Program',exact:true}).click();const launched=await launchedPromise;const live=await launched.json();assert.equal(launched.status(),200,live.error);assert.equal(live.operations.view.decision.live,true);await p.getByRole('heading',{name:'Program dashboard',exact:true}).waitFor();const retry=await a.context.request.post(launched.url(),{headers:{origin},data:launched.request().postDataJSON()});assert.equal(retry.status(),200);const events=checked(await db.from('rcap_launch_operation_events').select('step').eq('workspace_id',creation.result.workspaceId??live.operations.identity.workspaceId));assert.deepEqual(events.map(e=>e.step).sort(),['complete','prepared','public_verified','publication_staged'].sort());
 await record(a,['A-T31','A-T32'],['Confirm exact current versions','Start Program','Retry the exact protected publication request'],'One authorized publication completes through real public-route verification with no duplicate launch journal.',{fixture:slug,events:events.map(e=>e.step),materials:materialIds(live.operations)});
 await p.reload();await p.getByRole('link',{name:'Configure',exact:true}).click();await p.waitForFunction(()=>document.activeElement?.id==='configure-program');assert.equal(await p.getByRole('heading',{name:'Program dashboard',exact:true}).count(),1);
 await record(a,['A-T34'],['Refresh live workspace','Click Configure'],'Live program retains its dashboard and exposes safe editing without restarting onboarding.',{fixture:slug});
 await p.goto(origin+'/internal/partners/onboarding');await p.getByRole('searchbox',{name:'Find a program'}).fill(slug);await p.getByRole('button',{name:'Search',exact:true}).click();assert.equal(await p.getByRole('link',{name:'Open program',exact:true}).count(),1);await p.getByRole('link',{name:'Open program',exact:true}).click();await p.waitForURL(u=>u.pathname.endsWith('/'+slug));
 await record(a,['A-T02'],['Search exact program address','Open program'],'Search opens the correct tenant with saved LegalEase operator and live status.',{fixture:slug});
 write('server/admin-fixture.json',{slug,creation:creation.result,materials:materialIds(live.operations)});
} catch(error) {write('server/admin-campaign-failure.json',{slug,error:error.message,stack:error.stack,route:new URL(p.url()).pathname,body:(await p.locator('body').innerText()).slice(-10000)});throw error;} finally {await a.browser.close();}
