import assert from 'node:assert/strict';
import {actorBrowser,origin,save,db,checked,write,materialIds} from './campaign-support.mjs';
const profiles=[['CA','California',true],['DC','District of Columbia',false],['VA','Virginia',true],['MS','Mississippi',false],['WY','Wyoming',true],['IL','Illinois',false],['NY','New York',true],['TX','Texas',false],['FL','Florida',true],['WA','Washington',false]];
const receipts=[];
for(const [index,[code,name,spanish]] of profiles.entries()){
 const a=await actorBrowser('admin',undefined,{engine:index<5?'chromium':'webkit',width:[1280,375,390,430][index%4]}),p=a.page,slug=`grade-a-scale-${code.toLowerCase()}-${Date.now().toString(36)}`;const start=performance.now();const counts={creation:0,save:0,explicitGeneration:0};
 p.on('request',r=>{if(r.method()!=='POST')return;const u=new URL(r.url());if(u.pathname==='/api/internal/partners/provisioning')counts.creation++;if(u.pathname.endsWith('/configuration'))counts.save++;if(u.pathname.endsWith('/artifacts'))counts.explicitGeneration++;});
 try{
  await p.goto(origin+'/internal/partners/onboarding');await p.getByRole('link',{name:'Create program',exact:true}).click();await p.getByLabel('Program operator',{exact:true}).selectOption('legalease_managed');await p.getByLabel('Public organization name',{exact:true}).fill(`Grade A Isolated ${name} Organization`);await p.getByLabel('Program name',{exact:true}).fill(`Grade A ${code} Screening`);await p.getByLabel('Participant page address',{exact:false}).fill(slug);await p.getByRole('checkbox',{name,exact:true}).check();if(spanish)await p.getByLabel('Enable English and Spanish').check();await p.getByLabel('Internal creation reason',{exact:false}).fill('Authorized isolated scale acceptance using approved defaults. No copied agreements, contacts, funding or consent.');await p.getByRole('button',{name:'Review program',exact:true}).click();const created=p.waitForResponse(r=>r.request().method()==='POST'&&r.url().endsWith('/api/internal/partners/provisioning'));await p.getByRole('button',{name:'Create program',exact:true}).click();assert.equal((await created).status(),200);await p.waitForURL(u=>u.pathname.endsWith('/'+slug));const saved=await save(p);assert.equal(saved.preparationError,null);assert.deepEqual(saved.configuration.data.geography_audience_language_accessibility.jurisdictions,[code]);assert.equal(saved.configuration.data.geography_audience_language_accessibility.enable_spanish,spanish);assert.equal(saved.operations.canStart,true);assert.equal(saved.operations.view.materials.length,2);assert.deepEqual(saved.operations.view.materials.find(m=>m.type==='co_branded_page_configuration').document.pagePreview.missing,[]);
  const workspace=saved.operations.identity.workspaceId;assert.ok(workspace);const versions=checked(await db.from('partner_onboarding_artifact_versions').select('id,workspace_id').eq('workspace_id',workspace));assert.equal(versions.length,2);await p.getByRole('link',{name:'View Participant Page',exact:true}).click();if(spanish)await p.locator('#participant-page-preview').getByRole('button',{name:'Español',exact:true}).click();await p.reload();await p.getByLabel('Confirm operating scope and current materials',{exact:true}).waitFor();assert.equal(checked(await db.from('partner_onboarding_artifact_versions').select('id').eq('workspace_id',workspace)).length,2);
  receipts.push({result:'PASS',slug,workspace,code,spanish,browser:a.engine,width:a.width,counts,durationMs:Math.round(performance.now()-start),materials:materialIds(saved.operations),published:false});write('server/ten-program-scale.json',{result:receipts.length===10?'PASS':'IN_PROGRESS',receipts,provider:'approved bilingual defaults; no machine translation needed',productionWrites:0});console.log(JSON.stringify(receipts.at(-1)));
 }catch(e){write('server/scale-failure.json',{slug,error:e.message,route:new URL(p.url()).pathname});throw e;}finally{await a.browser.close();}
}
assert.equal(new Set(receipts.map(r=>r.workspace)).size,10);assert.equal(new Set(receipts.flatMap(r=>r.materials.map(m=>m.id))).size,20);
