// Auto-generated by scripts/generate-all50-state-pack-batch.mjs.
// Build-first metadata is sourced from private/Nationwide Record Clearing.
// QA, visual review, counsel review, and source freshness review are tracked
// separately and do not block ordinary RCAP build work.

export const louisianaAll50BuildMetadata = {
  "jurisdiction": {
    "code": "LA",
    "name": "Louisiana",
    "slug": "louisiana",
    "sourceFolders": [
      "LegalEase Louisiana"
    ]
  },
  "products": [
    "record_clearing_guidance_packet",
    "custom_pleading_or_state_pack_draft"
  ],
  "pathways": [
    {
      "id": "record_clearing_review",
      "label": "Louisiana record-clearing review",
      "output": "guidance_packet",
      "reviewRequiredBeforeLive": true
    },
    {
      "id": "custom_pleading",
      "label": "Louisiana custom pleading draft",
      "output": "custom_pleading_or_state_pack_draft",
      "reviewRequiredBeforeLive": true
    }
  ],
  "requiredUserInputs": [
    "participant_full_legal_name",
    "date_of_birth_if_required_by_selected_form",
    "contact_information",
    "case_number",
    "court_or_agency_name",
    "county_or_filing_location",
    "charge_or_record_description",
    "case_outcome",
    "disposition_date_if_known",
    "sentence_completion_or_supervision_status_if_applicable",
    "records_or_background_report_if_available"
  ],
  "filingDestinationGuidance": [
    "Use the court, clerk, agency, or official filing destination identified in the selected Nationwide resource packet or official form.",
    "If the correct filing destination is unclear, keep the packet guidance-only and flag the state for post-build QA/attorney review.",
    "Do not invent clerk addresses, agency addresses, local fees, or service rules."
  ],
  "filingSteps": [
    "Confirm the record-clearing pathway from the participant's answers and available source packet.",
    "Collect required user inputs and mark unknown information plainly.",
    "Select official form overlay, custom pleading, or guidance-only fallback.",
    "Generate internal review packet and source inventory artifact.",
    "Route to QA, visual review when an official PDF overlay exists, and counsel review before live use."
  ],
  "feesCopiesServiceNotes": [
    "Use fee, copy, and service notes only when present in the Nationwide source packet or official form.",
    "When fee/copy/service information is absent or unclear, state that the participant should verify current local requirements with the filing court or agency.",
    "Do not treat missing fee data as a blocker for guidance fallback generation."
  ],
  "officialFormInventory": [],
  "resourcePacketInventory": [
    {
      "fileName": "2 Louisiana Laws - Louisiana State Legislature.html",
      "relativePath": "LegalEase Louisiana/2 Louisiana Laws - Louisiana State Legislature.html",
      "classification": "reference",
      "sha256": "3d65f09be27166ddf31e513fe96fa4f13cc1e60e130e2825c65bd80f6d22c538",
      "sizeBytes": 5519
    },
    {
      "fileName": "3Louisiana Laws - Louisiana State Legislature.html",
      "relativePath": "LegalEase Louisiana/3Louisiana Laws - Louisiana State Legislature.html",
      "classification": "reference",
      "sha256": "e26627049d3dfe9c19eacb6f4f590e0033c6d55e3acfd3a9309421253956bd8f",
      "sizeBytes": 26395
    },
    {
      "fileName": "4Louisiana Laws - Louisiana State Legislature.html",
      "relativePath": "LegalEase Louisiana/4Louisiana Laws - Louisiana State Legislature.html",
      "classification": "reference",
      "sha256": "7ba43b44789b5106d9cb02cfec4c1624d160a82e730dee03373baf3615070669",
      "sizeBytes": 14634
    },
    {
      "fileName": "5Louisiana Laws - Louisiana State Legislature.html",
      "relativePath": "LegalEase Louisiana/5Louisiana Laws - Louisiana State Legislature.html",
      "classification": "reference",
      "sha256": "57ad77ce4802b6a08585cb509bc787cc4d86e83cdc601051a4782a9e8f9e38f4",
      "sizeBytes": 11364
    },
    {
      "fileName": "6Louisiana Laws - Louisiana State Legislature.html",
      "relativePath": "LegalEase Louisiana/6Louisiana Laws - Louisiana State Legislature.html",
      "classification": "reference",
      "sha256": "5e5e7827910b7e3e42a61319edc0d0699a920e7b5f3a3c3eb5043988ee698cc9",
      "sizeBytes": 27760
    },
    {
      "fileName": "7Louisiana Laws - Louisiana State Legislature.html",
      "relativePath": "LegalEase Louisiana/7Louisiana Laws - Louisiana State Legislature.html",
      "classification": "reference",
      "sha256": "e6284c1ec2462d6667be2a73a5524bf79b8797d3c52d09cbc7ae2e8572d86bfe",
      "sizeBytes": 35317
    },
    {
      "fileName": "Louisiana Expungement — Statewide Agent Reference.rtf",
      "relativePath": "LegalEase Louisiana/Louisiana Expungement — Statewide Agent Reference.rtf",
      "classification": "reference",
      "sha256": "d39dd26713e0a3a090dbb24ce0e3209c44a5200223a878a5ae8a4739feadad23",
      "sizeBytes": 58423
    },
    {
      "fileName": "Louisiana Laws - Louisiana State Legislature.html",
      "relativePath": "LegalEase Louisiana/Louisiana Laws - Louisiana State Legislature.html",
      "classification": "reference",
      "sha256": "89f6adefe76ed20d9374c25c098c523755fe834ef837983252bc5b873c39eeb5",
      "sizeBytes": 54605
    }
  ],
  "customPleadingSupport": {
    "supported": true,
    "status": "draft_config_allowed",
    "notes": "Pleading-style draft support may be built from Nationwide resources and coded state-pack data where available."
  },
  "guidanceOnlyFallback": {
    "supported": true,
    "label": "Louisiana record-clearing guidance fallback",
    "status": "built",
    "notes": "Available for internal review even when official forms or pleading templates need more work."
  },
  "disclaimer": "This RCAP build artifact is for internal document-preparation and review workflows. It is not legal advice, does not guarantee eligibility or outcomes, and is not approved for live use until QA, counsel, and any required visual review pass.",
  "buildStatusMetadata": {
    "buildStatus": "state_built",
    "statusHistory": [
      "not_started",
      "nationwide_resources_found",
      "resource_packet_ingested",
      "state_pack_built",
      "pleading_packet_rendered",
      "guidance_packet_rendered",
      "state_built"
    ],
    "reviewStatuses": {
      "qa": "pending",
      "visual": "not_applicable",
      "counsel": "pending",
      "sourceFreshness": "pending"
    },
    "loops": [
      {
        "id": "nationwide_folder_ingestion_loop",
        "status": "completed"
      },
      {
        "id": "all_state_build_loop",
        "status": "completed"
      },
      {
        "id": "official_pdf_overlay_factory_loop",
        "status": "not_applicable_no_pdf"
      },
      {
        "id": "field_map_retry_loop",
        "status": "not_applicable_no_pdf"
      },
      {
        "id": "custom_pleading_factory_loop",
        "status": "draft_ready"
      },
      {
        "id": "guidance_packet_loop",
        "status": "completed"
      },
      {
        "id": "packet_render_qa_loop",
        "status": "pending_review"
      },
      {
        "id": "review_artifact_loop",
        "status": "completed"
      },
      {
        "id": "integration_preview_loop",
        "status": "internal_preview_ready"
      },
      {
        "id": "official_forms_watcher_loop",
        "status": "source_tracked"
      }
    ],
    "liveRouting": {
      "approvedForLive": false,
      "live": false,
      "note": "Build-first state output is internal review material only."
    }
  },
  "buildIssues": []
} as const;
