// Louisiana eligibility rules. Sourced from the Louisiana Expungement Reference
// for Wilma (Nationwide Record Clearing), corroborated by La. Code Crim. Proc.
// tit. XXXIV, arts. 971-999.1 and the cited LSP/BCII guidance. Citations are
// La. Code Crim. Proc. unless noted.
export const laEligibilityRules = [
  "Louisiana expungement removes arrest or conviction records, photographs, fingerprints, dispositions, and related information from PUBLIC access; it does not destroy the record. Expunged records remain available to law enforcement, criminal-justice agencies, prosecutors, certain licensing/regulatory entities, courts, and other statutorily authorized users. Louisiana adult expungements are governed mainly by La. Code Crim. Proc. tit. XXXIV, arts. 971-999.1, and the official filing is a 'Motion for Expungement.'",
  "Filing bar (La. Code Crim. Proc. tit. XXXIV): a person in the physical custody of the Department of Public Safety and Corrections serving a hard-labor sentence may not file a motion to expunge an arrest or conviction record at that time — hard stop until custody status changes or an attorney advises.",
  "Arrest with no conviction (arts. 976-977): a felony or misdemeanor arrest that did not result in conviction may be expunged when (1) the person was not prosecuted and the time to prosecute has expired; (2) the DA declined to prosecute any offense from the arrest, including after completed pretrial diversion; (3) prosecution ended by dismissal, sustained motion to quash, or acquittal; or (4) the person was judicially determined factually innocent and entitled to wrongful-conviction compensation. Special DWI rule: if the arrest was for DWI (or a local equivalent) and the person entered pretrial diversion, expungement is not available until five years have elapsed from the date of arrest.",
  "Misdemeanor conviction (art. 977): may be expunged if (1) the conviction was set aside and prosecution dismissed under art. 894(B); or (2) more than five years have passed since completion of sentence/deferred adjudication/probation/parole with no felony conviction during that five-year period and no pending felony charge (a DA certification is required for the five-year route). Misdemeanor exclusions: flag legal review / likely ineligibility for a misdemeanor sex offense, domestic abuse battery, or stalking.",
  "First-offense marijuana (art. 998): a first-offense misdemeanor conviction for possession of marijuana, THC, or chemical derivatives may be filed 90 days after conviction using the special art. 998 form. The special fee cap in art. 983(M) is scheduled to terminate on August 1, 2026 — do not assume the reduced-cost structure after that date without checking the statute.",
  "Felony conviction (art. 978): may be expunged if not blocked by art. 978(B) and one of: (1) the conviction was set aside and prosecution dismissed under art. 893(E); (2) more than ten years have passed since completion of sentence/deferred adjudication/probation/parole, with no other criminal conviction during the ten-year period before filing and no pending charge (DA certification required); or (3) the person is entitled to a first-offender pardon for the offense, provided it is not a crime of violence or sex offense.",
  "First-offender pardon (La. R.S. 15:572): a first offender never previously convicted of a felony is automatically pardoned upon completion of sentence without Board of Pardons recommendation or governor action, but no pardon is issued unless court costs for the conviction are paid.",
  "Felony exclusions (art. 978(B)): generally blocks expungement for crimes of violence, sex offenses or offenses against minor victims, many controlled-dangerous-substance offenses outside listed exceptions, and domestic abuse battery. Drug convictions may still be eligible within art. 978 exceptions, including certain possession offenses, possession with intent to distribute, CDS offenses punishable by not more than five years, art. 893(E) cases, or first-offender-pardon cases.",
  "Special violent-offense exception (art. 978(E)): after a contradictory hearing the court may expunge records for aggravated battery, second degree battery, aggravated criminal damage to property, simple robbery, purse snatching, or illegal use of weapons/dangerous instrumentalities if more than ten years have passed since completion, the person has had no criminal conviction during that ten-year period, and has no pending charge.",
  "Multiple felonies: a person may have more than one felony conviction expunged in a ten-year period if each felony is independently eligible under art. 978.",
  "Interim expungement (arts. 994-995): where the person was originally arrested for a felony but the case resulted in a misdemeanor conviction, an interim expungement removes the felony arrest entry; it does not expunge the misdemeanor conviction (a separate art. 976-978 analysis). There is no art. 977/978 waiting-period limit and no numerical cap on interim expungements.",
  "Expungement by redaction: where a record names multiple people and only one is eligible, the court may order redaction — removing the eligible person's name and identifying information while the rest of the incident record may remain public as to others.",
  "Human-trafficking-victim pathway: a trafficking victim may request DA certification that the offense was committed substantially because of trafficking victimization; if obtained, the applicable art. 977 and 978 time delays are waived and the applicant is not required to pay expungement fees — route to legal aid / an attorney.",
  "Automated expungement (art. 985.2): an automated-expungement process exists for qualifying records but is subject to legislative appropriation/funding — do not promise a record will be automatically expunged; treat as a possible process to verify with LSP/BCII or the clerk.",
  "Immediate expungement by court discretion (art. 985.3): a court may order immediate expungement when a person is otherwise eligible and successfully completes a court-ordered probation or alternative-sentencing program; the signed order is served under art. 982 with the bill of information, sentencing minutes, and relevant arrest/plea records if available."
];
