// Louisiana filing workflow. Sourced from the Louisiana Expungement Reference for
// Wilma (Nationwide Record Clearing), sections 2, 6, and 9, corroborated by
// La. Code Crim. Proc. arts. 972.1, 980-982 and LSP/BCII guidance. Louisiana uses
// statutory forms built into the Code; this pack is shadow-only research and
// wires no renderer.
export const laFilingInstructions = [
  "Get the record first: obtain a Right to Review — a fingerprint-based Louisiana criminal-history check from Louisiana State Police / BCII — because the Motion for Expungement must match the state rap sheet, including the arrest/booking date, ORIGINAL arrest charge, arrest number, and all counts.",
  "Determine the pathway: no-conviction (arts. 976-977), misdemeanor conviction (art. 977: art. 894(B) set-aside or 5-year route), felony conviction (art. 978: art. 893(E) set-aside, 10-year route, or first-offender pardon), first-offense marijuana (art. 998), interim expungement (arts. 994-995), redaction, trafficking-victim, or program-completion immediate expungement (art. 985.3).",
  "Set aside first where required: if a deferred conviction under art. 893 (felony) or art. 894 (misdemeanor) has not yet been set aside but appears available, file a Motion to Set Aside Conviction and Dismiss Prosecution (art. 987) before the Motion for Expungement (art. 989).",
  "File in the parish of arrest/conviction: the packet is filed with the clerk of court in that parish. Art. 972.1 gives district courts, city/parish courts, mayor's/traffic courts, juvenile/family courts, and New Orleans municipal/traffic courts authority within their trial jurisdiction.",
  "Use the correct statutory forms: Motion for Expungement (art. 989), Order (art. 991), Order of Expungement of Arrest/Conviction Record (art. 992), Affidavit of Response / no-opposition route (art. 990), Certification of Fee Waiver (art. 988) if eligible, and Supplemental Forms (art. 993) for extra charges/counts. Art. 986 provides that only the forms in arts. 987-995 and 998 are used for standard expungement motions.",
  "Service: after filing, the clerk serves the motion by U.S. mail or electronically on the district attorney, Louisiana BCII, and the arresting law-enforcement agency. If expungement is granted, the clerk serves the order and judgment on the DA, BCII, sheriff, and arresting agency.",
  "Objection and hearing: an objecting agency must file an affidavit of response (generally within 60 days of service); a timely objection triggers a contradictory hearing where the agency must show by a preponderance why expungement should not be granted. If no objection is filed, the mover may waive the hearing and the court must grant the motion if it determines the mover is legally entitled.",
  "Match the rap sheet exactly: LSP flags common errors — wrong arrest date, using the amended charge instead of the original arrest charge, omitting counts, putting misdemeanors/felonies in the wrong section, missing dispositions/certifications/fee waivers, and choosing the wrong eligibility basis on the Motion for Expungement.",
  "Fees: the standard cap is $550 (collected at filing, nonrefundable even if denied); the first-offense-marijuana cap is $300 only while art. 983(M) remains in effect (scheduled to terminate August 1, 2026). DA-certified non-conviction categories, trafficking-victim certification, factual-innocence, certain pardons, and expedited expungement may create fee exemptions — but LSP says a person who has ever been convicted of a felony (including an expunged felony) is ineligible for a fee waiver."
];
