// Application copy only; partner facts retain their approved language.
export const RCAP_SPANISH_COPY:Readonly<Record<string,string>> = {
  "Current task":"Tarea actual",
  "Confirm the package is accurate and authorized for implementation review.": "Confirme que el paquete sea correcto y esté autorizado para revisión de implementación.",
  "Set the support, escalation, legal-referral, and reporting operating plan.": "Defina el plan operativo de apoyo, escalamiento, derivación legal e informes.",
  "Plan dashboard access without creating memberships or sending invitations.": "Planifique el acceso al panel sin crear membresías ni enviar invitaciones.",
  "Provide approved plain-language copy and organizational brand materials.": "Proporcione texto claro aprobado y materiales de marca de la organización.",
  "Plan participant access while keeping contract and billing terms read-only.": "Planifique el acceso de participantes; las condiciones contractuales y de facturación son de solo lectura.",
  "Describe where and how the participant program should serve your community.": "Describa dónde y cómo el programa debe servir a su comunidad.",
  "Define the program’s goals, audience, timing, and expected reach.": "Defina los objetivos, el público, los plazos y el alcance previsto del programa.",
  "Tell us who the program represents and who will help make it successful.": "Indique a quién representa el programa y quién ayudará a llevarlo adelante.",
  "Editing opens once your program terms are confirmed.": "La edición se habilita al confirmar las condiciones de su programa.",
  "Editing is currently locked.": "La edición está bloqueada.",
  "Changes save automatically.": "Los cambios se guardan automáticamente.",
  "After Save and Continue": "Después de guardar y continuar",
  "Needs information": "Falta información",
  "Saved task": "Tarea guardada",
  "Not finished": "Sin terminar",
  "In progress": "En curso",
  "Program configuration | Section": "Configuración del programa | Sección",
  "Use the official name for agreements and the public names participants should see.": "Use el nombre oficial para los acuerdos y los nombres públicos que verán los participantes.",
  "These addresses record responsibilities only. Saving them does not send invitations.": "Estas direcciones solo registran responsabilidades. Guardarlas no envía invitaciones.",
  "Goals and audience": "Objetivos y público",
  "Describe what the program should accomplish in concrete, plain language.": "Describa con palabras claras y concretas lo que debe lograr el programa.",
  "Use your best planning estimate. These values do not change contracted allocations.": "Use su mejor estimación de planificación. Estos valores no cambian las asignaciones contratadas.",
  "Enter one outreach channel per line and identify barriers the operating plan should address.": "Ingrese un canal de difusión por línea e identifique las barreras que debe abordar el plan operativo.",
  "Geography and service area": "Geografía y área de servicio",
  "Jurisdictions configure the participant path. County settings support routing and reporting; they are not eligibility promises.": "Las jurisdicciones configuran el recorrido del participante. Los condados permiten la derivación y los informes; no prometen elegibilidad.",
  "Language and accessibility": "Idioma y accesibilidad",
  "These settings configure the participant program experience; they do not change the language of this partner portal.": "Estas opciones configuran la experiencia del participante; no cambian el idioma de este portal de socios.",
  "Participant access plan": "Plan de acceso de participantes",
  "This records the intended access model only. No access code or invitation is created here.": "Esto solo registra el modelo de acceso previsto. Aquí no se crea ningún código de acceso ni invitación.",
  "What happens as the program approaches its cap. This is your operating procedure; it does not change the contracted capacity.": "Qué sucede cuando el programa se acerca a su límite. Este es su procedimiento operativo; no cambia la capacidad contratada.",
  "Contract, billing, and provisioning records control these values. Partner edits cannot change them.": "Los registros contractuales, de facturación y de habilitación controlan estos valores. Los cambios del socio no pueden modificarlos.",
  "Sponsored scope and capacity": "Alcance y capacidad patrocinados",
  "Approved public-page copy": "Texto aprobado de la página pública",
  "Provide plain text approved by your team. LegalEase-controlled legal and product language remains read-only.": "Proporcione texto sin formato aprobado por su equipo. El contenido legal y del producto controlado por LegalEase sigue siendo de solo lectura.",
  "Legal disclaimers, self-help boundaries, eligibility and outcome claims, platform privacy and security statements, payment logic, participant routing, and LegalEase legal links are reviewed and controlled by LegalEase.": "LegalEase revisa y controla los avisos legales, límites de autoayuda, declaraciones de elegibilidad y resultados, privacidad y seguridad, pagos, derivación de participantes y enlaces legales.",
  "This is an access plan only. Saving it does not create a membership or send an invitation.": "Esto es solo un plan de acceso. Guardarlo no crea una membresía ni envía una invitación.",
  "Access responsibilities": "Responsabilidades de acceso",
  "Choose the planned administrator and the roles responsible for recurring access tasks.": "Seleccione el administrador previsto y los roles responsables de las tareas de acceso recurrentes.",
  "Training, invitation, and membership truth comes from LegalEase systems. This plan cannot activate an account.": "Los sistemas de LegalEase determinan el estado real de capacitación, invitaciones y membresías. Este plan no puede activar una cuenta.",
  "Current account status": "Estado actual de la cuenta",
  "Participant and staff support": "Apoyo a participantes y personal",
  "Legal referral and escalation": "Derivación legal y escalamiento",
  "When a prosecutor objects, a contested hearing is scheduled, or individualized legal advocacy is required, the self-help path must stop and this approved referral process applies.": "Cuando un fiscal presenta una objeción, se programa una audiencia impugnada o se requiere representación legal individual, se debe detener la vía de autoayuda y aplicar este proceso de derivación aprobado.",
  "Escalation routes, owners, and response expectations": "Rutas de escalamiento, responsables y plazos de respuesta",
  "The Operations and Escalation Plan names each of these routes with the person who owns it and how quickly they respond. Anything left blank is shown in the plan as a named gap rather than filled in for you.": "El plan de operaciones y escalamiento identifica cada ruta, su responsable y el plazo de respuesta. Los espacios sin completar aparecen como datos pendientes en el plan.",
  "These entries define intended report delivery only; saving them sends nothing.": "Estos datos solo definen la entrega prevista de informes; guardarlos no envía nada.",
  "Reporting plan": "Plan de informes",
  "LegalEase technical support": "Soporte técnico de LegalEase",
  "Required acknowledgments": "Confirmaciones obligatorias",
  "Review each statement carefully. These acknowledgments let LegalEase prepare your program; they are not an e-signature or a replacement for an agreement.": "Revise cada declaración con cuidado. Estas confirmaciones permiten que LegalEase prepare su programa; no son una firma electrónica ni reemplazan un acuerdo.",
  "LegalEase records who submits this form, their work email, and the submission date and time.": "LegalEase registra quién envía el formulario, su correo laboral y la fecha y hora del envío.",
  "Submission audit details": "Datos de auditoría del envío",
  "Files remain private. Upload only approved organization, brand, and requested procurement materials. Never upload participant or case files.": "Los archivos permanecen privados. Suba solo materiales aprobados de organización, marca y compras solicitadas. Nunca suba archivos de participantes ni de casos.",
  "Information reused from earlier sections": "Información reutilizada de secciones anteriores",
  "Each answer is shown once. Use its edit link to make changes.": "Cada respuesta aparece una sola vez. Use su enlace de edición para cambiarla.",

  "Public organization name":"Nombre público de la organización",
  "Organization website":"Sitio web de la organización",
  "Main phone":"Teléfono principal",
  "Public program name":"Nombre público del programa",
  "Preferred public-page address":"Dirección preferida de la página pública",
  "Public identity and website":"Identidad pública y sitio web",
  "Confirm the names and contact details participants may see.":"Confirme los nombres y datos de contacto que podrán ver los participantes.",
  "These values will be available to the later private-page review.":"Estos datos estarán disponibles en la posterior revisión privada de la página.",
  "Fix this information before continuing": "Corrija esta información antes de continuar",
  "Your entries remain in place. The first invalid field receives focus.": "Sus respuestas se conservan. El primer campo que necesita una corrección recibe el foco.",
  "Prepared by LegalEase": "Preparado por LegalEase",
  "Partner updated": "Actualizado por su equipo",
  "Requested by": "Solicitado por",
  "Requested on": "Fecha de solicitud",
  "Reason": "Motivo",
  "Requested correction": "Corrección solicitada",
  "Current value": "Valor actual",
  "The saved value is shown in the field below.": "El valor guardado aparece en el campo siguiente.",
  "LegalEase requested an update to this field.": "LegalEase solicitó una actualización de este campo.",
  "One item per line.": "Un elemento por línea.",
  "Choose a contact": "Seleccione un contacto",
  "Choose an option": "Seleccione una opción",
  "Select an option": "Seleccione una opción",
  "Yes": "Sí",
  "No": "No",
  "Not sure": "No estoy seguro",
  "Save & Continue": "Guardar y continuar",
  "Save and continue": "Guardar y continuar",
  "Saved": "Guardado",
  "Save failed": "No se pudo guardar",
  "Your session expired. Sign in again to continue.": "Su sesión venció. Inicie sesión de nuevo para continuar.",
  "Program setup could not be updated. Try again.": "No se pudo actualizar la configuración del programa. Vuelva a intentarlo.",
  "Organization type": "Tipo de organización",
  "Legal organization name": "Nombre legal de la organización",
  "Program purpose": "Propósito del programa",
  "Program goal": "Objetivo del programa",
  "Desired outcomes": "Resultados deseados",
  "Target population": "Población a la que se dirige",
  "Estimated screenings": "Evaluaciones previstas",
  "Estimated packets": "Paquetes previstos",
  "Forecast period": "Período de la previsión",
  "Program model": "Modelo del programa",
  "Program start date": "Fecha de inicio del programa",
  "Program end date": "Fecha de finalización del programa",
  "Ongoing program": "Programa continuo",
  "Jurisdictions": "Jurisdicciones",
  "Counties": "Condados",
  "Service area": "Zona de servicio",
  "Service area description": "Descripción de la zona de servicio",
  "Primary language": "Idioma principal",
  "Enable Spanish": "Ofrecer español",
  "Additional languages": "Idiomas adicionales",
  "Accessibility needs": "Necesidades de accesibilidad",
  "Participant age restrictions": "Restricciones de edad de los participantes",
  "Out-of-area policy": "Política para personas de otras zonas",
  "Program headline": "Título de la página del programa",
  "Program subheadline": "Subtítulo de la página del programa",
  "Approved organization description": "Descripción aprobada de la organización",
  "Primary CTA label": "Texto del botón principal",
  "Participant support instructions": "Instrucciones de asistencia para participantes",
  "Partner privacy policy URL": "URL de la política de privacidad de la organización",
  "Accessibility URL": "URL de accesibilidad",
  "Impact URL": "URL de resultados",
  "Reporting cadence": "Frecuencia de los informes",
  "Report recipients": "Destinatarios de los informes",
  "Participant support email": "Correo de asistencia para participantes",
  "Participant support phone": "Teléfono de asistencia para participantes",
  "First name": "Nombre",
  "Last name": "Apellido",
  "Name": "Nombre",
  "Title": "Cargo",
  "Work email": "Correo de trabajo",
  "Phone": "Teléfono",
  "Role": "Función",
  "Organization": "Organización",
  "Add contact": "Añadir contacto",
  "Remove contact": "Eliminar contacto",
  "Add dashboard user": "Añadir usuario del panel",
  "Add report recipient": "Añadir destinatario del informe",
  "Remove": "Eliminar",
  "Upload": "Subir archivo",
  "Download": "Descargar",
  "Logo": "Logotipo",
  "Hero or community image": "Imagen principal o de la comunidad",
  "Why we ask": "Por qué preguntamos",
  "What does this mean?": "¿Qué significa esto?",
  "Start free": "Comenzar gratis",
  "English": "Inglés",
  "Spanish": "Español",
  "Privacy / data use": "Privacidad y uso de datos",
  "Self-help boundary": "Límites de la autoayuda",
  "No guaranteed legal result": "Sin garantía de un resultado legal",
  "This is the organization name participants will see.": "Este es el nombre de la organización que verán los participantes.",
  "This is a preference only. It does not change your current partner or public-page address.": "Esto es solo una preferencia. No cambia la dirección actual de su organización ni de su página pública.",
  "A person may hold more than one role. Use a separate row for each role; the same email may be reused across different roles.": "Una persona puede tener más de una función. Use una fila por función; puede repetir el correo para funciones distintas.",
  "Describe what the program seeks to achieve. This is a program goal, not a guarantee of court relief.": "Describa lo que el programa busca lograr. Es un objetivo del programa, no una garantía de una resolución judicial.",
  "Name results staff can actually measure and how they will verify them. Packet generation does not prove that a court granted relief.": "Indique resultados que el personal pueda medir y cómo los verificará. Generar un paquete no demuestra que un tribunal haya concedido una reparación.",
  "Describe the community you intend to reach, separately from legal eligibility rules.": "Describa la comunidad a la que desea llegar, por separado de las reglas de elegibilidad legal.",
  "Forecast screenings for the named period. This estimate does not purchase credits or promise an allocation; screenings and packets are different totals.": "Estime las evaluaciones para el período indicado. Esta estimación no compra créditos ni promete una asignación; las evaluaciones y los paquetes son totales distintos.",
  "Name the period covered by your screening forecast, such as the next quarter.": "Indique el período de su previsión de evaluaciones, por ejemplo, el próximo trimestre.",
  "Forecast packets for the named period, separately from screenings. This estimate does not purchase packet credits or promise an allocation.": "Estime los paquetes para el período indicado, por separado de las evaluaciones. Esta estimación no compra créditos para paquetes ni promete una asignación.",
  "Name the period covered by your packet forecast.": "Indique el período de su previsión de paquetes.",
  "Year-round means continuous service; clinic means assisted sessions; event is bounded; campaign is an outreach period; referral-only directs people to another service; cohort serves a defined group. Choosing a model does not activate Clinic Mode or publish intake.": "Todo el año significa servicio continuo; clínica significa sesiones asistidas; evento tiene una duración limitada; campaña es un período de difusión; solo remisiones dirige a otro servicio; cohorte atiende a un grupo definido. Elegir un modelo no activa el modo de clínica ni publica la inscripción.",
  "Record the planned program start. Saving a date does not activate intake.": "Registre la fecha prevista de inicio. Guardar una fecha no activa la inscripción.",
  "Record an end date for a bounded program; ongoing programs do not need one.": "Registre una fecha de finalización para un programa limitado; los programas continuos no la necesitan.",
  "Select whether this program continues without a fixed end. A program that is not ongoing needs an end date.": "Indique si el programa continúa sin una fecha fija de finalización. Un programa no continuo necesita una fecha de finalización.",
  "Describe today's actual process. Label a proposed future process as planned.": "Describa el proceso actual. Identifique un proceso futuro propuesto como previsto.",
  "Select obstacles you know affect participation. An example is not evidence that a barrier exists in your community.": "Seleccione obstáculos que sabe que afectan la participación. Un ejemplo no demuestra que exista una barrera en su comunidad.",
  "Describe outcomes your team records outside this platform and distinguish verified outcomes from participant reports. Packet generation is not court relief.": "Describa los resultados registrados por su equipo fuera de esta plataforma y distinga los verificados de los informados por los participantes. Generar paquetes no equivale a una reparación judicial.",
  "County selection configures routing and reporting; it is not an eligibility promise.": "Seleccionar condados configura las rutas y los informes; no promete elegibilidad.",
  "This configures the participant program; it does not change the partner portal language.": "Esto configura el programa para participantes; no cambia el idioma del portal de la organización.",
  "Describe required or planned usability support. Recording it does not certify that an accommodation is implemented or meets a standard.": "Describa la asistencia de accesibilidad necesaria o prevista. Registrarla no certifica que se haya implementado ni que cumpla una norma.",
  "Record partner-program limits separately from legal eligibility. An adults-only program has an age restriction; do not describe it as unrestricted.": "Registre los límites del programa por separado de la elegibilidad legal. Un programa solo para adultos tiene una restricción de edad; no lo describa como sin restricciones.",
  "This records the implementation plan only. It does not create or release access codes.": "Esto registra solo el plan de implementación. No crea ni distribuye códigos de acceso.",
  "Choose a saved contact. This does not change the contracted overage policy.": "Seleccione un contacto guardado. Esto no cambia la política contractual de excedentes.",
  "Describe what happens as the program approaches its cap: who is told, who decides, and what participants are told while a decision is pending.": "Describa qué ocurre cuando el programa se aproxima a su límite: quién recibe el aviso, quién decide y qué se comunica a los participantes mientras se espera una decisión.",
  "For example, a decision within two business days.": "Por ejemplo, una decisión dentro de dos días hábiles.",
  "Use organization-approved public copy. This text still requires public-page review before publication.": "Use texto público aprobado por la organización. Este texto aún necesita revisión de la página antes de publicarse.",
  "Use accurate public copy that can be reviewed before publication; do not promise a legal outcome.": "Use texto público preciso que se pueda revisar antes de publicarlo; no prometa un resultado legal.",
  "Describe the actual program scope in public copy for review, without promising court relief.": "Describa el alcance real del programa en texto público para revisión, sin prometer una reparación judicial.",
  "Describe the actual free entry step when using Start free. Do not imply that every later service is free.": "Describa el paso inicial realmente gratuito al usar Comenzar gratis. No implique que todos los servicios posteriores son gratuitos.",
  "State the help actually available. This text does not create staffing or a support commitment.": "Indique la ayuda realmente disponible. Este texto no crea personal ni un compromiso de asistencia.",
  "Use an existing, approved organization privacy page or leave blank. Do not guess a URL.": "Use una página de privacidad existente y aprobada, o deje el campo vacío. No invente una URL.",
  "Use an existing, approved organization accessibility page or leave blank. Do not guess a URL.": "Use una página de accesibilidad existente y aprobada, o deje el campo vacío. No invente una URL.",
  "Use an existing, approved organization impact page or leave blank. Do not guess a URL.": "Use una página de resultados existente y aprobada, o deje el campo vacío. No invente una URL.",
  "This is a plan only. Saving a row does not create a membership or send an invitation.": "Esto es solo un plan. Guardar una fila no crea una membresía ni envía una invitación.",
  "State how routinely account permissions are reviewed and how staff departures or role changes trigger prompt action. This answer schedules nothing and changes no access.": "Indique con qué frecuencia revisan los permisos de las cuentas y cómo las salidas o cambios de función del personal provocan una acción oportuna. Esta respuesta no programa nada ni cambia el acceso.",
  "Use a monitored address where staff can provide the stated help. Saving an address does not create a mailbox.": "Use una dirección supervisada donde el personal pueda brindar la ayuda indicada. Guardar una dirección no crea un buzón.",
  "Choose the actual program policy. Outside legal referral differs from internal escalation. Every choice preserves the self-help stop for prosecutor opposition, contested hearings, and individualized advocacy; it does not waive separate professional obligations in legal-services programs.": "Seleccione la política real del programa. La remisión legal externa es distinta de la escalación interna. Todas las opciones mantienen la suspensión de la autoayuda ante oposición de la fiscalía, audiencias controvertidas o defensa individualizada; no eximen de obligaciones profesionales separadas de los programas de servicios legales.",
  "For an established provider, name its real intake method. For general resources, name the concrete operator-reviewed resource route; no acceptance or automatic information transfer is guaranteed.": "Para un proveedor establecido, indique su método real de admisión. Para recursos generales, indique la ruta concreta revisada por un operador; no se garantiza aceptación ni transferencia automática de información.",
  "Record actual intake instructions or the concrete reviewed resource route. General resources create no standing referral relationship or automatic transfer of participant information.": "Registre instrucciones reales de admisión o la ruta concreta de recursos revisados. Los recursos generales no crean una relación permanente de remisión ni una transferencia automática de información del participante.",
  "The self-help path stops for prosecutor opposition, a contested hearing, or individualized advocacy. State who stops work, notifies the participant, and follows the chosen referral or internal escalation procedure; this does not authorize nonlawyer representation.": "La autoayuda se detiene ante oposición de la fiscalía, una audiencia controvertida o defensa individualizada. Indique quién detiene el trabajo, notifica al participante y sigue el procedimiento elegido de remisión o escalación interna; esto no autoriza representación por personas que no sean abogados.",
  "For example, a reply within one business day.": "Por ejemplo, una respuesta dentro de un día hábil.",
  "Record a verified referral acknowledgement expectation, not an invented provider promise or guaranteed acceptance.": "Registre una expectativa verificada de confirmación de la remisión, no una promesa inventada del proveedor ni una aceptación garantizada.",
  "Record the internal program lead acknowledgement/update target for a stopped matter. This is not an imaginary lawyer response, legal deadline, or guaranteed resolution.": "Registre el plazo interno de confirmación o actualización del responsable del programa para un asunto detenido. No es una respuesta imaginaria de un abogado, un plazo legal ni una resolución garantizada.",
  "State who receives a privacy request and what happens next. Saving this route does not create a mailbox or new enforcement.": "Indique quién recibe una solicitud de privacidad y qué ocurre después. Guardar esta ruta no crea un buzón ni nuevos mecanismos de aplicación.",
  "Choose a saved contact from Organization and contacts.": "Seleccione un contacto guardado en Organización y contactos.",
  "Record a planned acknowledgement/update target, not a legal deadline or guaranteed resolution.": "Registre un plazo previsto de confirmación o actualización, no un plazo legal ni una resolución garantizada.",
  "State who receives a security concern and the next action staff take.": "Indique quién recibe una inquietud de seguridad y la siguiente acción del personal.",
  "Record the media contact acknowledgement/update target, not a guaranteed answer or resolution.": "Registre el plazo de confirmación o actualización del contacto de medios, no una respuesta ni una resolución garantizada.",
  "State who can request and approve a pause and what staff communicate to participants. Saving this plan does not pause a program.": "Indique quién puede solicitar y aprobar una pausa y qué comunica el personal a los participantes. Guardar este plan no pausa un programa.",
  "Record a planned acknowledgement/update target for a pause request; saving it schedules no action.": "Registre un plazo previsto de confirmación o actualización de una solicitud de pausa; guardarlo no programa ninguna acción.",
  "State the reporting schedule. Saving it does not schedule reports or send automatic emails.": "Indique la frecuencia de los informes. Guardarla no programa informes ni envía correos automáticos.",
  "List actual funder obligations, rather than suggested metrics you have not agreed to provide.": "Enumere obligaciones reales con los financiadores, no métricas sugeridas que no hayan aceptado proporcionar.",
  "Record actual organization data-use rules. Saving prose does not implement new automatic enforcement.": "Registre las reglas reales de uso de datos de la organización. Guardar texto no implementa nuevos mecanismos automáticos de aplicación.",
  "Identify outside outcome sources and whether they are verified or self-reported. Generating a packet does not establish court relief.": "Identifique fuentes externas de resultados e indique si son verificadas o informadas por los participantes. Generar un paquete no establece una reparación judicial.",
  "Return to implementation center": "Volver al centro del programa",
  "Editing locked": "Edición bloqueada",
  "Program configuration · Section": "Configuración del programa · Sección",
  "Program configuration ": " Section|Configuración del programa · Sección",
  "of 8": "de 8",
  "Setup is waiting on your program terms": "La configuración espera las condiciones del programa",
  "You can review this task. Editing opens after LegalEase confirms the applicable commercial arrangement.": "Puede revisar esta tarea. La edición se habilita cuando LegalEase confirma el acuerdo comercial aplicable.",
  "Your entries remain in this view and nothing you typed was overwritten.": "Sus respuestas permanecen en esta vista y no se sobrescribió lo que escribió.",
  "Review the pre-filled information in this task.": "Revise la información preparada en esta tarea.",
  "Correct or clear anything that changed before continuing.": "Corrija o borre lo que haya cambiado antes de continuar.",
  "Review the request, then open the first task. The section-level model does not identify one authoritative field.": "Revise la solicitud y abra la primera tarea. La solicitud de la sección no identifica un único campo autorizado.",
  "Review section tasks": "Revisar las tareas de la sección",
  "Section tasks": "Tareas de la sección",
  "Open decision summary": "Abrir el resumen de decisiones",
  "Review responsibilities before deciding": "Revise las responsabilidades antes de decidir",
  "The partner decision covers organization facts and brand content. LegalEase controls legal language, eligibility and outcome claims, payment behavior, routing, privacy claims, and participant activation.": "La decisión de su equipo cubre los datos de la organización y su marca. LegalEase controla el lenguaje legal, las afirmaciones de elegibilidad y resultados, los pagos, las rutas, la privacidad y la activación de participantes.",
  "Partner approval does not publish the page or activate participant intake.": "La aprobación de su equipo no publica la página ni activa la inscripción de participantes.",
  "Decision summary comes first": "Primero aparece el resumen de decisiones",
  "Save this section, then open the final review to see decisions, exceptions, publication, activation, and the one current next action.": "Guarde esta sección y abra la revisión final para ver decisiones, excepciones, publicación, activación y la siguiente acción actual.",
  "No reusable public identity has been saved yet. Return to the source sections to provide it.": "Aún no se ha guardado una identidad pública reutilizable. Vuelva a las secciones de origen para proporcionarla.",
  "Content responsibility": "Responsabilidad del contenido",
  "Partner content": "Contenido de su organización",
  "Organization facts, brand assets, support information, and partner links.": "Datos de la organización, archivos de marca, información de asistencia y enlaces de su organización.",
  "LegalEase-controlled content": "Contenido controlado por LegalEase",
  "Legal boundaries, claims, privacy statements, payment behavior, eligibility, and participant routing.": "Límites legales, afirmaciones, declaraciones de privacidad, pagos, elegibilidad y rutas de participantes.",
  "Private preview": "Vista previa privada",
  "Participant page": "Página para participantes",
  "This page is not published and participant intake is inactive.": "Esta página no está publicada y la inscripción de participantes está inactiva.",
  "Save the canonical brand task before retrying the preview.": "Guarde la tarea de marca antes de volver a intentar la vista previa.",
  "Needed before review": "Necesario antes de la revisión",
  "Saving or approving these values does not publish this page, create an access code, or activate participant intake.": "Guardar o aprobar estos datos no publica la página, crea códigos de acceso ni activa la inscripción de participantes.",
  "What happened": "Qué ocurrió",
  "What remained safe": "Qué se conservó",
  "What to do now": "Qué hacer ahora",
  "Need help? Email": "¿Necesita ayuda? Escriba a",
  "Contact": "Contacto",
  "Spanish participant-program configuration will be included in launch preparation. LegalEase will review translated controlled content separately.": "La configuración en español para participantes se incluirá en la preparación del lanzamiento. LegalEase revisará por separado las traducciones de su contenido controlado.",
  "Participants can enter through the open program path. Code-planning fields are not active.": "Los participantes pueden ingresar mediante la ruta abierta del programa. Los campos de planificación de códigos no están activos.",
  "These items are not editable in partner onboarding.": "Estos elementos no se pueden editar en la configuración de su organización.",
  "Planned user": "Usuario previsto",
  "Add planned user": "Añadir usuario previsto",
  "Recipient": "Destinatario",
  "· up to": "· hasta",
  "Rejection reason:": "Motivo del rechazo:",
  "This asset record does not carry a partner-safe reason. Contact partners@legalease.com before replacing it.": "Este archivo no incluye un motivo visible para su equipo. Escriba a partners@legalease.com antes de reemplazarlo.",
  "Download private file": "Descargar archivo privado",
  "No current file.": "No hay un archivo actual.",
  "Uploading private file": "Subiendo archivo privado",
  "Drop an approved file here": "Arrastre aquí un archivo aprobado",
  "The file remains private. Uploading or replacing it does not publish the participant page or activate the program.": "El archivo permanece privado. Subirlo o reemplazarlo no publica la página de participantes ni activa el programa.",
  "Choose a person": "Seleccione una persona",
  "Current saved selection": "Selección guardada actual",
  "(required)": "(obligatorio)",
  "Partner response": "Respuesta de su equipo",
  "Resolution status": "Estado de resolución",
  "Edit source": "Editar información de origen",
  "LegalEase review request": "Solicitud de revisión de LegalEase",
  "This request applies to this part of the section.": "Esta solicitud se aplica a esta parte de la sección.",
  "The current request is attached to the section rather than one authoritative field. No field-level target has been inferred from the request text.": "La solicitud actual corresponde a la sección y no a un único campo autorizado. No se ha inferido un campo específico a partir del texto de la solicitud.",
  "Correct the relevant task, then submit the section. The current authoritative workflow records the partner response when that submission succeeds.": "Corrija la tarea correspondiente y envíe la sección. El flujo autorizado registra la respuesta de su equipo cuando el envío se completa.",
  "No further partner action is required unless LegalEase requests another correction.": "Su equipo no necesita actuar de nuevo a menos que LegalEase solicite otra corrección.",
  "View resolved request history (": "Ver historial de solicitudes resueltas (",
  "Requested": "Solicitado",
  "Partner response:": "Respuesta de su equipo:",
  "Staff program summary": "Resumen del programa para el personal",
  "You can read the submitted or approved implementation record because your active": "Puede leer el registro enviado o aprobado porque su función activa de",
  "staff role includes this workspace. A partner administrator manages corrections and submission.": "personal incluye este espacio. Un administrador de la organización gestiona las correcciones y el envío.",
  "Read-only section": "Sección de solo lectura",
  "Step": "Paso",
  "of": "de",
  "This task explains the implementation decision and has no staff-editable field.": "Esta tarea explica la decisión de implementación y no incluye campos editables por el personal.",
  "Need a correction? Contact": "¿Necesita una corrección? Contacte a",
  ". Staff access cannot edit or submit this record.": ". El acceso del personal no permite editar ni enviar este registro.",
  "Spanish headline": "Título en español",
  "Spanish supporting line": "Texto de apoyo en español",
  "Spanish organization description": "Descripción de la organización en español",
  "Spanish action label": "Texto del botón en español",
  "Spanish support instructions": "Instrucciones de asistencia en español",
  "Spanish service area": "Zona de servicio en español",
  "Spanish audience description": "Descripción de los participantes en español",
  "Spanish page content": "Contenido de la página en español",
  "Provide organization-approved Spanish copy. This requires the same page review as the English version.": "Proporcione texto en español aprobado por su organización. Requiere la misma revisión de página que la versión en inglés.",
  "Legal disclaimer": "Aviso legal",
  "What this program does and does not do": "Qué hace este programa y cuáles son sus límites",
  "Eligibility and outcomes": "Elegibilidad y resultados",
  "Privacy and security": "Privacidad y seguridad",
  "Cost to the participant": "Costo para el participante",
  "Where participants are sent": "A dónde se dirige a los participantes",
  "Platform terms": "Condiciones de la plataforma",
  "LegalEase provides self-help record-clearing tools and prepared documents. LegalEase is not a law firm, does not provide legal advice, and does not represent participants. Using this program does not create an attorney-client relationship.": "LegalEase ofrece herramientas de autoayuda para la eliminación de antecedentes y documentos preparados. LegalEase no es un bufete de abogados, no ofrece asesoría legal ni representa a los participantes. Usar este programa no crea una relación entre abogado y cliente.",
  "This program helps a participant prepare and file their own record-clearing paperwork. It stops short of legal representation. A contested matter, a prosecutor objection, or a scheduled contested hearing leaves the self-help path and follows the approved referral route.": "Este programa ayuda al participante a preparar y presentar sus propios documentos para la eliminación de antecedentes. No incluye representación legal. Un asunto controvertido, una objeción de la fiscalía o una audiencia controvertida programada sale de la ruta de autoayuda y sigue la ruta de remisión aprobada.",
  "Eligibility is decided by the court and by state law, not by this program. Nothing here guarantees that a record will be cleared or that any particular outcome will follow.": "La elegibilidad depende del tribunal y de la ley estatal, no de este programa. Nada aquí garantiza que se elimine un antecedente ni que se obtenga un resultado específico.",
  "Participant information is handled under the LegalEase privacy practices. LegalEase does not sell participant information.": "La información de los participantes se maneja conforme a las prácticas de privacidad de LegalEase. LegalEase no vende la información de los participantes.",
  "Sponsored participants pay nothing to LegalEase for the sponsored scope of this program. Court filing fees and other government charges are set by the court, not by LegalEase.": "Los participantes patrocinados no pagan a LegalEase por los servicios cubiertos por el patrocinio de este programa. Las tasas de presentación y otros cargos gubernamentales los fija el tribunal, no LegalEase.",
  "Participant routing between screening, document preparation, and the partner's own support is controlled by LegalEase so that a participant is never left without a next step.": "LegalEase controla las rutas entre la evaluación, la preparación de documentos y la asistencia de la organización para que el participante siempre tenga un siguiente paso.",
  "The LegalEase terms of service, privacy policy, and accessibility statement apply to this page and are linked from it.": "Las condiciones del servicio, la política de privacidad y la declaración de accesibilidad de LegalEase se aplican a esta página y están enlazadas desde ella.",
  "Partner staff contact LegalEase platform support through the partner dashboard support link. LegalEase does not provide legal advice or representation to participants.": "El personal de la organización contacta a la asistencia de la plataforma LegalEase mediante el enlace de ayuda del panel. LegalEase no proporciona asesoría legal ni representación a los participantes.",
  "Primary address": "Dirección principal",
  "Program contacts": "Contactos del programa",
  "Contact role": "Función del contacto",
  "Contact name": "Nombre del contacto",
  "Contact title": "Cargo del contacto",
  "Contact organization": "Organización del contacto",
  "Contact phone": "Teléfono del contacto",
  "Primary program goal": "Objetivo principal del programa",
  "Definition of success": "Definición de éxito",
  "Expected screening volume": "Cantidad prevista de evaluaciones",
  "Screening volume period": "Período de la previsión de evaluaciones",
  "Expected packet volume": "Cantidad prevista de paquetes",
  "Packet volume period": "Período de la previsión de paquetes",
  "This is an ongoing program": "Este es un programa continuo",
  "Outreach channels": "Canales de difusión",
  "Current workflow": "Proceso actual",
  "Known barriers": "Obstáculos conocidos",
  "Other known barrier": "Otro obstáculo conocido",
  "Partner-side outcome tracking": "Seguimiento de resultados de la organización",
  "Default county": "Condado predeterminado",
  "Primary participant language": "Idioma principal de los participantes",
  "Enable Spanish participant experience": "Ofrecer la experiencia en español a los participantes",
  "Accessibility accommodations": "Adaptaciones de accesibilidad",
  "Community-specific terminology": "Terminología de la comunidad",
  "Population restrictions": "Restricciones de población",
  "Participant access model": "Cómo ingresan los participantes",
  "Planned code structure": "Estructura prevista de los códigos",
  "Planned code source groups": "Grupos previstos de procedencia de los códigos",
  "Planned code expiration": "Vencimiento previsto de los códigos",
  "Planned code-level capacity": "Capacidad prevista por código",
  "Overage approver": "Responsable de aprobar excedentes",
  "Capacity escalation procedure": "Procedimiento cuando se alcanza la capacidad",
  "Capacity escalation response expectation": "Plazo previsto de respuesta sobre capacidad",
  "Primary action label": "Texto de la acción principal",
  "Participant support copy": "Texto de asistencia para participantes",
  "Partner privacy URL": "URL de privacidad de la organización",
  "Impact reporting URL": "URL del informe de resultados",
  "Planned dashboard users": "Usuarios previstos del panel",
  "Planned user name": "Nombre del usuario previsto",
  "Planned user work email": "Correo de trabajo del usuario previsto",
  "Requested role": "Función solicitada",
  "Special permissions": "Permisos especiales",
  "Training attendee": "Asistente a la capacitación",
  "Primary dashboard administrator": "Administrador principal del panel",
  "User invitation authority role": "Función autorizada para invitar usuarios",
  "Code management authority role": "Función autorizada para administrar códigos",
  "Report export authority role": "Función autorizada para exportar informes",
  "Access review frequency": "Frecuencia de revisión del acceso",
  "Partner staff support contact": "Contacto de asistencia para el personal",
  "Referral arrangement": "Acuerdo de remisión",
  "Legal services referral organization": "Organización de remisión a servicios legales",
  "Referral intake method": "Método de admisión de remisiones",
  "Referral intake details": "Detalles de admisión de remisiones",
  "Contested-matter procedure": "Procedimiento para asuntos controvertidos",
  "Urgent escalation contact": "Contacto para escalaciones urgentes",
  "Participant support response expectation": "Plazo previsto de respuesta a participantes",
  "Legal-services referral response expectation": "Plazo previsto de respuesta a remisiones legales",
  "Contested-matter response expectation": "Plazo previsto de respuesta a asuntos controvertidos",
  "Privacy request route": "Ruta de solicitudes de privacidad",
  "Privacy request owner": "Responsable de solicitudes de privacidad",
  "Privacy request response expectation": "Plazo previsto de respuesta a solicitudes de privacidad",
  "Security concern route": "Ruta de inquietudes de seguridad",
  "Security concern response expectation": "Plazo previsto de respuesta a inquietudes de seguridad",
  "Media inquiry response expectation": "Plazo previsto de respuesta a consultas de medios",
  "Program pause route": "Ruta de solicitudes de pausa del programa",
  "Program pause authority": "Responsable autorizado para pausar el programa",
  "Program pause response expectation": "Plazo previsto de respuesta a solicitudes de pausa",
  "Report recipient name": "Nombre del destinatario del informe",
  "Report recipient work email": "Correo de trabajo del destinatario del informe",
  "Funder-required metrics": "Métricas exigidas por los financiadores",
  "Data-use restrictions": "Restricciones de uso de datos",
  "External outcome data description": "Descripción de datos externos de resultados",
  "Organization information is accurate": "La información de la organización es precisa",
  "Program scope is approved for configuration": "El alcance del programa está aprobado para la configuración",
  "Brand assets are authorized for use": "Se autoriza el uso de los archivos de marca",
  "No eligibility or outcome guarantee is understood": "Se entiende que no se garantiza la elegibilidad ni un resultado",
  "Contested and representation matters follow the escalation plan": "Los asuntos controvertidos o que requieren representación siguen el plan de escalación",
  "Planned dashboard users are authorized": "Los usuarios previstos del panel están autorizados",
  "LegalEase may prepare draft implementation materials": "LegalEase puede preparar borradores de materiales de implementación",
  "Approver name": "Nombre de quien aprueba",
  "Approver title": "Cargo de quien aprueba",
  "Organization identity": "Identidad de la organización",
  "Record the legal identity and primary location used for implementation records.": "Registre la identidad legal y la ubicación principal para los registros de implementación.",
  "LegalEase will use these details to prepare the implementation record.": "LegalEase usará estos datos para preparar el registro de implementación.",
  "Executive sponsor and operational contacts": "Responsable ejecutivo y contactos operativos",
  "Name the people responsible for executive, program, communications, reporting, legal, finance, security, and media decisions.": "Indique las personas responsables de las decisiones ejecutivas, del programa, comunicaciones, informes, asuntos legales, finanzas, seguridad y medios.",
  "Saving the roster records responsibilities. It does not create accounts or send invitations.": "Guardar la lista registra responsabilidades. No crea cuentas ni envía invitaciones.",
  "Program goal and definition of success": "Objetivo del programa y definición de éxito",
  "Describe the result this program should pursue and how your team will recognize progress.": "Describa el resultado que busca el programa y cómo su equipo reconocerá los avances.",
  "LegalEase will use this language to align implementation decisions and reporting.": "LegalEase usará este texto para orientar las decisiones de implementación y los informes.",
  "Describe the community this program is intended to reach without promising legal eligibility or an outcome.": "Describa la comunidad a la que se dirige el programa sin prometer elegibilidad legal ni un resultado.",
  "This description will inform outreach and the participant experience.": "Esta descripción orientará la difusión y la experiencia de los participantes.",
  "Expected reach": "Alcance previsto",
  "Provide planning estimates for screenings and record-clearing packets.": "Proporcione estimaciones de planificación para evaluaciones y paquetes de eliminación de antecedentes.",
  "The estimates guide planning and do not change contracted allocations.": "Las estimaciones orientan la planificación y no cambian las asignaciones contratadas.",
  "Program timing and model": "Calendario y modelo del programa",
  "Choose the operating model and the dates your team currently expects.": "Elija el modelo operativo y las fechas que su equipo prevé actualmente.",
  "LegalEase will compare this plan with readiness and scheduling decisions.": "LegalEase comparará este plan con las decisiones de preparación y calendario.",
  "Outreach, workflow, and barriers": "Difusión, proceso y obstáculos",
  "Describe how people learn about the program, how work moves today, and what may prevent participation.": "Describa cómo se conoce el programa, cómo se realiza el trabajo actualmente y qué puede impedir la participación.",
  "These details will shape implementation tasks and operating guidance.": "Estos datos orientarán las tareas de implementación y las instrucciones operativas.",
  "Partner-side measurement": "Medición de su organización",
  "Explain what your team will measure outside LegalEase reporting.": "Explique qué medirá su equipo fuera de los informes de LegalEase.",
  "The saved answer will define the partner-side measurement responsibility.": "La respuesta guardada definirá la responsabilidad de medición de su organización.",
  "Jurisdiction and service area": "Jurisdicción y zona de servicio",
  "Identify the jurisdictions and describe the intended service area.": "Identifique las jurisdicciones y describa la zona de servicio prevista.",
  "LegalEase will use this information for participant routing and implementation review.": "LegalEase usará esta información para las rutas de participantes y la revisión de implementación.",
  "Counties and geographic restrictions": "Condados y restricciones geográficas",
  "Record county coverage, a default county when needed, and the out-of-area policy.": "Registre los condados cubiertos, el condado predeterminado cuando sea necesario y la política para otras zonas.",
  "These settings guide routing and reporting. They do not promise eligibility.": "Estos ajustes orientan las rutas y los informes. No prometen elegibilidad.",
  "Participant language": "Idioma de los participantes",
  "Record the primary language, Spanish configuration, additional languages, and community terminology.": "Registre el idioma principal, la configuración en español, los idiomas adicionales y la terminología de la comunidad.",
  "LegalEase will use this plan to identify language work before launch.": "LegalEase usará este plan para identificar tareas de idiomas antes del lanzamiento.",
  "Describe the accommodations participants may need to use this program.": "Describa las adaptaciones que podrían necesitar los participantes para usar el programa.",
  "The saved answer will be reviewed during participant-experience readiness.": "La respuesta guardada se revisará al comprobar la experiencia de los participantes.",
  "Record any program-specific population restrictions without changing legal screening rules.": "Registre restricciones de población del programa sin cambiar las reglas de evaluación legal.",
  "LegalEase will review the restriction before configuring participant routing.": "LegalEase revisará la restricción antes de configurar las rutas de participantes.",
  "Choose how participants are expected to enter the program.": "Elija cómo se prevé que ingresen los participantes al programa.",
  "This records the implementation plan. It does not create a code or release an invitation.": "Esto registra el plan de implementación. No crea un código ni envía una invitación.",
  "Sponsorship rules": "Reglas del patrocinio",
  "When codes or invitations are planned, describe their structure, source groups, and expiration.": "Cuando se prevean códigos o invitaciones, describa su estructura, grupos de procedencia y vencimiento.",
  "LegalEase will use the saved rules when access configuration is authorized.": "LegalEase usará las reglas guardadas cuando se autorice la configuración del acceso.",
  "Capacity and allocation": "Capacidad y asignación",
  "Record the planned code-level capacity and review the authoritative sponsored scope.": "Registre la capacidad prevista por código y revise el alcance autorizado del patrocinio.",
  "Partner planning is saved without changing contract, billing, or credit records.": "La planificación de su organización se guarda sin cambiar contratos, facturación ni registros de créditos.",
  "Grace, overage, or stop behavior": "Tolerancia, excedentes o suspensión",
  "Review the authoritative overage behavior and identify an approver when the plan requires one.": "Revise la política autorizada de excedentes e identifique a quien aprueba cuando el plan lo requiera.",
  "The contact choice supports escalation and cannot change commercial terms.": "El contacto elegido apoya la escalación y no puede cambiar las condiciones comerciales.",
  "Capacity escalation": "Escalación por capacidad",
  "Explain what happens near capacity and how quickly the responsible person should respond.": "Explique qué ocurre cerca del límite de capacidad y con qué rapidez debe responder la persona responsable.",
  "The saved procedure will appear in the operating plan.": "El procedimiento guardado aparecerá en el plan operativo.",
  "Reused public identity": "Identidad pública reutilizada",
  "Review the public organization, program, jurisdiction, and language values that are owned by earlier sections.": "Revise los datos públicos de organización, programa, jurisdicción e idioma que pertenecen a secciones anteriores.",
  "Use the source links to correct a reused value without creating a duplicate copy.": "Use los enlaces de origen para corregir un dato reutilizado sin crear una copia duplicada.",
  "Approved public copy": "Texto público aprobado",
  "Provide organization-approved description, headline, supporting line, and primary action label.": "Proporcione una descripción, título, texto de apoyo y acción principal aprobados por su organización.",
  "LegalEase will review the copy before it appears in an authorized private preview.": "LegalEase revisará el texto antes de que aparezca en una vista previa privada autorizada.",
  "Provide your approved Spanish headline, description, geography and support copy when your program supports Spanish.": "Proporcione título, descripción, zona y texto de asistencia aprobados en español cuando su programa ofrezca español.",
  "Both language versions require genuine page review before publication.": "Ambas versiones de idioma requieren una revisión real de la página antes de publicarse.",
  "Participant support information": "Información de asistencia para participantes",
  "Provide the approved support message participants should receive.": "Proporcione el mensaje de asistencia aprobado que deben recibir los participantes.",
  "The saved message remains private until publication is separately approved.": "El mensaje guardado permanece privado hasta que se apruebe por separado su publicación.",
  "Privacy and accessibility links": "Enlaces de privacidad y accesibilidad",
  "Provide organization-owned privacy, accessibility, and impact-reporting links when available.": "Proporcione enlaces de privacidad, accesibilidad e informes de resultados de su organización cuando estén disponibles.",
  "LegalEase will verify the links during private-page review.": "LegalEase verificará los enlaces durante la revisión de la página privada.",
  "Private organizational assets": "Archivos privados de la organización",
  "Upload only approved organization and brand materials. Never upload participant or case files.": "Suba únicamente materiales aprobados de la organización y su marca. Nunca suba archivos de participantes ni de casos.",
  "Files stay in private onboarding storage and remain subject to review.": "Los archivos permanecen en almacenamiento privado de configuración y están sujetos a revisión.",
  "Private preview and approval": "Vista previa privada y aprobación",
  "Review the desktop and mobile participant page, then decide whether the factual and brand content is accurate.": "Revise la página para participantes en escritorio y móvil y decida si los datos y el contenido de marca son precisos.",
  "Your factual and brand decision is recorded separately from LegalEase approval, publication, and participant activation.": "Su decisión sobre los datos y la marca se registra por separado de la aprobación de LegalEase, la publicación y la activación de participantes.",
  "Program staff and reporting viewers": "Personal del programa y lectores de informes",
  "Plan the people, requested roles, permissions, and training attendance for the dashboard.": "Planifique las personas, funciones solicitadas, permisos y asistencia a capacitación para el panel.",
  "Saving the roster does not create memberships or send invitations.": "Guardar la lista no crea membresías ni envía invitaciones.",
  "Primary administrator": "Administrador principal",
  "Choose the planned user who will own administrator decisions.": "Elija al usuario previsto que será responsable de las decisiones administrativas.",
  "The selection records the plan and does not change the active membership.": "La selección registra el plan y no cambia la membresía activa.",
  "Permission expectations": "Permisos previstos",
  "Record which role should invite users, manage codes, and export reports.": "Registre qué función debe invitar usuarios, administrar códigos y exportar informes.",
  "LegalEase will compare these expectations with the authorized role model.": "LegalEase comparará estas expectativas con el modelo de funciones autorizado.",
  "Access review cadence": "Frecuencia de revisión del acceso",
  "Set the planned review cadence and read the current training, invitation, and membership status.": "Indique la frecuencia prevista de revisión y consulte el estado actual de capacitación, invitaciones y membresías.",
  "The cadence is saved without changing authoritative account status.": "La frecuencia se guarda sin cambiar el estado autorizado de las cuentas.",
  "Participant support": "Asistencia para participantes",
  "Record the participant support address, phone, and response expectation.": "Registre el correo, teléfono y plazo previsto de respuesta para asistencia a participantes.",
  "These details will guide participant-facing support materials.": "Estos datos orientarán los materiales de asistencia para participantes.",
  "Staff support": "Asistencia para el personal",
  "Choose the saved partner contact who supports staff and review the LegalEase technical support route.": "Elija el contacto guardado que apoya al personal y revise la ruta de asistencia técnica de LegalEase.",
  "The saved owner will appear in implementation guidance.": "La persona responsable aparecerá en las instrucciones de implementación.",
  "Legal referral": "Remisión legal",
  "Choose the actual referral arrangement. For general resources, record the reviewed resource route and method; for no referrals, complete the stop-and-notify escalation plan.": "Elija el acuerdo real de remisión. Para recursos generales, registre la ruta y el método revisados; si no hay remisiones, complete el plan de detener y notificar.",
  "The saved process will be used when a matter leaves the self-help path.": "El proceso guardado se usará cuando un asunto salga de la ruta de autoayuda.",
  "Contested-matter escalation": "Escalación de asuntos controvertidos",
  "Explain when self-help stops, who receives the escalation, and how quickly they respond.": "Explique cuándo se detiene la autoayuda, quién recibe la escalación y con qué rapidez responde.",
  "LegalEase will validate this procedure before launch readiness can pass.": "LegalEase validará este procedimiento antes de que se pueda aprobar la preparación del lanzamiento.",
  "Privacy, security, and media routes": "Rutas de privacidad, seguridad y medios",
  "Describe how privacy and security concerns are routed and record the media response expectation.": "Describa cómo se dirigen las inquietudes de privacidad y seguridad y registre el plazo previsto de respuesta a medios.",
  "The operating plan will identify each route, owner, and response expectation.": "El plan operativo identificará cada ruta, responsable y plazo previsto de respuesta.",
  "Program continuity": "Continuidad del programa",
  "Describe who may request a pause, how they ask, and the expected response.": "Describa quién puede solicitar una pausa, cómo la solicita y la respuesta prevista.",
  "This records an escalation route and does not pause or activate the program.": "Esto registra una ruta de escalación y no pausa ni activa el programa.",
  "Reporting recipients": "Destinatarios de los informes",
  "List the people intended to receive program reporting.": "Enumere las personas previstas para recibir informes del programa.",
  "Saving recipients records the plan and sends no report or invitation.": "Guardar los destinatarios registra el plan y no envía informes ni invitaciones.",
  "Reporting cadence and restrictions": "Frecuencia y restricciones de los informes",
  "Record reporting cadence, funder metrics, data-use restrictions, and external outcome data.": "Registre la frecuencia de informes, métricas de financiadores, restricciones de uso de datos y datos externos de resultados.",
  "LegalEase will use these details to prepare reporting materials.": "LegalEase usará estos datos para preparar materiales de informes.",
  "Program summary": "Resumen del programa",
  "Review the section-level decisions before providing authorization.": "Revise las decisiones de cada sección antes de dar autorización.",
  "Use the source section links for any correction.": "Use los enlaces de las secciones de origen para corregir información.",
  "Exceptions and unresolved items": "Excepciones y asuntos pendientes",
  "Review missing information, requested changes, and actions still owned by LegalEase.": "Revise la información faltante, los cambios solicitados y las acciones que aún corresponden a LegalEase.",
  "The remaining decisions on your side need to be complete before you can submit.": "Debe completar las decisiones pendientes de su equipo antes de enviar.",
  "Partner acknowledgments": "Confirmaciones de su organización",
  "Confirm each implementation statement after reviewing the package.": "Confirme cada declaración de implementación después de revisar el paquete.",
  "These acknowledgments authorize implementation preparation and are not an e-signature.": "Estas confirmaciones autorizan la preparación de implementación y no son una firma electrónica.",
  "Authorized approver": "Persona autorizada para aprobar",
  "Record the name and title of the person authorizing implementation review.": "Registre el nombre y cargo de la persona que autoriza la revisión de implementación.",
  "The authenticated identity and server time are recorded only when the full package is submitted.": "La identidad autenticada y la hora del servidor se registran solo cuando se envía el paquete completo.",
  "Submission": "Envío",
  "Review the server-recorded audit details and continue to the package decision summary.": "Revise los datos de auditoría registrados por el servidor y continúe al resumen de decisiones del paquete.",
  "Submitting starts LegalEase review. It does not approve, publish, or activate the program.": "Enviar inicia la revisión de LegalEase. No aprueba, publica ni activa el programa."
};
