// New Hampshire eligibility rules. Sourced from the New Hampshire Expungement /
// Annulment Reference for Wilma (Nationwide Record Clearing), corroborated by the
// cited RSA sections and NH Judicial Branch / 603 Legal Aid guidance. Citations
// are RSA unless noted. In New Hampshire the legal term is ANNULMENT.
export const nhEligibilityRules = [
  "New Hampshire's main criminal-record annulment statute is RSA 651:5 (Annulment of Criminal Records). The core legal test is whether annulment will help the person's rehabilitation and be consistent with the public welfare. The court may grant or deny without a hearing unless the petitioner requests a hearing. Use 'annulment,' not 'expungement.' If granted, the person is generally treated as if never arrested/convicted/sentenced, but court records are sealed and available only to the person, their attorney, courts for sentencing, law enforcement for legitimate purposes, or other limited statutory uses.",
  "Favorable outcome — not guilty, dismissed, not prosecuted (RSA 651:5): for offenses disposed of BEFORE January 1, 2019, a person may petition at any time; for offenses disposed of ON OR AFTER January 1, 2019, qualifying not-guilty/dismissed/not-prosecuted records shall be annulled 30 days after the finding if no appeal is taken, or after final appeal determination.",
  "Vacated conviction (RSA 651:5): if a conviction was later vacated, the arrest record, court record, or both may be annulled; for qualifying post-2019 vacated convictions the arrest and court record shall be annulled.",
  "Conviction annulment (RSA 651:5): the person generally must (1) complete all terms and conditions of the sentence; (2) have no new disqualifying conviction during the waiting period; (3) satisfy the waiting period for the offense level; (4) have no pending charge that would block or extend eligibility; and (5) avoid statutory bars (violent crimes, felony obstruction-of-justice crimes, and extended-term sentences). The waiting period is counted from the date all terms and conditions of the sentence were completed.",
  "Conviction waiting periods (RSA 651:5): violation — 1 year; Class B misdemeanor — 2 years; Class A misdemeanor — 3 years; Class B felony — 5 years; Class A felony — 10 years; sexual assault under RSA 632-A:4 — 10 years; felony indecent exposure or lewdness under RSA 645:1, II — 10 years; misdemeanor domestic violence under RSA 631:2-b — 10 years; Class A misdemeanor or felony offense under RSA 318-B:26, II — 2 years; DWI/DUI-type offense — special 10-year rule (verify under RSA 265-A:21).",
  "Multiple convictions rule (RSA 651:5): if a person has more than one offense, no petition may be brought and no annulment granted (1) if any part of the record is barred, or (2) until the time requirements for ALL offenses of record have been met. This is a frequent eligibility error — do not mark eligible until every offense of record satisfies its waiting period.",
  "Barred offenses (RSA 651:5): annulment is barred for a violent crime (defined in RSA 651:5, XIII — incl. murder, manslaughter, class A felony negligent homicide, first-degree assault, aggravated/felonious sexual assault, kidnapping, criminal restraint, class A felony arson, robbery, certain incest/child-solicitation offenses, and felonious child sexual-abuse-image offenses), felony obstruction-of-justice crimes (RSA 651:5, XIV), or an extended-term sentence under RSA 651:6 — route to attorney review.",
  "Marijuana possession annulment (RSA 651:5-b): a person arrested or convicted before September 16, 2017 for knowingly/purposely possessing, obtaining, purchasing, or transporting 3/4 of an ounce of marijuana or less may petition the court where the arrest/conviction occurred at any time; the prosecutor has 10 days to object and, if objecting, must prove beyond a reasonable doubt that the amount exceeded 3/4 ounce. Note: 2025 HB 196 (cannabis-annulment expansion) did NOT become law — do not apply it as current law.",
  "DWI/DUI annulment (RSA 265-A:21): DWI is carved out of the ordinary waiting-period structure — convictions for driving/operating a vehicle, OHRV, or boat while under the influence generally require a 10-year waiting period after conviction before requesting annulment. Treat DWI as an escalation flag and verify the exact statute.",
  "Pending charges (RSA 651:5): if the person is charged with a new offense before the court decides the petition, and that charge would bar annulment or extend the waiting period, the court will not act on the petition until the new charge is resolved.",
  "Investigation and prosecutor role (RSA 651:5): on a timely petition, the court requires the Department of Corrections to report on the petitioner's convictions/arrests/prosecutions; the prosecutor is given the petition and an opportunity to be heard. For certain violation and Class B misdemeanor petitions, the prosecutor has 20 days to object on eligibility/sentence-completion grounds; if no timely objection (or the objection is denied), the court shall annul.",
  "Federal/military/out-of-state (RSA 651:5): New Hampshire courts can only annul New Hampshire records; federal and military convictions cannot be removed, and out-of-state records require relief in the state where they occurred. The federal government (including immigration authorities) does not recognize New Hampshire annulments, and third-party background-check providers may not update their records."
];
