// Rhode Island disqualifying / blocking offenses and exclusions. Sourced from the
// "Rhode Island Expungement / Sealing Reference for Wilma" (Nationwide Record
// Clearing), sections 2-3 and 11, reflecting the crime-of-violence bar
// (§ 12-1.3-1 / § 12-1.3-2), the multiple-misdemeanor exclusions (§ 12-1.3-3),
// and the mandatory attorney-escalation flags. Screening notes, not an
// exhaustive legal test; verify the exact current R.I. Gen. Laws text.
export const riDisqualifyingOffenseNotes = [
  "Crime-of-violence bar (§ 12-1.3-1 / § 12-1.3-2): a person convicted of a crime of violence is BARRED from conviction expungement (and deferred-sentence expungement). The statutory list includes murder, manslaughter, first-degree arson, kidnapping with intent to extort, robbery, larceny from the person, first- and second-degree sexual assault, first- and second-degree child molestation, assault with intent to murder, assault with intent to rob, assault with intent to commit first-degree sexual assault, burglary, and entering a dwelling with intent to commit murder, robbery, sexual assault, or larceny — escalate, never make final calls on violent or sex-related offenses.",
  "Multiple-misdemeanor exclusions (§ 12-1.3-3): the multiple-misdemeanor path EXCLUDES domestic-violence offenses under Title 12 ch. 29 (Domestic Violence Prevention Act), DUI (§ 31-27-2), and chemical-test refusal (§ 31-27-2.1). Do not say all DUI or all domestic-violence cases are impossible under every route — this is the multiple-misdemeanor exclusion; for any DUI, refusal, or DV case, require exact statutory review.",
  "First-offender blocks (§ 12-1.3-2): a prior felony or misdemeanor conviction or probation (defeats first-offender status), a pending criminal proceeding, a felony/misdemeanor arrest or conviction during the lookback period (5 years misdemeanor / 10 years felony), or unsatisfied court financial obligations (unless waived or reduced) block first-offender conviction expungement.",
  "Multiple-misdemeanor blocks (§ 12-1.3-3): any felony conviction, six or more misdemeanors, a felony/misdemeanor arrest or conviction in the 10 years before filing, pending criminal proceedings, or lack of good moral character block the multiple-misdemeanor path.",
  "Deferred-sentence blocks (§ 12-19-19): failure to complete all deferral terms (including fines, fees, costs, assessments, and restitution), a pending criminal proceeding, lack of good moral character, or a crime-of-violence conviction block deferred-sentence expungement.",
  "Scope exclusions: federal, out-of-state, military, and tribal matters are not clearable through Rhode Island state expungement or sealing; commercial-sexual-activity (§ 11-34.1-5) and marijuana possession-only (§ 12-1.3-5) follow their own special rules rather than the general first-offender path.",
  "Scope limits: Rhode Island expungement/sealing does not remove federal/FBI records, clear out-of-state or tribal convictions, automatically update private-background-check copies, restore gun rights, or fix immigration consequences; disclosure exceptions remain for law-enforcement employment, bar admission, teaching/coaching/early-childhood-education certificates, later sentencing, and certain court or law-enforcement uses."
];
