// Rhode Island eligibility rules. Sourced from the "Rhode Island Expungement /
// Sealing Reference for Wilma" (Nationwide Record Clearing), corroborated by the
// cited R.I. Gen. Laws sections and Rhode Island Judiciary guidance. Citations
// are R.I. Gen. Laws unless noted. Rhode Island record-clearing is not one
// pathway: it separates conviction expungement (ch. 12-1.3) from non-conviction
// sealing/destruction (§§ 12-1-12 / 12-1-12.1), with special routes for deferred
// sentences, filed complaints, marijuana possession, decriminalized offenses,
// and commercial-sexual-activity relief.
export const riEligibilityRules = [
  "Rhode Island uses BOTH 'expungement' and 'sealing'; do not treat them as identical. For convictions and probation, Rhode Island usually uses expungement under R.I. Gen. Laws ch. 12-1.3. For acquittals, dismissals, no true bills, no information, and other exonerated cases, Rhode Island usually uses sealing or destruction/sealing under § 12-1-12 and § 12-1-12.1. Expungement is defined as the sealing and retention of conviction or probation records and removal from active public files; the statutory definition of 'records' covers court, state/local police, Bureau of Criminal Identification (BCI), and probation records, fingerprints, photographs, physical measurements, and other identification records, but excludes certain Attorney General files not kept by BCI in the ordinary course of business.",
  "First-offender conviction expungement (ch. 12-1.3; § 12-1.3-2): a first offender may move to expunge a misdemeanor or felony conviction in the court where the conviction occurred if (1) they have not been convicted of a crime of violence, (2) they have no pending criminal proceeding, and (3) they have paid, or obtained a waiver or reduction of, all court-imposed or court-related financial obligations. A 'first offender' is a person convicted of a felony or misdemeanor who has not previously been convicted of, or placed on probation for, a felony or misdemeanor and who has no pending criminal proceeding.",
  "First-offender waiting periods: a single first-offender MISDEMEANOR conviction may be expunged 5 years from completion of sentence; a single first-offender FELONY conviction may be expunged 10 years from completion of sentence. Calculate the waiting period from completion of sentence, not from the arrest or conviction date. The court also weighs no felony/misdemeanor arrests or convictions during the lookback period, no pending proceedings, satisfied/waived financial obligations, good moral character, rehabilitation to the court's satisfaction, and consistency with the public interest.",
  "Multiple-misdemeanor expungement (§ 12-1.3-3): a person with MORE THAN ONE but FEWER THAN SIX misdemeanor convictions and NO felony conviction may move to expunge any or all of those misdemeanors 10 years after completion of the last sentence. The person must also have no felony or misdemeanor arrest or conviction in the 10 years before filing, no pending criminal proceedings, and good moral character. Excluded from this path: domestic-violence offenses under Title 12 ch. 29 (Domestic Violence Prevention Act), DUI (§ 31-27-2), and chemical-test refusal (§ 31-27-2.1). Do not say all DUI or all domestic-violence cases are impossible under every route — this is the multiple-misdemeanor exclusion; escalate DUI, refusal, or DV cases for exact statutory review.",
  "Deferred-sentence expungement (§ 12-19-19; § 12-1.3-2(e)): a person who received a deferred sentence under a written deferral agreement may move for expungement after completion of the deferred sentence. If, after a hearing, the court finds compliance with all terms of the deferral agreement — including payment of fines, fees, costs, assessments, and restitution — the person is immediately eligible for consideration for expungement. A deferred sentence is NOT automatic expungement; the person still needs the court process, hearing, no pending criminal proceedings, and good moral character. No person convicted of a crime of violence may have deferred-sentence records expunged.",
  "Non-conviction sealing / destruction (§ 12-1-12 and § 12-1-12.1): for acquittals, dismissals, no true bills, no information, and other exonerated outcomes, identification records (fingerprints, photographs, physical measurements, other arrest ID records) must generally be destroyed within 60 days, and court records are sealed consistent with § 12-1-12.1. For District Court Rule 48(a) dismissals: dismissals ON OR AFTER January 1, 2023 are automatically sealed by the court not less than 10 and not more than 20 days after dismissal; dismissals BEFORE January 1, 2023 are administratively sealed by the clerk at the defendant's request, with the order sent electronically to BCI and carried out within 90 days of receipt. Other acquittals/dismissals/no true bills/no information/exonerations may require a motion to seal, with notice to the Attorney General and the police department at least 10 days before hearing.",
  "Filed-complaint expungement (§ 12-10-12): if a complaint is placed on file and no action is taken during the filing period, the complaint is automatically expunged and no criminal record results. For domestic-violence filed complaints, if the defendant is not charged with another domestic-violence crime during the three-year period after filing, or if such a charge is dismissed or results in acquittal, all records relating to the filed domestic-violence complaint are expunged without a separate ch. 12-1.3 motion. Ask whether the complaint was a domestic-violence filing or a regular filing.",
  "Marijuana possession-only automatic expungement (§ 12-1.3-5): a person with a prior civil violation, misdemeanor conviction, or felony conviction for possession ONLY of a marijuana offense that has since been decriminalized is entitled to automatic expungement, notwithstanding the general ch. 12-1.3 rules. Eligible records were required to be expunged before July 1, 2024, and the Chief Justice may provide an expedited procedure. If the amount is not stated in the record, the court presumes 2 oz. or less. Pending cases, prior convictions, violent convictions, and outstanding fines/fees do NOT block marijuana expungement under this section; eligible marijuana-related amounts are waived, and other counts in the same case do not prevent expungement of the eligible marijuana count. A § 12-1.3-5 expungement is not treated as a prior conviction or civil adjudication for later sentencing. Confirm the case was possession only, not intent to deliver, distribution, weapons, violence, or non-marijuana counts.",
  "Decriminalized-offense expungement (ch. 12-1.3; § 12-1.3-2(g) / § 12-1.3-3(e)): separate from marijuana, a person may move to expunge an offense decriminalized after the date of conviction. The court holds a hearing and may require the petitioner to show the prior conviction would qualify as a decriminalized offense under current Rhode Island law; if sentence conditions are complete and required fines/fees/costs are paid, the court orders expungement without cost to the petitioner.",
  "Commercial-sexual-activity relief (§ 11-34.1-5): records of a person convicted, placed on probation, or whose case was filed under § 12-10-12 for violations of § 11-34.1-2 or § 11-34.1-4 may be expunged one year after completion of sentence, and the court may grant the motion regardless of first-offender status. Treat these cases carefully because they may involve trafficking, exploitation, coercion, or victimization.",
  "Crime-of-violence bar (§ 12-1.3-1; § 12-1.3-2): a person convicted of a crime of violence is barred from conviction expungement. The statutory definition includes murder, manslaughter, first-degree arson, kidnapping with intent to extort, robbery, larceny from the person, first- and second-degree sexual assault, first- and second-degree child molestation, assault with intent to murder, assault with intent to rob, assault with intent to commit first-degree sexual assault, burglary, and entering a dwelling with intent to commit murder, robbery, sexual assault, or larceny. Do not make final eligibility calls on violent or sex-related offenses — use attorney escalation.",
  "Scope limits: Rhode Island expungement usually means the record is sealed and removed from active public files — it does NOT mean every government, licensing, law-enforcement, federal, tribal, or private-background-check copy disappears, and does not clear out-of-state, federal, military, or tribal matters. After expungement the person may usually state they were not convicted of the expunged crime, but disclosure exceptions apply for law-enforcement employment, bar admission, teaching/coaching/early-childhood-education certificates, character-and-fitness/disciplinary matters, certain later sentencing or law-enforcement uses, and court orders."
];
