// Rhode Island filing workflow. Sourced from the "Rhode Island Expungement /
// Sealing Reference for Wilma" (Nationwide Record Clearing), sections 5-8,
// corroborated by R.I. Gen. Laws ch. 12-1.3, §§ 12-1-12 / 12-1-12.1, § 12-19-19,
// § 12-10-12, § 12-1.3-5, § 11-34.1-5, and Rhode Island Judiciary form
// instructions. Rhode Island uses official court Motion to Expunge or Seal
// Record / Affidavit forms; this pack is shadow-only research and wires no
// renderer.
export const riFilingInstructions = [
  "Classify the case first: single misdemeanor conviction; single felony conviction; multiple misdemeanor convictions; deferred sentence; acquittal / dismissal / no true bill / no information / otherwise exonerated; filed complaint under § 12-10-12; domestic-violence filing; marijuana possession-only record; decriminalized offense; commercial-sexual-activity offense; or federal, out-of-state, military, or tribal matter (not clearable through Rhode Island state expungement/sealing).",
  "On the official Motion to Expunge or Seal Record / Affidavit, the filer must select whether they are asking to SEAL or to EXPUNGE — convictions and probation usually use expungement (ch. 12-1.3); acquittals, dismissals, no true bills, no information, and other exonerated cases usually use sealing/destruction (§§ 12-1-12 / 12-1-12.1).",
  "Gather the official record: full legal name, date of birth, BCI number (if known), court name, case number, the police department that brought the charge, count number(s), charge name(s) and statute(s), disposition, conviction date (if any), sentence completion date, and probation completion date. Obtain the BCI criminal-history report to confirm first-offender status, the lookback period, and pending cases.",
  "Choose the correct court form by court of conviction: District Court — Motion to Expunge or Seal Record and Affidavit (DC-33) for District Court misdemeanor / sealing matters; Superior Court — Motion to Expunge or Seal Record — Felony (Superior-55) for Superior Court felony matters; Superior Court — Motion to Expunge or Seal Record — Misdemeanor for Superior Court misdemeanor matters; Family Court — Motion to Expunge or Seal Record and Affidavit — Misdemeanor for Family Court misdemeanor matters. Forms are revised February 2025; the affidavit must be signed before a notary or clerk.",
  "File in the court where the case occurred: a conviction expungement motion is filed in the court where the conviction took place, and the clerk's office fills in the hearing date. The hearing date must be at least 10 days after filing because notice must be provided to the Attorney General and the charging police department.",
  "Give notice: for conviction expungement (and a motion to seal a non-conviction), give notice of the hearing date to the Rhode Island Department of Attorney General and the police department that originally brought the charge at least 10 days before the hearing.",
  "Attend the hearing and bring the proposed order: the court considers the statutory criteria — rehabilitation, public interest, financial obligations, pending cases, arrest/conviction lookback period, good moral character, and the crime-of-violence bar. For deferred sentences, the court must find compliance with all deferral terms. For decriminalized-offense and § 12-1.3-5 marijuana matters, expungement is ordered without cost to the petitioner.",
  "Deliver certified orders if granted: the clerk prepares three certified copies of the order after all conditions are satisfied — one for the petitioner, one for the Attorney General's BCI unit, and one for the police department that charged the case. The PETITIONER is responsible for delivering the copies to BCI and the charging police department. For non-conviction relief, ID records (fingerprints, photographs, physical measurements) are destroyed, and BCI and court records are sealed.",
  "Non-conviction sealing (§ 12-1-12 / § 12-1-12.1): for a District Court Rule 48(a) dismissal on or after January 1, 2023, the court seals automatically 10-20 days after dismissal (no motion needed); for a dismissal before January 1, 2023, the clerk seals administratively at the defendant's request; for other acquittals/dismissals/no true bills/no information/exonerations, file a motion to seal with the 10-day notice to the AG and police.",
  "Marijuana possession-only (§ 12-1.3-5): possession-only marijuana civil violations, misdemeanors, or felonies that were decriminalized are entitled to automatic expungement with an expedited procedure available; confirm the case was possession only (not intent to deliver, distribution, weapons, violence, or non-marijuana counts) and escalate mixed-count cases.",
  "Filed complaints (§ 12-10-12): if no action was taken during the filing period, the complaint is automatically expunged; for a domestic-violence filing, apply the special three-year rule before filing any separate motion."
];
