// Rhode Island safety / plain-language. Sourced from the "Rhode Island
// Expungement / Sealing Reference for Wilma" (Nationwide Record Clearing):
// sections 1, 7-8, 11-12 (the "Do Not Say" rules and mandatory escalation
// flags), corroborated by R.I. Gen. Laws ch. 12-1.3 and §§ 12-1-12 / 12-1-12.1
// and Rhode Island Judiciary guidance.
export const riSafetyDisclaimer =
  "This Rhode Island RCAP draft is legal information, not legal advice, and does not guarantee eligibility or any court outcome. In Rhode Island, expungement usually means the record is sealed and removed from active public files (ch. 12-1.3) — it does not always mean every government, licensing, law-enforcement, federal, tribal, or private-background-check copy disappears. Rhode Island uses separate processes: conviction expungement (ch. 12-1.3), non-conviction sealing/destruction (§§ 12-1-12 / 12-1-12.1), deferred-sentence expungement (§ 12-19-19), filed-complaint expungement (§ 12-10-12), marijuana possession-only automatic expungement (§ 12-1.3-5), decriminalized-offense expungement, and commercial-sexual-activity relief (§ 11-34.1-5). Eligibility depends on the exact charge, offense level, first-offender status, disposition, sentence-completion date, financial obligations, the crime-of-violence bar, and arrest/conviction history; verify the official Rhode Island court, BCI, police, and agency records before filing.";

export const riPlainLanguage = {
  expungementVsSealing:
    "Do not treat expungement and sealing as identical. For convictions and probation, Rhode Island usually uses expungement (ch. 12-1.3). For acquittals, dismissals, no true bills, no information, and other exonerated cases, Rhode Island usually uses sealing or destruction/sealing (§§ 12-1-12 / 12-1-12.1). On the official form the filer must select whether they are asking to seal or to expunge.",
  doNotSay:
    "Rhode Island 'Do Not Say' rules: do not say 'your record will be erased from everywhere'; 'nobody can ever see it again'; 'Rhode Island expungement deletes FBI records'; 'this fixes immigration'; 'this restores gun rights'; 'all dismissed cases need a motion'; 'all marijuana cases are automatically expunged'; 'all domestic-violence cases are impossible'; 'all DUI cases are impossible'; 'multiple misdemeanors are always disqualifying'; 'deferred sentence means automatic expungement'; or 'private background-check companies will update automatically.'",
  mayInsteadSay:
    "Wilma may say: based on what you shared, you may have a Rhode Island expungement or sealing pathway; the next step is to verify the official court record, final disposition, offense type, sentence-completion date, financial obligations, arrest/conviction history, and whether any special category (marijuana, decriminalized offense, filed complaint, deferred sentence, commercial sexual activity) applies.",
  scopeLimits:
    "Do not promise Rhode Island relief will remove federal/FBI records, clear out-of-state or tribal convictions, remove private-background-check copies automatically, restore firearm rights, or fix immigration consequences. After expungement the person may usually say they were not convicted, but disclosure exceptions remain for law-enforcement employment, bar admission, teaching/coaching/early-childhood-education certificates, later sentencing, and certain court or law-enforcement uses.",
  escalation:
    "Recommend attorney / legal-clinic review for: any felony conviction; any possible crime of violence (burglary, robbery, sexual assault, child molestation, kidnapping, manslaughter, arson, assault with intent, larceny from the person); domestic violence; DUI or chemical-test refusal; a deferred sentence with unclear completion status; multiple misdemeanors close to the six-misdemeanor limit; any felony plus misdemeanor history; a pending criminal case; an arrest or conviction inside the required lookback period; unpaid restitution or unclear financial obligations; immigration consequences; law-enforcement, teaching, coaching, childcare, bar-admission, or professional-licensing issues; a federal or out-of-state record; a case mixing marijuana possession with non-marijuana counts; or a request for a guaranteed outcome."
};
