// New Mexico eligibility rules. Sourced from the New Mexico Expungement Reference
// for Wilma (Nationwide Record Clearing), corroborated by the cited NMSA 1978
// sections (Criminal Record Expungement Act §§ 29-3A-1 to 29-3A-9 and § 29-16-10)
// and NM Courts / NM DPS guidance. Citations are NMSA 1978 unless noted.
export const nmEligibilityRules = [
  "New Mexico's primary law is the Criminal Record Expungement Act, NMSA 1978 §§ 29-3A-1 to 29-3A-9, effective January 1, 2020. New Mexico uses the word 'expungement,' but for most non-cannabis records it means REMOVAL FROM PUBLIC ACCESS — removing notations of arrest, complaint, indictment, information, guilty plea, conviction, acquittal, dismissal, or discharge from public access (including public court/corrections/law-enforcement websites) — not physical destruction of every record (§ 29-3A-2).",
  "Filing location: the petition is filed in the DISTRICT COURT in the district where the arrest and/or criminal records originated, even if the original case was in municipal, magistrate, or metropolitan court, or was dismissed before the DA or city attorney filed a case. A New Mexico district court cannot expunge records from another state or federal records. Multiple charges/arrests under the same case number may be in one petition, but arrest records not associated with a filed case need a separate petition for each arrest; petition information is sealed from public access even if the petition is denied.",
  "Identity theft (§ 29-3A-3): a person wrongly identified in arrest or public records because of identity theft may petition the district court; after a hearing and a showing that the person is a victim of identity theft, the court must issue an order within 30 days requiring all arrest and public records to be expunged and delivered to relevant agencies and courts.",
  "Release without conviction (§ 29-3A-4): a person released without conviction may file ONE YEAR after the final disposition in the district where the charges originated. 'Released without conviction' includes acquittal or finding of not guilty, nolle prosequi, no bill or other dismissal, referral to a preprosecution diversion program, conditional discharge under § 31-20-13, or proceedings otherwise discharged. If the court finds no other charge or proceeding is pending and the person was released without conviction, it must issue an order within 30 days of the hearing. Required notice goes to the district attorney and DPS, and the petition must attach a DPS record of arrest and prosecutions dated no earlier than 90 days before filing.",
  "Conviction expungement (§ 29-3A-5): a person convicted of a municipal-ordinance violation, misdemeanor, or felony may petition after completing the sentence and paying fines or fees owed to the state for that conviction. The petition is filed in the district court where the person was convicted, with notice to the district attorney, DPS, and the arresting law-enforcement agency. The court must find that no other charge or proceeding is pending, justice will be served, victim restitution has been fulfilled, and no other criminal conviction occurred during the applicable waiting period. The waiting period is measured from the last date the person completed a sentence for a conviction in any jurisdiction.",
  "Conviction waiting periods (§ 29-3A-5(C)(4)): municipal-ordinance conviction — 2 years; misdemeanor not otherwise listed — 2 years; misdemeanor aggravated battery under § 30-3-5(B) — 4 years; fourth-degree felony not otherwise listed — 4 years; third-degree felony not otherwise listed — 6 years; second-degree felony not otherwise listed — 8 years; first-degree felony — 10 years; Crimes Against Household Members Act offense — 10 years.",
  "Conviction exclusions (§ 29-3A-5): conviction expungement does NOT apply to an offense committed against a child, an offense that caused great bodily harm or death, a sex offense as defined in § 29-11A-3, embezzlement under § 30-16-8, or an offense involving driving while under the influence of intoxicating liquor or drugs (DWI/DUI).",
  "DWI records nuance (§ 29-3A-2): the definition of 'arrest records' excludes DWI citations maintained by the Taxation and Revenue Department, computer-aided dispatch information, and breath-alcohol-testing equipment log books — so even where a non-conviction case has an expungement path, some DWI-related records may remain outside the standard expungement definition.",
  "Court discretion — 'justice will be served' (§ 29-3A-5): even when the waiting period is complete, conviction expungement is discretionary; the court weighs the nature and gravity of the offense, the petitioner's age, criminal history, employment history, time since the offense and sentence completion, adverse consequences of denial, and any reasons the district attorney submits to deny. Screen as 'may be eligible' / 'meets the basic timing screen,' never 'will be granted.'",
  "Cannabis automatic / administrative expungement (§ 29-3A-8): if a person was charged with a cannabis offense that is no longer a crime as of June 29, 2021, or would now be a lesser offense under the Cannabis Regulation Act, public records relating to the arrest or conviction are automatically expunged two years after the conviction date (or two years after the arrest date if there was no conviction); for minors the record is retained for two years or until age 18, whichever is first, then automatically expunged. This route applies to cannabis-and-paraphernalia-only records and requires destruction of those records; the Administrative Office of the Courts (AOC) provides a procedure to verify whether automatic expungement occurred and to request expedited expungement, and for mixed cannabis/non-cannabis cases the eligible cannabis charges may be requested through the AOC process.",
  "Cannabis sentence dismissal / vacatur (§ 29-3A-9): for people currently incarcerated for a cannabis offense that is no longer a crime or would be a lesser offense, facilities were required to notify the court that the case may be reopened, and the court must reopen and dismiss a legally invalid sentence; a person who completed such a sentence is entitled to dismissal and expungement because the conviction is legally invalid or redesignated as a penalty-assessment citation. A currently or formerly incarcerated person may petition at any time to modify the sentence or vacate the conviction, and no fee or cost may be imposed for sentence review under this section — route to legal aid / an attorney.",
  "DNA sample/profile expungement (§ 29-16-10): separate from court-record expungement, a person may request removal of their DNA sample and records from New Mexico's DNA identification system (and CODIS) if the conviction that led to the sample was reversed, or the arrest that led to the sample resulted in dismissal, nolle prosequi, successful pre-prosecution diversion, conditional discharge, misdemeanor conviction, acquittal, or did not result in a felony charge within one year. It requires a written request and certified documentation (or a sworn affidavit that no felony charges were filed within one year) and is not available if the person has a prior felony conviction or pending felony charge for which DNA collection is authorized.",
  "Effect (§ 29-3A-7): after an expungement order, proceedings are treated as if they never occurred and the person and officials may respond that no record exists — BUT arrest or conviction records must still be disclosed for applications or queries involving employment or association with a financial institution regulated by FINRA or the SEC. Courts, law enforcement, and other criminal-justice agencies will always retain access, records are not destroyed (except where the cannabis or DNA statutes require it), and the records may still be used in future criminal proceedings."
];
