// New Mexico filing workflow. Sourced from the New Mexico Expungement Reference
// for Wilma (Nationwide Record Clearing), sections 3-4 and 13, corroborated by
// NMSA 1978 §§ 29-3A-3 to 29-3A-9 and NM Courts guidance. New Mexico uses official
// statewide Rules of Court 4-95x petition forms; this pack is shadow-only research
// and wires no renderer.
export const nmFilingInstructions = [
  "Determine the pathway first: identity theft (§ 29-3A-3, Form 4-951), release without conviction (§ 29-3A-4, Form 4-952), conviction expungement (§ 29-3A-5, Form 4-953), cannabis automatic/administrative (§ 29-3A-8, AOC cannabis application), cannabis sentence dismissal/vacatur (§ 29-3A-9), or DNA expungement (§ 29-16-10, separate written request).",
  "File in district court in the district where the arrest and/or criminal records originated — even if the original case was in municipal, magistrate, or metropolitan court, or was dismissed before a case was filed. A New Mexico district court cannot reach another state's or federal records.",
  "Scope the petition: multiple charges/arrests under the same case number may be combined in one petition, but each arrest record not associated with a filed case needs its own petition. Petition information is sealed from public access even if the petition is denied.",
  "Get the record: obtain a DPS record of arrest and prosecutions (for § 29-3A-4 it must be dated no earlier than 90 days before filing), plus the court docket / Case Lookup printout, judgment and sentence, proof of sentence completion, proof that fines/fees and victim restitution are paid, and cannabis or identity-theft documentation as applicable.",
  "Identity theft (§ 29-3A-3): file Form 4-951 with supporting identity-theft documentation and records showing the wrongly identified arrest/case, a proposed order, and notice/hearing paperwork; after a hearing the court must order expungement within 30 days.",
  "Release without conviction (§ 29-3A-4): file Form 4-952 with the DPS record (within 90 days), final disposition, certificate/service to the district attorney and DPS, a proposed order, notice-of-hearing documents, and an indigency request if needed; file at least one year after the final disposition.",
  "Conviction (§ 29-3A-5): file Form 4-953 with the DPS/criminal-history record, judgment and sentence, proof of sentence completion, proof fines/fees are paid, proof restitution is completed, service to the district attorney, DPS, and the arresting agency, a statement explaining why justice will be served, a proposed order, and an indigency request if needed.",
  "Cannabis (§§ 29-3A-8, 29-3A-9): for cannabis-only or paraphernalia-only records, use the New Mexico Courts cannabis expungement application / AOC process first; for mixed cannabis/non-cannabis cases, route the eligible cannabis charges through the AOC cannabis request and separately screen the non-cannabis charges under the regular court-petition process. Sentence dismissal/vacatur for incarcerated or formerly incarcerated people (§ 29-3A-9) should be routed to legal aid / an attorney.",
  "DNA (§ 29-16-10): submit a written request for DNA sample/profile expungement with a certified copy of the qualifying disposition (dismissal, nolle prosequi, diversion completion, conditional discharge, misdemeanor conviction, acquittal, or reversal order) or a sworn affidavit that no felony charge was filed within one year; screen for a prior felony conviction or pending felony charge, which can block DNA expungement.",
  "Fees: the general district-court filing fee referenced by the court information sheet is $132; a person who cannot pay may file an Application for Free Process and Affidavit of Indigency (Form 4-222 NMRA); a DPS arrest-record check costs $15 and requires a notarized Authorization for Release of Information. Confirm current amounts before filing."
];
