import type { RcapIntakeSession } from "@/lib/rcap-intake/types";
import type { RcapDocumentPacketStatus } from "@/lib/rcap/documents/mississippi/types";
import type { PennsylvaniaDocumentType } from "@/lib/rcap/state-packs/pennsylvania/document-types";
import type { PennsylvaniaDocumentFieldKey } from "@/lib/rcap/state-packs/pennsylvania/required-fields";
import type { PennsylvaniaEligibilitySignal, PennsylvaniaPathway, PennsylvaniaRemedyType } from "@/lib/rcap/state-packs/pennsylvania/pathways";

export type PennsylvaniaOffenseGrade = "summary" | "M3" | "M2" | "M1" | "F3_property" | "drug_felony" | "felony_other" | "unknown";

export type PennsylvaniaDocumentPacketInput = {
  partnerSlug: string;
  intakeSessionId?: string;
  userId?: string;
  briefcaseId?: string;
  state?: string;
  county?: string;
  judicialDistrict?: string;
  docketNumber?: string;
  otn?: string;
  judgeName?: string;
  judgeAddress?: string;
  petitionerFirstName?: string;
  petitionerLastName?: string;
  otherNamesUsed?: string;
  petitionerAddress?: string;
  charge?: string;
  statuteTitle?: string;
  statuteSection?: string;
  statuteSubsection?: string;
  offenseGrade?: PennsylvaniaOffenseGrade;
  disposition?: string;
  dispositionDate?: string;
  arrestDate?: string;
  complaintDate?: string;
  arrestingAgency?: string;
  affiantName?: string;
  affiantAddress?: string;
  hasPatchReport?: boolean;
  patchWithin60Days?: boolean;
  patchMissingReason?: string;
  restitutionPaid?: boolean;
  victimRestitutionOwed?: boolean;
  nonRestitutionCostsOnly?: boolean;
  waitingPeriodSatisfied?: boolean;
  noPendingProceedings?: boolean;
  noArrestOrProsecutionFiveYears?: boolean;
  convictionFreeSevenYears?: boolean;
  convictionFreeTenYears?: boolean;
  sentenceUnderThirtyMonths?: boolean;
  ardCompleted?: boolean;
  fullPardon?: boolean;
  ageSeventyOrOlder?: boolean;
  deceasedThreeYears?: boolean;
  excludedOffenseSignal?: boolean;
  sexOffenderRegistrationSignal?: boolean;
  firearmWeaponSignal?: boolean;
  familyOrDangerToPersonSignal?: boolean;
  federalOrOutOfStateSignal?: boolean;
  cleanSlateAutomaticSignal?: boolean;
  commonwealthServiceReady?: boolean;
  feeWaiverRequested?: boolean;
  remedyType?: PennsylvaniaRemedyType;
  caseOutcome?: RcapIntakeSession["caseOutcome"];
  recordType?: RcapIntakeSession["recordType"];
};

export type PennsylvaniaMappedDocumentFields = PennsylvaniaDocumentPacketInput & {
  pathway: PennsylvaniaPathway;
  remedyType: PennsylvaniaRemedyType;
  documentTypes: PennsylvaniaDocumentType[];
  eligibilitySignal: PennsylvaniaEligibilitySignal;
  missingFields: PennsylvaniaDocumentFieldKey[];
  needsRecordReview: boolean;
};

export type PennsylvaniaDocumentGenerationResult = {
  state: "PA";
  remedyType: PennsylvaniaRemedyType;
  pathway: PennsylvaniaPathway;
  documentTypes: PennsylvaniaDocumentType[];
  eligibilitySignal: PennsylvaniaEligibilitySignal;
  status: RcapDocumentPacketStatus;
  missingFields: PennsylvaniaDocumentFieldKey[];
  draftTitle: string;
  draftHtml: string;
  draftPlainText: string;
  filingInstructions: string[];
  countyCourtInstructions: string[];
  safetyDisclaimer: string;
  nextStep: string;
  briefcaseItemTitle: string;
  fields: PennsylvaniaMappedDocumentFields;
};
