export const wyEligibilityRules = [
  "Wyoming uses the word expungement, but for adult records it generally means sealing / removal from public dissemination, not total destruction: expunged adult records are sealed from public access and can be seen by law enforcement. Juvenile expungement is stronger and uses destruction/deletion language. Wyoming does not automatically expunge most records; a petition must be filed with the proper court.",
  "Adult non-conviction expungement under Wyo. Stat. § 7-13-1401: available for arrest-only or dismissed/acquitted cases where at least 180 days have passed since arrest or dismissal, no formal charges are pending, all charges from the incident ended without conviction (or none were filed, or all were dismissed), and there was no disqualifying deferred disposition under W.S. 7-13-301, 35-7-1037, or former 7-13-203. There is no filing fee and the prosecutor has 20 days to object.",
  "Adult misdemeanor conviction expungement under Wyo. Stat. § 7-13-1501: a person who pled guilty or no contest to, or was convicted of, a Wyoming misdemeanor may petition the convicting court after 1 year for a status offense or 5 years for a non-status offense (measured from expiration of all sentence terms, including probation and court-ordered programs), if the offense did not involve use or attempted use of a firearm, the health-care-provider bar (W.S. 6-2-313) does not apply, the court finds no substantial danger, and no prior § 7-13-1501 expungement exists. The filing fee is $100 and the prosecutor or victim has 30 days to object.",
  "Adult felony conviction expungement under Wyo. Stat. § 7-13-1502: a person convicted of an eligible felony may petition the convicting court after 10 years from expiration of all sentence terms with restitution paid in full, if there is no other felony plea/no-contest/conviction outside the same episode, the offense did not involve use or attempted use of a firearm (except certain Title 23 offenses) and is not on the excluded-felony list, the court finds no substantial danger, and no prior § 7-13-1502 expungement exists. Expungement restores rights removed because of the conviction. The filing fee is $300 and the prosecutor or victim has 90 days to object.",
  "Juvenile / minor expungement under Wyo. Stat. § 14-6-241 is separate from adult expungement and uses stronger destruction/deletion language: available after the person reaches the age of majority for non-violent-felony juvenile adjudications, minor municipal convictions, minor misdemeanor circuit-court convictions, diversion/deferral, and non-conviction minor records, with no later felony conviction, no pending felony case, and rehabilitation shown. There is no filing fee and the prosecutor has 20 days to object.",
  "Human-trafficking victim vacatur under Wyo. Stat. § 6-2-708: at any time after conviction the court that entered the conviction may vacate it if the person's participation in the offense resulted from being a human-trafficking victim; official documentation creates a presumption but is not required.",
  "Deferred-disposition trap: a dismissal after a deferred prosecution is not automatically an expungement case. Section 7-13-1401 excludes certain deferred dispositions from the non-conviction route, and in Lynch v. State the Wyoming Supreme Court held that a completed felony deferred prosecution dismissed without conviction is not a felony conviction to expunge under § 7-13-1502."
];
