"use client";
import Link from "next/link";
import { useState } from "react";
import { useLocalization } from "@/components/expungement-ai/LocalizationProvider";
import type { PartnerDashboardRlsData } from "@/lib/partners/partner-dashboard-rls-repository";
import type { ProgramExperience } from "@/lib/partners/onboarding/program-experience";
export function ProgramDashboard({dashboard,program,clinicCount,participants=false,reporting=false}:{dashboard:Extract<PartnerDashboardRlsData,{kind:"partner"}>;program:ProgramExperience|null;clinicCount:number|null;participants?:boolean;reporting?:boolean}){
 const {locale}=useLocalization();const es=locale==="es";const t=(en:string,spanish:string)=>es?spanish:en;const [notice,setNotice]=useState("");
 const live=program?.decision.live===true;const setup=program?.decision.setupComplete===true;
 const name=program?.organizationName??dashboard.partner?.organizationName??dashboard.partner?.partnerName??t("Your program","Su programa");
 const unknown=t("Unavailable","No disponible");
 const intakes=!dashboard.warnings.some(w=>w.includes("Intake summary unavailable"));const packets=!dashboard.warnings.some(w=>w.includes("Document summary unavailable"));
 const metrics=[[t("Screenings started","Evaluaciones iniciadas"),intakes?dashboard.intake.totalSessions:null],[t("Screenings completed","Evaluaciones completadas"),intakes?dashboard.intake.completedSessions:null],[t("Packets generated","Paquetes generados"),packets?dashboard.documents.totalPackets:null],[t("Clinic events","Eventos de clínica"),clinicCount]];
 const actionClass="inline-flex min-h-12 items-center justify-center rounded-lg border border-slate-300 px-5 py-3 font-bold";
 return <main className="min-h-screen bg-[#F7F4EE] text-[#071B33]"><div className="mx-auto max-w-6xl space-y-7 px-4 py-8 md:px-6">
  <header><p className="text-sm font-bold text-[#0F6E56]">{name}</p><h1 className="mt-2 text-3xl font-black">{reporting?t("Program reporting","Informes del programa"):participants?t("Participant activity","Actividad de participantes"):t("Your program at a glance","Su programa de un vistazo")}</h1></header>
  {!participants?<section className="rounded-2xl border border-slate-200 bg-white p-6">
   <h2 className="text-2xl font-bold">{live?t("Your program is live.","Su programa está activo."):setup?t("Your program is set up.","Su programa está configurado."):program?t("Your program information is saved.","La información de su programa está guardada."):t("Program status is unavailable.","El estado del programa no está disponible.")}</h2>
   {!live&&setup?<p className="mt-3 max-w-3xl leading-7">{t("LegalEase is finalizing your program terms. Your information is saved, and you can return to your dashboard.","LegalEase está finalizando los términos de su programa. Su información está guardada y puede volver a su panel.")}</p>:null}
   {live&&program?.publicUrl?<div className="mt-4 flex flex-wrap items-center gap-3"><Link className={`${actionClass} bg-[#0F6E56] text-white`} href={program.publicUrl}>{t("Open participant page","Abrir página de participantes")}</Link><button className={actionClass} onClick={async()=>{try{await navigator.clipboard.writeText(new URL(program.publicUrl!,location.origin).href);setNotice(t("Participant link copied.","Enlace copiado."));}catch{setNotice(t("Copy the link from the participant page address bar.","Copie el enlace de la barra de direcciones de la página."));}}}>{t("Copy participant link","Copiar enlace de participantes")}</button></div>:!setup&&program?.decision.status!=="live"&&dashboard.role==="partner_admin"?<Link className={`${actionClass} mt-4 bg-[#0F6E56] text-white`} href="/partner/onboarding">{t("Continue setup","Continuar configuración")}</Link>:null}
   <p role="status" className="mt-2">{notice}</p>
  </section>:<p className="max-w-3xl leading-7">{t("These are aggregate counts for your program. Participant accounts, matters, and Briefcases remain private. Clinic follow-up is available only to assigned staff under the participant’s actual consent.","Estos son datos agregados de su programa. Las cuentas, casos y archivos personales son privados. El seguimiento de clínicas requiere personal asignado y el consentimiento real del participante.")}</p>}
  {dashboard.warnings.length?<p role="status" className="rounded border border-amber-300 bg-amber-50 p-4">{t("Some activity data is temporarily unavailable. Refresh to retry.","Algunos datos de actividad no están disponibles. Actualice para reintentar.")}</p>:null}
  <section aria-label={t("Program activity","Actividad del programa")} className="grid grid-cols-2 gap-4 lg:grid-cols-4">{metrics.map(([label,value])=><article key={label} className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="text-sm font-semibold">{label}</h2><p className="mt-3 text-3xl font-black">{value??unknown}</p></article>)}</section>
  <div className="grid gap-6 md:grid-cols-2"><section className="rounded-xl border bg-white p-6"><h2 className="text-xl font-bold">{t("Program services","Servicios del programa")}</h2>
   <p className="mt-3">{live?t("Public screening available","Evaluación pública disponible"):t("Public screening is not currently available.","La evaluación pública no está disponible actualmente.")}</p>
   <dl className="mt-4 space-y-3"><div className="flex justify-between gap-4"><dt>{t("Screenings remaining","Evaluaciones restantes")}</dt><dd className="font-bold">{program?.commercial.screenings??unknown}</dd></div><div className="flex justify-between gap-4"><dt>{t("Sponsored packets remaining","Paquetes patrocinados restantes")}</dt><dd className="font-bold">{program?.commercial.packets??unknown}</dd></div></dl>
   {program?.commercial.packets===0?<p className="mt-3">{t("Sponsored packets unavailable. Any paid service requires its own verified eligibility and checkout.","No hay paquetes patrocinados disponibles. Todo servicio de pago requiere su propia verificación de elegibilidad y pago.")}</p>:null}
   <p className="mt-4 text-sm">{program?.data.geography_audience_language_accessibility?.service_area_description??dashboard.partner?.serviceArea??t("Service area not recorded","Área de servicio no registrada")}</p>
  </section><section className="rounded-xl border bg-white p-6"><h2 className="text-xl font-bold">{t("Work with your team","Trabaje con su equipo")}</h2><p className="mt-3">{t("Manage clinic events, invite staff, and review recorded activity.","Administre clínicas, invite personal y revise la actividad registrada.")}</p><nav className="mt-5 flex flex-wrap gap-3"><Link className={actionClass} href="/partner/clinic">{t("Clinics","Clínicas")}</Link><Link className={actionClass} href="/partner/team">{t("Team","Equipo")}</Link><Link className={actionClass} href="/partner/settings">{t("Settings","Configuración")}</Link></nav></section></div>
 </div></main>;
}
