// Nevada eligibility rules. Sourced from the Nevada Record-Sealing Reference for
// Wilma (Nationwide Record Clearing), corroborated by the cited NRS sections.
// Citations are NRS unless noted. In Nevada the remedy is record sealing.
export const nvEligibilityRules = [
  "Nevada's usual remedy is record SEALING, not expungement. Sealing restricts public dissemination and the case is treated as if it did not happen for many purposes, but it does not necessarily erase every copy everywhere, and out-of-state / federal agencies may not be fully bound by a Nevada order. Nevada has several different sealing routes; do not treat them all the same.",
  "Conviction sealing (NRS 179.245): Nevada courts may seal records of most eligible adult convictions after the applicable waiting period, which generally runs from release from actual custody, discharge from parole/probation, or release from a suspended sentence — whichever applies and is later. The petition requires a current verified Nevada criminal-history record from the Central Repository and a list of agencies/custodians reasonably known to hold the records, and must identify the conviction, date of birth, and the arrest date tied to the conviction.",
  "NRS 179.245 waiting periods: Category A felony — 10 years; crime of violence — 10 years; residential burglary under NRS 205.060 — 10 years; Category B, C, or D felony — 5 years; Category E felony — 2 years; gross misdemeanor — 2 years; non-felony Medicaid fraud / non-felony DUI / non-felony battery domestic violence — 7 years; misdemeanor battery, harassment, stalking, or protection-order violation — 2 years; any other misdemeanor — 1 year.",
  "NRS 179.245 clean-period rule: during the applicable waiting period the person must not have pending charges and must not have been convicted of another offense, except minor moving or standing traffic violations. Screen for pending charges anywhere, new convictions since the case ended, open warrants, and any still-active probation/parole/suspended sentence.",
  "NRS 179.245 conviction exclusions: a person may not seal a crime against a child, a sexual offense, invasion of the home with a deadly weapon, certain felony DUI offenses, vehicular homicide / DUI-related homicide, certain felony boating-under-the-influence offenses, or certain boating DUI offenses.",
  "No-conviction route (NRS 179.255): if charges were dismissed or the person was acquitted, a petition may be filed at any time after the dismissal/acquittal; if prosecution was declined, the petition may be filed after the statute of limitations runs, 8 years after arrest, or by stipulation. The petition must include the current verified criminal-history record, disposition, list of agencies/custodians, date of birth, specific charges, and the arrest date. If the prosecutor stipulates, the court applies the sealing presumption; if there is no stipulation or objection within 30 days and statutory findings are met, the court may seal without a hearing; if there is an objection, a hearing is required.",
  "Rebuttable presumption (NRS 179.2445): for petitions under NRS 179.245, 179.247, 179.255, 179.259, or 179.2595 there is a rebuttable presumption that records should be sealed when all statutory requirements are met — but it is not an automatic guarantee, a party may object, and a hearing may be required. The presumption does not apply to a defendant who received a dishonorable discharge from probation under NRS 176A.850.",
  "Effect of sealing (NRS 179.285): once records are sealed the proceedings are generally deemed never to have occurred and the person may answer accordingly, including on employment applications. Sealing immediately restores the civil rights to vote, hold office, and serve on a jury if not already restored, but it does NOT restore firearm rights unless the person receives a pardon that does not restrict the right to bear arms.",
  "Who may still inspect sealed records (NRS 179.301): some sealed records may still be inspected by authorized entities in specific circumstances — the Gaming Control Board / Gaming Commission, the Division of Insurance, prosecutors in certain cases, the Central Repository for certain sexual-offense information, law enforcement for registry-related records, and the Pardons Board if the person applies for a pardon.",
  "Multiple records / multiple courts (NRS 179.2595): if a person would otherwise need to file in more than one court, they may file in district court to seal all such records; a district court may also order sealing of records in justice or municipal courts.",
  "Deferred judgment (NRS 176.211): a person may plead guilty, guilty but mentally ill, or no contest but have judgment deferred; on completing the terms the court discharges the person and dismisses the proceedings without adjudication of guilt (not a conviction for employment, civil-rights, licensing, and most other purposes, though it can count for certain repeat-offense or bail purposes). The court must order records sealed if the person fulfills the required terms, unless the Division or prosecutor petitions for good cause not to seal and requests a hearing.",
  "Probation / specialty-court routes (NRS 176A.245, 176A.265, 176A.295): after certain probation discharges, dismissals, conditional dismissals, or set-asides the court must order records sealed if the defendant fulfilled the terms, unless the Division petitions for good cause and requests a hearing. For certain domestic-battery or DUI-related charges under these provisions, sealing may require waiting 7 years after the conditional dismissal or set-aside and filing a petition.",
  "Reentry program sealing (NRS 179.259): four years after an eligible person completes a qualifying reentry program the court may seal records, if the person was convicted of a single felony that did not involve use or threatened use of force or violence (multiple felonies arising from the same transaction may count as one). Crimes against children and sexual offenses are excluded, and professional licensing boards and the Division of Insurance may still inspect records sealed under this section.",
  "Decriminalized offense (NRS 179.271): if an offense is later decriminalized, a person convicted before decriminalization may submit a written request to the convicting court. If the prosecutor does not object within 10 judicial days the court must grant it; if the prosecutor objects, the court holds a hearing and must grant unless the prosecutor proves good cause by clear and convincing evidence. No fee may be charged. This route does not apply to traffic offenses.",
  "Controlled-substance possession not for sale (NRS 453.3365): for certain possession-not-for-sale convictions the court may seal records three years after conviction and sentencing if the person completed all court/parole/probation terms and the court is satisfied after a hearing that the person is rehabilitated; if discharged from probation under NRS 453.3363 the court must order sealing if terms were fulfilled unless Parole and Probation petitions for good cause not to seal. Professional licensing boards may inspect records sealed under this section.",
  "Trafficking-victim vacatur and sealing (NRS 179.247): certain people may petition to vacate judgment and seal records where the conviction was for prostitution/solicitation-related conduct, certain nonviolent Nevada crimes, or loitering for prostitution/solicitation, and the person's participation resulted from being a victim of trafficking or involuntary servitude. If granted, the court vacates the judgment, dismisses the accusatory pleading, and seals related records — route to legal aid or an attorney.",
  "Favorable-disposition repository removal (NRS 179A.160): if a person was arrested, cited, or subject to a warrant and later acquitted or received a favorable disposition, they may apply in writing to the Central Repository and the record-holding agency to remove the record from generally searched criminal-history files; the agency must remove it unless an exception applies (fugitive status, active prosecution, deferred-prosecution / plea-bargain-type disposition, a prior felony / gross-misdemeanor conviction, or a new arrest/charge after the record at issue)."
];
