// Nevada filing workflow. Sourced from the Nevada Record-Sealing Reference for
// Wilma (Nationwide Record Clearing), sections 8-9 and 17-18, corroborated by the
// cited NRS sections and the Nevada State Police / RCCD, Clark County District
// Attorney, and Nevada Legal Services guidance referenced therein. Nevada
// procedures vary by county; this pack is shadow-only research and wires no
// renderer.
export const nvFilingInstructions = [
  "Determine the pathway first: conviction sealing (NRS 179.245), no-conviction / dismissed / acquitted / declined (NRS 179.255), multiple records across courts (NRS 179.2595), deferred judgment (NRS 176.211), probation/specialty dismissal or set-aside (NRS 176A.245, 176A.265, 176A.295), reentry program (NRS 179.259), decriminalized offense (NRS 179.271), controlled-substance possession not for sale (NRS 453.3365), trafficking-victim vacatur (NRS 179.247), or favorable-disposition repository removal (NRS 179A.160).",
  "Get the record: obtain a current verified Nevada criminal-history report from the Department of Public Safety / Central Repository, plus local court docket / disposition, judgment of conviction (if any), probation/parole discharge proof, proof of sentence completion, and the SCOPE / local arrest record (especially in Clark County). Nevada State Police directs people to contact the court in the jurisdiction where the arrest occurred and obtain a criminal-history record to complete the court forms.",
  "File in the right court: conviction and no-conviction petitions are generally filed in the court of the arrest/conviction jurisdiction; under NRS 179.2595 a person with records across multiple courts may file one petition in district court, which can also order sealing of justice- and municipal-court records.",
  "Assemble the packet: a typical Nevada sealing packet includes the Petition to Seal Records, an Affidavit or Declaration in Support, a Stipulation to Seal Records for prosecutor review, a proposed Order to Seal Records, the current verified Nevada criminal-history report, case dispositions / judgment / docket entries, an agency list for all record custodians, and a civil cover sheet / fee-waiver request if required locally.",
  "List each record entry: Clark County's instructions note the petition and order are prepared from criminal-history / SCOPE information and that the forms allow multiple arrest entries, each requiring the date of arrest, arresting agency, charge, and final disposition.",
  "Serve the prosecutors and agencies: Nevada Legal Services recommends obtaining the certified criminal-history record from DPS, checking local records first, filing in the appropriate court, sending the petition and stipulation to each prosecutor, and obtaining multiple certified copies of the signed order for all agencies that must seal their records.",
  "No-conviction timing and hearings (NRS 179.255): a dismissed or acquitted case may be filed at any time; a declined prosecution waits for the statute of limitations, 8 years from arrest, or a stipulation. With a stipulation the court applies the sealing presumption; with no objection within 30 days and the statutory findings met, the court may seal without a hearing; an objection triggers a hearing.",
  "Special-route notes: decriminalized-offense requests (NRS 179.271) charge no fee and give the prosecutor 10 judicial days to object; the favorable-disposition route (NRS 179A.160) is a written administrative application to the Central Repository and the record-holding agency, not a court petition; trafficking-victim vacatur (NRS 179.247) should be routed to legal aid / an attorney because it vacates the conviction, not just seals it."
];
