"use client";
import Link from "next/link";
import { useCallback,useEffect,useRef,useState } from "react";
import { useRouter } from "next/navigation";
import { useLocalization } from "@/components/expungement-ai/LocalizationProvider";
import { ArtifactDocumentView } from "@/components/partners/onboarding/ArtifactDocumentView";
import { ProgramPagePreview } from "@/components/partners/onboarding/ProgramPagePreview";
import { JurisdictionPicker } from "@/components/partners/onboarding/JurisdictionPicker";
import { programServiceArea, programGeographyIssue, STANDARD_PROGRAM_COPY } from "@/lib/partners/onboarding/program-defaults";
import { PROGRAM_CONFIGURATION_FIELDS } from "@/lib/partners/onboarding/program-configuration";
import { ONBOARDING_SCHEMA_REGISTRY } from "@/lib/partners/onboarding/schema";
import { PROGRAM_STEPS,firstProgramStep,type ProgramExperience,type ProgramStep } from "@/lib/partners/onboarding/program-experience";
import type { OnboardingPartnerData,OnboardingSectionKey } from "@/lib/partners/onboarding/types";
import { PartnerTeamInviteForm } from "../team/PartnerTeamInviteForm";
const control="mt-2 min-h-12 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 font-normal text-slate-900 focus:border-teal focus:outline-none focus:ring-2 focus:ring-teal/30";
const primary="inline-flex min-h-12 items-center justify-center rounded-lg bg-[#0F6E56] px-6 py-3 font-bold text-white disabled:opacity-50";
class ProgramRequestError extends Error { constructor(message:string,readonly code?:string){super(message);} }
const displayValue=(value:unknown)=>Array.isArray(value)?value.join(", "):value==null?"—":typeof value==="object"?JSON.stringify(value):String(value);
export function ProgramOnboarding({initial,requestedStep,settings=false}:{initial:ProgramExperience;requestedStep?:string;settings?:boolean}){
 const router=useRouter();const {locale,text}=useLocalization();const es=locale==="es";const t=(en:string,spanish:string)=>es?spanish:en;
 const [view,setView]=useState(initial),[draft,setDraft]=useState(initial.data),[step,setStep]=useState<ProgramStep>(PROGRAM_STEPS.includes(requestedStep as ProgramStep)?requestedStep as ProgramStep:firstProgramStep(initial.data));
 const [saveState,setSaveState]=useState<"saved"|"saving"|"error">("saved"),[error,setError]=useState(""),[busy,setBusy]=useState(false),[confirmedReview,setConfirmedReview]=useState<string|null>(null);
 const [conflict,setConflict]=useState(false),[reconciliation,setReconciliation]=useState<{server:ProgramExperience;data:OnboardingPartnerData;fields:Array<{section:OnboardingSectionKey;key:string;saved:unknown;mine:unknown}>}|null>(null);
 const acknowledgedLiveVersion=useRef<number|null>(null);
 const latest=useRef(initial),draftRef=useRef(initial.data),lock=useRef<Promise<void>|null>(null),request=useRef<{payload:string;id:string}|null>(null);
 const heading=useRef<HTMLHeadingElement>(null); const content=useRef<HTMLDivElement>(null);
 const dirty=JSON.stringify(draft)!==JSON.stringify(view.data);
 const reviewIdentity=JSON.stringify([view.version,view.decision.scopeHash,view.reviewToken,view.materials.map(material=>[material.id,material.version,material.hash])]);
 const confirmed=confirmedReview===reviewIdentity && !dirty;
 const update=useCallback((section:OnboardingSectionKey,key:string,value:unknown)=>{if(latest.current.decision.status==="live" && acknowledgedLiveVersion.current!==latest.current.version){if(!window.confirm(es?"¿Guardar los cambios y suspender la entrada de nuevos participantes hasta revisar e iniciar de nuevo el programa actualizado?":"Save changes and hold new participant entry until the updated program is reviewed and started again?"))return;acknowledgedLiveVersion.current=latest.current.version;}setConfirmedReview(null);setDraft(previous=>{const next={...previous,[section]:{...previous[section],[key]:value}};if(key==="jurisdictions"){const geo=previous.geography_audience_language_accessibility;if(!geo?.service_area_description||geo.service_area_description===programServiceArea(geo.jurisdictions??[]))next.geography_audience_language_accessibility={...next.geography_audience_language_accessibility,service_area_description:programServiceArea(value as string[])};}draftRef.current=next;return next;});setSaveState("saving");},[es]);
 const call=useCallback(async(action:string,extra:Record<string,unknown>={})=>{
  const payload=JSON.stringify({action,...extra});if(request.current?.payload!==payload)request.current={payload,id:crypto.randomUUID()};
  const response=await fetch("/api/partners/onboarding/program",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,...extra,requestId:request.current.id})});
  const body=await response.json();if(!response.ok||!body.view)throw new ProgramRequestError(typeof body.error==="string"?body.error:"Your information could not be saved. Retry.",body.code);
  return body.view as ProgramExperience;
 },[]);
 const adopt=useCallback((next:ProgramExperience,sent:OnboardingPartnerData)=>{
  const pending=draftRef.current;const merged:OnboardingPartnerData=structuredClone(next.data);
  for(const [section,values] of Object.entries(pending))for(const [key,value] of Object.entries(values??{})){
   if(JSON.stringify(value)!==JSON.stringify((sent[section as OnboardingSectionKey] as Record<string,unknown>|undefined)?.[key])){
    const k=section as OnboardingSectionKey;merged[k]??={};Object.assign(merged[k]!,{[key]:value});
   }
  }
  latest.current=next;draftRef.current=merged;setView(next);setDraft(merged);setSaveState(JSON.stringify(merged)===JSON.stringify(next.data)?"saved":"saving");
 },[]);
 const flush=useCallback(async()=>{
  if(conflict||reconciliation)throw new Error(es?"Revise los cambios guardados antes de continuar.":"Review the saved changes before continuing.");
  if(lock.current)await lock.current;
  const sent=structuredClone(draftRef.current),base=latest.current.data;
  const patches=Object.entries(sent).flatMap(([section,values])=>{
   const before=(base[section as OnboardingSectionKey]??{}) as Record<string,unknown>;
   const changed=Object.fromEntries(Object.entries(values??{}).filter(([key,value])=>JSON.stringify(value)!==JSON.stringify(before[key])));
   return Object.keys(changed).length?[{section,values:changed,base:before}]:[];
  });
  if(!patches.length)return;
  const promise=(async()=>{try{setSaveState("saving");setError("");adopt(await call("save",{patches,expectedVersion:latest.current.version,confirmPublicationHold:acknowledgedLiveVersion.current===latest.current.version}),sent);}catch(e){if(e instanceof ProgramRequestError&&e.code==="revision_conflict")setConflict(true);setSaveState("error");setError(e instanceof Error?e.message:"Could not save. Retry.");throw e;}})();
  lock.current=promise;try{await promise;}finally{lock.current=null;}
 },[adopt,call,conflict,reconciliation,es]);
 useEffect(()=>{if(!dirty||busy||saveState==="error")return;const timeout=setTimeout(()=>{void flush().catch(()=>{});},750);return()=>clearTimeout(timeout);},[dirty,draft,busy,flush,saveState]);
 useEffect(()=>{
  const unsaved=()=>JSON.stringify(draftRef.current)!==JSON.stringify(latest.current.data);
  const beforeUnload=(event:BeforeUnloadEvent)=>{if(unsaved())event.preventDefault();};
  const navigate=(event:MouseEvent)=>{
   const link=event.target instanceof Element?event.target.closest<HTMLAnchorElement>("a[href]"):null;
   if(!link||event.defaultPrevented||event.button!==0||event.metaKey||event.ctrlKey||event.shiftKey||event.altKey||link.target==="_blank"||!unsaved())return;
   const destination=new URL(link.href,location.href);
   if(destination.pathname===location.pathname&&destination.search===location.search)return;
   if(!window.confirm(es?"Hay cambios sin guardar. ¿Salir sin guardarlos?":"Your latest changes are not saved. Leave without saving them?")){event.preventDefault();event.stopPropagation();}
  };
  window.addEventListener("beforeunload",beforeUnload);document.addEventListener("click",navigate,true);
  return()=>{window.removeEventListener("beforeunload",beforeUnload);document.removeEventListener("click",navigate,true);};
 },[es]);
 useEffect(()=>{heading.current?.focus();},[step]);
 useEffect(()=>{const pop=()=>{const next=new URL(location.href).searchParams.get("step");if(PROGRAM_STEPS.includes(next as ProgramStep))setStep(next as ProgramStep);};window.addEventListener("popstate",pop);return()=>window.removeEventListener("popstate",pop);},[]);
 async function reviewSavedChanges(){
  setBusy(true);
  try{
   const response=await fetch("/api/partners/onboarding/program",{cache:"no-store"});const body=await response.json();
   if(!response.ok||!body.view)throw new Error(t("The saved version could not be loaded. Your edits are preserved.","No se pudo cargar la versión guardada. Se conservan sus cambios."));
   const server=body.view as ProgramExperience,data=structuredClone(server.data),fields:NonNullable<typeof reconciliation>["fields"]=[];
   for(const [section,keys] of Object.entries(PROGRAM_CONFIGURATION_FIELDS))for(const key of keys){
    const part=section as OnboardingSectionKey,base=(latest.current.data[part] as Record<string,unknown>|undefined)?.[key],mine=(draftRef.current[part] as Record<string,unknown>|undefined)?.[key],saved=(server.data[part] as Record<string,unknown>|undefined)?.[key];
    if(JSON.stringify(base??null)===JSON.stringify(mine??null))continue;
    Object.assign(data,{[part]:{...data[part],[key]:mine}});
    if(JSON.stringify(base??null)!==JSON.stringify(saved??null)&&JSON.stringify(mine??null)!==JSON.stringify(saved??null))fields.push({section:part,key,saved,mine});
   }
   setReconciliation({server,data,fields});setError("");
  }catch(e){setError(e instanceof Error?e.message:t("Please retry.","Inténtelo de nuevo."));}finally{setBusy(false);}
 }
 function useReconciledChanges(){
  if(!reconciliation||reconciliation.fields.length)return;
  if(reconciliation.server.decision.status==="live"&&JSON.stringify(reconciliation.data)!==JSON.stringify(reconciliation.server.data)){
   if(!window.confirm(t("Save your reviewed changes and hold new participant entry until the updated program is reviewed and started again?","¿Guardar los cambios revisados y suspender la entrada de nuevos participantes hasta revisar e iniciar de nuevo el programa?")))return;
   acknowledgedLiveVersion.current=reconciliation.server.version;
  }
  latest.current=reconciliation.server;draftRef.current=reconciliation.data;setView(reconciliation.server);setDraft(reconciliation.data);request.current=null;setReconciliation(null);setConflict(false);setError("");setSaveState(JSON.stringify(reconciliation.data)===JSON.stringify(reconciliation.server.data)?"saved":"saving");
 }
 async function go(next:ProgramStep){setBusy(true);setError("");try{
  if(["organization","program"].includes(step)&&PROGRAM_STEPS.indexOf(next)>PROGRAM_STEPS.indexOf(step)){const invalid=content.current?.querySelector<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>("input:invalid,select:invalid,textarea:invalid");if(invalid){for(let ancestor=invalid.parentElement;ancestor;ancestor=ancestor.parentElement)if(ancestor instanceof HTMLDetailsElement)ancestor.open=true;invalid.reportValidity();invalid.focus();return;}}
  await flush();
  if(!settings&&latest.current.decision.policyVersion==="rcap2.2"&&!latest.current.decision.setupComplete&&["join","organization","program"].includes(step)){const sent=draftRef.current;adopt(await call("initialize"),sent);}
  setStep(next);window.history.pushState({},"",`${settings?"/partner/settings":"/partner/onboarding"}?step=${next}`);
  if(next==="start"&&latest.current.decision.policyVersion==="rcap2.2"&&!latest.current.reviewToken){const sent=draftRef.current;adopt(await call("review"),sent);}
 }catch(e){setError(e instanceof Error?e.message:t("Please retry.","Inténtelo de nuevo."));}finally{setBusy(false);}}
 async function finish(){setBusy(true);setError("");try{await flush();const next=await call("finish",{reviewToken:view.reviewToken,confirmed});adopt(next,draftRef.current);if(!next.decision.setupComplete)throw new Error(t("Your program changed. Review the updated information.","Su programa cambió. Revise la información actualizada."));router.push("/partner/dashboard");router.refresh();}catch(e){setError(e instanceof Error?e.message:t("Please retry.","Inténtelo de nuevo."));}finally{setBusy(false);}}
 const names=es?["Unirse","Organización","Programa","Equipo","Comenzar"]:["Join","Organization","Program","Team","Start"];
 const titles=es?["Bienvenido a RCAP.","Cuéntenos sobre su organización.","¿Cómo funcionará su programa?","¿Alguien más ayuda a dirigir su programa?","Revise su programa."]:["Welcome to RCAP.","Tell us about your organization.","How will your program work?","Anyone else helping run your program?","Review your program."];
 const geo=draft.geography_audience_language_accessibility??{};
 const geographyIssue=programGeographyIssue(draft);
 const field=(section:OnboardingSectionKey,key:string,label:string,type="text",required=false)=>{
  const value=(draft[section] as Record<string,unknown>|undefined)?.[key];return <label className="block text-sm font-semibold">{label}{required?" *":""}<input className={control} value={typeof value==="string"?value:""} type={type} required={required} maxLength={type==="url"?2048:500} autoComplete={key==="legal_organization_name"?"organization":key==="website"?"url":key.includes("email")?"email":undefined} disabled={!view.canEdit||key==="legal_organization_name"&&view.legalIdentityLocked} onChange={e=>update(section,key,e.target.value)}/></label>;
 };
 const choice=(section:OnboardingSectionKey,key:string,label:string,options:[string,string][])=> <label className="block text-sm font-semibold">{label}<select className={control} value={String((draft[section] as Record<string,unknown>|undefined)?.[key]??"")} disabled={!view.canEdit} onChange={e=>update(section,key,e.target.value)}><option value="">{t("Choose an option","Elija una opción")}</option>{options.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>;
 return <main className="min-h-screen bg-[#F7F4EE] px-4 py-8 text-[#071B33] sm:px-6"><div className="mx-auto max-w-5xl">
  <div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm font-bold tracking-wide">{view.organizationName}</p><Link href="/partner/dashboard" className="inline-flex min-h-11 items-center underline">{t("Dashboard","Panel")}</Link></div>
  <ol aria-label={t("Program setup","Configuración del programa")} className="my-6 grid grid-cols-5 gap-1 sm:gap-3">{PROGRAM_STEPS.map((item,index)=><li key={item} aria-current={item===step?"step":undefined}><button disabled={busy||Boolean(reconciliation)} onClick={()=>void go(item)} className={`min-h-12 w-full rounded-lg px-1 text-xs font-bold sm:text-sm ${item===step?"bg-[#0F6E56] text-white":"border border-slate-300 bg-white text-slate-700"}`}><span className="block text-xs opacity-75">{index+1}</span>{names[index]}</button></li>)}</ol>
  <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-9"><h1 ref={heading} tabIndex={-1} className="text-2xl font-extrabold outline-none sm:text-3xl">{titles[PROGRAM_STEPS.indexOf(step)]}</h1>
   <p role="status" aria-live="polite" className="mt-3 min-h-6 text-sm text-slate-600">{saveState==="saving"?t("Saving…","Guardando…"):saveState==="error"?t("Could not save. Retry","No se pudo guardar. Reintentar"):t("Saved","Guardado")}</p>
   {error?<div role="alert" className="my-4 rounded-lg border border-orange/30 bg-orange/10 p-4"><p>{text(error)}</p>{saveState==="error"?<button disabled={busy} className="mt-2 min-h-11 underline" onClick={()=>conflict?void reviewSavedChanges():void flush().catch(()=>{})}>{conflict?t("Review saved changes","Revisar los cambios guardados"):t("Retry saving","Volver a guardar")}</button>:null}</div>:null}
   {reconciliation?<section aria-label={t("Resolve saved changes","Resolver cambios guardados")} className="my-4 space-y-4 rounded border p-5"><h2 className="text-xl font-bold">{t("Your edits are preserved. Choose which changes to save.","Se conservan sus cambios. Elija cuáles guardar.")}</h2>{reconciliation.fields.map(item=><div key={`${item.section}.${item.key}`} className="rounded border p-4"><h3 className="font-bold">{ONBOARDING_SCHEMA_REGISTRY.find(field=>field.sectionKey===item.section&&field.key===item.key)?.label??item.key}</h3><p className="break-words">{t("Saved:","Guardado:")} {displayValue(item.saved)}</p><p className="break-words">{t("My edit:","Mi cambio:")} {displayValue(item.mine)}</p>{([['mine',t('Keep my edit','Conservar mi cambio')],['saved',t('Use saved value','Usar el valor guardado')]] as const).map(([choice,label])=><button key={choice} type="button" className="mr-3 min-h-11 underline" onClick={()=>setReconciliation(previous=>previous?{...previous,data:{...previous.data,[item.section]:{...previous.data[item.section],[item.key]:item[choice]}},fields:previous.fields.filter(field=>field!==item)}:null)}>{label}</button>)}</div>)}{!reconciliation.fields.length?<button type="button" className={primary} onClick={useReconciledChanges}>{t("Save reviewed changes","Guardar los cambios revisados")}</button>:null}</section>:null}
   {view.decision.policyVersion==="legacy"?<div className="my-4 rounded border p-4"><p>{t("Your existing answers and approvals are preserved. Choosing five-step setup changes the setup policy and requires review of current program materials. It does not change your contracts or funding.","Se conservan sus respuestas y aprobaciones. La configuración de cinco pasos cambia la política y requiere revisar los materiales actuales. No cambia sus contratos ni financiación.")}</p><button className={primary+" mt-3"} disabled={busy||!view.canEdit} onClick={async()=>{setBusy(true);setError("");try{adopt(await call("upgrade_policy",{confirmed:true,expectedVersion:view.version}),draftRef.current);}catch(e){setError(e instanceof Error?e.message:"Please retry.");}finally{setBusy(false);}}}>{t("Use five-step setup","Usar configuración de cinco pasos")}</button></div>:null}
   <div ref={content} className="mt-6 space-y-6" inert={Boolean(reconciliation)}>
    {step==="join"?<p className="max-w-2xl leading-7">{t("Your administrator account is connected to this organization. We will save your progress as you prepare your program.","Su cuenta de administrador está vinculada a esta organización. Guardaremos su progreso mientras prepara su programa.")}</p>:null}
    {step==="organization"?<div className="grid gap-5 sm:grid-cols-2">
     {field("organization_contacts","legal_organization_name",t("Legal organization name","Nombre legal de la organización"),"text",true)}
     {field("organization_contacts","public_organization_name",t("Public organization name","Nombre público de la organización"),"text",true)}
     {field("organization_contacts","public_program_name",t("Program name","Nombre del programa"),"text",true)}
     {field("organization_contacts","website",t("Website (optional)","Sitio web (opcional)"),"url")}
     <fieldset className="sm:col-span-2 rounded-xl border p-4"><legend className="px-2 font-bold">{t("Primary program contact","Contacto principal del programa")}</legend><div className="grid gap-4 sm:grid-cols-2">{([['name',t('Name','Nombre')],['work_email',t('Work email','Correo laboral')],['title',t('Title (optional)','Cargo (opcional)')]] as const).map(([key,label])=><label key={key} className="text-sm font-semibold">{label}<input className={control} type={key==='work_email'?'email':'text'} autoComplete={key==='work_email'?'email':key==='name'?'name':'organization-title'} value={draft.organization_contacts?.contacts?.[0]?.[key]??''} onChange={e=>{const contacts=[...(draftRef.current.organization_contacts?.contacts??[])];contacts[0]={...(contacts[0]??{stable_row_id:crypto.randomUUID(),role:'program_operator' as const,name:'',title:'',work_email:''}),[key]:e.target.value};update('organization_contacts','contacts',contacts);}}/></label>)}</div></fieldset>
     <div className="sm:col-span-2"><p className="text-sm text-slate-600">{t("A logo is optional. Your program can use the RCAP text identity.","El logotipo es opcional. Su programa puede usar la identidad de texto de RCAP.")}</p></div>
    </div>:null}
    {step==="program"?<>
     <div className="grid gap-5 sm:grid-cols-2"><div className="sm:col-span-2"><JurisdictionPicker value={geo.jurisdictions??[]} allowed={view.permittedJurisdictions??initial.data.geography_audience_language_accessibility?.jurisdictions??[]} spanish={es} disabled={busy||!view.canEdit} onChange={codes=>update("geography_audience_language_accessibility","jurisdictions",codes)}/><p className="mt-2 text-sm">{t("To expand your permitted service area, contact LegalEase support.","Para ampliar el área de servicio permitida, contacte al soporte de LegalEase.")}</p></div>
      {field("geography_audience_language_accessibility","service_area_description",t("Service area","Área de servicio"),"text",true)}
      {choice("program_goals","participation_mode",t("How will people participate?","¿Cómo participarán las personas?"),[["online",t("Online","En línea")],["clinics",t("At clinics or events","En clínicas o eventos")],["both",t("Both","Ambas opciones")]])}
      {choice("access_sponsorship_capacity","participant_access_model",t("Who can join?","¿Quién puede participar?"),[["open",t("Anyone with the link","Cualquier persona con el enlace")],["required_code",t("People with an access code","Personas con código de acceso")],["invite_only",t("Invited participants only","Solo participantes invitados")]])}
      {field("support_referrals_reporting","participant_support_email",t("Participant support email","Correo de soporte para participantes"),"email",true)}
      <label className="flex min-h-12 items-center gap-3 text-sm font-semibold"><input type="checkbox" checked={geo.enable_spanish===true} onChange={e=>update("geography_audience_language_accessibility","enable_spanish",e.target.checked)}/>{t("Offer English and Spanish","Ofrecer inglés y español")}</label>
     </div>
     {geographyIssue?<div role="alert" className="rounded-lg border border-orange p-4"><p>{text(geographyIssue)}</p><button type="button" className="min-h-11 underline" disabled={busy||!view.canEdit} onClick={()=>update("geography_audience_language_accessibility","service_area_description",programServiceArea(geo.jurisdictions??[]))}>{t("Use selected jurisdictions in description","Usar las jurisdicciones seleccionadas en la descripción")}</button></div>:null}
     {["optional_code","required_code","invite_only"].includes(draft.access_sponsorship_capacity?.participant_access_model??"") ? <p className="text-sm">{dirty ? t("Save the current access setting before managing codes.","Guarde la configuración de acceso antes de gestionar los códigos.") : <Link className="inline-flex min-h-11 items-center underline" href="/partner/access-codes">{t("Manage access codes","Gestionar códigos de acceso")}</Link>}</p> : null}
     <details><summary className="min-h-12 cursor-pointer py-3 font-bold">{t("Participant page content","Contenido de la página del participante")}</summary><p className="my-3 text-sm">{t("Edit the public English source. Review automatically prepared Spanish alongside it before confirming your program.","Edite el texto público original en inglés. Revise el español preparado automáticamente junto con él antes de confirmar su programa.")}</p><div className="space-y-4">{field("program_goals","target_population",t("Who the program serves","A quién sirve el programa"),"text",true)}{([['program_headline',t('Headline','Título')],['program_subheadline',t('Introduction','Introducción')],['approved_organization_description',t('Organization description','Descripción de la organización')],['participant_support_copy',t('Participant support instructions','Instrucciones de soporte para participantes')]] as const).map(([key,label])=><label key={key} className="block text-sm font-semibold">{label}<textarea aria-label={label} className={control} rows={key==='program_headline'?2:3} maxLength={key==='program_headline'?180:key==='program_subheadline'?500:2000} required value={draft.brand_public_page?.[key]??''} disabled={!view.canEdit} onChange={event=>update('brand_public_page',key,event.target.value)}/></label>)}<label className="block text-sm font-semibold">{t("Participant button label","Texto del botón del participante")}<input aria-label={t("Participant button label","Texto del botón del participante")} className={control} required maxLength={60} value={draft.brand_public_page?.primary_cta_label??''} disabled={!view.canEdit} onChange={event=>update('brand_public_page','primary_cta_label',event.target.value)}/><span className="mt-2 block font-normal">{t("Use a short action, up to 60 characters.","Use una acción breve, de hasta 60 caracteres.")}</span></label><button type="button" className="min-h-11 underline" disabled={!view.canEdit} onClick={()=>update('brand_public_page','primary_cta_label',STANDARD_PROGRAM_COPY.primaryActionLabel[0])}>{t("Use Start free screening","Usar Comenzar evaluación gratuita")}</button></div></details>
     <details><summary className="min-h-12 cursor-pointer py-3 font-bold">{t("Contested matters and referrals","Asuntos disputados y referencias")}</summary><label className="block text-sm font-semibold">{t("Contested matter procedure","Procedimiento para asuntos disputados")}<textarea aria-label={t("Contested matter procedure","Procedimiento para asuntos disputados")} className={control} rows={4} minLength={20} maxLength={4000} required value={draft.support_referrals_reporting?.contested_matter_procedure??''} disabled={!view.canEdit} onChange={event=>update('support_referrals_reporting','contested_matter_procedure',event.target.value)}/></label></details>
     <aside className="rounded-xl bg-slate-50 p-5"><h2 className="font-bold">{t("Who pays for packets?","¿Quién paga los paquetes?")}</h2><p className="mt-2">{text(view.commercial.label)}</p><p className="mt-2 text-sm">{t("Screenings available","Evaluaciones disponibles")}: {view.commercial.screenings??t("Unavailable","No disponible")} · {t("Sponsored packets available","Paquetes patrocinados disponibles")}: {view.capabilities.issue_sponsored_packet?view.commercial.packets??t("Unavailable","No disponible"):t("Unavailable under current authority","No disponible bajo la autoridad actual")}</p></aside>
     <p className="text-sm leading-6 text-slate-600">{t("For contested hearings, prosecutor objections, or requests for representation, stop the self-help process and contact program support. LegalEase does not provide representation.","Si hay audiencias disputadas, objeciones del fiscal o solicitudes de representación, detenga el proceso de autoayuda y contacte al soporte del programa. LegalEase no brinda representación.")}</p>
     {geo.enable_spanish?<p className="rounded-xl border p-5 text-sm">{t("Spanish drafts are prepared automatically from your saved English copy when you continue to review. Review English and Español together and confirm the exact materials once. Disabling Spanish preserves your saved copy.","Los borradores en español se preparan automáticamente a partir del texto guardado en inglés al continuar a la revisión. Revise inglés y español juntos y confirme los materiales exactos una sola vez. Desactivar español conserva el texto guardado.")}</p>:null}
    </>:null}
    {step==="team"?<><p className="leading-7">{t("You are already an active administrator. Invite a colleague as Partner Staff, or continue on your own. Clinic permissions are assigned when you create an event.","Usted ya es administrador activo. Invite a un colega como personal del programa o continúe sin ayuda. Los permisos de clínica se asignan al crear un evento.")}</p><details><summary className="min-h-12 cursor-pointer font-bold">{t("Invite team","Invitar al equipo")}</summary><div className="mt-4 max-w-xl"><PartnerTeamInviteForm partnerSlug={view.partnerSlug} partnerName={view.organizationName}/></div></details></>:null}
    {step==="start"&&view.decision.policyVersion==="rcap2.2"?<>
      <p className="leading-7">{t("Review the program information and participant page below. Your confirmation covers these current versions.","Revise la información del programa y la página del participante a continuación. Su confirmación cubre estas versiones actuales.")}</p>
      <nav aria-label={t("Program materials","Materiales del programa")} className="flex flex-wrap gap-3">{[...view.materials,...(view.draftMaterials??[])].map(material=><a key={material.id} className="inline-flex min-h-11 items-center rounded border px-4 font-bold" href={`#partner-material-${material.type}`} onClick={()=>document.getElementById(`partner-material-${material.type}`)?.focus({preventScroll:true})}>{material.type==="implementation_brief"?t("View Program Summary","Ver resumen del programa"):t("View Participant Page","Ver página del participante")}</a>)}</nav>
      {[...view.materials,...(view.draftMaterials??[])].map(material=><article key={material.id} id={`partner-material-${material.type}`} tabIndex={-1} className="scroll-mt-28" data-material-id={material.id} data-material-version={material.version} data-material-hash={material.hash}><h2 className="mb-3 text-xl font-bold">{material.type==="implementation_brief"?t("Program Summary","Resumen del programa"):t("Participant Page","Página del participante")} · {t("Version","Versión")} {material.version}{material.issues?.length?t(" · Incomplete draft"," · Borrador incompleto"):""}</h2>{material.document.pagePreview?<ProgramPagePreview preview={material.document.pagePreview} logoSrc={material.document.pagePreview.logo.assetId?`/api/partners/onboarding/assets/${material.document.pagePreview.logo.assetId}`:null}/>:<ArtifactDocumentView document={material.document} versionNumber={material.version}/>}</article>)}
      <section aria-labelledby="partner-final-review" className="rounded-xl border p-5"><h2 id="partner-final-review" className="text-xl font-bold">{t("Final review & program confirmation","Revisión final y confirmación del programa")}</h2>
      {view.decision.setupComplete&&view.reviewToken?<div className="mt-3 space-y-3"><p>{view.decision.live?t("Your program is live.","Su programa está activo."):t("Your confirmation is saved for these current materials.","Su confirmación está guardada para estos materiales actuales.")}</p>{view.publicationNextAction?<><p>{text(view.publicationNextAction.reason)}</p><Link className="inline-flex min-h-11 items-center underline" href={view.publicationNextAction.href}>{es?view.publicationNextAction.labelEs:view.publicationNextAction.label}</Link></>:null}</div>:!view.reviewToken?<><p className="mt-3">{busy?t("Preparing current materials…","Preparando los materiales actuales…"):view.decision.blockers[0]?.label??t("Update the missing or outdated materials, including Spanish drafts, before confirming.","Actualice los materiales faltantes o desactualizados, incluidos los borradores en español, antes de confirmar.")}</p><button type="button" className={primary+" mt-4"} disabled={busy||!view.canEdit} onClick={()=>void go(view.decision.configurationComplete?"start":firstProgramStep(view.data))}>{view.decision.configurationComplete?t("Update Materials","Actualizar materiales"):t("Complete program details","Completar los detalles del programa")}</button></>:<><p className="mt-3">{t("Ready for your review and confirmation.","Listo para su revisión y confirmación.")}</p><p className="mt-2">{programServiceArea(view.data.geography_audience_language_accessibility?.jurisdictions??[])} · {view.data.geography_audience_language_accessibility?.enable_spanish?"English / Español":"English"}</p><label className="mt-4 flex items-start gap-3 leading-6"><input className="mt-1 h-5 w-5" type="checkbox" disabled={busy||dirty} checked={confirmed} onChange={e=>setConfirmedReview(e.target.checked?reviewIdentity:null)}/><span>{t("I confirm that the organization, program, support route, and participant page shown above are accurate and authorized for use. I understand that results are not guaranteed, LegalEase does not provide representation, and packet services depend on the program's actual terms.","Confirmo que la organización, el programa, la vía de soporte y la página del participante que se muestran son correctos y están autorizados. Entiendo que los resultados no están garantizados, LegalEase no brinda representación y los servicios de paquetes dependen de las condiciones reales del programa.")}</span></label></>}
      </section>
    </>:null}
   </div>
   <footer inert={Boolean(reconciliation)} className="mt-8 flex flex-wrap items-center justify-between gap-4 border-t pt-6">
    {step!=="join"?<button disabled={busy} className="min-h-12 px-3 font-semibold underline" onClick={()=>void go(PROGRAM_STEPS[Math.max(0,PROGRAM_STEPS.indexOf(step)-1)])}>{t("Back","Atrás")}</button>:<span/>}
    {step==="start"?view.decision.policyVersion==="legacy"?<Link className={primary} href="/partner/dashboard">{t("Go to my dashboard","Ir a mi panel")}</Link>:view.decision.setupComplete?<Link className={primary} href="/partner/dashboard">{t("Go to my dashboard","Ir a mi panel")}</Link>:view.reviewToken?<button className={primary} disabled={busy||!confirmed||!view.canEdit} onClick={()=>void finish()}>{busy?t("Saving…","Guardando…"):view.decision.delegated?t("Start my program","Iniciar mi programa"):t("Confirm my program","Confirmar mi programa")}</button>:null:<button className={primary} disabled={busy||!view.canEdit} onClick={()=>void go(PROGRAM_STEPS[PROGRAM_STEPS.indexOf(step)+1])}>{busy?t("Saving…","Guardando…"):step==="team"?t("I'll do this later","Lo haré después"):t("Continue","Continuar")}</button>}
   </footer>
  </section><p className="mt-5 text-sm text-slate-600">{t("Your progress stays with your organization's account.","Su progreso permanece en la cuenta de su organización.")}</p>
 </div></main>;
}
