import type {NextRequest} from "next/server";
import {requireInternalOnboardingContext} from "@/lib/partners/onboarding/auth-context";
import {isRcapLaunchStudioEnabled} from "@/lib/partners/onboarding/feature";
import {getSupabaseAdminClient} from "@/lib/supabase/server";
import {assertSameOrigin,readBoundedJson,requireRequestId} from "@/lib/partners/onboarding/request-security";
import {onboardingJson,onboardingHttpError} from "@/lib/partners/onboarding/http";
import {Phase1OnboardingError} from "@/lib/partners/onboarding/errors";
export async function POST(request:NextRequest){try{assertSameOrigin(request);if(!isRcapLaunchStudioEnabled())throw new Phase1OnboardingError("feature_disabled","Assigned preparation unavailable.");const body=await readBoundedJson(request);const context=await requireInternalOnboardingContext(String(body.partnerSlug??""));const admin=getSupabaseAdminClient()!;
 if(body.action==="revoke"){if(String(body.authorityReference??"").trim().length<10)throw new Phase1OnboardingError("invalid_input","Record a specific revocation authority reference.");const {data,error}=await admin.from("rcap_partner_operator_assignments").update({revoked_at:new Date().toISOString(),revoked_by:context.authUserId,revocation_reason:String(body.authorityReference??"")}).eq("id",requireRequestId(body.assignmentId)).eq("partner_slug",context.partnerSlug).is("revoked_at",null).select("id");if(error||data?.length!==1)throw new Phase1OnboardingError("invalid_input","Assignment revocation refused.");return onboardingJson({success:true});}
 if(!Array.isArray(body.capabilities)||body.capabilities.length<1||body.capabilities.some(c=>!["prepare","review_operational_material"].includes(String(c)))||String(body.authorityReference??"").trim().length<10)throw new Phase1OnboardingError("invalid_input","Only bounded preparation and operational review capabilities are permitted.");
 const {error}=await admin.from("rcap_partner_operator_assignments").insert({auth_user_id:requireRequestId(body.authUserId),partner_slug:context.partnerSlug,capabilities:body.capabilities,granted_by:context.authUserId,authority_reference:String(body.authorityReference).trim(),expires_at:body.expiresAt??null});if(error)throw new Phase1OnboardingError("invalid_input","Assignment could not be recorded for that existing operator and partner.");return onboardingJson({success:true});}catch(error){return onboardingHttpError(error);}}
