import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import crypto from 'node:crypto';import {RESUME,requireResumeAuthorization,exactSessionClosureSql,resumeSql,assertResumeBytes} from './rcap-clinic-resume-contract.mjs';import {startEphemeralPg} from './lib/rcap-ephemeral-pg.mjs';
const source=fs.readFileSync('scripts/rcap-clinic-resume-contract.mjs','utf8');
function fixture(){const r=RESUME;return {job:{id:r.job,matter_id:r.matter,status:'delivered',attempt_count:1,accounting_result:'consumed',delivery_eligibility:'eligible',output_sha256:r.hash,normalized_output_sha256:r.normalizedHash,output_byte_count:r.bytes,page_count:r.pages,container_digest:r.priorDigest,credit_ledger_id:r.credit,sponsored_consumer_briefcase_item_id:r.item,sponsored_consumer_auth_user_id:r.owner,sponsored_session_id:r.session,sponsored_clinic_event_id:r.event,sponsored_verification_hash:r.verification,partner_id:r.partner,failure_disposition:null,error_code:null},item:{id:r.item,user_id:r.owner,source_session_id:r.session},session:{session_id:r.session,claimed_slot_state:'consumed',partner_slug:'mvl-demo'},case:{id:r.clinicCase,matter_id:r.item,screening_session_id:r.session,assisted_session_id:r.assisted,participant_user_id:r.owner,event_id:r.event,queue_status:'packet_ready',route_disposition:'packet'},assisted:{id:r.assisted,participant_user_id:r.owner,event_id:r.event,screening_session_id:r.session,status:'active',ended_at:null,ended_reason:null},verification:{status:'verified',verification_hash:r.verification,consumer_auth_user_id:r.owner,matter_id:r.matter},provenance:[{render_job_id:r.job,verification_hash:r.verification,consumer_auth_user_id:r.owner}],generation:[{id:'generated'}],credit:[{id:r.credit,event_type:'consumed'}],capacity:{allPartnerRows:[{consumed:1,packet_cap:2}],screening:{screenings_used:1,screenings_allowed:2},eventConsumed:1,event:{sponsorship_allocation:2}},sessionAudit:[],access:{uses_count:2,max_uses:2,is_active:true},claimable:[],housekeeping:[],delivery:['delivery_authorized','transmission_started','transmission_completed'].map((event_type,i)=>({id:`prior-${i}`,event_type}))};}
// Execute the actual orchestration with transport ports. Only fixed binary and
// separately-tested capacity guards are adapted to synthetic local fixtures.
const bytes=Buffer.from('%PDF-1.7\nresume fixture\n');
const text=source.replace(/^import .*;$/mg,'').replace(/export /g,'').replace(/export const /g,'const ');
const controller=vm.runInNewContext(text+'\n({runResumeProof,assertResumeState,assertPageLoadUnchanged,assertRepeatDelivery})',{assert:{...assert,deepEqual:(a,b,...rest)=>assert.deepEqual(JSON.parse(JSON.stringify(a)),JSON.parse(JSON.stringify(b)),...rest)},Buffer,createHash:crypto.createHash,assertPacketCapacity:()=>({}),packetCapacitySql:()=>'',});
// Use the real binary assertion as a refusal test; success-path controller uses
// an in-memory fixture identity, never a configurable hosted expected hash.
const localText=text.replace(`hash:'${RESUME.hash}'`,`hash:'${crypto.createHash('sha256').update(bytes).digest('hex')}'`).replace('bytes:68873','bytes:'+bytes.length);
const local=vm.runInNewContext(localText+'\n({runResumeProof})',{assert:{...assert,deepEqual:(a,b,...rest)=>assert.deepEqual(JSON.parse(JSON.stringify(a)),JSON.parse(JSON.stringify(b)),...rest)},Buffer,createHash:crypto.createHash,assertPacketCapacity:()=>({}),packetCapacitySql:()=>''});
test('resume defaults read-only; exact project and BOTH explicit execution authorities',async()=>{assert.equal(requireResumeAuthorization({project:RESUME.project}),false);assert.throws(()=>requireResumeAuthorization({project:'wwtwtsmywnckfkdaqqeg'}));assert.throws(()=>requireResumeAuthorization({project:RESUME.project,execute:true}));assert.throws(()=>exactSessionClosureSql(RESUME.project,''));assert.throws(()=>assertResumeBytes(bytes));assert.ok((await resumeSql(RESUME.project)).startsWith('select '));});
test('immutable namespace and accounting drift fail closed',()=>{const s=fixture();controller.assertResumeState(s);for(const change of [x=>x.job.id='other',x=>x.job.attempt_count=2,x=>x.job.container_digest='other',x=>x.case.assisted_session_id='other',x=>x.credit.push({}),x=>x.access.uses_count=0,x=>x.housekeeping.push('other'),x=>x.claimable.push('other'),x=>x.verification.verification_hash='other']){const bad=structuredClone(s);change(bad);assert.throws(()=>controller.assertResumeState(bad));}const b=structuredClone(s);b.delivery.push({});assert.throws(()=>controller.assertPageLoadUnchanged(s,b));});
test('actual resume sequencing; automatic download and page-load accounting mutations stop before explicit action',async()=>{
 const run=async(mutate)=>{const s=fixture();s.job.output_sha256=crypto.createHash('sha256').update(bytes).digest('hex');s.job.output_byte_count=bytes.length;let count=0,clicked=0;const calls=[];const p={snapshot:async()=>structuredClone(s),requireSuccessorPreview:async()=>({successor:true}),signInOwner:async()=>calls.push('sign-in'),observeBeforeMatter:async()=>calls.push('observe'),openReadyMatter:async()=>{calls.push('open');mutate?.(s,()=>count++);},downloadRequests:()=>count,explicitDownload:async()=>{clicked++;count++;s.delivery.push(...['delivery_authorized','transmission_started','transmission_completed'].map((event_type,i)=>({id:`repeat-${i}`,event_type})));return bytes;},proveDenials:async()=>({stranger:404,anonymous:401}),proveExactStaffCase:async()=>{},resetDeviceAndCloseExactSession:async()=>{Object.assign(s.assisted,{status:'reset',ended_reason:'staff_reset',ended_at:'now'});s.sessionAudit.push({target_id:RESUME.assisted,event_id:RESUME.event,actor_user_id:RESUME.owner,metadata:{reason:'staff_reset'}});return{signOutConfirmed:true,cookies:0,storage:{local:0,session:0},historySafe:true,sameDeviceStranger:404};}};try{const receipt=await local.runResumeProof(p);assert.equal(receipt.passed,true);assert.deepEqual(calls,['sign-in','observe','open']);assert.equal(clicked,1);}catch(e){assert.equal(clicked,0);throw e;}};
 await run();await assert.rejects(run((s,hit)=>hit()));await assert.rejects(run(s=>s.credit.push({})));await assert.rejects(run(s=>s.delivery.push({})));
});
test('exact lost-cookie session closure uses canonical function, idempotent and preserves unrelated rows',()=>{
 const db=startEphemeralPg();try{db.sql(`create table clinic_assisted_sessions(id uuid primary key,event_id uuid,participant_user_id uuid,screening_session_id uuid,status text,ended_at timestamptz,ended_reason text);create table clinic_cases(id uuid,assisted_session_id uuid,matter_id uuid,screening_session_id uuid,participant_user_id uuid,event_id uuid,queue_status text);create table clinic_event_staff(event_id uuid,status text,permissions text[],partner_user_id uuid);create table partner_users(id uuid,auth_user_id uuid,status text,partner_slug text);create table clinic_events(id uuid,partner_slug text);create table clinic_event_audit(event_id uuid,actor_user_id uuid,action text,target_type text,target_id uuid,metadata jsonb);`);
 const canonical=fs.readFileSync('supabase/migrations/20260825122000_clinic_mode_accounting_reporting.sql','utf8');const start=canonical.indexOf('create or replace function public.clinic_end_assisted_session');db.sql(canonical.slice(start,canonical.indexOf('create or replace function public.clinic_upsert_case',start)));
 const r=RESUME;db.sql(`insert into clinic_assisted_sessions values('${r.assisted}','${r.event}','${r.owner}','${r.session}','active',null,null),('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','${r.event}','${r.owner}','${r.session}','active',null,null);insert into clinic_cases values('${r.clinicCase}','${r.assisted}','${r.item}','${r.session}','${r.owner}','${r.event}','packet_ready');`);
 const sql=exactSessionClosureSql(r.project,'Roger:clinic-resume:36211668984:close-exact-lost-cookie-session');db.sql(sql);db.sql(sql);assert.equal(db.scalar(`select status from clinic_assisted_sessions where id='${r.assisted}'`),'reset');assert.equal(db.scalar('select count(*) from clinic_event_audit'),'1');assert.equal(db.scalar("select status from clinic_assisted_sessions where id='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'"),'active');db.sql(`update clinic_cases set matter_id='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'`);assert.throws(()=>db.sql(sql));
 }finally{db.stop();}
});
test('read-only resume query parses against current packet/consumer schema without invoking lifecycle writers',async()=>{
 const {packetApplicationTestDatabase}=await import('./rcap-packet-database-reference.mjs');const db=packetApplicationTestDatabase(process.cwd());try{
 db.sql('create table clinic_assisted_sessions(id uuid);create table clinic_event_access_codes(id uuid);create table clinic_event_audit(target_id uuid,action text);');
 const row=db.json(await resumeSql(RESUME.project));assert.equal(row.job,null);assert.deepEqual(row.claimable,[]);assert.deepEqual(row.housekeeping,[]);
 }finally{db.stop();}
});
