import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import {once} from 'node:events';import {execFileSync} from 'node:child_process';import {chromium} from 'playwright';
import {handleResumeRequest,createNetworkEvidence,ACCEPTANCE_ORIGIN,TURNSTILE_LOADER,TOOLBAR_LOADER} from './rcap-clinic-resume-network-policy.mjs';
import {installSignInSafety,signInWithRealForm} from './rcap-clinic-resume-sign-in.mjs';
const fixture=process.env.RCAP_SIGNIN_FIXTURE;assert.ok(fixture,'RCAP_SIGNIN_FIXTURE must name actual compiled fixture; use rcap-clinic-resume-sign-in-fixture.mjs');
for(const file of ['src/components/expungement-ai/ConsumerSignInForm.tsx','src/components/expungement-ai/LocalizationProvider.tsx','src/lib/supabase/browser.ts','src/lib/supabase/config.ts','src/components/auth/TurnstileWidget.tsx','src/lib/auth/captcha.ts','package-lock.json'])assert.deepEqual(fs.readFileSync(path.join(fixture,file)),fs.readFileSync(file),'fixture must use unchanged '+file);
const policy={project:'hyflxnlhpmiqxvvcoiia',serverCaptchaRequired:false,frontend:{clientCaptchaRequired:false,widgetSiteKeyConfigured:true},syntheticProfile:'bounded no-analytics Clinic resume'};
const old=await import('data:text/javascript;base64,'+Buffer.from(execFileSync('git',['show','7214b7cbec3566a9a9895eaaffb9dbc6d46baa7d:scripts/rcap-clinic-resume-network-policy.mjs'])).toString('base64'));
const defer=()=>{let resolve;return {promise:new Promise(r=>resolve=r),resolve:v=>resolve(v)}};
async function site(){const gate=defer(),arrived=defer();let hold=true;const requests=[];const server=http.createServer(async(req,res)=>{const u=new URL(req.url,'http://fixture');requests.push({path:u.pathname,queryNames:[...u.searchParams.keys()],bypass:req.headers['x-vercel-protection-bypass']==='synthetic',toolbar:req.headers['x-vercel-skip-toolbar']==='1'});if(u.pathname.startsWith('/_next/')){if(hold&&u.pathname.endsWith('.js')){arrived.resolve();await gate.promise;}const file=path.join(fixture,'.next',u.pathname.slice(7));if(!fs.existsSync(file)){res.statusCode=404;return res.end();}res.setHeader('content-type',u.pathname.endsWith('.js')?'application/javascript':'text/css');return res.end(fs.readFileSync(file));}res.setHeader('content-type','text/html');const html=fs.readFileSync(path.join(fixture,'.next/server/app/expungement-ai/sign-in.html'),'utf8');res.end(html.replace('</body>',`<script src="${TOOLBAR_LOADER}"></script></body>`));});server.listen(0,'127.0.0.1');await once(server,'listening');return {origin:`http://127.0.0.1:${server.address().port}`,requests,arrived:arrived.promise,release:()=>{hold=false;gate.resolve()},close:()=>{gate.resolve();server.closeAllConnections();server.close()}};}
async function setup(handler=handleResumeRequest,{safety=true,install=installSignInSafety}={}){const s=await site(),browser=await chromium.launch({headless:true}),c=await browser.newContext(),network=createNetworkEvidence(),violations=[],events={auth:0,native:[],scriptErrors:0,externalForwarded:0};c.setDefaultTimeout(3000);if(safety)await install(c);await c.route('**/*',async route=>{const r=route.request(),u=new URL(r.url());if(u.searchParams.has('password')){events.native.push({path:u.pathname,method:r.method(),queryNames:[...u.searchParams.keys()]});return route.abort();}if(u.origin===ACCEPTANCE_ORIGIN){events.auth++;assert.equal(u.pathname,'/auth/v1/token');assert.equal(r.method(),'POST');return route.fulfill({status:400,contentType:'application/json',body:'{"error":"invalid_grant","error_description":"synthetic refusal"}'});}return handler(route,{origin:s.origin,bypass:'synthetic',violations,network,captchaPolicy:policy});});c.on('page',p=>p.on('pageerror',()=>events.scriptErrors++));return {...s,c,network,violations,events,close:async()=>{s.release();await browser.close();s.close()}};}
const args=s=>({context:s.c,origin:s.origin,email:'synthetic@example.invalid',password:'synthetic-noncredential',next:'/briefcase'});
test('actual compiled successor form: pre-hydration controls refuse submission and native method is POST',async()=>{const s=await setup(old.handleResumeRequest,{safety:false});try{const p=await s.c.newPage();await p.goto(s.origin+'/expungement-ai/sign-in?mode=signin&next=%2Fbriefcase',{waitUntil:'domcontentloaded'});await s.arrived;assert.equal(await p.locator('input[name=email]').isDisabled(),true);assert.equal(await p.locator('input[name=password]').isDisabled(),true);assert.equal(await p.getByRole('button',{name:'Sign in',exact:true}).isDisabled(),true);assert.equal(await p.locator('form').getAttribute('method'),'post');assert.equal(s.events.auth,0);assert.deepEqual(s.events.native,[]);}finally{await s.close()}});
test('real initialization + fetch/fulfill: readiness precedes credentials, application handles single submit and issues auth POST; expected scripts remain physically blocked',async()=>{const s=await setup();try{const proofs=[];const pending=signInWithRealForm({...args(s),observe:p=>proofs.push(p)});const outcome=assert.rejects(pending,/sanitized sign-in diagnostics/);await s.arrived;const p=s.c.pages()[0];await p.waitForSelector('input[name=email]');assert.equal(await p.locator('input[name=email]').inputValue(),'');assert.equal(await p.locator('input[name=password]').inputValue(),'');assert.equal(s.events.auth,0);s.release();await outcome;const proof=proofs.at(-1);assert.equal(proof.interactive,true);assert.equal(proof.inputPresence,true);assert.equal(proof.authRequestObserved,true);assert.equal(proof.authResponseObserved,true);assert.equal(proof.scriptErrors,0);assert.equal(proof.documentRequests,1);assert.deepEqual(proof.submitEvents,[{handledByApplication:true,nativeFallbackBlocked:false,emailPresent:true,passwordPresent:true}]);assert.equal(s.events.auth,1);assert.deepEqual(s.events.native,[]);assert.deepEqual(s.violations,[]);assert.equal(s.network.counts['expected_block:vercel_toolbar_loader'],1);assert.equal(s.network.counts['expected_block:optional_sign_in_turnstile_loader'],1);assert.ok(s.requests.every(r=>r.bypass&&r.toolbar));assert.ok(!JSON.stringify(proofs).includes(args(s).password));assert.ok(!JSON.stringify(proofs).includes(args(s).email));console.log(JSON.stringify({case:'interactive-form',proof,network:s.network.counts,successfulAuthFabricated:false}));}finally{await s.close()}});
test('harness defense still blocks a deliberately re-enabled pre-hydration form',async()=>{const s=await setup();try{const p=await s.c.newPage();await p.goto(s.origin+'/expungement-ai/sign-in?mode=signin&next=%2Fbriefcase',{waitUntil:'domcontentloaded'});await s.arrived;await p.evaluate(()=>{document.querySelector('fieldset').disabled=false;document.querySelector('button[type=submit]').disabled=false;});await p.locator('input[name=email]').fill(args(s).email);await p.locator('input[name=password]').fill(args(s).password);await p.getByRole('button',{name:'Sign in',exact:true}).click();assert.deepEqual(await p.evaluate(()=>window.__rcapSignInSafety),[{handledByApplication:false,nativeFallbackBlocked:true,emailPresent:true,passwordPresent:true}]);assert.deepEqual(s.events.native,[]);assert.equal(s.events.auth,0);}finally{await s.close()}});
test('readiness is non-vacuous: attached but broken real visibility handler refuses before filling or auth',async()=>{const s=await setup();try{s.release();const original=s.c.newPage.bind(s.c);s.c.newPage=async()=>{const p=await original();p.setDefaultTimeout(700);const go=p.goto.bind(p);p.goto=async(...a)=>{const r=await go(...a);await p.waitForFunction(()=>document.documentElement.dataset.expungementAiLocale);await p.evaluate(()=>{const b=document.querySelector('input[name=password]').parentElement.querySelector('button');const k=Object.keys(b).find(k=>k.startsWith('__reactProps$'));b[k].onClick=()=>{};});return r};return p};const proofs=[];await assert.rejects(signInWithRealForm({...args(s),observe:p=>proofs.push(p)}));assert.equal(proofs.at(-1).interactive,false);assert.equal(proofs.at(-1).inputPresence,false);assert.equal(s.events.auth,0);}finally{await s.close()}});
test('semantic exact sign-in context: reordered/encoded query accepts optional block; lost native form context remains refused',async()=>{for(const [query,expected]of [['next=/briefcase&mode=signin',true],['mode=signin&next=%2fbriefcase',true],['mode=signin&next=%2Fbriefcase&next=%2Fbriefcase',false],['mode=create&next=%2Fbriefcase',false]]){const s=await setup();try{s.release();const p=await s.c.newPage();await p.goto(s.origin+'/expungement-ai/sign-in?'+query);await p.waitForFunction(()=>Boolean(document.getElementById('cloudflare-turnstile-script')));await p.waitForFunction(()=>document.readyState==='complete');assert.equal(Boolean(s.network.counts['expected_block:optional_sign_in_turnstile_loader']),expected);if(!expected)assert.ok(s.violations.length>0);}finally{await s.close()}}});
test('transport comparison: real hydrated form initiates auth under both continue and fetch/fulfill, with zero script errors',async()=>{
 for(const transport of ['continue','fetch_fulfill']){const handler=transport==='fetch_fulfill'?handleResumeRequest:async(route,options)=>{if(new URL(route.request().url()).origin===options.origin)return route.continue({headers:{...route.request().headers(),'x-vercel-protection-bypass':'synthetic','x-vercel-skip-toolbar':'1'}});return handleResumeRequest(route,options)};const s=await setup(handler);try{s.release();const proofs=[];await assert.rejects(signInWithRealForm({...args(s),observe:p=>proofs.push(p)}));assert.equal(s.events.auth,1);assert.equal(s.events.scriptErrors,0);assert.equal(proofs.at(-1).interactive,true);assert.equal(proofs.at(-1).authRequestObserved,true);console.log(JSON.stringify({transport,authRequests:1,scriptErrors:0,credentialsInNavigation:false}));}finally{await s.close()}}
});
test('caller installs safeguards in every context and preserves exact identity checks and sanitized failure routing',()=>{
 const source=fs.readFileSync('scripts/rcap-clinic-resume-browser-ports.mjs','utf8');assert.match(source,/await installSignInSafety\(c\)/);assert.match(source,/return signInWithRealForm\(\{context:c,origin,email,password,next,observe:/);assert.match(source,/assert.equal\(signed.id,RESUME.owner\)/);assert.match(source,/assert.equal\(signed.id,RESUME.stranger\)/);assert.match(fs.readFileSync('scripts/rcap-hosted-clinic-resume.mjs','utf8'),/assert.deepEqual\(violations,\[\]/);
});
test('toolbar cached tag remains physically blocked over later exact resume navigations',async()=>{const s=await setup();try{s.release();const p=await s.c.newPage();for(const pathname of ['/briefcase','/briefcase/6e7a0013-f372-438d-9454-6ba6451b290c','/clinic/staff/77000000-0000-4000-8000-000000000055/queue','/clinic/mississippi-volunteer-lawyers-demo']){await p.goto(s.origin+pathname);}// Fixture intentionally renders the real form on these URLs; optional widget outside sign-in MUST refuse.
 assert.equal(s.network.counts['expected_block:vercel_toolbar_loader'],4);assert.ok(s.violations.every(v=>v.includes('turnstile')));assert.ok(s.requests.every(r=>r.toolbar&&r.bypass));}finally{await s.close()}});
test('mutation control: deleting the observable readiness check fails the broken-handler refusal test on the real component',async()=>{
 const src=fs.readFileSync(new URL('./rcap-clinic-resume-sign-in.mjs',import.meta.url),'utf8');
 const first=src.indexOf("  await page.getByRole('button',{name:'Show password'"),last=src.indexOf('  assert.equal(proof.scriptErrors',first);assert.ok(first>0&&last>first);
 const mutant=await import('data:text/javascript;base64,'+Buffer.from((src.slice(0,first)+src.slice(last)).replace("'./rcap-clinic-resume-network-policy.mjs'",JSON.stringify(new URL('./rcap-clinic-resume-network-policy.mjs',import.meta.url).href))).toString('base64'));
 const s=await setup(handleResumeRequest,{install:mutant.installSignInSafety});try{s.release();const original=s.c.newPage.bind(s.c);s.c.newPage=async()=>{const p=await original();const go=p.goto.bind(p);p.goto=async(...a)=>{const r=await go(...a);await p.waitForFunction(()=>document.documentElement.dataset.expungementAiLocale);await p.evaluate(()=>{const b=document.querySelector('input[name=password]').parentElement.querySelector('button'),k=Object.keys(b).find(k=>k.startsWith('__reactProps$'));b[k].onClick=()=>{};});return r};return p};const proofs=[];await assert.rejects(mutant.signInWithRealForm({...args(s),observe:p=>proofs.push(p)}));assert.throws(()=>assert.equal(proofs.at(-1).interactive,false),'removed guard must make regression red');assert.equal(s.events.auth,1,'mutant reaches auth instead of refusing before credentials');}finally{await s.close()}
});
