import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {startEphemeralPg} from './lib/rcap-ephemeral-pg.mjs';
import {RESUME as r,CHECKPOINT as c,queuePrivacySql,assertQueuePrivacyPrerequisites,exactSessionClosureSql} from './rcap-clinic-resume-contract.mjs';
const migration=fs.readFileSync('supabase/migrations/20260825122000_clinic_mode_accounting_reporting.sql','utf8');
function canonical(name){const start=migration.indexOf(`create or replace function public.${name}(`);assert.ok(start>=0);return migration.slice(start,migration.indexOf('create or replace function public.',start+1));}
test('canonical queue: active staff visible; expired staff authorized/hidden; admin durable; wrong tenant and missing permission denied; expired closure idempotent',()=>{
 const db=startEphemeralPg();try{
 db.sql(`create table clinic_events(id uuid,partner_slug text);create table partner_users(id uuid,auth_user_id uuid,status text,role text,partner_slug text);create table clinic_event_staff(event_id uuid,status text,permissions text[],partner_user_id uuid);create table clinic_assisted_sessions(id uuid,event_id uuid,participant_user_id uuid,screening_session_id uuid,status text,expires_at timestamptz,ended_at timestamptz,ended_reason text);create table clinic_cases(id uuid,event_id uuid,participant_user_id uuid,queue_status text,route_disposition text,jurisdiction text,court_identity_verified boolean,county_name text,court_name text,follow_up_due_at timestamptz,last_activity_at timestamptz,assisted_session_id uuid,matter_id uuid,screening_session_id uuid);create table clinic_event_audit(event_id uuid,actor_user_id uuid,action text,target_type text,target_id uuid,metadata jsonb);`);
 for(const name of ['clinic_actor_can_event','clinic_get_event_queue','clinic_end_assisted_session'])db.sql(canonical(name));
 db.sql(`insert into clinic_events values('${r.event}','mvl-demo');insert into partner_users values('${c.staffPartnerUser}','${c.staff}','active','partner_staff','mvl-demo'),('${c.adminPartnerUser}','${c.admin}','active','partner_admin','mvl-demo');insert into clinic_event_staff values('${r.event}','approved',array['assist','queue'],'${c.staffPartnerUser}');insert into clinic_assisted_sessions values('${r.assisted}','${r.event}','${r.owner}','${r.session}','active',now()+interval '1 hour',null,null);insert into clinic_cases(id,event_id,participant_user_id,queue_status,route_disposition,jurisdiction,last_activity_at,assisted_session_id,matter_id,screening_session_id) values('${r.clinicCase}','${r.event}','${r.owner}','packet_ready','packet','MS',now(),'${r.assisted}','${r.item}','${r.session}');`);
 const visible=actor=>db.scalar(`select count(*) from public.clinic_get_event_queue('${r.event}','${actor}') where id='${r.clinicCase}'`);
 assert.equal(visible(c.staff),'1','active ordinary staff sees exact case');
 db.sql(`update clinic_assisted_sessions set expires_at='2026-09-26T02:58:28.570261Z'`);
 // Use the fixture's clock-independent expired timestamp for canonical testing.
 db.sql(`update clinic_assisted_sessions set expires_at=now()-interval '1 hour'`);
 assert.equal(db.scalar(`select clinic_actor_can_event('${r.event}','${c.staff}','queue')`),'t');assert.equal(visible(c.staff),'0','authorized ordinary staff cannot see expired case');assert.equal(visible(c.admin),'1','same-partner admin sees durable case');assertQueuePrivacyPrerequisites(db.json(queuePrivacySql(r.project)));
 db.sql(`update partner_users set partner_slug='other-tenant' where id='${c.staffPartnerUser}'`);assert.throws(()=>visible(c.staff));db.sql(`update partner_users set partner_slug='mvl-demo' where id='${c.staffPartnerUser}';update clinic_event_staff set permissions=array['assist']`);assert.throws(()=>visible(c.staff));db.sql(`update clinic_event_staff set permissions=array['assist','queue']`);
 const mutant=canonical('clinic_get_event_queue').replace('and s.expires_at>now()','');assert.notEqual(mutant,canonical('clinic_get_event_queue'));db.sql(mutant);assert.throws(()=>assert.equal(visible(c.staff),'0'),'removing expiry must fail privacy regression');db.sql(canonical('clinic_get_event_queue'));
 const expiry=db.scalar('select expires_at from clinic_assisted_sessions');const closure=exactSessionClosureSql(r.project,'Roger:clinic-resume:36211668984:close-exact-lost-cookie-session');db.sql(closure);assert.equal(db.scalar('select status from clinic_assisted_sessions'),'reset');assert.equal(db.scalar('select ended_reason from clinic_assisted_sessions'),'staff_reset');assert.equal(db.scalar('select ended_at is not null from clinic_assisted_sessions'),'t');assert.equal(db.scalar('select expires_at from clinic_assisted_sessions'),expiry);
 assert.equal(db.scalar(`select count(*) from clinic_event_audit where action='assisted_session_ended' and actor_user_id='${r.owner}' and event_id='${r.event}' and target_id='${r.assisted}' and metadata->>'reason'='staff_reset'`),'1');db.sql(closure);assert.equal(db.scalar('select count(*) from clinic_event_audit'),'1','second closure is idempotent');
 }finally{db.stop();}
});
