// Auto-generated by scripts/generate-all50-state-pack-batch.mjs.
// Build-first metadata is sourced from private/Nationwide Record Clearing.
// QA, visual review, counsel review, and source freshness review are tracked
// separately and do not block ordinary RCAP build work.

export const oklahomaAll50BuildMetadata = {
  "jurisdiction": {
    "code": "OK",
    "name": "Oklahoma",
    "slug": "oklahoma",
    "sourceFolders": [
      "LegalEase Oklahoma"
    ]
  },
  "products": [
    "record_clearing_guidance_packet",
    "custom_pleading_or_state_pack_draft"
  ],
  "pathways": [
    {
      "id": "record_clearing_review",
      "label": "Oklahoma record-clearing review",
      "output": "guidance_packet",
      "reviewRequiredBeforeLive": true
    },
    {
      "id": "custom_pleading",
      "label": "Oklahoma custom pleading draft",
      "output": "custom_pleading_or_state_pack_draft",
      "reviewRequiredBeforeLive": true
    }
  ],
  "requiredUserInputs": [
    "participant_full_legal_name",
    "date_of_birth_if_required_by_selected_form",
    "contact_information",
    "case_number",
    "court_or_agency_name",
    "county_or_filing_location",
    "charge_or_record_description",
    "case_outcome",
    "disposition_date_if_known",
    "sentence_completion_or_supervision_status_if_applicable",
    "records_or_background_report_if_available"
  ],
  "filingDestinationGuidance": [
    "Use the court, clerk, agency, or official filing destination identified in the selected Nationwide resource packet or official form.",
    "If the correct filing destination is unclear, keep the packet guidance-only and flag the state for post-build QA/attorney review.",
    "Do not invent clerk addresses, agency addresses, local fees, or service rules."
  ],
  "filingSteps": [
    "Confirm the record-clearing pathway from the participant's answers and available source packet.",
    "Collect required user inputs and mark unknown information plainly.",
    "Select official form overlay, custom pleading, or guidance-only fallback.",
    "Generate internal review packet and source inventory artifact.",
    "Route to QA, visual review when an official PDF overlay exists, and counsel review before live use."
  ],
  "feesCopiesServiceNotes": [
    "Use fee, copy, and service notes only when present in the Nationwide source packet or official form.",
    "When fee/copy/service information is absent or unclear, state that the participant should verify current local requirements with the filing court or agency.",
    "Do not treat missing fee data as a blocker for guidance fallback generation."
  ],
  "officialFormInventory": [],
  "resourcePacketInventory": [
    {
      "fileName": "Facets of Expungement of Criminal Records in Oklahoma - Oklahoma Bar Association.html",
      "relativePath": "LegalEase Oklahoma/Facets of Expungement of Criminal Records in Oklahoma - Oklahoma Bar Association.html",
      "classification": "reference",
      "sha256": "189922562fb855c91a674e4f556fd2a598807619948e2d573bec5ff0f408c0c9",
      "sizeBytes": 103570
    },
    {
      "fileName": "Oklahoma Expungement Reference for Wilma.rtf",
      "relativePath": "LegalEase Oklahoma/Oklahoma Expungement Reference for Wilma.rtf",
      "classification": "reference",
      "sha256": "f2ee0505feb05451bf5020048ecc57b485950db72d9607bf786d1437f8711c9a",
      "sizeBytes": 62478
    },
    {
      "fileName": "Oklahoma Statutes §22-18a (2025) - Petition to Expunge Records and Order to Expunge Records. : 2025.html",
      "relativePath": "LegalEase Oklahoma/Oklahoma Statutes §22-18a (2025) - Petition to Expunge Records and Order to Expunge Records. : 2025.html",
      "classification": "reference",
      "sha256": "edada8618ef060157182f4d819abc46400e74687f6b2fd6e936204fe213a0f6a",
      "sizeBytes": 69057
    }
  ],
  "customPleadingSupport": {
    "supported": true,
    "status": "draft_config_allowed",
    "notes": "Pleading-style draft support may be built from Nationwide resources and coded state-pack data where available."
  },
  "guidanceOnlyFallback": {
    "supported": true,
    "label": "Oklahoma record-clearing guidance fallback",
    "status": "built",
    "notes": "Available for internal review even when official forms or pleading templates need more work."
  },
  "disclaimer": "This RCAP build artifact is for internal document-preparation and review workflows. It is not legal advice, does not guarantee eligibility or outcomes, and is not approved for live use until QA, counsel, and any required visual review pass.",
  "buildStatusMetadata": {
    "buildStatus": "state_built",
    "statusHistory": [
      "not_started",
      "nationwide_resources_found",
      "resource_packet_ingested",
      "state_pack_built",
      "pleading_packet_rendered",
      "guidance_packet_rendered",
      "state_built"
    ],
    "reviewStatuses": {
      "qa": "pending",
      "visual": "not_applicable",
      "counsel": "pending",
      "sourceFreshness": "pending"
    },
    "loops": [
      {
        "id": "nationwide_folder_ingestion_loop",
        "status": "completed"
      },
      {
        "id": "all_state_build_loop",
        "status": "completed"
      },
      {
        "id": "official_pdf_overlay_factory_loop",
        "status": "not_applicable_no_pdf"
      },
      {
        "id": "field_map_retry_loop",
        "status": "not_applicable_no_pdf"
      },
      {
        "id": "custom_pleading_factory_loop",
        "status": "draft_ready"
      },
      {
        "id": "guidance_packet_loop",
        "status": "completed"
      },
      {
        "id": "packet_render_qa_loop",
        "status": "pending_review"
      },
      {
        "id": "review_artifact_loop",
        "status": "completed"
      },
      {
        "id": "integration_preview_loop",
        "status": "internal_preview_ready"
      },
      {
        "id": "official_forms_watcher_loop",
        "status": "source_tracked"
      }
    ],
    "liveRouting": {
      "approvedForLive": false,
      "live": false,
      "note": "Build-first state output is internal review material only."
    }
  },
  "buildIssues": []
} as const;
