export const okEligibilityRules = [
  "Oklahoma uses the word expungement, but in most adult criminal-record contexts it means sealing, not automatic destruction. A Section 18/19 expungement can seal criminal records and related public civil records arising from the same arrest, transaction, or occurrence; Oklahoma distinguishes fully sealed records (not available to the public or law enforcement, though OSBI may retain them for research/statistical purposes) from partially sealed records (hidden from the public but available to law enforcement).",
  "Section 18/19 adult expungement under 22 O.S. §§ 18-19 covers categories including acquittal, conviction reversed and dismissed, DNA factual innocence, arrest with no charges filed, all charges dismissed without a deferred judgment, deferred/delayed-sentence dismissals, eligible misdemeanor and felony convictions, a nonviolent felony reclassified as a misdemeanor, full gubernatorial pardons, and identity-theft / wrong-person records.",
  "Section 18/19 waiting periods: misdemeanor deferred dismissal 1 year; nonviolent felony (not listed in 57 O.S. § 571) deferred dismissal 5 years; up to two felony deferred dismissals 10 years; misdemeanor fine-only under $501 with no incarceration is eligible once the fine is paid; other misdemeanor conviction 5 years after the last misdemeanor sentence; one nonviolent felony conviction 5 years after completion (and no separate misdemeanor conviction in the last 7 years); not more than two felony convictions (none listed in 21 O.S. § 13.1 or requiring sex-offender registration) 10 years after completion; a nonviolent felony reclassified as a misdemeanor 30 days after completion or commutation with restitution paid and any ordered treatment completed.",
  "Section 991(c) deferred-sentence court-record expungement under 22 O.S. § 991c: on successful completion of a deferred judgment and payment of ordered fines, fees, and assessments, the person is discharged without a judgment of guilt, the plea is expunged from the court record, and the charge is dismissed with prejudice; per OSBI this does not remove the arrest record, which requires separate Section 18/19 relief.",
  "Section 19 procedure under 22 O.S. § 19: the qualified person petitions the district court where the arrest information is located; the court sets a hearing with 30 days' notice to the prosecuting agency, arresting agency, OSBI, and any other relevant agency, and may seal records if the harm to privacy or danger of unwarranted adverse consequences outweighs the public interest in retaining them. After sealing, the official actions are deemed never to have occurred. Section 19 does not authorize physical destruction of criminal-justice records.",
  "Identity-theft / wrong-person expungement under 22 O.S. § 19a and the Section 18 identity-theft category: available where the person was charged, arrested, or subject to a warrant for a crime committed by another person who used their name or identifying information without consent.",
  "Victim Protective Order record expungement under 22 O.S. § 60.18 seals certain VPO court records from public inspection (but not from law enforcement, the court, or the district attorney) in defined categories: an ex parte order terminated by dismissal/denial/failure to appear after 90 days, a plaintiff who failed to appear for the full hearing after 90 days, an order vacated after 3 years, or a deceased party.",
  "Juvenile record expungement under 10A O.S. § 2-6-109: available after completion of informal adjustment, deferred adjudication, probation, or custody, with the case dismissed or closing, no pending adult arrest or charge, and all court costs, restitution, fines, and ordered requirements completed.",
  "Human-trafficking-survivor relief under 22 O.S. § 19c covers prostitution-related records where the offense was committed as a result of human-trafficking victimization; it can be sought by motion or petition and should be routed to legal aid or an attorney.",
  "Clean Slate automatic sealing under 22 O.S. §§ 18(C) and 19(B) directs OSBI to identify eligible records monthly, notify the prosecutor/arresting agency, and allow a 45-day objection window before unobjectioned cases go to courts for signed orders; implementation is phased and not guaranteed, so a petition remains available if automatic sealing has not occurred."
];
