import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {assertForwardAliasScope,assertForwardOwner,forwardOwnerNote,forwardAuthorization,assertForwardPhase,validateForwardNativeDocuments,FORWARD_PHASES} from './verify-forward-production-successor.mjs';
const held={applicationSha:'a'.repeat(40),workerSourceSha:'b'.repeat(40),workerDigest:'sha256:'+'c'.repeat(64),workerInputFingerprint:'sha256:'+'d'.repeat(64),toolsSha:'e'.repeat(40),productionAuthorized:false,productionAuthorization:null,hostedAdmission:{deploymentId:'dpl_Synthetic',productionRollback:'dpl_Predecessor',runId:123456789,capturedAt:new Date(Date.now()-60000).toISOString(),productionAliases:[{alias:'synthetic.invalid',redirect:null}]}};
const owner={schemaVersion:'rcap-forward-owner-authorization/v1',authorized:true,recordedBy:'Roger Roman',recordedAt:new Date(Date.now()-30000).toISOString(),productionProjectRef:'wwtwtsmywnckfkdaqqeg',...Object.fromEntries(['applicationSha','workerSourceSha','workerDigest','workerInputFingerprint','toolsSha'].map(k=>[k,held[k]])),stagedDeploymentId:held.hostedAdmission.deploymentId,rollbackDeploymentId:held.hostedAdmission.productionRollback,productionAliases:held.hostedAdmission.productionAliases,hostedRunId:held.hostedAdmission.runId,phases:FORWARD_PHASES,maxActivationAttempts:1,maxPublicVerificationAttempts:1,note:forwardOwnerNote(held)};
const smoke={runId:222222222,receiptSha256:'f'.repeat(64)};
function candidate(receipts={},states={activation:'authorized_not_executed',publicVerification:'authorized_not_executed'}){return {productionAuthorized:true,productionProjectRef:owner.productionProjectRef,productionAuthorization:forwardAuthorization(owner,receipts,states),forwardProduction:{owner,receipts,states}};}
test('future explicit authorization reaches smoke while held predecessor remains unauthorized',()=>{assertForwardOwner(owner,held);assertForwardPhase(candidate(),held,'smoke');assert.throws(()=>assertForwardPhase(held,held,'smoke'));});
test('only fresh native smoke enables activation; consumed activation enables worker/public checks',()=>{assert.throws(()=>assertForwardPhase(candidate(),held,'activate'));assertForwardPhase(candidate({smoke}),held,'activate');const c=candidate({smoke,activate:{runId:333333333}},{activation:'consumed_successfully',publicVerification:'authorized_not_executed'});assertForwardPhase(c,held,'production_worker_deploy');assertForwardPhase(c,held,'public_verify');assert.throws(()=>assertForwardPhase(c,held,'activate'));assert.throws(()=>assertForwardPhase(c,held,'smoke'));const closed=candidate({...c.forwardProduction.receipts,public_verify:{runId:444444444}},{activation:'consumed_successfully',publicVerification:'consumed_successfully'});assert.throws(()=>assertForwardPhase(closed,held,'public_verify'));});
for(const [key,value]of Object.entries({applicationSha:'wrong',workerSourceSha:'wrong',workerDigest:'wrong',workerInputFingerprint:'wrong',toolsSha:'wrong',stagedDeploymentId:'dpl_Old',rollbackDeploymentId:'dpl_Wrong',productionAliases:[],hostedRunId:1,recordedBy:'wrong',note:'old production approval',phases:['clinic_migrate'],maxActivationAttempts:2,recordedAt:'2026-09-20T00:00:00.000Z'}))test(`future approval rejects wrong ${key}`,()=>assert.throws(()=>assertForwardOwner({...owner,[key]:value},held)));
for(const phase of ['preflight','restage','clinic_migrate','legal_aid_keys_create','production_packet_canary'])test(`future release refuses unrelated ${phase}`,()=>assert.throws(()=>assertForwardPhase(candidate({smoke}),held,phase)));
test('held acceptance and arbitrary flag flips cannot imply approval',()=>{const c=candidate();c.productionAuthorization={historical:true};assert.throws(()=>assertForwardPhase(c,held,'smoke'));const c2=candidate({activate:{runId:1}},{activation:'authorized_not_executed',publicVerification:'authorized_not_executed'});assert.throws(()=>assertForwardPhase(c2,held,'activate'));});
const receipt={schemaVersion:'rcap-production-canary-smoke/v1',passed:true,...Object.fromEntries(['applicationSha','workerSourceSha','workerDigest','productionProjectRef','stagedDeploymentId','rollbackDeploymentId'].map(k=>[k,owner[k]])),finishedAt:new Date(Date.now()-10000).toISOString(),transactionalFixtureRolledBack:true,productionDatabasePersistentlyMutated:false,realParticipantRecordsCreated:false,realChargesCreated:false,workerRun:false,aliasChanged:false,deploymentTriggered:false};const receiptBytes=Buffer.from(JSON.stringify(receipt));
const ref={runId:222222222,workflowSourceSha:held.toolsSha,jobId:111,artifactId:333,receiptSha256:createHash('sha256').update(receiptBytes).digest('hex')};
const docs={run:{id:ref.runId,head_sha:ref.workflowSourceSha,path:'.github/workflows/rcap-f1-ephemeral-staging.yml',event:'workflow_dispatch',head_branch:'captain-release',run_attempt:1,conclusion:'success',status:'completed',repository:{full_name:'Roger-LegalEase/legalease-partner-dashboard-clean'}},jobs:{jobs:[{id:111,run_id:ref.runId,head_sha:ref.workflowSourceSha,run_attempt:1,conclusion:'success',status:'completed',steps:['Verify the exact frozen identity and image-input equivalence','Run the bounded no-alias Production canary smoke','Upload the immutable Production preflight evidence'].map(name=>({name,conclusion:'success'}))}]},artifact:{id:333,expired:false,workflow_run:{id:ref.runId,head_sha:ref.workflowSourceSha},digest:'sha256:synthetic-archive'},receipt,receiptBytes,archiveDigest:'sha256:synthetic-archive'};
test('native successful smoke binds workflow job archive and exact post-owner tuple',()=>validateForwardNativeDocuments(docs,ref,owner,'smoke'));
for(const [name,edit]of [['wrong workflow',d=>d.run.head_sha='wrong'],['wrong job',d=>d.jobs.jobs[0].id++],['wrong native digest',d=>d.artifact.digest='wrong'],['failed required step',d=>d.jobs.jobs[0].steps[1].conclusion='failure'],['old production receipt',d=>d.receipt.applicationSha='wrong'],['stale receipt',d=>d.receipt.finishedAt='2026-09-20T00:00:00.000Z'],['live writes',d=>d.receipt.productionDatabasePersistentlyMutated=true]])test(`native ${name} refuses`,()=>{const d=structuredClone(docs);edit(d);assert.throws(()=>validateForwardNativeDocuments(d,ref,owner,'smoke'));});

test('production alias scope rejects additional domains and redirect changes',()=>{const aliases=[{alias:'synthetic.invalid',redirect:null}];assertForwardAliasScope(aliases,aliases,['synthetic.invalid']);assert.throws(()=>assertForwardAliasScope(aliases,aliases,['unapproved.invalid']));assert.throws(()=>assertForwardAliasScope([{alias:'synthetic.invalid',redirect:'elsewhere.invalid'}],aliases,['synthetic.invalid']));});
import {assertForwardSingleAttempt} from './forward-production-single-attempt.mjs';
function attemptTransport(priorStep=null){const current={id:1000,head_sha:held.toolsSha,run_attempt:1,event:'workflow_dispatch',path:'.github/workflows/rcap-f1-ephemeral-staging.yml',head_branch:'captain-release',repository:{full_name:'Roger-LegalEase/legalease-partner-dashboard-clean'}};return async(url,options)=>{assert.equal(options.method,'GET');assert.equal(options.redirect,'error');const body=url.includes('/jobs?')?{jobs:[{steps:priorStep?[priorStep]:[]}]}:url.includes('/workflows/')?{workflow_runs:[{id:999,created_at:new Date().toISOString()},current]}:current;return new Response(JSON.stringify(body),{status:200});};}
const attemptEnv={RCAP_PRODUCTION_PHASE:'activate',GITHUB_TOKEN:'synthetic-read-only',GITHUB_RUN_ID:'1000',GITHUB_SHA:held.toolsSha};
test('first native activation attempt passes GET-only inventory',()=>assertForwardSingleAttempt(candidate({smoke}),{env:attemptEnv,fetchImpl:attemptTransport()}));
for(const [status,conclusion]of [['completed','failure'],['completed','success'],['in_progress',null]])test(`prior ${conclusion??status} native activation consumes one attempt`,()=>assert.rejects(assertForwardSingleAttempt(candidate({smoke}),{env:attemptEnv,fetchImpl:attemptTransport({name:'Activate the exact staged Production deployment with rollback protection',status,conclusion})})));
test('unavailable native attempt inventory fails closed',()=>assert.rejects(assertForwardSingleAttempt(candidate({smoke}),{env:{...attemptEnv,GITHUB_TOKEN:''},fetchImpl:()=>assert.fail('no credentials must not issue request')})));
test('actual public-verification receipt schema closes without claiming mutation',()=>{const d=structuredClone(docs);d.receipt={schemaVersion:'rcap-production-public-verify/v1',passed:true,...Object.fromEntries(['applicationSha','workerSourceSha','workerDigest','productionProjectRef','rollbackDeploymentId'].map(k=>[k,owner[k]])),activatedDeploymentId:owner.stagedDeploymentId,finishedAt:receipt.finishedAt,originPersisted:false,secretsPersisted:false,mutations:Object.fromEntries(['deploymentTriggered','productionAliasChanged','environmentVariableChanged','productionDatabaseMutated','accountCreated','checkoutOpened','realChargesCreated'].map(k=>[k,false]))};d.receiptBytes=Buffer.from(JSON.stringify(d.receipt));const r={...ref,receiptSha256:createHash('sha256').update(d.receiptBytes).digest('hex')};d.jobs.jobs[0].steps=['Require current release and separate public-verification authorization','Verify the activated release on the public domain','Upload the public verification evidence'].map(name=>({name,conclusion:'success'}));validateForwardNativeDocuments(d,r,owner,'public_verify');d.receipt.mutations.accountCreated=true;assert.throws(()=>validateForwardNativeDocuments(d,r,owner,'public_verify'));});
import fs from 'node:fs';
test('worker startup supplies history and dependencies before the strict identity gate',()=>{const workflow=fs.readFileSync(new URL('../../.github/workflows/deploy-rcap-render-worker-production.yml',import.meta.url),'utf8');assert(/actions\/checkout@v4\s+with:\s+fetch-depth: 0/.test(workflow));assert(workflow.indexOf('run: npm ci')<workflow.indexOf('name: Refuse any worker identity'));});
test('activation and public executors enforce native one-attempt inventory before service reads',()=>{for(const name of ['rcap-production-activate.mjs','rcap-production-public-verify.mjs']){const source=fs.readFileSync(new URL('../'+name,import.meta.url),'utf8');assert(source.includes('await assertForwardSingleAttempt(RELEASE_CANDIDATE);'));}});
