import test from 'node:test';
import assert from 'node:assert/strict';
import {assertForwardTuple,assertForwardHosted} from './verify-pinned-worker-successor.mjs';
// All identities here are synthetic local fixtures, never release evidence.
const expected={applicationSha:'a'.repeat(40),workerSourceSha:'b'.repeat(40),workerDigest:'sha256:'+'c'.repeat(64),workerInputFingerprint:'sha256:'+'d'.repeat(64),toolsSha:'e'.repeat(40),publication:{runId:1,workflowSourceSha:'f'.repeat(40),artifactId:2,digest:'sha256:'+'c'.repeat(64)},readOnlyImageAcceptance:{runId:3,jobId:4,workflowSourceSha:'1'.repeat(40),digest:'sha256:'+'c'.repeat(64)}};
const record={...expected,productionAuthorized:false,productionAuthorization:null,deploymentAuthorized:false,clinicDispatchReady:false,runtimeAccepted:true,workerRebuildRequired:false,resume:null,previewExecution:'held'};
const hosted={...expected,capturedAt:new Date().toISOString(),workflowSourceSha:'2'.repeat(40),runId:5,workerRollbackVerified:true,sharedHostRoutingMethod:'frozen-proxy-map-and-staged-targets',deploymentId:'dpl_synthetic',productionRollback:'dpl_3j4Dr4GHyXmwmrFCTZ6orNNNP7sc',productionAliasesUnchanged:true,autoAssignCustomDomains:false,signupVerified:true,sharedHostRoutingVerified:true,productionWrites:false,target:'production',readyState:'READY',liveAuthCalls:0,productionAuthorized:false};
test('forward tuple binds distinct application, worker, publication and acceptance identities without activation',()=>{assertForwardTuple(record,expected);assertForwardHosted(hosted,expected);});
for(const key of ['applicationSha','workerSourceSha','workerDigest','workerInputFingerprint','toolsSha'])test(`wrong ${key} and stale hosted identity rejected`,()=>{assert.throws(()=>assertForwardTuple({...record,[key]:'wrong'},expected));assert.throws(()=>assertForwardHosted({...hosted,[key]:'wrong'},expected));});
for(const field of ['publication','readOnlyImageAcceptance'])test(`wrong ${field} workflow identity rejected`,()=>assert.throws(()=>assertForwardTuple({...record,[field]:{...record[field],workflowSourceSha:expected.workerSourceSha}},expected)));
test('old authorization and automatically production-authorized held successor rejected',()=>{assert.throws(()=>assertForwardTuple({...record,productionAuthorization:{historical:true}},expected));assert.throws(()=>assertForwardTuple({...record,productionAuthorized:true},expected));assert.throws(()=>assertForwardHosted({...hosted,productionAuthorized:true},expected));});
for(const [key,value]of Object.entries({autoAssignCustomDomains:true,productionAliasesUnchanged:false,productionWrites:true,signupVerified:false,sharedHostRoutingVerified:false,liveAuthCalls:1,target:null,readyState:'ERROR'}))test(`hosted ${key} fails closed`,()=>assert.throws(()=>assertForwardHosted({...hosted,[key]:value},expected)));

test("same-tuple stale hosted evidence rejected",()=>assert.throws(()=>assertForwardHosted({...hosted,capturedAt:new Date(Date.now()-86400001).toISOString()},expected)));
for(const flag of ["migrationReplayAuthorized","housekeepingReplayAuthorized","additionalWorkerPublicationAuthorized","imageAcceptanceRerunAuthorized","hostedFullReady"])test(`held flag ${flag} cannot advance`,()=>assert.throws(()=>assertForwardTuple({...record,[flag]:true},expected)));
