import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {PREVIEW_ADMISSION_SCHEMA,PREVIEW_CREATION_RUN,ACCEPTANCE_PROJECT,assertNativePreviewCreation,assertPreviewDeployment,assertPreviewClosureDocuments} from './preview-closure-contract.mjs';
import {assertForwardHosted} from './verify-pinned-worker-successor.mjs';
import {HOSTED_VERCEL_PROJECT_ID} from '../rcap-hosted-acceptance-vercel-identity.mjs';
const tuple={applicationSha:'a'.repeat(40),workerSourceSha:'b'.repeat(40),workerDigest:'sha256:'+'c'.repeat(64),workerInputFingerprint:'sha256:'+'d'.repeat(64),toolsSha:'e'.repeat(40)};
const aliases=[{alias:'production.invalid',redirect:null}],domains=[{name:'production.invalid',redirect:null,redirectStatusCode:null,gitBranch:null,customEnvironmentId:null}];
const d={id:'dpl_SyntheticPreview',url:'synthetic-preview.vercel.app',projectId:HOSTED_VERCEL_PROJECT_ID,gitSource:{sha:tuple.applicationSha},meta:{rcapApplicationSha:tuple.applicationSha,rcapWorkerSourceSha:tuple.workerSourceSha,rcapWorkerDigest:tuple.workerDigest,rcapWorkerInputFingerprint:tuple.workerInputFingerprint,rcapAcceptanceProjectRef:ACCEPTANCE_PROJECT},target:null,readyState:'READY'};
const names=['Require exact current release or HELD acceptance Preview tuple','Require CURRENT authority except exact HELD acceptance Preview creation','Read the existing sandbox catalog for the replacement Preview','Deploy the frozen application SHA to Vercel Preview','Upload the hosted acceptance evidence'];
const run={id:PREVIEW_CREATION_RUN,head_sha:'f'.repeat(40),status:'completed',conclusion:'success',run_attempt:1,event:'workflow_dispatch',path:'.github/workflows/rcap-f1-ephemeral-staging.yml',repository:{full_name:'Roger-LegalEase/legalease-partner-dashboard-clean'}};
const docs={run,jobs:{jobs:[{run_id:run.id,status:'completed',conclusion:'success',steps:names.map(name=>({name,conclusion:'success'}))}]},artifact:{id:123,name:`rcap-hosted-replace_preview-${run.id}`,workflow_run:{id:run.id,head_sha:run.head_sha},digest:'sha256:'+'1'.repeat(64)},archiveDigest:'sha256:'+'1'.repeat(64),preflight:{schemaVersion:'rcap-hosted-acceptance-preflight/v1',passed:true,acceptanceProjectRef:ACCEPTANCE_PROJECT,cases:{projectIdentity:{status:'ACTIVE_HEALTHY'}}},deploy:{schemaVersion:'rcap-hosted-acceptance-deploy/v1',passed:true,applicationSha:tuple.applicationSha,acceptanceProjectRef:ACCEPTANCE_PROJECT,requiredCases:['deployed_to_preview_not_production','deployment_carries_the_final_application_sha','deployment_carries_the_accepted_worker_binding','bound_to_the_acceptance_supabase_project_only','production_aliases_unchanged','production_environment_variables_unchanged'],failedCases:[],neverPassedProdFlag:true,neverWroteProjectLevelEnv:true,productionBefore:{aliases:[],environmentShape:[]},productionAfter:{aliases:[],environmentShape:[]},deployment:{id:d.id,immutableHostname:d.url,projectId:d.projectId,gitSourceSha:d.gitSource.sha,metadata:d.meta,target:d.target,readyState:d.readyState}},creationCandidate:{...tuple,status:'FORWARD_BOUND_HOSTED_PENDING',productionAuthorized:false}};
const inputs={creationRunId:run.id,deploymentId:d.id,hostname:d.url};
const creation=assertNativePreviewCreation(docs,tuple,inputs);
const admission={schemaVersion:PREVIEW_ADMISSION_SCHEMA,...tuple,capturedAt:new Date().toISOString(),workflowSourceSha:'2'.repeat(40),closureControlSha:'3'.repeat(40),runId:456,deploymentId:d.id,hostname:d.url,projectId:d.projectId,acceptanceProjectRef:ACCEPTANCE_PROJECT,previewCreation:creation,productionRollback:'dpl_3j4Dr4GHyXmwmrFCTZ6orNNNP7sc',productionDeploymentAliases:aliases,productionProjectDomains:domains,productionDeploymentAliasesUnchanged:true,productionProjectDomainsUnchanged:true,productionEnvironmentUnchanged:true,projectLevelProductionEnvironmentMutations:0,autoAssignCustomDomains:false,signupVerified:true,workerRollbackVerified:true,queueSafetyVerified:true,sharedHostRoutingVerified:true,sharedHostRoutingMethod:'frozen-proxy-map-and-staged-targets',productionWrites:false,target:null,readyState:'READY',liveAuthCalls:0,productionAuthorized:false,newDeploymentCreated:false,workerClaims:0,realPayments:0,participantWrites:0};
const evidence={'candidate-ready.json':{id:d.id,url:d.url,target:d.target,readyState:d.readyState,projectId:d.projectId,applicationSha:tuple.applicationSha,meta:d.meta},'candidate-aliases.json':{aliases:[]},'acceptance-project-state.json':{projectRef:ACCEPTANCE_PROJECT,status:'ACTIVE_HEALTHY'},'worker-rollback.json':{passed:true,readOnly:true},'queue-safety.json':{passed:true,readOnly:true,queue:{stale_queued:0,queued:0,claimed:0,terminal_failed:0}},'shared-host-routing.json':{passed:true,source:tuple.applicationSha,cases:[['expungement.ai','/','/expungement-ai'],['legalease.com','/','/static/legalease/index.html'],['legaleasepartner.com','/','/partners']]},'browser-results.json':['en','es'].flatMap(locale=>[375,1440].map(width=>({locale,width,status:'PASS',auth:'MOCKED: NO LIVE AUTH',claim:'MOCKED: NO LIVE CLAIM'}))),'production-aliases-before.json':aliases,'production-aliases-after.json':aliases,'production-project-domains-before.json':domains,'production-project-domains-after.json':domains,'production-environment-before.json':[],'production-environment-after.json':[]};
test('v3 accepts exact native Preview creation and complete read-only closure without Production authority',()=>{assertPreviewDeployment(d,tuple,creation,{aliases,domains});assertForwardHosted(admission,tuple);assertPreviewClosureDocuments(admission,n=>evidence[n]);assert.equal(admission.productionAuthorized,false);});
for(const [key,value]of [['deploymentId','dpl_Wrong'],['hostname','wrong.vercel.app'],['creationRunId',1]])test(`wrong input ${key} refuses`,()=>assert.throws(()=>assertNativePreviewCreation(docs,tuple,{...inputs,[key]:value})));
for(const key of Object.keys(tuple))test(`wrong native ${key} refuses`,()=>assert.throws(()=>assertNativePreviewCreation({...docs,creationCandidate:{...docs.creationCandidate,[key]:'wrong'}},tuple,inputs)));
for(const [key,value]of [['id','dpl_Wrong'],['url','wrong.vercel.app'],['projectId','prj_Wrong'],['target','production'],['readyState','ERROR']])test(`wrong observed Preview ${key} refuses`,()=>assert.throws(()=>assertPreviewDeployment({...d,[key]:value},tuple,creation)));
for(const key of Object.keys(d.meta))test(`wrong observed ${key} refuses`,()=>assert.throws(()=>assertPreviewDeployment({...d,meta:{...d.meta,[key]:'wrong'}},tuple,creation)));
test('native run/artifact mutation refuses',()=>{for(const changed of [{...docs,run:{...run,conclusion:'failure'}},{...docs,artifact:{...docs.artifact,digest:'wrong'}},{...docs,deploy:{...docs.deploy,productionAfter:{aliases:['changed']}}}])assert.throws(()=>assertNativePreviewCreation(changed,tuple,inputs));});
test('Production alias or project-domain attached to Preview refuses',()=>{assert.throws(()=>assertPreviewDeployment(d,tuple,creation,{aliases:[{alias:d.url}],domains}));assert.throws(()=>assertPreviewDeployment(d,tuple,creation,{aliases,domains:[{name:d.url}]}));});
for(const name of Object.keys(evidence))test(`missing ${name} refuses`,()=>assert.throws(()=>assertPreviewClosureDocuments(admission,n=>n===name?undefined:evidence[n])));
for(const name of ['production-aliases-after.json','production-project-domains-after.json','production-environment-after.json'])test(`mutated ${name} refuses`,()=>assert.throws(()=>assertPreviewClosureDocuments(admission,n=>n===name?[{changed:true}]:evidence[n])));
for(const [key,value]of [['target','production'],['capturedAt',new Date(Date.now()-86400001).toISOString()],['productionAuthorized',true],['queueSafetyVerified',false],['workerRollbackVerified',false],['sharedHostRoutingVerified',false],['productionWrites',true],['liveAuthCalls',1],['toolsSha','wrong']])test(`v3 ${key} refuses`,()=>assert.throws(()=>assertForwardHosted({...admission,[key]:value},tuple)));
test('real historical v1/v2 native receipts retain staged Production semantics and bytes',()=>{
 for(const n of ['37460556784','37482645230']){const p=`hosted-acceptance-evidence/successor-closure/${n}/admission.json`;const bytes=fs.readFileSync(p);const h=JSON.parse(bytes);assert(['rcap-readonly-successor-admission/v1','rcap-readonly-successor-admission/v2'].includes(h.schemaVersion));assert.equal(h.target,'production');assertPreviewTargetRefuses(h);assert(bytes.equals(fs.readFileSync(p)));}
 function assertPreviewTargetRefuses(h){assert.throws(()=>assertForwardHosted({...h,capturedAt:new Date().toISOString(),target:null},h),/production/);}
});
