// Auto-generated by scripts/generate-all50-state-pack-batch.mjs.
// Build-first metadata is sourced from private/Nationwide Record Clearing.
// QA, visual review, counsel review, and source freshness review are tracked
// separately and do not block ordinary RCAP build work.

export const westVirginiaAll50BuildMetadata = {
  "jurisdiction": {
    "code": "WV",
    "name": "West Virginia",
    "slug": "west-virginia",
    "sourceFolders": [
      "LegalEase West Virginia"
    ]
  },
  "products": [
    "record_clearing_guidance_packet",
    "official_pdf_overlay_draft",
    "custom_pleading_or_state_pack_draft"
  ],
  "pathways": [
    {
      "id": "record_clearing_review",
      "label": "West Virginia record-clearing review",
      "output": "guidance_packet",
      "reviewRequiredBeforeLive": true
    },
    {
      "id": "official_form_overlay",
      "label": "West Virginia official form overlay draft",
      "output": "official_pdf_overlay_draft",
      "reviewRequiredBeforeLive": true
    },
    {
      "id": "custom_pleading",
      "label": "West Virginia custom pleading draft",
      "output": "custom_pleading_or_state_pack_draft",
      "reviewRequiredBeforeLive": true
    }
  ],
  "requiredUserInputs": [
    "participant_full_legal_name",
    "date_of_birth_if_required_by_selected_form",
    "contact_information",
    "case_number",
    "court_or_agency_name",
    "county_or_filing_location",
    "charge_or_record_description",
    "case_outcome",
    "disposition_date_if_known",
    "sentence_completion_or_supervision_status_if_applicable",
    "records_or_background_report_if_available"
  ],
  "filingDestinationGuidance": [
    "Use the court, clerk, agency, or official filing destination identified in the selected Nationwide resource packet or official form.",
    "If the correct filing destination is unclear, keep the packet guidance-only and flag the state for post-build QA/attorney review.",
    "Do not invent clerk addresses, agency addresses, local fees, or service rules."
  ],
  "filingSteps": [
    "Confirm the record-clearing pathway from the participant's answers and available source packet.",
    "Collect required user inputs and mark unknown information plainly.",
    "Select official form overlay, custom pleading, or guidance-only fallback.",
    "Generate internal review packet and source inventory artifact.",
    "Route to QA, visual review when an official PDF overlay exists, and counsel review before live use."
  ],
  "feesCopiesServiceNotes": [
    "Use fee, copy, and service notes only when present in the Nationwide source packet or official form.",
    "When fee/copy/service information is absent or unclear, state that the participant should verify current local requirements with the filing court or agency.",
    "Do not treat missing fee data as a blocker for guidance fallback generation."
  ],
  "officialFormInventory": [
    {
      "fileName": "SCA-C-903.pdf",
      "relativePath": "LegalEase West Virginia/SCA-C-903.pdf",
      "sha256": "242048f1ff5b2e795ca43900bec6d9c353c59950bffd3c7776374ff1cc6c7035",
      "sizeBytes": 112484
    },
    {
      "fileName": "SCA-C900.pdf",
      "relativePath": "LegalEase West Virginia/SCA-C900.pdf",
      "sha256": "89ff7d2d911406465bd39da947737a3ee262edbcbc98db9a3cedda952598864e",
      "sizeBytes": 204715
    },
    {
      "fileName": "SCA-C906.pdf",
      "relativePath": "LegalEase West Virginia/SCA-C906.pdf",
      "sha256": "8c6ced88c37870359bc38537c4409b2dc99a5ed6fc6b69c9c41d386fa7fe6e8c",
      "sizeBytes": 153424
    },
    {
      "fileName": "SCA-C907.pdf",
      "relativePath": "LegalEase West Virginia/SCA-C907.pdf",
      "sha256": "2a72314146636c4120d87bdfb83f8609e35e9e904eed2f8169bc2375fba30222",
      "sizeBytes": 283289
    },
    {
      "fileName": "SCA-C912.pdf",
      "relativePath": "LegalEase West Virginia/SCA-C912.pdf",
      "sha256": "3f41ed988e72e2aef1ff2142442d5b0321e39e46143a6747925ce9e901a7f59d",
      "sizeBytes": 262858
    }
  ],
  "resourcePacketInventory": [
    {
      "fileName": "West Virginia Expungement Reference for Wilma.rtf",
      "relativePath": "LegalEase West Virginia/West Virginia Expungement Reference for Wilma.rtf",
      "classification": "reference",
      "sha256": "54399edabc53f956771dc7b86571db7ade7e97d4f5fa0f5bfd61da297e50c3d5",
      "sizeBytes": 83930
    }
  ],
  "customPleadingSupport": {
    "supported": true,
    "status": "draft_config_allowed",
    "notes": "Pleading-style draft support may be built from Nationwide resources and coded state-pack data where available."
  },
  "guidanceOnlyFallback": {
    "supported": true,
    "label": "West Virginia record-clearing guidance fallback",
    "status": "built",
    "notes": "Available for internal review even when official forms or pleading templates need more work."
  },
  "disclaimer": "This RCAP build artifact is for internal document-preparation and review workflows. It is not legal advice, does not guarantee eligibility or outcomes, and is not approved for live use until QA, counsel, and any required visual review pass.",
  "buildStatusMetadata": {
    "buildStatus": "state_built",
    "statusHistory": [
      "not_started",
      "nationwide_resources_found",
      "resource_packet_ingested",
      "official_forms_ingested",
      "overlay_field_maps_drafted",
      "overlay_samples_rendered",
      "state_pack_built",
      "pleading_packet_rendered",
      "guidance_packet_rendered",
      "state_built"
    ],
    "reviewStatuses": {
      "qa": "pending",
      "visual": "pending",
      "counsel": "pending",
      "sourceFreshness": "pending"
    },
    "loops": [
      {
        "id": "nationwide_folder_ingestion_loop",
        "status": "completed"
      },
      {
        "id": "all_state_build_loop",
        "status": "completed"
      },
      {
        "id": "official_pdf_overlay_factory_loop",
        "status": "draft_ready"
      },
      {
        "id": "field_map_retry_loop",
        "status": "pending_retry_artifacts"
      },
      {
        "id": "custom_pleading_factory_loop",
        "status": "draft_ready"
      },
      {
        "id": "guidance_packet_loop",
        "status": "completed"
      },
      {
        "id": "packet_render_qa_loop",
        "status": "pending_review"
      },
      {
        "id": "review_artifact_loop",
        "status": "completed"
      },
      {
        "id": "integration_preview_loop",
        "status": "internal_preview_ready"
      },
      {
        "id": "official_forms_watcher_loop",
        "status": "source_tracked"
      }
    ],
    "liveRouting": {
      "approvedForLive": false,
      "live": false,
      "note": "Build-first state output is internal review material only."
    }
  },
  "buildIssues": []
} as const;
