// West Virginia disqualifying offenses and escalation/blocks. Sourced from the
// "West Virginia Expungement Reference for Wilma" (Nationwide Record Clearing),
// sections 4, 7, 8, 15, 16, 20, reflecting the § 61-11-25 prior-felony bar, the
// § 61-11-26 conviction exclusions, the § 61-11-26b CDL/DUI limit, the pardon
// exclusions, and the attorney/legal-aid referral triggers. Screening notes, not an
// exhaustive legal test; verify the exact current W. Va. Code text.
export const wvDisqualifyingOffenseNotes = [
  "No-conviction route bar (§ 61-11-25): a person with a prior felony conviction may not file under § 61-11-25, and a dismissal in exchange for a guilty plea to another conviction does not qualify; criminal-investigation reports and certain sex-offender-registration-related records are exempt.",
  "Conviction exclusions (§ 61-11-26): not eligible for a felony offense of violence against the person; a misdemeanor involving intentional physical injury to a minor or law-enforcement officer; a felony where the victim was a minor; sex offenses under § 61-8B-1 et seq.; any offense using or exhibiting a deadly weapon or dangerous instrument; domestic battery/assault and certain assault/battery offenses involving a spouse, co-parent, or cohabitant; strangulation; DUI; driving while license revoked for DUI; and certain child, abuse, sexual, dwelling-burglary, sexually-motivated, CDL, attempt, or conspiracy offenses listed in the statute.",
  "Motor-vehicle / CDL / DUI limitation (§ 61-11-26b): courts may not expunge a motor-vehicle traffic-control violation for a person who held a CDL/commercial permit or was operating a commercial motor vehicle at the time, may not mask/divert/modify a charge to keep it off the commercial driving record, and may not expunge DUI convictions; but a DUI at least 5 years old does not automatically block an unrelated otherwise-expungable felony.",
  "One-time-use rule (§ 61-11-26): a person may only obtain expungement relief under § 61-11-26 and § 61-11-26a once.",
  "Accelerated-route requirements (§ 61-11-26a): requires medically documented substance-abuse history with treatment/recovery compliance or a DOE-approved job-readiness certificate; route to legal review where documentation is unclear.",
  "Drug conditional-discharge limits (§ 60A-4-407): not available with a prior drug-related conviction or after serious/repeated probation violations; only one discharge and dismissal is allowed.",
  "Pardon exclusions (§ 5-1-16a): pardon-based expungement is not available for first-degree murder, treason, kidnapping, or felony sex offenses under Article 8B, and not until 1 year after the pardon and 5 years after sentence discharge.",
  "Juvenile limit (§ 49-5-104): juvenile records for a juvenile convicted under adult criminal jurisdiction may not be marked and kept confidential.",
  "Escalation categories (legal review): any felony; multiple felonies or an unclear same-transaction/series issue; any violence, domestic violence, household-member, strangulation, sex, child-victim, deadly-weapon, dwelling-burglary, or DUI-related issue; any CDL/commercial-motor-vehicle issue; pending charges; any protection/no-contact/restitution/restraining order; an identified victim who may oppose; prior expungement relief; pardon-based relief; trafficking-survivor vacatur; firearm-rights, immigration, professional-licensing, law-enforcement/corrections-employment, childcare, healthcare, security-clearance, or federal-record questions; and federal/tribal/military/out-of-state records.",
  "Scope limits: West Virginia expungement does not restore firearm rights, fix immigration consequences, or reach federal/tribal/military/out-of-state records; law-enforcement/criminal-justice job applicants and legally required background checks may still require or reveal expunged convictions."
];
