// West Virginia eligibility rules. Sourced from the "West Virginia Expungement
// Reference for Wilma" (Nationwide Record Clearing / LegalEase West Virginia),
// corroborated by the cited West Virginia Code (W. Va. Code) sections and the West
// Virginia Judiciary's official expungement forms. Citations are W. Va. Code unless
// otherwise noted.
export const wvEligibilityRules = [
  "West Virginia uses the word 'expungement,' but the practical effect is removal from public access and sealing/expungement of records held by courts and agencies. For conviction expungement the statute defines expungement as removal from public records of evidence that a person was charged or convicted, except records specifically exempted; sealing means removing court, website, and law-enforcement records from public inspection or access. Expungement can remove a qualifying record from public access, but it is not a magic erase button — some sealed records can still be accessed by court order or by legally authorized criminal-history checks.",
  "No-conviction expungement (W. Va. Code § 61-11-25): a person found NOT GUILTY or whose charges were DISMISSED (and not dismissed in exchange for a guilty plea to another offense resulting in conviction) may file a civil petition in the circuit court where the charges were filed, no sooner than 60 days after the order of acquittal or dismissal. No filing fees or costs are charged for a § 61-11-25 action. A person with a prior felony conviction may not file under § 61-11-25, and criminal-investigation reports and certain sex-offender-registration-related records are exempt.",
  "Diversion / deferred-adjudication expungement (W. Va. Code § 61-11-25, with §§ 61-11-22 / 61-11-22a): a person whose charges were dismissed after successful pretrial diversion (§ 61-11-22) or deferred adjudication (§ 61-11-22a) may petition to expunge all charges originally brought if they arose from the same transaction or occurrence. Pretrial diversion agreements generally may not exceed 24 months and exclude DUI under § 17C-5-2 and several violence/sex/child/strangulation/domestic-battery/household-member offenses; deferred adjudication can last up to three years for a felony and two years for a misdemeanor, with similar exclusions.",
  "Misdemeanor conviction expungement (W. Va. Code § 61-11-26): a person convicted of a misdemeanor offense or offenses may petition the circuit court where the conviction occurred. Waiting periods: a single misdemeanor — 1 year after conviction, completion of incarceration, or completion of supervision, whichever is later; multiple misdemeanors — 2 years after the last conviction/incarceration/supervision for the last conviction, whichever is later. A person bears the burden by clear and convincing evidence.",
  "Nonviolent felony conviction expungement (W. Va. Code § 61-11-26): a person convicted of a nonviolent felony offense or offenses arising from the same transaction or series of transactions may petition the circuit court where the conviction occurred, 5 years after conviction, completion of incarceration, or completion of supervision, whichever is later.",
  "One-time-use rule (W. Va. Code § 61-11-26): a person may only obtain expungement relief under § 61-11-26 and § 61-11-26a once.",
  "Accelerated treatment/job-readiness expungement (W. Va. Code § 61-11-26a): for a person otherwise eligible under § 61-11-26 who has a medically documented substance-abuse history with successful compliance with an approved treatment/recovery/counseling program, or completion of a West Virginia Department of Education-approved job-readiness adult training course. Timing: single misdemeanor — after sentence/supervision completion and 90 days of approved treatment/recovery compliance or job-readiness completion; multiple misdemeanors — 1 year; eligible nonviolent felony — 3 years. The $100 State Police processing fee is waived for § 61-11-26a petitions.",
  "First-offense drug-possession conditional discharge (W. Va. Code § 60A-4-407): a first-time controlled-substance possession defendant with no prior drug-related conviction may, with consent, receive deferred proceedings and probation without entry of judgment; on fulfilling the terms, the court discharges the person and dismisses the proceedings without adjudication of guilt. After at least 6 months from the end of probation, the person may apply for expungement of official records of the arrest, trial, and conviction if there were no serious or repeated probation violations. Only one discharge and dismissal is allowed under this section.",
  "Pardon-based expungement (W. Va. Code § 5-1-16a): a person who receives a full and unconditional pardon from the Governor may petition the circuit court in the county of conviction to expunge the conviction, serving the prosecutor and publishing a Class I legal advertisement. Eligibility is not available until 1 year after being pardoned and 5 years after discharge of the sentence; it is unavailable for first-degree murder, treason, kidnapping, or felony sex offenses under Article 8B.",
  "Sex-trafficking victim vacatur/expungement (W. Va. Code § 61-14-9): a person convicted of prostitution, or adjudicated delinquent, as a direct result of being a trafficking victim may petition the circuit court in the county of conviction/adjudication to vacate the conviction/adjudication and expunge the record; no rehabilitation requirement is imposed for this route. Route to legal aid or an attorney.",
  "Juvenile records (W. Va. Code § 49-5-104): juvenile proceeding records are generally not public; one year after the juvenile's 18th birthday, or one year after jurisdiction ends (whichever is later), records may be kept in a separate secure confidential place and inspected only by circuit-court order; marking them confidential extinguishes the offense as if it never occurred. Records of a juvenile convicted under adult criminal jurisdiction may not be marked and kept confidential.",
  "Motor-vehicle / CDL / DUI limitation (W. Va. Code § 61-11-26b): courts may not expunge a motor-vehicle traffic-control violation for a person who held a commercial driver's license or permit or was operating a commercial motor vehicle at the time; may not mask/divert/modify a charge or conviction so it does not appear on the commercial driving record; and may not expunge DUI convictions. A DUI conviction does not automatically block expungement of an unrelated otherwise-expungable felony if the DUI is at least 5 years old when the petition is filed.",
  "Scope limits: West Virginia expungement lets a person answer most ordinary applications as if the record does not exist, but applicants for jobs involving prevention/detection/investigation/prosecution/incarceration of law violators must disclose expunged convictions, and entities required by law to obtain criminal-history checks may still learn of them; expungement does not restore firearm rights, fix immigration consequences, or reach federal/tribal/military/out-of-state records."
];
