// West Virginia filing workflow. Sourced from the "West Virginia Expungement
// Reference for Wilma" (Nationwide Record Clearing), sections 11, 12, 13, 19,
// corroborated by W. Va. Code §§ 61-11-25 and 61-11-26 and the West Virginia
// Judiciary's official SCA-C expungement forms. West Virginia uses official forms;
// this pack is shadow-only research and wires no renderer.
export const wvFilingInstructions = [
  "Determine the route first: no-conviction (acquittal/dismissal, § 61-11-25), diversion/deferred-adjudication dismissal (§ 61-11-25 with §§ 61-11-22 / 61-11-22a), misdemeanor or nonviolent-felony conviction (§ 61-11-26), accelerated treatment/job-readiness (§ 61-11-26a), first-offense drug-possession conditional discharge (§ 60A-4-407), pardon-based (§ 5-1-16a), trafficking-victim vacatur (§ 61-14-9), or juvenile confidentiality (§ 49-5-104). Screen exclusions before giving any 'likely eligible' answer.",
  "No-conviction expungement (§ 61-11-25): file a civil petition in the circuit court where the charges were filed, no sooner than 60 days after the acquittal/dismissal order, using SCA-C903 (Motion for Expungement of Criminal Records Due to Acquittal or Dismissal for Reasons Other than Entry of a Plea). Attach the certified dismissal/acquittal order and, if applicable, the diversion/deferred-adjudication completion order; confirm the dismissal was not in exchange for a guilty plea to another conviction. No filing fees or costs are charged.",
  "Misdemeanor conviction expungement (§ 61-11-26): use SCA-C906 (Petition for Expungement of Misdemeanor Violations and Traffic Citations). The petition must be verified under oath and include identity/address history, arrest/court/case/statute/conviction/disposition/sentence details, victim/no-victim and restitution/protection/no-contact disclosures, a rehabilitation statement, and prior-expungement disclosure.",
  "Nonviolent felony conviction expungement (§ 61-11-26): use SCA-C907 (Petition for Expungement of Felony Violations) with a nonviolent-felony analysis, same-transaction/series analysis for multiple felonies, the exclusion checklist, waiting-period proof, and a pending-charge check.",
  "Service for § 61-11-26: serve the petition and supporting documentation on the Superintendent of the State Police, the prosecutor, the arresting law-enforcement agency, any institution of confinement, and the court that disposed of the charge. The prosecutor serves any identified victims (who may file SCA-C912, Victim's Notice of Opposition). Opposing parties have 30 days to file opposition, and the petitioner may reply within 30 days after service.",
  "Court timeline and standard (§ 61-11-26): within 60 days after filing, the circuit court must grant, return for missing information/errors, set for hearing, or deny the petition; the petitioner bears the burden by clear and convincing evidence. SCA-C900 (Instructions for Expungement of Records Petition) explains the process.",
  "Accelerated route (§ 61-11-26a): add to the misdemeanor or felony packet the medical documentation of substance-abuse history and proof of treatment/recovery compliance, and/or the DOE-approved job-readiness certificate; note the $100 State Police processing fee is waived under § 61-11-26a.",
  "First-offense drug-possession conditional discharge (§ 60A-4-407): include the conditional discharge order, proof probation completed, the probation-expiration date, the 6-month waiting-period calculation, and proof of no serious or repeated probation violations; the proposed order expunges official records of the arrest, trial, and conviction.",
  "Pardon route (§ 5-1-16a): include the full and unconditional Governor's pardon, proof of at least 1 year since the pardon and 5 years since sentence discharge, the Class I legal-advertisement publication notice, service on the prosecutor, a good-cause statement, and the exclusion check (first-degree murder, treason, kidnapping, Article 8B felony sex offense).",
  "Effect and fees: on a granted § 61-11-26 order, court records are sealed and agency/law-enforcement records expunged, with agencies certifying completion within 60 days. The circuit clerk charges the same fee as a civil action for § 61-11-26, and a person who receives an expungement order pays the $100 State Police processing fee (waived for § 61-11-26a; no fees for § 61-11-25). Do not generate a conviction packet without the arresting agency, court of disposition, confinement institution (if any), prosecutor address, victim/no-contact information, and rehabilitation statement."
];
