// Missouri eligibility rules. Sourced from the Missouri Expungement Reference
// for Wilma (Nationwide Record Clearing), corroborated by the cited RSMo
// sections and Mo. Const. Art. XIV. Citations are Mo. Rev. Stat. unless noted.
export const moEligibilityRules = [
  "Missouri expungement generally closes/seals records from ordinary public access. Under the general closure rule, closed records are not destroyed — they are inaccessible to the general public but remain available to specified government, criminal-justice, licensing, driver-license, public-safety, care-screening, and federal entities (§ 610.120). Missouri has several different record-clearing routes; do not treat them all the same.",
  "General expungement (§ 610.140, effective January 1, 2025): a person may apply in the Missouri court where they were charged or found guilty to expunge records of arrest, plea, trial, or conviction, so long as the crime occurred in Missouri, was prosecuted under Missouri court jurisdiction, is listed in the petition, and is not excluded by statute. It can cover many convictions but requires an eligible offense, a completed waiting period, satisfied obligations, no pending charges, and that lifetime limits are not exceeded.",
  "§ 610.140 waiting periods: felony — 3 years; misdemeanor — 1 year; municipal violation — 1 year; infraction — 1 year. The clock runs from completion of the authorized disposition imposed for each crime (not the arrest or conviction date), and fines and restitution must be satisfied.",
  "§ 610.140 clean-period rule: during the relevant waiting period (3 years felony / 1 year other), the person must not have been found guilty of another misdemeanor or felony, excluding certain traffic-regulation violations in chapters 301, 302, 303, 304, and 307.",
  "§ 610.140 court findings: for each listed crime the court considers whether the waiting period is complete, there was no disqualifying new guilt during the waiting period, all obligations (fines/restitution) are satisfied, there are no pending charges, the person's habits and conduct show they are not a threat to public safety, and expungement is consistent with public welfare and the interests of justice. Pleading the public-safety / interests-of-justice factors creates a rebuttable presumption if the first four criteria are met, but a prosecutor/circuit attorney may rebut it and a victim may be heard.",
  "§ 610.140 lifetime limits: misdemeanor offenses or ordinance violations with authorized imprisonment — 3; felony offenses — 2; infractions — no numerical limit. Multiple crimes committed as part of the same course of criminal conduct may be included together and count only as the highest level for eligibility purposes.",
  "§ 610.140 arrest-only route: a petition to expunge records related to an arrest for an eligible crime may be filed no earlier than 18 months from the date of arrest, if during that time the person has not been charged and has not been found guilty of any misdemeanor or felony. This is separate from § 610.122 false-information arrest expungement and § 610.105 automatic closure.",
  "Closed-record outcomes (§ 610.105): if a person was arrested and charged but the case was later nolle prossed, dismissed, resulted in not guilty, or resulted in a suspended imposition of sentence (SIS) in the prosecuting court, official records become closed records after final termination, subject to statutory exceptions. This is closure by operation of law, distinct from a full expungement petition — check what still appears on Case.net and the MSHP record.",
  "False-information arrest expungement (§§ 610.122-610.123): an arrest record may be expunged if the arrest was based on false information with no probable cause at the time of expungement, no charges will be pursued, and the person did not receive SIS for the offense; OR for a misdemeanor Chapter 303 offense or moving violation (excluding intoxication-related traffic) where every related offense was nolle prossed, dismissed, or found not guilty and the person was not a CDL holder operating a commercial vehicle. No civil action may be pending. The petition is filed in the civil division of the circuit court in the county of arrest, with a fingerprint card; records ordered expunged under § 610.123 are destroyed (or blacked out if destruction is not feasible).",
  "First intoxication-related offense (§ 610.130): a person may apply after at least 10 years to expunge a first intoxication-related traffic or boating offense that was a misdemeanor or county/city ordinance violation, was not a commercial-motor-vehicle DUI, with no later intoxication-related conviction or alcohol-related enforcement contact and no pending such offense. Only one expungement under this section; it does not apply to CDL holders or those required to have a CDL. Note: § 610.140 excludes intoxication-related traffic/boating offenses, so they route here.",
  "Marijuana expungement (Mo. Const. Art. XIV, § 2): Missouri's adult-use amendment created marijuana-specific relief. Missouri courts were directed to order expungement of misdemeanor marijuana offenses and qualifying felony marijuana offenses (automatic for completed sentences), with petition routes for those incarcerated or on probation/parole. Exclusions include distribution/delivery to a minor, violence, and marijuana-impaired operation of a motor vehicle. A marijuana expungement order is legally effective immediately, the person is treated as if never arrested/convicted/sentenced, the conviction is vacated as legally invalid, and the court issues a certificate of expungement.",
  "Stolen/mistaken identity (§ 610.145): if a person was named in a charge because another used their identifying information or because of mistaken identity, and the charge was dismissed or resulted in not guilty, they may apply in the court where the charge was last pending for expungement; the court holds a hearing and, on finding identity theft/mistaken identity plus dismissal/not guilty, orders expungement. Costs are not taxed against the eligible person.",
  "Minor in possession of alcohol (§ 311.326): a person with a first-time MIP alcohol violation may apply after at least one year after reaching age 21, if they have had no other alcohol-related offense; excludes CDL/commercial-vehicle situations; only one expungement under this section, restoring the person to the status occupied before the arrest/plea/trial/conviction."
];
