// Missouri filing workflow. Sourced from the Missouri Expungement Reference for
// Wilma (Nationwide Record Clearing), sections 6 and 10, corroborated by RSMo
// §§ 610.140 and 610.122-610.123. Missouri uses standardized statewide CR-series
// court forms; this pack is shadow-only research and wires no renderer.
export const moFilingInstructions = [
  "Determine the pathway first: general § 610.140 (charge/plea/trial/conviction), arrest-only § 610.140 (18 months), already-closed § 610.105, false-information arrest §§ 610.122-610.123, first intoxication § 610.130, marijuana (Art. XIV), identity theft/mistaken identity § 610.145, or minor in possession § 311.326.",
  "Get the record: obtain the Missouri Case.net printout, a certified docket sheet/judgment, the final disposition/minute entry, probation/parole discharge documents, receipts for fines/restitution, and an MSHP name-based or fingerprint-based criminal-history record (and an FBI Identity History Summary if needed).",
  "General § 610.140: file in the Missouri court where the person was charged or found guilty (or, for an arrest-only § 610.140 petition, in a court of competent jurisdiction in the county of arrest).",
  "Name all record holders as defendants: the § 610.140 petition must name as defendants all agencies/entities believed to possess records — law enforcement agencies, courts, prosecutors/circuit attorneys, central repositories, and others. The court's order does NOT affect an entity that was not named as a defendant, so naming the right agencies is a Missouri-specific packet-quality issue.",
  "Complete the petition (CR360 for § 610.140) with the required information: full name; sex; race; driver's license number if applicable; current address; each crime to be expunged; the approximate date charged for each crime; the county and municipality where charged; and the case number and court name for each crime. Attach a proposed Judgment and Order of Expungement.",
  "Notice and objection (§ 610.140): the clerk gives notice to the prosecuting attorney; a written objection must be filed within 30 days after receipt of service; unless otherwise agreed, the court holds a hearing within 60 days after a written objection is filed; if no objection is filed the court may still set a hearing and notify named entities. The court must issue an order of expungement or dismissal within six months of filing.",
  "False-information arrest (§§ 610.122-610.123): file in the civil division of the circuit court in the county of arrest; include identity details, the offense charged, arrest date, county/municipality, arresting agency, case number/court, and a fingerprint card; name all record-holding agencies; the court sets a hearing no sooner than 30 days from filing.",
  "Fee handling: do not assume a $250 surcharge — the former § 488.650 expungement surcharge is repealed (effective August 28, 2023). County filing/service/copy/fingerprint costs vary; a person may request to proceed as a poor person (Motion and Affidavit in Support of Request to Proceed as a Poor Person). Confirm the current fee with the specific circuit clerk before filing."
];
