// South Carolina disqualifying offenses, exclusions, and blocks. Sourced from the
// "South Carolina Expungement — Wilma Agent Training Reference" (Nationwide Record
// Clearing), sections 5-9 and 14, reflecting the route-specific exclusions and
// blocking rules. Screening notes, not an exhaustive legal test; verify the exact
// current S.C. Code text. Citations are S.C. Code unless noted.
export const scDisqualifyingOffenseNotes = [
  "Pending charges and related-charge blocks (S.C. Code §§ 17-22-950, 22-5-910): pending charges usually block or delay most expungement routes. Summary court should not issue an order if the dismissal happened at a preliminary hearing, or if related charges from the same course of events are still pending in summary court or General Sessions.",
  "First low-level conviction exclusions (S.C. Code § 22-5-910): the route does NOT apply to offenses involving operation of a motor vehicle; the penalty must be not more than 30 days or a $1,000 fine; available only once; requires no other convictions during the 3-year period. Third-degree domestic violence uses the special 5-year timing and is also once-only.",
  "Youthful Offender Act exclusions (S.C. Code § 22-5-920): motor-vehicle offenses, violent crimes under § 16-1-60, most Chapter 25 domestic-violence offenses (except as specifically allowed), and sex-offender-registration offenses are excluded. A person merely eligible for YOA sentencing but not actually sentenced under YOA is generally not eligible (limited older-law exception). Later convictions during service or the 5-year period block relief.",
  "Fraudulent check exclusion (S.C. Code § 34-11-90(e)): felony fraudulent-check cases are NOT eligible; only a first-offense misdemeanor with no other conviction during the one-year period, once only.",
  "Failure to stop exclusion (S.C. Code § 56-5-750(F)): felony failure-to-stop cases are NOT eligible; only a first-offense non-felony with no other conviction during the 3-year period. Statute amended with certain changes effective May 12, 2026 — confirm subsection, injury/death, high-speed pursuit, and classification.",
  "Diversion-program exclusions: AEP (§ 17-22-530) excludes DUI-type offenses and requires no prior alcohol-related offense and age 17-under 21 at arrest; TEP (§ 17-22-330) is not available if the offense caused death or serious bodily injury and is limited to fine-only/four-points-or-less offenses; conditional discharge (§ 44-53-450) is one-time and requires no prior qualifying drug conviction.",
  "Juvenile exclusions (S.C. Code § 63-19-2050): violent-crime adjudications cannot be expunged; expungement requires age 18+, completed disposition, no subsequent adjudication or conviction, and no pending Family Court or General Sessions charges (except a Family Court not-guilty finding, which is expunged regardless of age and without a fee).",
  "Drug conviction caution (S.C. Code § 22-5-930): do not route all drug convictions here — distinguish simple possession, unlawful prescription drug, first-offense PWID, trafficking, distribution, and manufacturing; treat as manual-review until the exact statute, level, and dates are confirmed.",
  "Pardon is not expungement: a pardon may restore certain rights but does not erase the conviction and must not be treated as an expungement route.",
  "Scope limits: South Carolina expungement does not automatically remove federal/FBI records, clear out-of-state convictions, restore firearm rights, or fix immigration consequences; some records may be retained under seal for limited law-enforcement, prosecution, detention, or litigation-defense purposes."
];
