// South Carolina eligibility rules. Sourced from the "South Carolina Expungement
// — Wilma Agent Training Reference" (Nationwide Record Clearing), corroborated by
// the cited S.C. Code sections and South Carolina Judicial Branch / SLED guidance.
// Citations are S.C. Code unless noted. South Carolina is expungement-friendly only
// in narrow statutory lanes — route by disposition + court level + offense type +
// prior record + waiting period, not by the word "misdemeanor" alone.
export const scEligibilityRules = [
  "South Carolina record-clearing is not one pathway. The Uniform Expungement Act (S.C. Code § 17-22-910 et seq.) lists the major expungement authorizations, and eligibility generally turns on the offense pled guilty to or convicted of, not necessarily the original charge. Route first by court level — summary court (magistrate/municipal), General Sessions, or Family Court (juvenile) — then by disposition, then by offense type, prior record, and waiting period. Expungement removes the charge or conviction from public state records and directs agencies to destroy, seal, or remove records, but some records may still be retained under seal for limited law-enforcement, prosecution, detention, or litigation-defense purposes.",
  "Summary court non-conviction (S.C. Code § 17-22-950): for a magistrate or municipal court charge dismissed, nolle prossed, or resulting in not guilty, summary court issues the expungement order through a direct process, usually at no cost. If the person was fingerprinted and the charge was dismissed/nolle prossed/not guilty, the court issues the order at no cost; if not fingerprinted, the defendant applies at no cost using the summary-court application (SCCA 223E). The court should not issue the order if the dismissal happened at a preliminary hearing, or if related charges from the same course of events are still pending in summary court or General Sessions.",
  "Summary court objection window (S.C. Code § 17-22-950): prosecution or law enforcement may object within 30 days, but only on limited grounds — pending charges or an ineligible charge — transmitted using form SCCA 223D. If no objection is filed, the trial judge signs the order no sooner than 31 days and no later than 40 days after notice. Internet public records must remove eligible criminal charges within 30 days after disposition, applied retroactively to older cases.",
  "General Sessions non-conviction (S.C. Code § 17-1-40): charges dismissed, nolle prossed, found not guilty, discharged, or acquitted are expunged, usually through the Solicitor's Office in the circuit/county where the charge occurred. These are generally exempt from the Solicitor administrative fee, UNLESS the dismissal, discharge, or nolle prosequi happened as part of a plea arrangement where the person pled guilty and was sentenced on other charges. If multiple charges came from one incident and some were dismissed while others resulted in a guilty plea, ask whether the dismissal was part of the plea deal — that affects fees and packet handling. Section 17-1-40 expressly allows law enforcement and prosecutors to retain certain records under seal.",
  "Diversion program completions — PTI, AEP, TEP: Pretrial Intervention (S.C. Code § 17-22-150) results in a noncriminal disposition after successful completion, and the person may apply to destroy official arrest records (prosecution resumes if PTI is violated). Alcohol Education Program (S.C. Code § 17-22-530) is for persons at least 17 but under 21 at arrest with no prior alcohol-related offense; eligible offenses include underage-alcohol, open-container, public-disorderly, false-age, and fake-ID offenses, but DUI-type offenses are excluded. Traffic Education Program (S.C. Code § 17-22-330) applies to qualifying traffic offenses punishable only by fine with loss of four points or less, not available if the offense caused death or serious bodily injury. Each program completion produces a noncriminal disposition that can support expungement of official arrest records.",
  "Conditional discharge — drug possession (S.C. Code § 44-53-450): a person with no prior qualifying drug conviction who pleads or is found guilty of certain drug possession offenses may receive a conditional discharge; on fulfilling the terms the court discharges the person and dismisses the proceeding without adjudication, and the person may apply to expunge official records. This route is one-time only.",
  "First-offense misdemeanor fraudulent check (S.C. Code § 34-11-90(e)): a first-offense conviction may be expunged 1 year after conviction, only if the conviction was a misdemeanor and the person had no other conviction during that one-year period. Felony fraudulent-check cases are not eligible under this route, which is available only once.",
  "First low-level conviction (S.C. Code § 22-5-910): a person convicted of a crime carrying a penalty of not more than 30 days imprisonment or a $1,000 fine may apply 3 years after the date of conviction if they have no other convictions during that period. This route does NOT apply to offenses involving operation of a motor vehicle and is available only once. The statute also now includes certain first-offense unlawful-possession-of-firearm-or-weapon convictions with a penalty of not more than 1 year or a $1,000 fine.",
  "Third-degree domestic violence (S.C. Code § 22-5-910 special timing): the wait is 5 years from conviction, with no other conviction during the period. Conviction includes a guilty plea, nolo contendere plea, or bail forfeiture. Pending charges can block relief unless the pending charge is older than 5 years under the statute's tolling rules. This route is only available once.",
  "Youthful Offender Act (S.C. Code § 22-5-920): a person sentenced under the South Carolina Youthful Offender Act may apply after completing the sentence, including probation and parole, and then remaining conviction-free for 5 years. Closely connected offenses from the same incident may count as one offense. Major exclusions include motor-vehicle offenses, violent crimes under § 16-1-60, most Chapter 25 domestic-violence offenses except as specifically allowed, and sex-offender-registration offenses. A person merely eligible for YOA sentencing but not actually sentenced under YOA is generally not eligible under this route (limited older-law exception).",
  "Drug conviction route (S.C. Code § 22-5-930): a separate route for certain first-offense drug convictions, including simple possession and some possession-with-intent categories. Treat as manual-review unless the exact statute, offense level, conviction date, sentence-completion date, and later conviction history are known. Do not route all drug convictions here — confirm whether it was simple possession, unlawful prescription drug, first-offense PWID, trafficking, distribution, or manufacturing.",
  "Failure to stop for blue light (S.C. Code § 56-5-750(F)): a first-offense non-felony conviction may be expunged 3 years after completion of all sentence terms and conditions, if the person has no other conviction during that 3-year period. Felony failure-to-stop cases are not eligible. South Carolina amended this statute, with certain changes effective May 12, 2026 — confirm offense date, subsection, injury/death facts, high-speed-pursuit facts, and felony/misdemeanor classification before routing.",
  "Old unlawful handgun possession (S.C. Code § 17-1-65 / SCCA 223C): a special deadline route for old unlawful-possession-of-handgun convictions under former § 16-23-20 before the Constitutional Carry Act. The SCCA 223C form references convictions before March 7, 2024, requires the application to be submitted before March 7, 2029, and limits the person to no prior application under § 17-1-65.",
  "Human trafficking survivor relief (S.C. Code § 16-3-2020 trafficking-victim provisions): a victim convicted or adjudicated delinquent of offenses under the trafficking article, prostitution, or another nonviolent misdemeanor or Class F felony may move the court to expunge the record if the offense was directly caused by or interrelated to trafficking, proven by a preponderance of the evidence. For minors, the statute also protects trafficking victims under 18 from prosecution/adjudication for certain trafficking-related conduct. Trauma rule: ask only what is needed to route; do not require graphic details; trigger manual/legal review.",
  "Juvenile expungement (S.C. Code § 63-19-2050): a person taken into custody, charged, or adjudicated delinquent for a status offense or nonviolent crime may petition Family Court to expunge official records. Violent-crime adjudications cannot be expunged. The court must not grant expungement unless the person is at least 18, completed the disposition, has no subsequent adjudication or conviction, and has no pending Family Court or General Sessions charges. If the juvenile was found not guilty in Family Court, the court must grant expungement regardless of age and without a fee. A status offense is treated more favorably than a nonviolent delinquency adjudication.",
  "Pardon is not expungement (S.C. Code § 17-22-910 framing): a South Carolina pardon is state forgiveness that may restore certain rights, generally through the Department of Probation, Parole and Pardon Services, but it does not remove the conviction from the record by itself. Never tell a user a pardon clears their record — a pardon may restore rights but is separate from expungement and does not automatically erase the conviction.",
  "One charge per order and related-charge rules (Uniform Expungement Act, S.C. Code § 17-22-910 et seq.): South Carolina generally expunges one charge per order, with special rules about fee treatment for related charges from the same incident. SLED verification fees are not charged for several routes, including § 17-1-40, PTI, AEP, TEP, and conditional discharge. Start with the SLED criminal-history (rap sheet) and the court docket from the magistrate, municipal, General Sessions, or Family Court, plus a certified disposition where available.",
  "Scope limits: South Carolina expungement does not automatically remove federal/FBI records, clear out-of-state convictions, restore firearm rights, or fix immigration consequences, and some records may be retained under seal for limited law-enforcement, prosecution, detention, or litigation purposes. Most conviction routes require no later convictions and no pending charges. Do not promise expungement until the exact charge, final disposition, court, sentence-completion date, prior/later conviction history, and pending-charge status are known."
];
