// South Carolina filing workflow. Sourced from the "South Carolina Expungement —
// Wilma Agent Training Reference" (Nationwide Record Clearing), sections 3-9 and 12,
// corroborated by S.C. Code §§ 17-22-910 et seq., 17-1-40, 17-22-950, 63-19-2050,
// and South Carolina Judicial Branch / SLED guidance. South Carolina expungements
// start with either the Solicitor's Office or the summary court and use the official
// SCCA 223-series forms; this pack is shadow-only research and wires no renderer.
export const scFilingInstructions = [
  "Determine the court level and disposition first: summary court (magistrate/municipal) -> check § 17-22-950; General Sessions -> check § 17-1-40, diversion, YOA, drug, firearm, and conviction routes; Family Court -> check juvenile § 63-19-2050. Pending charges usually block or delay most routes. South Carolina generally expunges one charge per order.",
  "Get the records: start with the SLED criminal-history / rap sheet, the court docket from the magistrate, municipal, General Sessions, Family Court, or other court, a certified disposition if available, and Solicitor or clerk confirmation for the expungement route. SLED is the state agency responsible for reports of arrests and convictions, and a SLED report may be obtained for a fee.",
  "General Sessions expungements (§ 17-1-40): apply through the Solicitor's Office in the circuit/county where the charge occurred. The Solicitor sends the application to SLED to verify eligibility when required, obtains signatures if eligible, files the expungement order with the Clerk of Court, and provides certified copies to the required agencies. Section 17-1-40 non-convictions are generally exempt from the Solicitor administrative fee unless the dismissal/nolle was part of a plea arrangement with guilty pleas/sentence on other charges.",
  "Summary court dismissed, nolle prossed, or not guilty charge (§ 17-22-950): summary court uses the Judicial Branch expungement forms, including the SCCA 223-series. If the person was fingerprinted, the court generally issues the expungement order at no cost. If the person was not fingerprinted, the defendant applies at no cost using SCCA 223E, and the court issues the appropriate order if eligible.",
  "Summary court objection (§ 17-22-950): a prosecutor/law-enforcement objection is transmitted using form SCCA 223D within 30 days, only on the limited grounds of pending charges or an ineligible charge. If no objection is filed, the trial judge signs the order no sooner than 31 days and no later than 40 days after notice.",
  "Diversion completions (PTI § 17-22-150, AEP § 17-22-530, TEP § 17-22-330): after successful completion the Solicitor effects a noncriminal disposition; apply to destroy/expunge official arrest records through the Solicitor's Office. Confirm the program-specific eligibility (PTI completion, AEP age 17-under 21 and no DUI-type offense, TEP fine-only/four-points-or-less and no death/serious injury).",
  "Conditional discharge drug possession (§ 44-53-450): confirm no prior qualifying drug conviction and successful completion; after the discharge/dismissal without adjudication, apply to expunge official records. One-time route.",
  "Conviction routes (§ 34-11-90(e) fraudulent check; § 22-5-910 first low-level / DV-3rd; § 22-5-920 YOA; § 22-5-930 drug; § 56-5-750(F) failure to stop): confirm the exact statute, offense level, conviction date, sentence-completion date, prior/later conviction history, and pending-charge status, then route through the Solicitor's Office with SLED verification where required. Verify the waiting period (1 yr, 3 yr, or 5 yr) has run and that the route has not been used before where it is once-only.",
  "Old unlawful handgun possession (§ 17-1-65): use the SCCA 223C order/form route for pre-Constitutional-Carry convictions; the application must be submitted before March 7, 2029, and the person must have no prior § 17-1-65 application.",
  "Juvenile expungement (§ 63-19-2050): file the Family Court / juvenile route; confirm status offense vs. nonviolent adjudication vs. violent (violent adjudications are not expungeable), age 18+, completed disposition, no later adjudication/conviction, and no pending Family Court or General Sessions charges. A Family Court not-guilty finding is expunged regardless of age and without a fee.",
  "Human trafficking survivor relief (§ 16-3-2020 trafficking-victim provisions): this is an evidence-specific court motion to expunge convictions/adjudications directly caused by or interrelated to trafficking, proven by a preponderance of the evidence. Ask only what is needed to route, do not require graphic details, and trigger manual/legal review.",
  "Pardon (§ 17-22-910 framing): a pardon is a separate process through the Department of Probation, Parole and Pardon Services and is NOT expungement — do not file a pardon as an expungement and do not tell the user a pardon clears the record."
];
