// Auto-generated by scripts/generate-all50-state-pack-batch.mjs.
// Build-first metadata is sourced from private/Nationwide Record Clearing.
// QA, visual review, counsel review, and source freshness review are tracked
// separately and do not block ordinary RCAP build work.

export const vermontAll50BuildMetadata = {
  "jurisdiction": {
    "code": "VT",
    "name": "Vermont",
    "slug": "vermont",
    "sourceFolders": [
      "LegalEase Vermont"
    ]
  },
  "products": [
    "record_clearing_guidance_packet",
    "official_pdf_overlay_draft",
    "custom_pleading_or_state_pack_draft"
  ],
  "pathways": [
    {
      "id": "record_clearing_review",
      "label": "Vermont record-clearing review",
      "output": "guidance_packet",
      "reviewRequiredBeforeLive": true
    },
    {
      "id": "official_form_overlay",
      "label": "Vermont official form overlay draft",
      "output": "official_pdf_overlay_draft",
      "reviewRequiredBeforeLive": true
    },
    {
      "id": "custom_pleading",
      "label": "Vermont custom pleading draft",
      "output": "custom_pleading_or_state_pack_draft",
      "reviewRequiredBeforeLive": true
    }
  ],
  "requiredUserInputs": [
    "participant_full_legal_name",
    "date_of_birth_if_required_by_selected_form",
    "contact_information",
    "case_number",
    "court_or_agency_name",
    "county_or_filing_location",
    "charge_or_record_description",
    "case_outcome",
    "disposition_date_if_known",
    "sentence_completion_or_supervision_status_if_applicable",
    "records_or_background_report_if_available"
  ],
  "filingDestinationGuidance": [
    "Use the court, clerk, agency, or official filing destination identified in the selected Nationwide resource packet or official form.",
    "If the correct filing destination is unclear, keep the packet guidance-only and flag the state for post-build QA/attorney review.",
    "Do not invent clerk addresses, agency addresses, local fees, or service rules."
  ],
  "filingSteps": [
    "Confirm the record-clearing pathway from the participant's answers and available source packet.",
    "Collect required user inputs and mark unknown information plainly.",
    "Select official form overlay, custom pleading, or guidance-only fallback.",
    "Generate internal review packet and source inventory artifact.",
    "Route to QA, visual review when an official PDF overlay exists, and counsel review before live use."
  ],
  "feesCopiesServiceNotes": [
    "Use fee, copy, and service notes only when present in the Nationwide source packet or official form.",
    "When fee/copy/service information is absent or unclear, state that the participant should verify current local requirements with the filing court or agency.",
    "Do not treat missing fee data as a blocker for guidance fallback generation."
  ],
  "officialFormInventory": [
    {
      "fileName": "200-00129 – Petition to Expunge Criminal History.pdf",
      "relativePath": "LegalEase Vermont/200-00129 – Petition to Expunge Criminal History.pdf",
      "sha256": "6b855b1976bb10bb1a623e4ae1741545d36108c5e320c7ce542d214481ab9be5",
      "sizeBytes": 2000422
    },
    {
      "fileName": "200-00130A - Filing a Petition to Expunge or Seal a Criminal Record.pdf",
      "relativePath": "LegalEase Vermont/200-00130A - Filing a Petition to Expunge or Seal a Criminal Record.pdf",
      "sha256": "8a44b91cd2f48af494cefcadb557c3c0f5a35b0bdeef06272ee54c66f9ca8078",
      "sizeBytes": 675949
    },
    {
      "fileName": "200-00131.pdf",
      "relativePath": "LegalEase Vermont/200-00131.pdf",
      "sha256": "5afb8d524b52a6e9faaa2a797c9d2230dc11a492d1f5544bd9cf9f05a9d3379a",
      "sizeBytes": 1326589
    },
    {
      "fileName": "200-00132 – Stipulation to Seal Criminal History Record + Order.pdf",
      "relativePath": "LegalEase Vermont/200-00132 – Stipulation to Seal Criminal History Record + Order.pdf",
      "sha256": "088116244572ec7ccf00db799e1f6561928715e45c178f20b06de48d8d7a81c2",
      "sizeBytes": 1999317
    },
    {
      "fileName": "200-00132A – Stipulation to Expunge Criminal History Record + Order.pdf",
      "relativePath": "LegalEase Vermont/200-00132A – Stipulation to Expunge Criminal History Record + Order.pdf",
      "sha256": "9f530430fba20599eb5d838c3e0aa505647124fbe976e74d0a6a349e3ea41dec",
      "sizeBytes": 1959576
    },
    {
      "fileName": "200-00631.pdf",
      "relativePath": "LegalEase Vermont/200-00631.pdf",
      "sha256": "a4afde13b306a87f65fb40f43eb00a8e57a15d4e8b80255d11decfca0b96e6d3",
      "sizeBytes": 832881
    },
    {
      "fileName": "400-00171.pdf",
      "relativePath": "LegalEase Vermont/400-00171.pdf",
      "sha256": "b57dc05d9bccb54468aa5928745a46464c72e7470bf1b93cf3fcad2e7ef53a1a",
      "sizeBytes": 1964636
    }
  ],
  "resourcePacketInventory": [
    {
      "fileName": "application-waive-filing-fees-and-service-costs.html",
      "relativePath": "LegalEase Vermont/application-waive-filing-fees-and-service-costs.html",
      "classification": "reference",
      "sha256": "1b9348d18347d3adb278a209046c3593e595c385b1c2081c6a33142767196b59",
      "sizeBytes": 48897
    },
    {
      "fileName": "Vermont Expungement & Sealing — Wilma Agent Training Reference.rtf",
      "relativePath": "LegalEase Vermont/Vermont Expungement & Sealing — Wilma Agent Training Reference.rtf",
      "classification": "reference",
      "sha256": "7aa863113d51ccb74de46d561096281498a5a0de58e2d3ce005f63dff1ebc7b1",
      "sizeBytes": 77815
    }
  ],
  "customPleadingSupport": {
    "supported": true,
    "status": "draft_config_allowed",
    "notes": "Pleading-style draft support may be built from Nationwide resources and coded state-pack data where available."
  },
  "guidanceOnlyFallback": {
    "supported": true,
    "label": "Vermont record-clearing guidance fallback",
    "status": "built",
    "notes": "Available for internal review even when official forms or pleading templates need more work."
  },
  "disclaimer": "This RCAP build artifact is for internal document-preparation and review workflows. It is not legal advice, does not guarantee eligibility or outcomes, and is not approved for live use until QA, counsel, and any required visual review pass.",
  "buildStatusMetadata": {
    "buildStatus": "state_built",
    "statusHistory": [
      "not_started",
      "nationwide_resources_found",
      "resource_packet_ingested",
      "official_forms_ingested",
      "overlay_field_maps_drafted",
      "overlay_samples_rendered",
      "state_pack_built",
      "pleading_packet_rendered",
      "guidance_packet_rendered",
      "state_built"
    ],
    "reviewStatuses": {
      "qa": "pending",
      "visual": "pending",
      "counsel": "pending",
      "sourceFreshness": "pending"
    },
    "loops": [
      {
        "id": "nationwide_folder_ingestion_loop",
        "status": "completed"
      },
      {
        "id": "all_state_build_loop",
        "status": "completed"
      },
      {
        "id": "official_pdf_overlay_factory_loop",
        "status": "draft_ready"
      },
      {
        "id": "field_map_retry_loop",
        "status": "pending_retry_artifacts"
      },
      {
        "id": "custom_pleading_factory_loop",
        "status": "draft_ready"
      },
      {
        "id": "guidance_packet_loop",
        "status": "completed"
      },
      {
        "id": "packet_render_qa_loop",
        "status": "pending_review"
      },
      {
        "id": "review_artifact_loop",
        "status": "completed"
      },
      {
        "id": "integration_preview_loop",
        "status": "internal_preview_ready"
      },
      {
        "id": "official_forms_watcher_loop",
        "status": "source_tracked"
      }
    ],
    "liveRouting": {
      "approvedForLive": false,
      "live": false,
      "note": "Build-first state output is internal review material only."
    }
  },
  "buildIssues": []
} as const;
