// Vermont eligibility rules. Sourced from the "Vermont Expungement & Sealing —
// Wilma Agent Training Reference" (Nationwide Record Clearing / LegalEase Vermont),
// corroborated by the cited Vermont Statutes Annotated (V.S.A.) sections and
// Vermont Judiciary guidance. Citations are V.S.A. unless otherwise noted.
export const vtEligibilityRules = [
  "Vermont changed its record-clearing law effective July 1, 2025: it is now SEALING-FIRST and expungement-NARROW. Most conviction relief is sealing, not expungement. The primary statutes are 13 V.S.A. §§ 7601–7611 (adult sealing/expungement) and 33 V.S.A. § 5119 (youth/juvenile sealing). Do not call ordinary conviction relief 'expungement' after the 2025 change; for most convictions say it looks like a possible sealing route, not expungement.",
  "Expungement vs. sealing: Vermont expungement annuls the record of arrest, conviction, and sentence — the person is treated as if never arrested, convicted, or sentenced, the response to public inquiry is 'NO CRIMINAL RECORD EXISTS,' and when all charges on a docket are expunged the case file is destroyed under Court Administrator policies. A sealed record is NOT destroyed; the person is still generally treated as if never arrested/convicted and the public response is also 'NO CRIMINAL RECORD EXISTS,' but sealed records remain available for specific exceptions (criminal-justice purposes, firearm-background checks, discovery obligations, law-enforcement employment/internal investigations, and certain litigation uses).",
  "Adult conviction expungement is now narrow (13 V.S.A. § 7602): a person may petition to expunge a conviction record only if the underlying conduct is no longer prohibited by law or no longer designated as a criminal offense. The court grants if the person completed sentence/supervision and paid restitution and surcharges, unless surcharges were waived. Old cannabis/marijuana conduct is a common example, but verify the exact statute, amount, offense, and current law before saying it fits — old marijuana alone is not enough.",
  "Adult misdemeanor sealing (13 V.S.A. § 7602(c)): most qualifying misdemeanor convictions are sealable 3 years after completion of sentence terms and conditions, with restitution/surcharges paid (unless surcharge waived), if the prosecutor does not show sealing is contrary to the interests of justice. The qualifying-crime definition excludes listed crimes, child sexual exploitation, abuse-prevention/stalking/sexual-assault/protective-order violations, vulnerable-adult abuse/exploitation, voyeurism, animal cruelty, sex-offender-registry failure, hate-motivated crimes, cruelty to a child, female genital mutilation, sexual exploitation of a minor, extreme-risk-protection-order violation, CDL motor-vehicle offenses, and any offense requiring sex-offender registration.",
  "Adult felony sealing (13 V.S.A. § 7602(d); qualifying list at § 7601(4)(B)): qualifying felonies are sealable 7 years after completion of sentence terms and conditions, restitution/surcharges paid (unless surcharge waived), if the prosecutor does not show sealing is contrary to the interests of justice. Qualifying felonies include certain burglary, designated felony property offenses (forgery/counterfeiting, false pretenses, home-improvement fraud, identity theft, grand larceny, embezzlement, receiving stolen property, retail theft, theft of services, failure to return rented property, false claims, unlawful mischief, unlawful trespass, certain mills/dams/bridges offenses, unauthorized removal of human remains, grave-marker offenses, computer crimes, and regulated-drug fraud/deceit), certain regulated-drug offenses, and any offense for which the person received an unconditional pardon from the Governor. Do not route a felony as eligible unless the exact statute is on the qualifying list or the person has an unconditional pardon.",
  "DUI sealing (13 V.S.A. § 7602(e)): a qualifying DUI misdemeanor can be sealed 10 years after sentence completion if the person is NOT a commercial driver's license or commercial-permit holder and the prosecutor does not show sealing is contrary to the interests of justice. A DUI committed under age 25 may instead have a young-person sealing path under 33 V.S.A. § 5119.",
  "Non-conviction sealing: non-conviction records are now broadly sealable. The court should issue a sealing order within 60 days after final disposition, unless a party objects in the interests of justice, if the court did not find probable cause at arraignment, the charge was dismissed before trial (with or without prejudice), or the defendant was acquitted. A person may also petition at any time, and the court grants if sealing serves the interests of justice or if the parties stipulate.",
  "Young adult sealing — age 18–21 (13 V.S.A. § 7609): a person who was 18–21 when they committed a qualifying crime may petition to seal 30 days after completing the sentence; restitution and surcharges must be paid or waived and the prosecutor must not show sealing would be contrary to the interests of justice. A record containing both qualifying and nonqualifying offenses is not eligible under this section.",
  "Offenses committed before age 25 (33 V.S.A. § 5119(g)): the court shall seal a Vermont crime committed before age 25 if 2 years have passed since final discharge, there is no conviction/adjudication for a listed crime in the prior 10 years, there is no pending proceeding seeking such conviction/adjudication, and rehabilitation has been attained to the court's satisfaction. Check this path for anyone under 25 at the offense date even if the offense would not fit the normal adult qualifying-crime list.",
  "Juvenile sealing (33 V.S.A. § 5119): for delinquency matters adjudicated on or after July 1, 1996, Vermont generally seals the record 2 years after final discharge unless the State's Attorney objects and the court finds a listed-crime issue or lack of rehabilitation. Dismissed juvenile matters (charged on or after July 1, 2006 and before the age of majority) are sealed immediately on dismissal; older dismissed juvenile cases may be sealed 2 years after dismissal.",
  "Pending charges and re-filing: if the person has a pending criminal charge when the petition is before the court, the court cannot act until the new charge is resolved. If a petition is denied, the person generally must wait at least 2 years before filing another petition unless the court authorizes a shorter period. Always confirm there are no pending charges anywhere in Vermont before saying a petition is ready.",
  "Scope limits: Vermont relief does not erase private background-check copies that already exist, does not clear federal or out-of-state cases, and does not by itself fix immigration consequences; a sealed record is not destroyed and remains available for the statutory exceptions."
];
