// Vermont filing workflow. Sourced from the "Vermont Expungement & Sealing — Wilma
// Agent Training Reference" (Nationwide Record Clearing), section 13, corroborated
// by Vermont Judiciary guidance and 13 V.S.A. §§ 7601–7611. Vermont uses official
// Vermont Judiciary forms; this pack is shadow-only research and wires no renderer.
export const vtFilingInstructions = [
  "Get records first: the person needs the case/docket number, year of offense, offense description, conviction date, and related details. Court records can be requested using the Criminal Record Check Request (form 200-00331), and the Vermont Crime Information Center (VCIC) provides statewide conviction reports for a fee. The Vermont Judiciary's expungement/sealing page lists the official forms.",
  "Determine the route in order: (1) conviction or non-conviction? (2) if conviction, is the conduct no longer a crime (expungement)? (3) if not, is it a qualifying misdemeanor, qualifying felony, qualifying DUI, age 18–21 qualifying crime, under-25 offense, juvenile case, or unconditional pardon? (4) are restitution and surcharges paid or waived? (5) is there a pending charge? (6) will the prosecutor stipulate?",
  "Contact the prosecutor (State's Attorney or Attorney General's Office) to ask whether they will stipulate. If they stipulate, file the stipulation and petition (200-00132 to seal or 200-00132A to expunge) and the judge may review without a hearing. If they will not stipulate, file the petition; the court notifies the prosecutor, the prosecutor notifies any victim, and a hearing is scheduled if the prosecutor opposes.",
  "Use the correct petition: Petition to Expunge Criminal History (200-00129) for an expungement route, or Petition to Seal Criminal History (200-00130) for a sealing route; the general filing guide is 200-00130A. The prosecutor responds using Response to Petition to Expunge or Seal (200-00131).",
  "File in the Criminal Division of the Vermont Superior Court for the county/court that handled the case. If multiple offenses are from the same incident, one petition can cover them; unrelated offenses or offenses in multiple counties require separate petitions.",
  "Special routes: for a juvenile diversion expungement use Petition to Expunge — Juvenile Diversion (400-00171); for a special-index sealing use Request for Sealing Order in Special Index (200-00631).",
  "Fees: there is generally no filing fee to ask to seal or expunge a Vermont criminal record. The exception is sealing a DUI conviction (23 V.S.A. § 1201(a)) committed when the person was 25 or older — that route has a filing fee (the statutory court-fee provision lists it as $90), and a person can request a waiver using Application to Waive Filing Fees and Service Costs (600-00229).",
  "Order and notice: if granted, the court sends the order to the person and notifies VCIC, the arresting agency, the Restitution Unit, and any other entity that may have a record; VCIC then notifies the FBI's National Crime Information Center.",
  "Before saying a petition is ready, confirm there are no pending charges anywhere in Vermont and that, if a prior petition was denied, the 2-year re-filing wait (or a court-authorized shorter period) is satisfied."
];
