// South Dakota eligibility rules. Sourced from the South Dakota Expungement
// Reference for Wilma (Nationwide Record Clearing), corroborated by the cited
// South Dakota Codified Laws (SDCL) sections and South Dakota Unified Judicial
// System (UJS) / Department of Corrections guidance. Citations are SDCL unless
// noted.
export const sdEligibilityRules = [
  "South Dakota is NARROW: it is not a broad adult conviction-expungement state. Separate cases into adult arrest-record expungement (SDCL §§ 23A-3-26 to 23A-3-32; § 23A-3-27), diversion expungement (§§ 23A-3-35 to 23A-3-37), automatic minor-case public-record removal (§ 23A-3-34), suspended imposition of sentence sealing (§§ 23A-27-13 to 23A-27-17), the controlled-substance deferred route (§ 23A-27-53), pardon-based sealing (§ 24-14-11 / Chapter 24-14), juvenile delinquency sealing (§§ 26-7A-115 to 26-7A-116), and juvenile trafficking expungement (§ 26-7A-115.1). In South Dakota, expungement means the sealing of criminal records, and the statute specifically says expungement does NOT imply physical destruction of records.",
  "Adult arrest expungement (§ 23A-3-27): a person may apply to the court with jurisdiction over the crime for which they were arrested if (a) an arrest occurred but no accusatory instrument was filed — apply after 1 year from arrest; (b) the prosecutor formally dismissed the entire criminal case — apply after 1 year from formal dismissal; (c) the person was acquitted — apply any time after acquittal; or (d) the entire case was formally dismissed and there is compelling necessity — apply within 1 year from dismissal if compelling necessity is shown. The motion can be made only on a record of arrest, and more than one arrest record requires a separate case for each arrest record.",
  "Adult arrest expungement standard and service: the motion must be served on the prosecuting attorney (State's Attorney) at least 14 days before the hearing, and the prosecutor may contest. A hearing may be set unless waived by the arrested person/defendant, the prosecutor, and any victim. The court may enter an expungement order only after finding by CLEAR AND CONVINCING evidence that the ends of justice and the best interests of the public and the defendant or arrested person will be served (§ 23A-3-27).",
  "Effect of adult arrest expungement: the court reports the order to the Division of Criminal Investigation (DCI), which retains a nonpublic disposition record for use only by law enforcement, prosecutors, and courts for sentencing on later offenses; all other official records are sealed. The effect is to restore the person to the status occupied before the arrest, indictment, or information, and the person is not guilty of perjury or false statement for failing to disclose the arrest, indictment, information, or trial.",
  "Diversion expungement (§§ 23A-3-35 to 23A-3-37): a person who successfully completes a diversion program may be eligible for expungement of the entire criminal record related to the arrest if they are not charged with a new crime (other than petty offenses and minor traffic violations) within one year and thirty days after successful completion. If the requirements are met, the State's Attorney must file a dismissal of all charges related to the arrest and a notice that the person completed diversion; the court must then grant expungement without a motion or further court action.",
  "Automatic public-record removal for minor cases (§ 23A-3-34): South Dakota automatically removes certain minor cases from the public record after 5 years if all court-ordered conditions are satisfied and the person has no further convictions during that 5-year period. This applies when the highest charged offense was a petty offense, municipal ordinance violation, or Class 2 misdemeanor. The record is not gone for every purpose — it remains available to court personnel or by court order and may be used to enhance a penalty for a later criminal offense.",
  "Suspended imposition of sentence (SIS) sealing (§§ 23A-27-13 to 23A-27-17): for certain felonies not punishable by death or life imprisonment, a court may suspend imposition of sentence if the person has never before been convicted of a felony. After the person completes all conditions, the defendant is discharged and the case is dismissed without adjudication of guilt; the discharge and dismissal are not deemed a conviction for disqualifications or disabilities. South Dakota limits the benefit to once for felony SIS and once for misdemeanor SIS — a person may not receive a second felony SIS if they already had one. On discharge and dismissal, the court seals all official records other than the nonpublic DCI records.",
  "Controlled-substance deferred route (§ 23A-27-53): for a guilty plea to specified controlled-substance offenses, the court may defer sentencing and require probation, treatment, testing, service, or other conditions. After one year, if the person completed treatment and all required conditions, the court must dismiss the original charge when the person pleads guilty to the specified lesser offense. The person is not eligible if there are aggravating circumstances or if the person is serving a sentence with the executive branch.",
  "Pardon-based sealing (§ 24-14-11 / Chapter 24-14): a pardon releases the person from penalties and disabilities resulting from the offense. When the Governor grants a pardon under Chapter 24-14, the Governor orders related records sealed (a public document certifying the pardon stays filed with the Secretary of State for five years, then is sealed). South Dakota law does not allow sealing unless the pardon goes through the Chapter 24-14 Board of Pardons and Paroles process. A pardon is NOT expungement and may still count as a prior conviction for later sentencing, habitual-offender proceedings, and later DUI sentencing; DCI retains a nonpublic record.",
  "Juvenile delinquency sealing (§§ 26-7A-115 to 26-7A-116): a juvenile, parent, guardian, or guardian ad litem may petition to seal juvenile delinquency records only after one year has passed from the juvenile's unconditional release from court jurisdiction or DOC discharge, whichever is later. The court may seal if the child has not been adjudicated delinquent since release/discharge, has no pending or instituted serious proceeding of the listed types, and the court finds rehabilitation has been attained. After sealing, the record can still be used in certain juvenile proceedings or later criminal sentencing.",
  "Juvenile trafficking expungement (§ 26-7A-115.1): a child who was a victim of human trafficking or sexual exploitation may petition (directly or through a parent, guardian, or guardian ad litem) for expungement of a delinquency record that resulted from trafficking or sexual exploitation. Expungement under this statute vacates the underlying delinquency proceeding; route to legal aid or an attorney.",
  "Adult conviction limits: South Dakota generally has no broad adult conviction-expungement route. A conviction that is not clearly SIS-based, pardon-based, diversion-based, or minor-case automatic removal should be escalated for attorney review; any felony, DUI, domestic violence, sex offense, child-victim offense, violence, firearm, or protection-order matter is an escalation category.",
  "Scope limits: South Dakota relief does not remove federal/FBI records, clear tribal, military, or out-of-state convictions, automatically update private background-check copies, restore firearm rights, or fix immigration consequences; DCI retains nonpublic records for law enforcement, prosecutor, and court use even after sealing, and sealing is not destruction."
];
