// South Dakota filing workflow. Sourced from the South Dakota Expungement
// Reference for Wilma (Nationwide Record Clearing), sections 5, 7, 15,
// corroborated by SDCL § 23A-3-27 and the official South Dakota Unified Judicial
// System (UJS) expungement instructions (UJS-390) and forms (UJS-232, UJS-391
// through UJS-395). South Dakota uses the official UJS expungement packet; this
// pack is shadow-only research and wires no renderer.
export const sdFilingInstructions = [
  "Determine the pathway first: adult arrest-record expungement (SDCL § 23A-3-27 motion), diversion expungement (§§ 23A-3-35 to 23A-3-37, automatic), automatic minor-case removal (§ 23A-3-34, automatic after 5 years), suspended imposition of sentence sealing (§§ 23A-27-13 to 23A-27-17), controlled-substance deferred dismissal (§ 23A-27-53), pardon-based sealing (§ 24-14-11 / Chapter 24-14), or juvenile sealing/expungement (§§ 26-7A-115 to 26-7A-116; § 26-7A-115.1). Federal, tribal, military, and out-of-state records are not covered.",
  "Adult arrest expungement starts a NEW civil action filed in the same court that has jurisdiction over the underlying case or arrest. Confirm the correct court and county. The motion can be made only on a record of arrest, and more than one arrest record requires a separate case for each arrest record.",
  "Prepare the UJS expungement packet: UJS-390 (Instructions for Expungement), UJS-232 (Case Filing Statement), and UJS-391 (Motion for Expungement and Statement of Mailing). Attach the dismissal order, acquittal judgment, or proof that no accusatory instrument was filed.",
  "File the motion and case filing statement with the clerk where the arrest or case is filed and pay the $72 filing fee (the same as the civil filing fee), or request a fee waiver if indigent (the court may waive the fee on a finding of indigency).",
  "Serve the prosecuting attorney (State's Attorney): mail/serve the motion at least 14 days before the hearing. The prosecutor may contest the motion.",
  "Hearing: a hearing may be set unless waived by the arrested person/defendant, the prosecutor, and any victim. If a hearing is required, prepare UJS-393 (Notice of Hearing for Expungement) and serve it at least 14 days before the hearing. If all required parties waive, prepare UJS-392 (Waiver of Expungement Hearing). The court may require affidavits, testimony, or other evidence and decides by clear and convincing evidence.",
  "Order: prepare the proposed UJS-394 (Order of Expungement). After the order is signed, prepare and file UJS-395 (Notice of Entry of Expungement Order) and mail it with the order to the State's Attorney. The court reports the order to DCI, which retains a nonpublic record.",
  "Diversion expungement (§§ 23A-3-35 to 23A-3-37): after successful completion and the one-year-and-thirty-day clean window, the State's Attorney files the dismissal of all charges related to the arrest plus a notice of diversion completion; the court then grants expungement without a motion. Provide the diversion agreement and proof of successful completion.",
  "Suspended imposition of sentence (§§ 23A-27-13 to 23A-27-17): provide the SIS order, proof of completion of all conditions, and the discharge-and-dismissal order; on discharge, the court seals official records other than nonpublic DCI records. Warn that DCI retains a nonpublic record.",
  "Pardon-based sealing (§ 24-14-11 / Chapter 24-14): route through the Board of Pardons and Paroles application process; only a Governor's pardon under Chapter 24-14 triggers sealing. Prepare the pardon application materials and Board process documents, and warn that the pardoned offense can still count in later sentencing.",
  "Juvenile matters: for delinquency sealing (§§ 26-7A-115 to 26-7A-116) confirm 1 year has passed since unconditional release / DOC discharge, no later adjudication, no pending serious proceeding, and assemble rehabilitation evidence; for juvenile trafficking expungement (§ 26-7A-115.1) route to legal aid or an attorney."
];
