// Auto-generated by scripts/generate-all50-state-pack-batch.mjs.
// Build-first metadata is sourced from private/Nationwide Record Clearing.
// QA, visual review, counsel review, and source freshness review are tracked
// separately and do not block ordinary RCAP build work.

export const dcAll50BuildMetadata = {
  "jurisdiction": {
    "code": "DC",
    "name": "District of Columbia",
    "slug": "dc",
    "sourceFolders": [
      "LegalEase DC"
    ]
  },
  "products": [
    "record_clearing_guidance_packet",
    "official_pdf_overlay_draft",
    "custom_pleading_or_state_pack_draft"
  ],
  "pathways": [
    {
      "id": "record_clearing_review",
      "label": "District of Columbia record-clearing review",
      "output": "guidance_packet",
      "reviewRequiredBeforeLive": true
    },
    {
      "id": "official_form_overlay",
      "label": "District of Columbia official form overlay draft",
      "output": "official_pdf_overlay_draft",
      "reviewRequiredBeforeLive": true
    },
    {
      "id": "custom_pleading",
      "label": "District of Columbia custom pleading draft",
      "output": "custom_pleading_or_state_pack_draft",
      "reviewRequiredBeforeLive": true
    }
  ],
  "requiredUserInputs": [
    "participant_full_legal_name",
    "date_of_birth_if_required_by_selected_form",
    "contact_information",
    "case_number",
    "court_or_agency_name",
    "county_or_filing_location",
    "charge_or_record_description",
    "case_outcome",
    "disposition_date_if_known",
    "sentence_completion_or_supervision_status_if_applicable",
    "records_or_background_report_if_available"
  ],
  "filingDestinationGuidance": [
    "Use the court, clerk, agency, or official filing destination identified in the selected Nationwide resource packet or official form.",
    "If the correct filing destination is unclear, keep the packet guidance-only and flag the state for post-build QA/attorney review.",
    "Do not invent clerk addresses, agency addresses, local fees, or service rules."
  ],
  "filingSteps": [
    "Confirm the record-clearing pathway from the participant's answers and available source packet.",
    "Collect required user inputs and mark unknown information plainly.",
    "Select official form overlay, custom pleading, or guidance-only fallback.",
    "Generate internal review packet and source inventory artifact.",
    "Route to QA, visual review when an official PDF overlay exists, and counsel review before live use."
  ],
  "feesCopiesServiceNotes": [
    "Use fee, copy, and service notes only when present in the Nationwide source packet or official form.",
    "When fee/copy/service information is absent or unclear, state that the participant should verify current local requirements with the filing court or agency.",
    "Do not treat missing fee data as a blocker for guidance fallback generation."
  ],
  "officialFormInventory": [
    {
      "fileName": "23-110_Motion.pdf",
      "relativePath": "LegalEase DC/23-110_Motion.pdf",
      "sha256": "bf17ab93b780ffa4e61f63141113d2ad2d4d696421e3578651c93b4403d6a253",
      "sizeBytes": 104796
    },
    {
      "fileName": "How_to_file_a_motion_to_seal.pdf",
      "relativePath": "LegalEase DC/How_to_file_a_motion_to_seal.pdf",
      "sha256": "310381f170d1875ef7a40e9e71c8653c1ea5c847628a6c718ea9016c0e312712",
      "sizeBytes": 47232
    }
  ],
  "resourcePacketInventory": [
    {
      "fileName": "DC Expungement : Record Sealing Reference for Wilma.rtf",
      "relativePath": "LegalEase DC/DC Expungement : Record Sealing Reference for Wilma.rtf",
      "classification": "reference",
      "sha256": "dd58fc73206bf30bf54c236b46630e5cddf01aaccc34b85a57fdb54f97dc8c85",
      "sizeBytes": 61930
    }
  ],
  "customPleadingSupport": {
    "supported": true,
    "status": "draft_config_allowed",
    "notes": "Pleading-style draft support may be built from Nationwide resources and coded state-pack data where available."
  },
  "guidanceOnlyFallback": {
    "supported": true,
    "label": "District of Columbia record-clearing guidance fallback",
    "status": "built",
    "notes": "Available for internal review even when official forms or pleading templates need more work."
  },
  "disclaimer": "This RCAP build artifact is for internal document-preparation and review workflows. It is not legal advice, does not guarantee eligibility or outcomes, and is not approved for live use until QA, counsel, and any required visual review pass.",
  "buildStatusMetadata": {
    "buildStatus": "state_built",
    "statusHistory": [
      "not_started",
      "nationwide_resources_found",
      "resource_packet_ingested",
      "official_forms_ingested",
      "overlay_field_maps_drafted",
      "overlay_samples_rendered",
      "state_pack_built",
      "pleading_packet_rendered",
      "guidance_packet_rendered",
      "state_built"
    ],
    "reviewStatuses": {
      "qa": "pending",
      "visual": "pending",
      "counsel": "pending",
      "sourceFreshness": "pending"
    },
    "loops": [
      {
        "id": "nationwide_folder_ingestion_loop",
        "status": "completed"
      },
      {
        "id": "all_state_build_loop",
        "status": "completed"
      },
      {
        "id": "official_pdf_overlay_factory_loop",
        "status": "draft_ready"
      },
      {
        "id": "field_map_retry_loop",
        "status": "pending_retry_artifacts"
      },
      {
        "id": "custom_pleading_factory_loop",
        "status": "draft_ready"
      },
      {
        "id": "guidance_packet_loop",
        "status": "completed"
      },
      {
        "id": "packet_render_qa_loop",
        "status": "pending_review"
      },
      {
        "id": "review_artifact_loop",
        "status": "completed"
      },
      {
        "id": "integration_preview_loop",
        "status": "internal_preview_ready"
      },
      {
        "id": "official_forms_watcher_loop",
        "status": "source_tracked"
      }
    ],
    "liveRouting": {
      "approvedForLive": false,
      "live": false,
      "note": "Build-first state output is internal review material only."
    }
  },
  "buildIssues": []
} as const;
