// Auto-generated by scripts/generate-all50-state-pack-batch.mjs.
// Build-first metadata is sourced from private/Nationwide Record Clearing.
// QA, visual review, counsel review, and source freshness review are tracked
// separately and do not block ordinary RCAP build work.

export const washingtonAll50BuildMetadata = {
  "jurisdiction": {
    "code": "WA",
    "name": "Washington",
    "slug": "washington",
    "sourceFolders": [
      "LegalEase Washington"
    ]
  },
  "products": [
    "record_clearing_guidance_packet",
    "official_pdf_overlay_draft",
    "custom_pleading_or_state_pack_draft"
  ],
  "pathways": [
    {
      "id": "record_clearing_review",
      "label": "Washington record-clearing review",
      "output": "guidance_packet",
      "reviewRequiredBeforeLive": true
    },
    {
      "id": "official_form_overlay",
      "label": "Washington official form overlay draft",
      "output": "official_pdf_overlay_draft",
      "reviewRequiredBeforeLive": true
    },
    {
      "id": "custom_pleading",
      "label": "Washington custom pleading draft",
      "output": "custom_pleading_or_state_pack_draft",
      "reviewRequiredBeforeLive": true
    }
  ],
  "requiredUserInputs": [
    "participant_full_legal_name",
    "date_of_birth_if_required_by_selected_form",
    "contact_information",
    "case_number",
    "court_or_agency_name",
    "county_or_filing_location",
    "charge_or_record_description",
    "case_outcome",
    "disposition_date_if_known",
    "sentence_completion_or_supervision_status_if_applicable",
    "records_or_background_report_if_available"
  ],
  "filingDestinationGuidance": [
    "Use the court, clerk, agency, or official filing destination identified in the selected Nationwide resource packet or official form.",
    "If the correct filing destination is unclear, keep the packet guidance-only and flag the state for post-build QA/attorney review.",
    "Do not invent clerk addresses, agency addresses, local fees, or service rules."
  ],
  "filingSteps": [
    "Confirm the record-clearing pathway from the participant's answers and available source packet.",
    "Collect required user inputs and mark unknown information plainly.",
    "Select official form overlay, custom pleading, or guidance-only fallback.",
    "Generate internal review packet and source inventory artifact.",
    "Route to QA, visual review when an official PDF overlay exists, and counsel review before live use."
  ],
  "feesCopiesServiceNotes": [
    "Use fee, copy, and service notes only when present in the Nationwide source packet or official form.",
    "When fee/copy/service information is absent or unclear, state that the participant should verify current local requirements with the filing court or agency.",
    "Do not treat missing fee data as a blocker for guidance fallback generation."
  ],
  "officialFormInventory": [
    {
      "fileName": "CR08.0900_Mt and Decl for Or Vacating Record of Felony_2025 07.pdf",
      "relativePath": "LegalEase Washington/CR08.0900_Mt and Decl for Or Vacating Record of Felony_2025 07.pdf",
      "sha256": "ec8b175e3a2ccfdf247328822b7ed8ac570dacd27c8b728d09a10eca05c6559e",
      "sizeBytes": 133614
    },
    {
      "fileName": "CR08.0920_Order re Vacating Record of Felony Conviction 2025 07.pdf",
      "relativePath": "LegalEase Washington/CR08.0920_Order re Vacating Record of Felony Conviction 2025 07.pdf",
      "sha256": "e5ccd2e0847fc9b0c2b54ef4ff75fd8d500b7b2af5a9eed963dd3855bb0226db",
      "sizeBytes": 160031
    },
    {
      "fileName": "CR08.0930_Vacating Record of Felony Conviction_2023 01.pdf",
      "relativePath": "LegalEase Washington/CR08.0930_Vacating Record of Felony Conviction_2023 01.pdf",
      "sha256": "17e2fdfceb0823387f25dd285276c2b06778f73e10d76180dfb2ee2d6f030a00",
      "sizeBytes": 135696
    },
    {
      "fileName": "CrRLJ 09_0150 Notice of Hearing_2019 07.pdf",
      "relativePath": "LegalEase Washington/CrRLJ 09_0150 Notice of Hearing_2019 07.pdf",
      "sha256": "5bf278480630d1487e97dea92a00008b2436d1d57bf63c720da0e62c246aff69",
      "sizeBytes": 105414
    },
    {
      "fileName": "CrRLJ 09.0100 Petition to Vacate Conviction_(f)(U).pdf",
      "relativePath": "LegalEase Washington/CrRLJ 09.0100 Petition to Vacate Conviction_(f)(U).pdf",
      "sha256": "1f72e901e93d576cf6c7ecad910d253da65b6af1a89ca75304c9739fa159909b",
      "sizeBytes": 161259
    },
    {
      "fileName": "CrRLJ 09.0200 Ord Pet Vacate Conviction_(f)(U).pdf",
      "relativePath": "LegalEase Washington/CrRLJ 09.0200 Ord Pet Vacate Conviction_(f)(U).pdf",
      "sha256": "b53035ddc5ea31aa9bd6816d5f157a58c8c8201db8e4a2cbb15f9874b4c851f2",
      "sizeBytes": 160460
    },
    {
      "fileName": "CrRLJ 09.0300 InstructVacateMisdConvictions_2022 07.pdf",
      "relativePath": "LegalEase Washington/CrRLJ 09.0300 InstructVacateMisdConvictions_2022 07.pdf",
      "sha256": "42ac9ccb16474172ee3b4076b416e9d949c2dfdbb43edc0cdc734eca299f4176",
      "sizeBytes": 128109
    },
    {
      "fileName": "CrRLJ 09.0800 PetitionDeclVacateConviction_Cannabis_2022 07(2).pdf",
      "relativePath": "LegalEase Washington/CrRLJ 09.0800 PetitionDeclVacateConviction_Cannabis_2022 07(2).pdf",
      "sha256": "260367f6930cacc89727fc8a48aa0591b07ad5c7183b6412aa247b1810503d7b",
      "sizeBytes": 57643
    },
    {
      "fileName": "CrRLJ 09.0870 OrderPetVacateConviction_Cannabis_2022 07(2).pdf",
      "relativePath": "LegalEase Washington/CrRLJ 09.0870 OrderPetVacateConviction_Cannabis_2022 07(2).pdf",
      "sha256": "a69335fbbf311f4c92357db5ecb38f931b3409e14f987810247faae2f6295cc3",
      "sizeBytes": 136567
    },
    {
      "fileName": "JU 10_0320 Order re Sealing Records of Juvenile Offender_2022 01.pdf",
      "relativePath": "LegalEase Washington/JU 10_0320 Order re Sealing Records of Juvenile Offender_2022 01.pdf",
      "sha256": "bbe5a288b36a91b71cadbf1279ad6e10bfcc75732c2ef64bb5c21bc2d3ab5d86",
      "sizeBytes": 136817
    }
  ],
  "resourcePacketInventory": [
    {
      "fileName": "CrRLJ CR 09_0500 Motion and Decl Vacate Conv Treaty Indian Fishing rights.doc",
      "relativePath": "LegalEase Washington/CrRLJ CR 09_0500 Motion and Decl Vacate Conv Treaty Indian Fishing rights.doc",
      "classification": "document",
      "sha256": "59d91eb42c66b0361ff53d01fe0b0eceadf7d7e1cbf6a19d4087705353f10eed",
      "sizeBytes": 71680
    },
    {
      "fileName": "CrRLJ CR 09_0600 Notice of Hearing.doc",
      "relativePath": "LegalEase Washington/CrRLJ CR 09_0600 Notice of Hearing.doc",
      "classification": "document",
      "sha256": "61e81ab4f30c5c04d8ad5cbb1f1958df826bc1f1ecf4f1a7199d5985cf09446c",
      "sizeBytes": 41472
    },
    {
      "fileName": "CrRLJ CR 09_0700 Or Vacating Conv treaty Indian Fishing Rights_final.doc",
      "relativePath": "LegalEase Washington/CrRLJ CR 09_0700 Or Vacating Conv treaty Indian Fishing Rights_final.doc",
      "classification": "document",
      "sha256": "f70ff836843b32ca2629656662c5049b637b2f078bc97058ad1b3fa63bede3cb",
      "sizeBytes": 60928
    },
    {
      "fileName": "JU10_0300_MTAFseal.doc",
      "relativePath": "LegalEase Washington/JU10_0300_MTAFseal.doc",
      "classification": "document",
      "sha256": "bc9d5cbe59d58cb6c82c57d88832c92fd46dd3899ca0bd0aa7d75075e82ebd7b",
      "sizeBytes": 40448
    },
    {
      "fileName": "JU10_0315_NT of Resp MT to Seal Records of JU Offender  13.50.050.doc",
      "relativePath": "LegalEase Washington/JU10_0315_NT of Resp MT to Seal Records of JU Offender  13.50.050.doc",
      "classification": "document",
      "sha256": "d554d3f42dcd69127540094fdaf402b75966a797833179d34812488c0ccab836",
      "sizeBytes": 62976
    },
    {
      "fileName": "Washington State Record Relief — Wilma Agent Training Reference.rtf",
      "relativePath": "LegalEase Washington/Washington State Record Relief — Wilma Agent Training Reference.rtf",
      "classification": "reference",
      "sha256": "9a14bc117ea18aa7c6ba978a1c1052cadac7afb89e3845b156f474e38869410d",
      "sizeBytes": 84188
    }
  ],
  "customPleadingSupport": {
    "supported": true,
    "status": "draft_config_allowed",
    "notes": "Pleading-style draft support may be built from Nationwide resources and coded state-pack data where available."
  },
  "guidanceOnlyFallback": {
    "supported": true,
    "label": "Washington record-clearing guidance fallback",
    "status": "built",
    "notes": "Available for internal review even when official forms or pleading templates need more work."
  },
  "disclaimer": "This RCAP build artifact is for internal document-preparation and review workflows. It is not legal advice, does not guarantee eligibility or outcomes, and is not approved for live use until QA, counsel, and any required visual review pass.",
  "buildStatusMetadata": {
    "buildStatus": "state_built",
    "statusHistory": [
      "not_started",
      "nationwide_resources_found",
      "resource_packet_ingested",
      "official_forms_ingested",
      "overlay_field_maps_drafted",
      "overlay_samples_rendered",
      "state_pack_built",
      "pleading_packet_rendered",
      "guidance_packet_rendered",
      "state_built"
    ],
    "reviewStatuses": {
      "qa": "pending",
      "visual": "pending",
      "counsel": "pending",
      "sourceFreshness": "pending"
    },
    "loops": [
      {
        "id": "nationwide_folder_ingestion_loop",
        "status": "completed"
      },
      {
        "id": "all_state_build_loop",
        "status": "completed"
      },
      {
        "id": "official_pdf_overlay_factory_loop",
        "status": "draft_ready"
      },
      {
        "id": "field_map_retry_loop",
        "status": "pending_retry_artifacts"
      },
      {
        "id": "custom_pleading_factory_loop",
        "status": "draft_ready"
      },
      {
        "id": "guidance_packet_loop",
        "status": "completed"
      },
      {
        "id": "packet_render_qa_loop",
        "status": "pending_review"
      },
      {
        "id": "review_artifact_loop",
        "status": "completed"
      },
      {
        "id": "integration_preview_loop",
        "status": "internal_preview_ready"
      },
      {
        "id": "official_forms_watcher_loop",
        "status": "source_tracked"
      }
    ],
    "liveRouting": {
      "approvedForLive": false,
      "live": false,
      "note": "Build-first state output is internal review material only."
    }
  },
  "buildIssues": []
} as const;
