// Washington disqualifying offenses and escalation/blocks. Sourced from the
// "Washington State Record Relief — Wilma Agent Training Reference" (Nationwide
// Record Clearing), sections 4–6 and 9, reflecting the RCW 9.96.060 misdemeanor
// bars, the RCW 9.94A.640 felony bars, and the attorney-escalation flags. Screening
// notes, not an exhaustive legal test; verify the exact current RCW text.
export const waDisqualifyingOffenseNotes = [
  "Misdemeanor/gross-misdemeanor vacation bars (RCW 9.96.060): incomplete sentence; pending criminal charges in Washington, another state, federal, or tribal court; violent misdemeanor/gross-misdemeanor offenses and attempts; chapter 9.68, 9.68A, and 9A.44 sex/obscenity/child-exploitation offenses (except failure to register); a new conviction in the prior 3 years; and current qualifying protection/no-contact/anti-harassment/civil restraining orders or recent violations. Vacation does not automatically restore firearm rights.",
  "DUI / prior-offense exclusion (RCW 9.96.060): DUI, actual physical control, railroad intoxication, and certain prior-offense cases are excluded where there has been a later alcohol/drug violation within 10 years or less than 10 years has passed since the prior-offense arrest.",
  "Felony vacation bars (RCW 9.94A.640): Class A felonies are not available under the normal route; pending charges in Washington, another state, or federal court block; violent offenses and crimes against persons are usually barred (except Assault 2, certain Assault 3, and Robbery 2 with no firearm/deadly-weapon/sexual-motivation enhancement); felony DUI/physical control is barred; and the Class B 10-year / Class C 5-year wait and clean-period requirements must be met.",
  "Non-conviction deletion refusal factors (RCW 10.97.060): the agency may refuse deletion if the disposition was a deferred prosecution or similar diversion, the person has a prior felony or gross-misdemeanor conviction, or the person was arrested for or charged with another crime during the intervening period; deletion is also unavailable while the person is a fugitive or the case is under active prosecution.",
  "Domestic violence (RCW 9.96.060): DV misdemeanors are a manual-review category — written notice to the prosecuting attorney is required, two or more DV convictions from different incidents and failure to truthfully disclose prior DV convictions can block, and a 5-year completion period (including treatment) applies.",
  "Juvenile sealing limits (RCW 13.50.260): administrative sealing is not scheduled for a most-serious offense, a sex offense under chapter 9A.44, or a drug offense under RCW 9.94A.030; motion sealing requires the crime-free community period (5 years Class A / 2 years others), no pending proceeding/diversion, no active registration duty, and payment of restitution to the individual victim.",
  "Escalation categories (legal review): any felony (class/RCW and discharge analysis); violent offenses or crimes against persons; DUI/physical-control/prior-offense matters; domestic violence; sex, child-exploitation, obscenity, or sexually motivated offenses; firearm/deadly-weapon-enhanced offenses; protection/no-contact-order issues; victim/survivor vacation; Blake refunds; juvenile sealing edge cases; and firearm-rights, immigration, or licensing questions.",
  "Scope limits: a Washington vacate order does not delete the court record or remove it from court indexes/public court websites, does not automatically restore firearm rights, and does not by itself fix immigration, licensing, or FBI/private-background-check exposure."
];
