// Washington eligibility rules. Sourced from the "Washington State Record Relief —
// Wilma Agent Training Reference" (Nationwide Record Clearing / LegalEase
// Washington), corroborated by the cited Revised Code of Washington (RCW) sections
// and Washington Courts / Washington State Patrol (WSP) / Washington LawHelp
// guidance. Citations are RCW unless otherwise noted.
export const waEligibilityRules = [
  "Washington is NOT a normal adult expungement state. For adult convictions the usual remedy is VACATING the conviction, not destroying or sealing the record. Vacation cancels the judgment and lets the person say they were not convicted of that offense, but it does NOT make the court record private and there is no general Washington law allowing deletion/destruction of adult conviction records. Distinguish adult misdemeanor/gross-misdemeanor vacation (RCW 9.96.060), adult felony vacation (RCW 9.94A.640), non-conviction deletion (RCW 10.97.060), Blake drug-possession vacatur/refund, cannabis vacation, victim/survivor vacation (RCW 9.96.080; RCW 9.94A.648), and juvenile sealing (RCW 13.50.260).",
  "Adult misdemeanor / gross-misdemeanor vacation (RCW 9.96.060): apply to the sentencing court; the court has discretion if the statutory requirements are met. Confirm all sentence terms are complete (including financial obligations unless a special route applies), no pending criminal charges in Washington/another state/federal/tribal court, the offense is not a barred violent offense, and the ordinary 3-year waiting period (from the later of release from supervision/probation, release from confinement, or sentencing date) with no new conviction in the prior 3 years. A current qualifying protection/no-contact/anti-harassment/civil restraining order, or a recent violation, can block relief. Vacation does NOT automatically restore firearm rights.",
  "Domestic violence misdemeanor/gross-misdemeanor vacation (RCW 9.96.060): DV misdemeanors are not automatically barred but have stricter rules — written notice to the prosecuting attorney; check whether the person has two or more DV convictions from different incidents; whether they truthfully disclosed prior DV convictions; and whether at least 5 years have passed since completing original sentence conditions including treatment, excluding payment of financial obligations. DV cases are a manual-review category.",
  "DUI / prior-offense exclusion (RCW 9.96.060): DUI, actual physical control, railroad intoxication, and certain prior-offense cases are excluded where there has been a later alcohol/drug violation within 10 years or less than 10 years has passed since the prior-offense arrest. Ask whether the conviction was DUI, physical control, reckless driving reduced from DUI, negligent driving 1st, or another alcohol/drug driving-related prior offense.",
  "Adult felony vacation (RCW 9.94A.640): the person generally must first be discharged under RCW 9.94A.637, then apply to the sentencing court. Class A felonies are not available under this route. Class B felonies require a 10-year wait (from the latest of release from community custody, release from confinement, or sentencing date) and no new conviction in the prior 10 years; Class C felonies require a 5-year wait with no new conviction in the prior 5 years. Violent offenses and crimes against persons are usually barred, except that Assault 2, certain Assault 3, and Robbery 2 may be vacated if there was no firearm, deadly weapon, or sexual-motivation enhancement. Felony DUI/physical control is barred. Use the offense class and exact RCW; do not route on 'felony' or 'nonviolent' as described by the user.",
  "Non-conviction deletion (RCW 10.97.060): Washington's deletion route is mainly for NON-CONVICTION data, not adult convictions. Non-conviction criminal-history record information may be deleted from generally searched criminal-justice files when 2+ years have passed since favorable disposition, or 3 years from arrest/citation/warrant where no conviction was obtained, unless the person is a fugitive or the case is under active prosecution. The agency may refuse deletion if the disposition was a deferred prosecution or similar diversion, the person has a prior felony or gross-misdemeanor conviction, or the person was arrested/charged with another crime during the intervening period. If charges were dismissed, the person was acquitted, or no charges were filed, check non-conviction deletion, not conviction vacation.",
  "Blake drug-possession vacation and refunds: under State v. Blake, simple drug-possession convictions under RCW 69.50.4013 or RCW 69.50.4014, predecessor statutes, similar local ordinances, and certain inchoate offenses are unconstitutionally void and must be vacated, with paid legal financial obligations (LFOs) and accrued interest refunded. Washington Courts provides Blake-specific motions and orders for superior, district, and municipal courts. This is not a normal waiting-period route; eligibility is based on the void-conviction category.",
  "Misdemeanor cannabis vacation (RCW 9.96.060): a person who was 21 or older at the time of a misdemeanor cannabis offense (RCW 69.50.4014 from July 1, 2004 onward, specified predecessor statutes, and equivalent municipal ordinances) may apply to the sentencing court, and if the applicant qualifies the court SHALL vacate the record. Cannabis vacation is not the same as Blake drug-possession relief.",
  "Victim/survivor vacation: special routes apply when the conviction was committed as a result of being a victim of sex trafficking, prostitution, commercial sexual abuse of a minor, sexual assault, or domestic violence. For misdemeanors/gross misdemeanors, RCW 9.96.080 allows the victim or prosecutor to apply with an affidavit proving the victimization connection by a preponderance of the evidence, no pending charges other than prostitution, the new-conviction rules, and victim-penalty-assessment/restitution requirements (with exceptions). For Class B/C felonies, RCW 9.94A.648 allows a similar route with 5-year (Class C) or 10-year (Class B) new-offense rules and the same proof, payment, and exclusion structure. Route to manual/legal review and do not ask for graphic details.",
  "Juvenile record sealing (RCW 13.50.260): courts hold administrative sealing hearings scheduled after the latest of the respondent's 18th birthday, anticipated end of probation, or anticipated release/completion of parole; administrative sealing is not scheduled for a most-serious offense, a sex offense (chapter 9A.44), or a drug offense (RCW 9.94A.030). Acquittal after fact-finding or dismissal with prejudice triggers immediate sealing. Motion-based sealing requires 5 consecutive crime-free years for Class A offenses (with additional conditions) and 2 consecutive years for Class B/C, gross misdemeanor, misdemeanor, and diversion records, plus payment of restitution to the individual victim and no disqualifying registration/pending-proceeding issues.",
  "Scope limits: a Washington vacate order does not delete the court record or remove it from court indexes/public court websites, does not automatically restore firearm rights, and does not by itself fix immigration, licensing, or FBI/private-background-check exposure. A separate firearm-rights restoration process exists."
];
