// Auto-generated by scripts/generate-all50-state-pack-batch.mjs.
// Build-first metadata is sourced from private/Nationwide Record Clearing.
// QA, visual review, counsel review, and source freshness review are tracked
// separately and do not block ordinary RCAP build work.

export const northDakotaAll50BuildMetadata = {
  "jurisdiction": {
    "code": "ND",
    "name": "North Dakota",
    "slug": "north-dakota",
    "sourceFolders": [
      "LegalEase North Dakota"
    ]
  },
  "products": [
    "record_clearing_guidance_packet",
    "official_pdf_overlay_draft",
    "custom_pleading_or_state_pack_draft"
  ],
  "pathways": [
    {
      "id": "record_clearing_review",
      "label": "North Dakota record-clearing review",
      "output": "guidance_packet",
      "reviewRequiredBeforeLive": true
    },
    {
      "id": "official_form_overlay",
      "label": "North Dakota official form overlay draft",
      "output": "official_pdf_overlay_draft",
      "reviewRequiredBeforeLive": true
    },
    {
      "id": "custom_pleading",
      "label": "North Dakota custom pleading draft",
      "output": "custom_pleading_or_state_pack_draft",
      "reviewRequiredBeforeLive": true
    }
  ],
  "requiredUserInputs": [
    "participant_full_legal_name",
    "date_of_birth_if_required_by_selected_form",
    "contact_information",
    "case_number",
    "court_or_agency_name",
    "county_or_filing_location",
    "charge_or_record_description",
    "case_outcome",
    "disposition_date_if_known",
    "sentence_completion_or_supervision_status_if_applicable",
    "records_or_background_report_if_available"
  ],
  "filingDestinationGuidance": [
    "Use the court, clerk, agency, or official filing destination identified in the selected Nationwide resource packet or official form.",
    "If the correct filing destination is unclear, keep the packet guidance-only and flag the state for post-build QA/attorney review.",
    "Do not invent clerk addresses, agency addresses, local fees, or service rules."
  ],
  "filingSteps": [
    "Confirm the record-clearing pathway from the participant's answers and available source packet.",
    "Collect required user inputs and mark unknown information plainly.",
    "Select official form overlay, custom pleading, or guidance-only fallback.",
    "Generate internal review packet and source inventory artifact.",
    "Route to QA, visual review when an official PDF overlay exists, and counsel review before live use."
  ],
  "feesCopiesServiceNotes": [
    "Use fee, copy, and service notes only when present in the Nationwide source packet or official form.",
    "When fee/copy/service information is absent or unclear, state that the participant should verify current local requirements with the filing court or agency.",
    "Do not treat missing fee data as a blocker for guidance fallback generation."
  ],
  "officialFormInventory": [
    {
      "fileName": "1. N of Motion to Prohibit Public Access AR41 5f1.pdf",
      "relativePath": "LegalEase North Dakota/1. N of Motion to Prohibit Public Access AR41 5f1.pdf",
      "sha256": "a85f5ca2b8514491838246fbb56bfa90aaaf8063388ca116857ff4e9af1a8903",
      "sizeBytes": 1208303
    },
    {
      "fileName": "10. Confidential Info Form AR41 5f1.pdf",
      "relativePath": "LegalEase North Dakota/10. Confidential Info Form AR41 5f1.pdf",
      "sha256": "ede55c05a3cb7b57d5b85b939be6f042b48483b33f779df5bd50887d26f10790",
      "sizeBytes": 1236475
    },
    {
      "fileName": "2. Motion to Prohibit Public Access AR41 5f1.pdf",
      "relativePath": "LegalEase North Dakota/2. Motion to Prohibit Public Access AR41 5f1.pdf",
      "sha256": "0326913ada876838b1f9a294cb0d1fe1d2446f46f7d4f878bd2e110f56b9b2b8",
      "sizeBytes": 1244725
    },
    {
      "fileName": "3. Brief Prohibit Public Access AR41 5f1.pdf",
      "relativePath": "LegalEase North Dakota/3. Brief Prohibit Public Access AR41 5f1.pdf",
      "sha256": "44bf8283ac6b042689843335e37d64cf632c647f4f606036eeb412bded7387b4",
      "sizeBytes": 1425955
    },
    {
      "fileName": "4. Declaration Prohibit Public Access AR41 5f1.pdf",
      "relativePath": "LegalEase North Dakota/4. Declaration Prohibit Public Access AR41 5f1.pdf",
      "sha256": "af76c52d1f9aa8b2e986fbd719655c8e3a1f1b8158f5f606d4a6da25d3465e5b",
      "sizeBytes": 1288096
    },
    {
      "fileName": "5. Findings Concl Order Prohibit Public Access AR41 5f1.pdf",
      "relativePath": "LegalEase North Dakota/5. Findings Concl Order Prohibit Public Access AR41 5f1.pdf",
      "sha256": "47dafce1f10f1972d505e6d988ee05c74421c93be02cddcbb26f15312bfb8d2d",
      "sizeBytes": 1675405
    },
    {
      "fileName": "6. Affidavit Service Mail Motion AR41 5f1.pdf",
      "relativePath": "LegalEase North Dakota/6. Affidavit Service Mail Motion AR41 5f1.pdf",
      "sha256": "9070a339facab5a2c2a15a453ab468dfdf915a531f798c5d02b14c2a2864fe23",
      "sizeBytes": 1291529
    },
    {
      "fileName": "Close-Nonconviction-Records.pdf",
      "relativePath": "LegalEase North Dakota/Close-Nonconviction-Records.pdf",
      "sha256": "21b3a790b35f35c345560d9840bf39ca6f1e46cf1b9166c0e5ae2cf8ff7e4d7f",
      "sizeBytes": 1319263
    },
    {
      "fileName": "Expungement.pdf",
      "relativePath": "LegalEase North Dakota/Expungement.pdf",
      "sha256": "40fd33d0fece1fe31587208a22e549f816c24f71c00c71b4a1d76409109f930f",
      "sizeBytes": 274927
    },
    {
      "fileName": "Sealing Criminal Records Research Guide.pdf",
      "relativePath": "LegalEase North Dakota/Sealing Criminal Records Research Guide.pdf",
      "sha256": "b39a0c1532bff3381382544a3888478835edb2109af597a2468a34e2a5f19a3c",
      "sizeBytes": 303777
    },
    {
      "fileName": "Sealing-DUI-Records-Research-Guide.pdf",
      "relativePath": "LegalEase North Dakota/Sealing-DUI-Records-Research-Guide.pdf",
      "sha256": "a3dd1b924bedad7c8ba0b77742bcd99ef6855a1b05021374b7083f1b445e1264",
      "sizeBytes": 222600
    }
  ],
  "resourcePacketInventory": [
    {
      "fileName": "North Dakota Expungement : Sealing Reference for Wilma.rtf",
      "relativePath": "LegalEase North Dakota/North Dakota Expungement : Sealing Reference for Wilma.rtf",
      "classification": "reference",
      "sha256": "68c9109532391768ba04b29801f6e7ed4dbee4e2905b9a79bb162b4cd7905a68",
      "sizeBytes": 89056
    }
  ],
  "customPleadingSupport": {
    "supported": true,
    "status": "draft_config_allowed",
    "notes": "Pleading-style draft support may be built from Nationwide resources and coded state-pack data where available."
  },
  "guidanceOnlyFallback": {
    "supported": true,
    "label": "North Dakota record-clearing guidance fallback",
    "status": "built",
    "notes": "Available for internal review even when official forms or pleading templates need more work."
  },
  "disclaimer": "This RCAP build artifact is for internal document-preparation and review workflows. It is not legal advice, does not guarantee eligibility or outcomes, and is not approved for live use until QA, counsel, and any required visual review pass.",
  "buildStatusMetadata": {
    "buildStatus": "state_built",
    "statusHistory": [
      "not_started",
      "nationwide_resources_found",
      "resource_packet_ingested",
      "official_forms_ingested",
      "overlay_field_maps_drafted",
      "overlay_samples_rendered",
      "state_pack_built",
      "pleading_packet_rendered",
      "guidance_packet_rendered",
      "state_built"
    ],
    "reviewStatuses": {
      "qa": "pending",
      "visual": "pending",
      "counsel": "pending",
      "sourceFreshness": "pending"
    },
    "loops": [
      {
        "id": "nationwide_folder_ingestion_loop",
        "status": "completed"
      },
      {
        "id": "all_state_build_loop",
        "status": "completed"
      },
      {
        "id": "official_pdf_overlay_factory_loop",
        "status": "draft_ready"
      },
      {
        "id": "field_map_retry_loop",
        "status": "pending_retry_artifacts"
      },
      {
        "id": "custom_pleading_factory_loop",
        "status": "draft_ready"
      },
      {
        "id": "guidance_packet_loop",
        "status": "completed"
      },
      {
        "id": "packet_render_qa_loop",
        "status": "pending_review"
      },
      {
        "id": "review_artifact_loop",
        "status": "completed"
      },
      {
        "id": "integration_preview_loop",
        "status": "internal_preview_ready"
      },
      {
        "id": "official_forms_watcher_loop",
        "status": "source_tracked"
      }
    ],
    "liveRouting": {
      "approvedForLive": false,
      "live": false,
      "note": "Build-first state output is internal review material only."
    }
  },
  "buildIssues": []
} as const;
