export const ndEligibilityRules = [
  "North Dakota is a sealing-first state, not a broad expungement state. Under N.D.C.C. Chapter 12-60.1, sealing generally means prohibiting disclosure of the existence or contents of court and prosecution records unless authorized by court order; expungement (deletion/destruction) is available only in limited circumstances.",
  "Conviction sealing under N.D.C.C. § 12-60.1-02: a misdemeanor conviction (guilty plea or finding) may be sealed with no new conviction for at least 3 years before filing; a felony conviction with no new conviction for at least 5 years before filing; and an unconditional gubernatorial pardon can support a sealing petition.",
  "Nonconviction court record closing under N.D.C.C. § 12-60.1-05: a nonconviction means all charges in the case were dismissed or the person was acquitted of all charges. Orders entered on or after August 1, 2025 close automatically 61 days after the order; earlier orders use a Petition to Close Nonconviction Records.",
  "DUI record sealing under N.D.C.C. § 39-08-01.6: available where the person pled guilty, pled nolo contendere, or was found guilty under N.D.C.C. § 39-08-01 or an equivalent municipal ordinance, and had no later DUI or any other criminal offense within 7 years; commercial drivers are excluded.",
  "Deferred imposition of sentence / dismissal under N.D.C.C. §§ 12.1-32-07.1 and 12.1-32-07.2: after successful probation the court may allow withdrawal of the guilty plea, set aside the guilty verdict, and dismiss the charge, after which the records and papers are restricted to limited authorized persons.",
  "Marijuana relief under N.D.C.C. § 19-03.1-23(9): a first offense for possession of one ounce or less of marijuana or two grams or less of THC must be sealed on motion if there is no subsequent controlled-substance conviction within two years; a separate Summary Pardon Application exists for certain marijuana offenses with no other convictions in the past five years.",
  "Human-trafficking-victim relief under N.D.C.C. § 12.1-41-14: a person convicted of prostitution or certain listed offenses committed as a direct result of being a trafficking victim may move to vacate the conviction and seal the record; escalate to an attorney or survivor legal clinic.",
  "Limited expungement categories identified in North Dakota court guidance cover juvenile unruly/delinquency records, DNA profiles, and unconstitutional arrests; these are specialized and should be escalated.",
  "For a conviction-sealing petition the petitioner must prove, by clear and convincing evidence, good cause, that the benefit to the petitioner outweighs the presumption of openness, completion of all imprisonment and probation, payment of all restitution, and that reformation/rehabilitation warrants relief."
];
