// Auto-generated by scripts/generate-all50-state-pack-batch.mjs.
// Build-first metadata is sourced from private/Nationwide Record Clearing.
// QA, visual review, counsel review, and source freshness review are tracked
// separately and do not block ordinary RCAP build work.

export const illinoisAll50BuildMetadata = {
  "jurisdiction": {
    "code": "IL",
    "name": "Illinois",
    "slug": "illinois",
    "sourceFolders": [
      "LegalEase Illinois"
    ]
  },
  "products": [
    "record_clearing_guidance_packet",
    "official_pdf_overlay_draft",
    "custom_pleading_or_state_pack_draft"
  ],
  "pathways": [
    {
      "id": "record_clearing_review",
      "label": "Illinois record-clearing review",
      "output": "guidance_packet",
      "reviewRequiredBeforeLive": true
    },
    {
      "id": "official_form_overlay",
      "label": "Illinois official form overlay draft",
      "output": "official_pdf_overlay_draft",
      "reviewRequiredBeforeLive": true
    },
    {
      "id": "custom_pleading",
      "label": "Illinois custom pleading draft",
      "output": "custom_pleading_or_state_pack_draft",
      "reviewRequiredBeforeLive": true
    }
  ],
  "requiredUserInputs": [
    "participant_full_legal_name",
    "date_of_birth_if_required_by_selected_form",
    "contact_information",
    "case_number",
    "court_or_agency_name",
    "county_or_filing_location",
    "charge_or_record_description",
    "case_outcome",
    "disposition_date_if_known",
    "sentence_completion_or_supervision_status_if_applicable",
    "records_or_background_report_if_available"
  ],
  "filingDestinationGuidance": [
    "Use the court, clerk, agency, or official filing destination identified in the selected Nationwide resource packet or official form.",
    "If the correct filing destination is unclear, keep the packet guidance-only and flag the state for post-build QA/attorney review.",
    "Do not invent clerk addresses, agency addresses, local fees, or service rules."
  ],
  "filingSteps": [
    "Confirm the record-clearing pathway from the participant's answers and available source packet.",
    "Collect required user inputs and mark unknown information plainly.",
    "Select official form overlay, custom pleading, or guidance-only fallback.",
    "Generate internal review packet and source inventory artifact.",
    "Route to QA, visual review when an official PDF overlay exists, and counsel review before live use."
  ],
  "feesCopiesServiceNotes": [
    "Use fee, copy, and service notes only when present in the Nationwide source packet or official form.",
    "When fee/copy/service information is absent or unclear, state that the participant should verify current local requirements with the filing court or agency.",
    "Do not treat missing fee data as a blocker for guidance fallback generation."
  ],
  "officialFormInventory": [
    {
      "fileName": "CXP Additional Cannabis Convictions.pdf",
      "relativePath": "LegalEase Illinois/CXP Additional Cannabis Convictions.pdf",
      "sha256": "32b1ef344909ff9a38b816f0235f261678c57abaebe9858aec12b70094e55969",
      "sizeBytes": 396270
    },
    {
      "fileName": "CXP Additional Notice of Court Date.pdf",
      "relativePath": "LegalEase Illinois/CXP Additional Notice of Court Date.pdf",
      "sha256": "4a6dde5541b6531f99a4294e07a28ea85096ea5c982ee76e46cf3e8dd00b0afa",
      "sizeBytes": 283605
    },
    {
      "fileName": "CXP Getting Started Motion to Vacate and Expunge.pdf",
      "relativePath": "LegalEase Illinois/CXP Getting Started Motion to Vacate and Expunge.pdf",
      "sha256": "52ce3880f8d813ca7ebebb1654da5a04f4d70dca538868f7094163a7199eb0b2",
      "sizeBytes": 150220
    },
    {
      "fileName": "CXP Instructions.pdf",
      "relativePath": "LegalEase Illinois/CXP Instructions.pdf",
      "sha256": "2e1459e6a984555a1bd675a7f462c3616aabd70cdc675f9a4cf972bb27831afd",
      "sizeBytes": 869078
    },
    {
      "fileName": "CXP Motion to Vacate and Expunge.pdf",
      "relativePath": "LegalEase Illinois/CXP Motion to Vacate and Expunge.pdf",
      "sha256": "728ad50c5db068d3d3a6bc68901c79431e865f8e2eaa94c37c38a086d9815acf",
      "sizeBytes": 227699
    },
    {
      "fileName": "CXP Notice of Court Date for Motion.pdf",
      "relativePath": "LegalEase Illinois/CXP Notice of Court Date for Motion.pdf",
      "sha256": "56179412256e2c98b0f535a328801e4cf012ae3d179848c3a1efe7df6377b041",
      "sizeBytes": 370872
    },
    {
      "fileName": "CXP Order Granting or Denying Motion.pdf",
      "relativePath": "LegalEase Illinois/CXP Order Granting or Denying Motion.pdf",
      "sha256": "ca0fdef8909a3ef134c562d09a89dcc24de22036c7b8238902443892c3ac77cc",
      "sizeBytes": 332731
    },
    {
      "fileName": "EXP Certificate of Service Circuit Clerk.pdf",
      "relativePath": "LegalEase Illinois/EXP Certificate of Service Circuit Clerk.pdf",
      "sha256": "34fd161b26d91351cfe782d7518bb6037b868d542a972b3052664c555d0f5f44",
      "sizeBytes": 769636
    },
    {
      "fileName": "EXP-AD Additional Cases Expungement.pdf",
      "relativePath": "LegalEase Illinois/EXP-AD Additional Cases Expungement.pdf",
      "sha256": "36ad55c62b891fb2ede8de8bddaeb023c1acc8cbb62880c426dfcdf289686f00",
      "sizeBytes": 821758
    },
    {
      "fileName": "EXP-AD Additional Cases Sealing.pdf",
      "relativePath": "LegalEase Illinois/EXP-AD Additional Cases Sealing.pdf",
      "sha256": "fd423706a659ad6b953adc96a900f5f501eb1567851e52b8ded404c5544159cc",
      "sizeBytes": 817586
    },
    {
      "fileName": "EXP-AD Case List Request to Expunge Seal Records.pdf",
      "relativePath": "LegalEase Illinois/EXP-AD Case List Request to Expunge Seal Records.pdf",
      "sha256": "b72d30d274b061e0671933b8bd65abf7d2c37a6f1dd4ebfbf3968bc55b9bed0c",
      "sizeBytes": 744328
    },
    {
      "fileName": "EXP-AD Order Denying.pdf",
      "relativePath": "LegalEase Illinois/EXP-AD Order Denying.pdf",
      "sha256": "2d3039fa873801bc58bf425a2c73f489951bb82de33b11af031e8bf62df3ffa8",
      "sizeBytes": 782948
    },
    {
      "fileName": "Getting_Started_Juv_Exp.pdf",
      "relativePath": "LegalEase Illinois/Getting_Started_Juv_Exp.pdf",
      "sha256": "437d109797580a45116a4a12f1c4bb79a79bdc66194171e88acb25a50f08c0d9",
      "sizeBytes": 82025
    },
    {
      "fileName": "Illinois-Expungement-Sealing-Agent-Reference.pdf",
      "relativePath": "LegalEase Illinois/Illinois-Expungement-Sealing-Agent-Reference.pdf",
      "sha256": "46eb4fd128286fe28e2ae74912a544f6e5e2114c2d73960574e654f1d895c9a4",
      "sizeBytes": 35550
    },
    {
      "fileName": "Instructions_Juv_Exp.pdf",
      "relativePath": "LegalEase Illinois/Instructions_Juv_Exp.pdf",
      "sha256": "c0be48a780568e0c59190801cd7b46468a1d7e1642c4a8e2a20f7d16d3cf4669",
      "sizeBytes": 601508
    },
    {
      "fileName": "Notice_Juv_Exp.pdf",
      "relativePath": "LegalEase Illinois/Notice_Juv_Exp.pdf",
      "sha256": "5ac7217797ae86c4dea8fe32400bd328d59b95c6fdafb701ea1661e0b982a522",
      "sizeBytes": 875865
    },
    {
      "fileName": "Order_Juv_Exp.pdf",
      "relativePath": "LegalEase Illinois/Order_Juv_Exp.pdf",
      "sha256": "7b0db0a6dddff71dcb5a29fcf4a2fc85b88018592e7a2b3a409a0622b5ebf50e",
      "sizeBytes": 831896
    },
    {
      "fileName": "Request_Juv_Exp.pdf",
      "relativePath": "LegalEase Illinois/Request_Juv_Exp.pdf",
      "sha256": "aee004ee42d5e1a27c4a29106589772c13e0a23fe133a4771bc94db994214be0",
      "sizeBytes": 876666
    }
  ],
  "resourcePacketInventory": [
    {
      "fileName": "Illinois Expungement & Sealing — Wilma Agent Training Reference.rtf",
      "relativePath": "LegalEase Illinois/Illinois Expungement & Sealing — Wilma Agent Training Reference.rtf",
      "classification": "reference",
      "sha256": "03fcda6296a34a7feaff5292f4265c6c52a474f451c7c2fee4ae4186c5e2f507",
      "sizeBytes": 110013
    }
  ],
  "customPleadingSupport": {
    "supported": true,
    "status": "draft_config_allowed",
    "notes": "Pleading-style draft support may be built from Nationwide resources and coded state-pack data where available."
  },
  "guidanceOnlyFallback": {
    "supported": true,
    "label": "Illinois record-clearing guidance fallback",
    "status": "built",
    "notes": "Available for internal review even when official forms or pleading templates need more work."
  },
  "disclaimer": "This RCAP build artifact is for internal document-preparation and review workflows. It is not legal advice, does not guarantee eligibility or outcomes, and is not approved for live use until QA, counsel, and any required visual review pass.",
  "buildStatusMetadata": {
    "buildStatus": "state_built",
    "statusHistory": [
      "not_started",
      "nationwide_resources_found",
      "resource_packet_ingested",
      "official_forms_ingested",
      "overlay_field_maps_drafted",
      "overlay_samples_rendered",
      "state_pack_built",
      "pleading_packet_rendered",
      "guidance_packet_rendered",
      "state_built"
    ],
    "reviewStatuses": {
      "qa": "pending",
      "visual": "pending",
      "counsel": "pending",
      "sourceFreshness": "pending"
    },
    "loops": [
      {
        "id": "nationwide_folder_ingestion_loop",
        "status": "completed"
      },
      {
        "id": "all_state_build_loop",
        "status": "completed"
      },
      {
        "id": "official_pdf_overlay_factory_loop",
        "status": "draft_ready"
      },
      {
        "id": "field_map_retry_loop",
        "status": "pending_retry_artifacts"
      },
      {
        "id": "custom_pleading_factory_loop",
        "status": "draft_ready"
      },
      {
        "id": "guidance_packet_loop",
        "status": "completed"
      },
      {
        "id": "packet_render_qa_loop",
        "status": "pending_review"
      },
      {
        "id": "review_artifact_loop",
        "status": "completed"
      },
      {
        "id": "integration_preview_loop",
        "status": "internal_preview_ready"
      },
      {
        "id": "official_forms_watcher_loop",
        "status": "source_tracked"
      }
    ],
    "liveRouting": {
      "approvedForLive": false,
      "live": false,
      "note": "Build-first state output is internal review material only."
    }
  },
  "buildIssues": []
} as const;
