// Utah disqualifying offenses and escalation/blocks. Sourced from the "Utah
// Expungement Reference for Wilma" (Nationwide Record Clearing), sections 2
// (Paths G and H), 5, and 8, reflecting the § 77-40a-303 certificate bars, the
// numerical criminal-history limits, and the attorney-escalation flags. Screening
// notes, not an exhaustive legal test; verify the exact current Utah Code text.
export const utDisqualifyingOffenseNotes = [
  "Certificate eligibility bars (§ 77-40a-303): a capital felony, first-degree felony, violent felony, and felony DUI under § 41-6a-501(2) are not eligible through an ordinary BCI certificate. A sex/kidnap/child-abuse registry offense is not eligible if registration was required at sentencing or application. Escalate all barred or near-barred cases to attorney review.",
  "Status bars: eligibility is blocked by a pending misdemeanor/felony case or pending plea in abeyance (except certain traffic matters), current incarceration/parole/probation (with narrow infraction/traffic/minor regulatory exceptions), or a criminal protective order or stalking injunction in effect. A false or misleading BCI application blocks eligibility and may itself be a criminal offense.",
  "Numerical criminal-history limits usually block eligibility: 2+ non-drug-possession felonies from separate episodes; 3+ non-drug-possession convictions including 2 Class A misdemeanors from separate episodes; 4+ non-drug-possession convictions including 3 Class B misdemeanors from separate episodes; 5+ non-drug-possession convictions of any degree from separate episodes; 3+ felony drug-possession convictions from separate episodes; and 5+ drug-possession convictions from separate episodes. Special 10-year relief rules can relax some limits.",
  "Financial-obligation bar: for conviction expungement, all court-ordered fines, interest, and restitution for the conviction being expunged must be paid; do not tell users to ignore unpaid restitution.",
  "Automatic Clean Slate exclusions: automatic relief excludes felonies, most Class A misdemeanors other than drug possession, assault, DUI, domestic-violence-related offenses, sex offenses, and certain weapons offenses; a case may fail automatic screening but still be worth petition review.",
  "Traffic / DUI: DUI is not treated as ordinary traffic. Misdemeanor DUI has a 10-year petition waiting period and felony DUI is barred from ordinary certificate eligibility; CDL and commercial-driving traffic matters need careful screening.",
  "Escalation categories (legal review): noncitizen/immigration issues; any felony; first-degree or capital felony; violent felony; felony or misdemeanor DUI; sex/kidnap/child-abuse registry issues; domestic violence; stalking; weapons offenses; assault or other offense against the person; an active protective order or stalking injunction; pending misdemeanor/felony charge or plea in abeyance; current incarceration/parole/probation; unpaid restitution; multiple convictions near or above the numerical limits; cannabis medical-condition claims; human-trafficking/vacatur matters; pardon-needed cases; juvenile/adult court confusion; and federal/tribal/military/out-of-state cases.",
  "Scope limits: Utah expungement does not erase news articles or private background-check copies, does not automatically restore firearm rights, and does not fix immigration consequences; agencies keep, index, and maintain expunged records and may release them to specific entities or under court order."
];
