// Utah eligibility rules. Sourced from the "Utah Expungement Reference for Wilma"
// (Nationwide Record Clearing / LegalEase Utah), corroborated by the cited Utah
// Code Title 77, Chapter 40a sections and Utah Courts / Bureau of Criminal
// Identification (BCI) guidance. Citations are Utah Code unless otherwise noted.
export const utEligibilityRules = [
  "Utah expungement is controlled mainly by Utah Code Title 77, Chapter 40a (Expungement of Criminal Records). Utah uses both automatic Clean Slate expungement and petition-based expungement. Utah law defines 'expunge' as removing a record from public inspection by sealing, restricting, or denying access; it specifically says expungement does NOT mean destruction of the record. After expungement, the person may generally answer questions as if the arrest, investigation, detention, prosecution, or conviction did not occur, unless another law or court order requires a different answer.",
  "Identify the pathway first: automatic Clean Slate expungement, petition-based expungement with a BCI Certificate of Eligibility, petition-based non-conviction expungement, petition-based conviction expungement, traffic offense deletion/petition, cannabis-possession petition without a BCI certificate, pardon-based expungement, juvenile expungement, or vacatur/human-trafficking expungement.",
  "Automatic Clean Slate (acquittal / dismissal with prejudice): a Utah case may be automatically expunged if it resulted in an acquittal on all charges (statutory goal 60 days after acquittal for qualifying post-May 1, 2020 cases) or was dismissed with prejudice (goal 180 days after dismissal or final nonappealable order). A dismissal with prejudice after successful completion of a plea in abeyance is excluded from that favorable-outcome automatic category. As of January 1, 2026 the court identifies and clears eligible automatic-expungement cases on its own (no temporary request form); the process can take up to 120 days.",
  "Automatic Clean Slate (eligible convictions): Clean Slate automatic expungement can apply where each conviction or charge is a controlled-substance possession misdemeanor, Class B misdemeanor, Class C misdemeanor, or infraction. Automatic waiting periods are generally 5 years for Class C misdemeanors/infractions, 6 years for Class B misdemeanors, and 7 years for Class A controlled-substance possession misdemeanors. Automatic Clean Slate is narrower than petition-based expungement and excludes felonies, most Class A misdemeanors other than drug possession, assault, DUI, domestic-violence-related offenses, sex offenses, and certain weapons offenses.",
  "Petition with BCI Certificate of Eligibility: most adult expungement petitions require a Certificate of Eligibility from the Utah Bureau of Criminal Identification (BCI). BCI reviews the person's total criminal history, including other states and previous expungements. The petitioner applies to BCI (fingerprints, valid ID, application fee), and if approved files the petition in the correct Utah court within 180 days of certificate issuance. A BCI certificate does NOT finish the expungement; it only allows filing the petition with the court, and the judge issues the expungement order.",
  "Petition-based non-conviction expungement: for arrest/charge without conviction, a BCI certificate can be issued if at least 30 days have passed after arrest or charge and a statutory outcome applies — no charges will be filed, all charges dismissed with prejudice, charges dismissed without prejudice/condition with prosecutor consent or 180 days passed, acquittal on all charges, or statute of limitations expired. A person is ineligible for the non-conviction certificate with a pending misdemeanor/felony proceeding, pending plea in abeyance, current incarceration/parole/probation, or a criminal protective order or stalking injunction in effect, subject to limited traffic/minor exceptions.",
  "Petition-based conviction expungement: Utah requires payment of all court-ordered fines, interest, and restitution for the conviction being expunged. The waiting period runs from the latest of conviction, release from incarceration, release from parole, or release from probation. Petition waiting periods: misdemeanor DUI under § 41-6a-501(2) and certain serious controlled-substance driving injury/death felonies — 10 years; felony generally — 7 years; felony drug-possession — 5 years; Class A misdemeanor — 5 years; Class B misdemeanor — 4 years; Class C misdemeanor or infraction — 3 years.",
  "Certificate eligibility bars (§ 77-40a-303): Utah bars ordinary certificate eligibility for a capital felony, first-degree felony, violent felony, felony DUI under § 41-6a-501(2), and sex/kidnap/child-abuse registry offenses if registration was required at sentencing or application. Eligibility is also blocked by a pending misdemeanor/felony case or pending plea in abeyance (except certain traffic matters), current incarceration/parole/probation (with narrow infraction/traffic/minor regulatory exceptions), a protective order or stalking injunction in effect, or a false or misleading BCI application.",
  "Numerical criminal-history limits: BCI evaluates the person's full criminal history, including previously expunged convictions. Patterns that usually block eligibility include 2+ non-drug-possession felonies from separate episodes; 3+ non-drug-possession convictions including 2 Class A misdemeanors from separate episodes; 4+ non-drug-possession convictions including 3 Class B misdemeanors from separate episodes; 5+ non-drug-possession convictions of any degree from separate episodes; 3+ felony drug-possession convictions from separate episodes; and 5+ drug-possession convictions from separate episodes. Special 10-year relief rules can relax some numerical limits, and BCI may disregard infractions, traffic, minor regulatory offenses, and already-automatically-expunged Clean Slate cases for some calculations.",
  "Traffic offense expungement/deletion: Utah separates traffic cases from regular criminal expungement. Some traffic offenses are automatically deleted (traffic acquittals, dismissals with prejudice, and certain adjudicated Class C/infraction or Class B traffic cases after 5 years for Class C/infraction and 6 years for Class B). A person may also petition for traffic expungement WITHOUT a BCI certificate using shorter timing — 3 years after adjudication/dismissal for Class C misdemeanor/infraction traffic and 4 years for Class B misdemeanor traffic — if there is no pending traffic case, no pending traffic plea in abeyance, and the person is not on probation for a traffic case. DUI is NOT treated as ordinary traffic.",
  "Cannabis possession petition without BCI certificate: Utah allows a petition to expunge a cannabis-possession conviction WITHOUT a BCI certificate if, at the time of the arrest or citation, the person had a qualifying medical condition and the cannabis possession was in a form and amount to medicinally treat that condition. This is a legal-detail-heavy pathway; escalate if the facts are unclear.",
  "Pardon-based expungement: if BCI denies eligibility, a person may explore the Utah Board of Pardons and Parole pardoned-expungement route. A pardon route is separate from ordinary court expungement.",
  "Vacatur / human-trafficking-related expungement (§ 77-40a-402): Utah has a separate vacatur-related expungement process; a person who receives a vacatur order must deliver it to affected agencies and attach the BCI application/fingerprints for processing. Treat this as a mandatory attorney or survivor-legal-services escalation pathway.",
  "Juvenile expungement: Utah juvenile expungement is separate from adult expungement. Juvenile courts require a certificate of the person's adult Utah criminal-history report before applying for juvenile record expungement; using the adult expungement application for a juvenile matter can delay the process.",
  "Scope limits: Utah expungement does not erase news articles or private background-check copies, does not automatically restore firearm rights, and does not fix immigration consequences (Utah Courts warns noncitizens to consult an immigration lawyer because the FBI may still have records). Agencies keep, index, and maintain expunged records, and expunged records may be released to specific entities or under court order; an order does not restrict an agency's use until that agency receives the order."
];
