// Utah filing workflow. Sourced from the "Utah Expungement Reference for Wilma"
// (Nationwide Record Clearing), sections 3 and 4, corroborated by Utah Code
// Title 77, Chapter 40a and Utah Courts / BCI guidance. Utah uses official Utah
// Courts forms and the BCI certificate process; this pack is shadow-only research
// and wires no renderer.
export const utFilingInstructions = [
  "Classify the case first: acquittal; dismissal with prejudice; dismissal without prejudice; dismissal after plea in abeyance; conviction; drug possession; cannabis possession; traffic offense; DUI; felony; juvenile; vacatur/trafficking-related; pardon-based; or federal/tribal/military/out-of-state (Utah state expungement cannot directly clear non-Utah cases).",
  "Check automatic Clean Slate status before assuming a petition is needed. Acquittals and dismissals with prejudice (excluding plea-in-abeyance dismissals) and eligible lower-level cases may clear automatically; the court now identifies eligible cases on its own (as of January 1, 2026) and the process can take up to 120 days. Confirm the case has not already been automatically expunged (e.g., via MyCase/My Court Case).",
  "For most adult non-traffic, non-medical-cannabis petitions, apply to BCI for a Certificate of Eligibility: submit the BCI application, fingerprints, valid ID, and the application fee. BCI reviews the person's full criminal history and can take up to 12 months to respond.",
  "File the petition in the correct court: the court where the criminal case was filed; if that court no longer exists, the court that would now have jurisdiction; if charges were never filed, the district court in the county where the arrest occurred or citation was issued.",
  "Watch the 180-day certificate deadline: a BCI certificate or special certificate is valid for 180 days, and the court may not accept a petition filed after it expires.",
  "Prosecutor and victim notice: the court notifies the prosecuting office; for conviction cases and plea-in-abeyance dismissals the prosecutor makes reasonable efforts to notify any victim. The prosecutor has 35 days to object or recommend, the victim has 60 days, and the petitioner may respond within 14 days after receiving an objection or AP&P response.",
  "Hearing or no hearing: if an objection is filed, the court schedules a hearing; if no objection is received within 60 days after filing, the court may grant the expungement without a hearing. The court issues an order if it finds by clear and convincing evidence that the certificate is valid, statutory and case-specific requirements are met, and the public interest would not be harmed.",
  "After the order: the petitioner may request certified copies within 28 days. BCI notifies affected agencies and forwards a copy to the FBI; agencies must expunge records once they receive the order, but the order does not restrict an agency's ordinary use until that agency receives it.",
  "Traffic petition (no BCI certificate): use the traffic expungement petition (e.g., form 1002EX) and proposed order (e.g., 1022EX), confirm no pending traffic case/plea in abeyance and no traffic probation, and pay the court filing fee or request a waiver. Do not route DUI as ordinary traffic.",
  "Cannabis-possession petition (no BCI certificate): use the cannabis expungement petition (e.g., form 1003EX) and proposed order (e.g., 1023EX), and document the qualifying medical condition and the form and amount of cannabis tied to medicinal treatment; recommend attorney review.",
  "Juvenile matters: use the juvenile court expungement process, not the adult BCI certificate application; the juvenile court requires an adult Utah criminal-history report from BCI. Vacatur/trafficking matters (§ 77-40a-402) route to an attorney or survivor legal services."
];
