// Maryland eligibility rules. Sourced from the Maryland Wilma Agent Training
// Reference (Nationwide Record Clearing). Each entry paraphrases the Nationwide
// source; statutory citations are Md. Code, Criminal Procedure unless noted.
export const mdEligibilityRules = [
  "Maryland is a true expungement state for many outcomes: expungement removes eligible court records, police records, and other qualifying State or local records from public inspection. An order can reach both court and police records, and custodians generally must certify compliance within 60 days after the order unless a statutory exception applies (§ 10-105). Shielding is a separate, weaker remedy that only makes conviction records inaccessible to the public.",
  "Unit rule (§ 10-107): the rules are very case-unit dependent. If two or more charges, other than minor traffic violations or cannabis possession, arise from the same incident, transaction, or set of facts, they are treated as a unit; if one charge or conviction in the unit is not expungeable, the other charges in that unit usually cannot be expunged either. Wilma must ask about every charge in the same incident. Cannabis possession and minor traffic violations are the key exceptions to the unit rule.",
  "Adult non-conviction expungement (§ 10-105): the most common route, for cases that did not end in a regular conviction. Eligible outcomes include acquittal, dismissal, PBJ (unless excluded), nolle prosequi, stet, compromise under Criminal Law § 3-207, transfer to juvenile court, certain not-criminally-responsible findings, a conviction for an act no longer a crime (with exceptions), cannabis possession under Criminal Law § 5-601, and a conviction vacated under the actual-innocence statute.",
  "Automatic expungement (§ 10-105.1): for qualifying cases entered on or after October 1, 2021, Maryland automatically expunges certain all-favorable-disposition cases after 3 years. It applies when no charge in the case resulted in anything other than acquittal, dismissal, not guilty, or nolle prosequi, except a treatment-related nolle prosequi is excluded. A person who wants relief before 3 years may petition early using Form CC-DC-CR-072C with no fee.",
  "Arrest with no charge filed: if the person was arrested on or after October 1, 2007 and no charge was filed, the arrest should be automatically expunged within 60 days of release from custody. If the arrest was before October 1, 2007, the person may need to contact the arresting police department. If the person requested law-enforcement expungement and received a denial or no action after more than 60 days, Form DC-CR-071 is used to ask the court to expunge the police record.",
  "Eligible conviction expungement (§ 10-110): Maryland allows expungement of many, but not all, guilty convictions. The exact charge statute must be matched against the Maryland Courts List of Expungeable Charges Under Criminal Procedure § 10-110 (currently form/list CC-DC-CR-072G2). Section 10-110 covers a long list of specified misdemeanors across several Maryland code articles, certain felony theft, burglary, and possession-with-intent-to-distribute convictions, and attempts, conspiracies, or solicitations of listed eligible offenses. Do not classify by plain-English offense name alone; use the exact statute, CJIS charge code if available, degree, and misdemeanor/felony status.",
  "Cannabis routing: cannabis deserves its own branch. Cannabis possession under Criminal Law § 5-601 uses Form CC-DC-CR-072D and may be petitioned after sentence completion. Possession with intent to distribute cannabis uses Form CC-DC-CR-072D and is available 3 years after sentence completion. Cannabis possession is excluded from the unit rule, so it does not block expungement of the other charges in the unit. A governor cannabis pardon may shield or support relief, but full expungement still requires the correct expungement route. Do not collapse possession, possession with intent, distribution, and paraphernalia into one rule.",
  "Maryland Second Chance Act shielding (§§ 10-301 to 10-306): a fallback for certain convictions when expungement is unavailable or not yet available. Shielding removes the record from public view but does not destroy it. Eligible shielding convictions listed by Maryland Courts are disorderly conduct, disturbing the peace, failure to obey a reasonable and lawful order, malicious destruction of property in the lesser degree, trespass on posted property, possession or administering a controlled dangerous substance, possession or administering a non-controlled substance, use of or possession with intent to use drug paraphernalia, driving without a license, and driving while privilege is canceled, suspended, refused, or revoked. A person may petition no earlier than 3 years after satisfying the sentence for all convictions being shielded (including parole, probation, or mandatory supervision), may be granted only one shielding petition in a lifetime, and a pending criminal proceeding blocks eligibility.",
  "Juvenile expungement (Cts. & Jud. Proc. § 3-8A-27.1; Md. Rule 11-506): separate from adult expungement, with no filing fee. A person may be eligible if a CINS petition, juvenile delinquency petition, or juvenile citation was filed concerning them. The petition is filed in the court where the juvenile petition or citation was filed, or in the court to which the case was transferred. Common eligibility checks: petitioner is at least 18; at least 2 years have passed since the last official action in the juvenile record; no more than one delinquency adjudication; no later criminal conviction; no pending delinquency petition or criminal charge; and the adjudication was not for an offense that would be a felony, crime of violence, or sex-offender-registration offense if committed by an adult.",
  "Do-not-say-eligible discipline: for § 10-105, confirm every charge in the unit is identified, disposition confirmed, the waiting period or waiver/good cause is met, PBJ/stet/treatment/DUI special rules are checked, no pending criminal proceeding, the unit rule is checked, and restitution is considered. For § 10-110, confirm the exact conviction statute matches the official § 10-110 eligible list, the correct 5/7/10/15-year waiting period has passed, the sentence-completion date is confirmed, no disqualifying new conviction during the waiting period, no pending criminal proceeding, the unit rule is checked, victim notice/hearing possibility is explained, and public-safety / interest-of-justice findings are supportable."
];
