// Auto-generated by scripts/generate-all50-state-pack-batch.mjs.
// Build-first metadata is sourced from private/Nationwide Record Clearing.
// QA, visual review, counsel review, and source freshness review are tracked
// separately and do not block ordinary RCAP build work.

export const kansasAll50BuildMetadata = {
  "jurisdiction": {
    "code": "KS",
    "name": "Kansas",
    "slug": "kansas",
    "sourceFolders": [
      "LegalEase Kansas"
    ]
  },
  "products": [
    "record_clearing_guidance_packet",
    "official_pdf_overlay_draft",
    "custom_pleading_or_state_pack_draft"
  ],
  "pathways": [
    {
      "id": "record_clearing_review",
      "label": "Kansas record-clearing review",
      "output": "guidance_packet",
      "reviewRequiredBeforeLive": true
    },
    {
      "id": "official_form_overlay",
      "label": "Kansas official form overlay draft",
      "output": "official_pdf_overlay_draft",
      "reviewRequiredBeforeLive": true
    },
    {
      "id": "custom_pleading",
      "label": "Kansas custom pleading draft",
      "output": "custom_pleading_or_state_pack_draft",
      "reviewRequiredBeforeLive": true
    }
  ],
  "requiredUserInputs": [
    "participant_full_legal_name",
    "date_of_birth_if_required_by_selected_form",
    "contact_information",
    "case_number",
    "court_or_agency_name",
    "county_or_filing_location",
    "charge_or_record_description",
    "case_outcome",
    "disposition_date_if_known",
    "sentence_completion_or_supervision_status_if_applicable",
    "records_or_background_report_if_available"
  ],
  "filingDestinationGuidance": [
    "Use the court, clerk, agency, or official filing destination identified in the selected Nationwide resource packet or official form.",
    "If the correct filing destination is unclear, keep the packet guidance-only and flag the state for post-build QA/attorney review.",
    "Do not invent clerk addresses, agency addresses, local fees, or service rules."
  ],
  "filingSteps": [
    "Confirm the record-clearing pathway from the participant's answers and available source packet.",
    "Collect required user inputs and mark unknown information plainly.",
    "Select official form overlay, custom pleading, or guidance-only fallback.",
    "Generate internal review packet and source inventory artifact.",
    "Route to QA, visual review when an official PDF overlay exists, and counsel review before live use."
  ],
  "feesCopiesServiceNotes": [
    "Use fee, copy, and service notes only when present in the Nationwide source packet or official form.",
    "When fee/copy/service information is absent or unclear, state that the participant should verify current local requirements with the filing court or agency.",
    "Do not treat missing fee data as a blocker for guidance fallback generation."
  ],
  "officialFormInventory": [
    {
      "fileName": "Criminal Cover Sheet 102025.pdf",
      "relativePath": "LegalEase Kansas/Criminal Cover Sheet 102025.pdf",
      "sha256": "6384f934dc431601dfd07d0822c32b83ee8fcd0412cff5496af1481169cdea60",
      "sizeBytes": 126589
    },
    {
      "fileName": "Kansas-Expungement-Reference.pdf",
      "relativePath": "LegalEase Kansas/files-4/Kansas-Expungement-Reference.pdf",
      "sha256": "cb730ad65ca95ec091c010ee71b968fb6b9dc2193db82130a972d036b4a36404",
      "sizeBytes": 8449
    },
    {
      "fileName": "Instructions for Expungement of Conviction or Diverson 122016.pdf",
      "relativePath": "LegalEase Kansas/Instructions for Expungement of Conviction or Diverson 122016.pdf",
      "sha256": "dd1b80739a926a41156c324893bd4330ab666dbbd3a0b92665f52878623cc831",
      "sizeBytes": 128248
    },
    {
      "fileName": "Notice of Hearing on Petition for Expungement of Conviction or Diversion 122016.pdf",
      "relativePath": "LegalEase Kansas/Notice of Hearing on Petition for Expungement of Conviction or Diversion 122016.pdf",
      "sha256": "a960c857ec505a3013e725526718580ad2047aa9b3dd85191a70b8375cc83ffd",
      "sizeBytes": 19255
    },
    {
      "fileName": "Order Denying Expungement of Conviction or Diversion 122016.pdf",
      "relativePath": "LegalEase Kansas/Order Denying Expungement of Conviction or Diversion 122016.pdf",
      "sha256": "b29254fb58433d496041c185fc69ec864ba1beff1e5e9722738c3b1ebedfe2ba",
      "sizeBytes": 126038
    },
    {
      "fileName": "Order of Expungement of Conviction or Diversion Cover Sheet 122016.pdf",
      "relativePath": "LegalEase Kansas/Order of Expungement of Conviction or Diversion Cover Sheet 122016.pdf",
      "sha256": "d4171396d12f55a50d6c4e0d5a3b694ad982325e7377d74deaa5839d3bfad537",
      "sizeBytes": 67384
    },
    {
      "fileName": "Petition for Expungement of Conviction or Diversion 82022.pdf",
      "relativePath": "LegalEase Kansas/Petition for Expungement of Conviction or Diversion 82022.pdf",
      "sha256": "1113f7b64a57d7ca9568f75d04922d94fabbeea6c7c5839402689ed7fc0db07c",
      "sizeBytes": 234581
    }
  ],
  "resourcePacketInventory": [
    {
      "fileName": "Kansas-Expungement-Forms.html",
      "relativePath": "LegalEase Kansas/files-4/Kansas-Expungement-Forms.html",
      "classification": "reference",
      "sha256": "8c14f026f34f799798bed5989387152edf4bfa9d1edf62745228ec346c73dce2",
      "sizeBytes": 34588
    },
    {
      "fileName": "Kansas-Expungement-Reference.html",
      "relativePath": "LegalEase Kansas/files-4/Kansas-Expungement-Reference.html",
      "classification": "reference",
      "sha256": "4225b9557c5cc5689d97e467710e627235557ad23064f337578e83dce15d8698",
      "sizeBytes": 10901
    }
  ],
  "customPleadingSupport": {
    "supported": true,
    "status": "draft_config_allowed",
    "notes": "Pleading-style draft support may be built from Nationwide resources and coded state-pack data where available."
  },
  "guidanceOnlyFallback": {
    "supported": true,
    "label": "Kansas record-clearing guidance fallback",
    "status": "built",
    "notes": "Available for internal review even when official forms or pleading templates need more work."
  },
  "disclaimer": "This RCAP build artifact is for internal document-preparation and review workflows. It is not legal advice, does not guarantee eligibility or outcomes, and is not approved for live use until QA, counsel, and any required visual review pass.",
  "buildStatusMetadata": {
    "buildStatus": "state_built",
    "statusHistory": [
      "not_started",
      "nationwide_resources_found",
      "resource_packet_ingested",
      "official_forms_ingested",
      "overlay_field_maps_drafted",
      "overlay_samples_rendered",
      "state_pack_built",
      "pleading_packet_rendered",
      "guidance_packet_rendered",
      "state_built"
    ],
    "reviewStatuses": {
      "qa": "pending",
      "visual": "pending",
      "counsel": "pending",
      "sourceFreshness": "pending"
    },
    "loops": [
      {
        "id": "nationwide_folder_ingestion_loop",
        "status": "completed"
      },
      {
        "id": "all_state_build_loop",
        "status": "completed"
      },
      {
        "id": "official_pdf_overlay_factory_loop",
        "status": "draft_ready"
      },
      {
        "id": "field_map_retry_loop",
        "status": "pending_retry_artifacts"
      },
      {
        "id": "custom_pleading_factory_loop",
        "status": "draft_ready"
      },
      {
        "id": "guidance_packet_loop",
        "status": "completed"
      },
      {
        "id": "packet_render_qa_loop",
        "status": "pending_review"
      },
      {
        "id": "review_artifact_loop",
        "status": "completed"
      },
      {
        "id": "integration_preview_loop",
        "status": "internal_preview_ready"
      },
      {
        "id": "official_forms_watcher_loop",
        "status": "source_tracked"
      }
    ],
    "liveRouting": {
      "approvedForLive": false,
      "live": false,
      "note": "Build-first state output is internal review material only."
    }
  },
  "buildIssues": []
} as const;
